### ISSUE TITLE
Update the link on the Healthcare page

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1017]
### Content Update 

A link on this page: https://covid19.ca.gov/healthcare/#top needs to be updated. Can you replace this link below with this one: https://www.dmhc.ca.gov/Portals/0/Docs/DO/DMHC-FAQForHealthCoverageOfCOVID-19Testing.pdf
Health care — including coronavirus testing for people who need it — should be affordable for all Californians.
All patients with full-service Medi-Cal or commercial insurance in California will have copays, coinsurance and deductibles waived for COVID-19 testing and screening.  Medicare and Medicare Advantage Plans cover coronavirus tests and antibody tests, with no out-of-pocket costs. The cost of coronavirus screening, testing, and treatment for the uninsured is paid for by the government. 

If you don’t have health care coverage or recently lost employer-sponsored health care coverage, see the Health Care Coverage Options Factsheet (PDF) to get covered.

### Content Captain
@JasonKarim

**Comment by JasonKarim** [comment]
Content drafted. Reviewed by @thepegisin. Waiting for approval by @abquirarte
