### ISSUE TITLE
Updates to Food page for Pandemic-EBT

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1025]
[Staging doc with edits](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit#)

- [x] Review by @thepegisin 
- [x] Review by @abquirarte 
- [x] Edits are live

**Comment by abquirarte** [comment]
☑️ @LizNobriga  :)

**Comment by LizNobriga** [comment]
Completed live 7/17/20
