### ISSUE TITLE
Broken link in all versions of Help for immigrants page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1036]
In all translated versions of the **Help for immigrants** page, there is one broken link to a PDF.

In one accordion, there is a link that should go to the Immigrant's Guide PDF that is in the same language as the page.

Instead, it has a broken link that used to go to the English version of the Immigrant's Guide PDF.

Here is that accordion and link in the Spanish page:

<img width="721" alt="2020-07-20_09-59-55" src="https://user-images.githubusercontent.com/63249920/87965533-bfb9e380-ca70-11ea-912c-e909c644ab01.png">

Needs to be fixed in:

- [ ] [https://covid19.ca.gov/guide-immigrant-californians-es/](https://covid19.ca.gov/guide-immigrant-californians-es/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-zh-hant/](https://covid19.ca.gov/guide-immigrant-californians-zh-hant/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-zh-hans/](https://covid19.ca.gov/guide-immigrant-californians-zh-hans/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-tl/](https://covid19.ca.gov/guide-immigrant-californians-tl/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-ar/](https://covid19.ca.gov/guide-immigrant-californians-ar/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-ko/](https://covid19.ca.gov/guide-immigrant-californians-ko/)
- [ ] [https://covid19.ca.gov/guide-immigrant-californians-vi/](https://covid19.ca.gov/guide-immigrant-californians-vi/)

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/compare/d860359ecc63...a3a6e21b91a9

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/commit/4946755f2073ac49cf95dadd913a8e2bdd445da1

**Comment by aaronhans** [comment]
This is fixed
