### ISSUE TITLE
Broken link in all translated versions of Get PPE page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1037]
Just removed a broken link to a FEMA PDF on the English version of **Get PPE.**

<img width="671" alt="2020-07-20_16-01-44" src="https://user-images.githubusercontent.com/63249920/87995325-0543d400-caa4-11ea-8dab-c19e227692e0.png">

This same broken link is on all the translated versions of this page. Using this as a test to see how fast (or if) AvantPage will update translated pages with the "translate" tag.

- [x] AvantPage updated 7 translated versions of **Get PPE**

**BTW, this is the last broken link to fix from what was once a very long list!**

**Comment by abquirarte** [comment]
nice!! :) I emailed the SMEs

**Comment by thepegisin** [comment]
I removed this link in the English page, so we could probably just do that on the translated pages.

**Comment by abquirarte** [comment]
This is what they sent me
------
> I’m actually seeing a different page than the screenshot you shared. I don’t have that best practices link

> Here’s the content I have for that section:

> If PPE is required as part of routine duties performed by essential workers:

- Extend use times of undamaged, not visibly soiled PPE.
- Put in place expanded facility-based PPE reuse policies.
- Use CDC strategies to [optimize the supply of PPE.](https://www.cdc.gov/coronavirus/2019-ncov/hcp/ppe-strategy/index.html)
- [Practice decontamination](https://www.cdc.gov/coronavirus/2019-ncov/hcp/ppe-strategy/decontamination-reuse-respirators.html) and reuse strategies for filtering facepiece respirators (FFRs) as a contingency measure.
- Understand PPE requirements and track burn rate. Use [CDC’s PPE burn rate calculator ](https://www.cdc.gov/coronavirus/2019-ncov/hcp/ppe-strategy/burn-calculator.html)if needed.
- Use alternative types or sources of PPE to support necessary operations.
- Use NIOSH-approved respiratory protection that was not approved before by the FDA.
- Check FDA and OSHA websites for updates and on relaxed enforcement and [Emergency Use Authorizations.](https://www.fda.gov/emergency-preparedness-and-response/mcm-legal-regulatory-and-policy-framework/emergency-use-authorization)
- Read [NIOSH guidance](https://www.cdc.gov/coronavirus/2019-ncov/community/conserving-respirator-supply.html) on conserving FFRs in non-healthcare worksites, such as manufacturing and construction.

**Comment by thepegisin** [comment]
Yes. On the "Use CDC strategies" bullet, I removed the end of the sentence that had the broken link (after "optimize the supply of PPE"). 

It looks like they did that too, so this is now fixed. I'll close it.
