### ISSUE TITLE
Updates to stay home QA- Can I vote?

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1046]
GO legal and Secretary of State have provided updates to the "Can I vote" content in our Stay Home QA. 

(In your inbox). Please provide edits/improvements/questions by 2:15 pm. Otherwise please publish as is. 
@thepegisin @ashleydraper @LizNobriga 

Separate task: 

- [ ] add "Register to vote" link to footer @kkoryaka. Link to: https://registertovote.ca.gov/

**Comment by ashleydraper** [comment]
@abquirarte @thepegisin @LizNobriga 
Liz and I have made edits in the redline section of the response. Looking for feedback. Went from grade 16 readability to around 13!! 

[Stay home](https://docs.google.com/document/d/1RD_243YxY09iMKbBhkjHwa36IeLHkiAc/edit#)

**Comment by thepegisin** [comment]
I suggest a clean copy of the redline edit, because otherwise it's impossible to read.

**Comment by ashleydraper** [comment]
Clean version is below
