### ISSUE TITLE
Replace latest news section with this. 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#105]
H2 ## California is working around the clock to respond to COVID-19.

- Directed Californians to stay at home to slow the spread of the virus
- Made testing free for most Californians who are medically eligible for testing
- Ensured students continue to learn and get meals even when schools physically close
- Deployed the California National Guard to work at food banks
- Distributed millions of N95 masks and other protective gear to health care workers, with more to come soon
- Secured travel trailers and hotels to house people experiencing homelessness

[Learn more ](https://www.gov.ca.gov/california-takes-action-to-combat-covid-19/) about how the state is combating COVID-19.

- [x] Move the automated latest news to the footer (for now)

**Comment by artuoma** [comment]
Working on this

**Comment by abquirarte** [comment]
This is now live
