### ISSUE TITLE
Adding stay home Q&A based on user feedback

### ISSUE THREAD

**Issue by ashleydraper** [cagov/covid19#1058]
A travel restriction QA was removed from the CDPH site, but users are still seeking guidance around this issue. There is a proposed QA in the [stay home doc](https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#), are we able to add this here?

**Comment by thepegisin** [comment]
In [Staging doc](https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#) - needs @abquirarte's approval.

**Comment by abquirarte** [comment]
May have a new content edit based on lastest DMV announcement. 
@thepegisin 

[attachment_125426_8.4.20 DMV Expands Online Services with Commercial Drivers License Renewals.pdf](https://github.com/cagov/covid19/files/5024392/attachment_125426_8.4.20.DMV.Expands.Online.Services.with.Commercial.Drivers.License.Renewals.pdf)

**Comment by thepegisin** [comment]
Moving this ^ to a new issue. Travel q/a's approved and updated.
