### ISSUE TITLE
New Page- Housing for farmworkers 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1060]
### context: 
> A state team has developed [a new program](https://docs.google.com/document/d/1tnWGJaP_sE3tU7hV4kOnAClXWrIUeEuu/edit) to provide housing for farmworkers who are COVID positive or exposed and need to isolate, but are unable to do so in their home. Attached (in your inbox) is the program overview, it is modeled after Housing for Healthcare workers, with some components of Project Room key.

> CDFA is the lead agency on this (in very close partnership with DSS).

> It is expected this program will be announced tomorrow (Friday) and it would be great to have a landing page on the covid19.ca.gov site. 

## Timeline
Draft in WP staging by today Thrs 7/23 (published, no crawl, or with PW). 

## Notes:
We will likely go through a few iterations with SMEs. 
The expectation is to have a landing page for this. But look through the content and see where else it may make sense to point/link to this. The 2 programs this is being modeled after don't have their own pages, so we may need more content clean up through this. 

Tagging @thepegisin as lead with @LizNobriga & @ashleydraper since you're familiar with the other programs.

**Comment by LizNobriga** [comment]
- [ ] [housing for farmworkers staging doc](https://docs.google.com/document/d/1uTWYYSaia5AK-KDGum9Wk-ZsJHn87TIqwBYgc6vlZ9A/edit#)
- [ ] immigrant guide
- [ ] financial help
- [ ] [workers staging doc](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit#)

**Comment by ashleydraper** [comment]
@LizNobriga I think you meant to post the **[housing and homelessness](https://docs.google.com/document/d/1lQ8hiUpSGQeW-JL5mmKcBrfKyTYSTOtMGoTYU3mDez0/edit#)** doc here. The financial help page is posted in issue #980

**Comment by LizNobriga** [comment]
yes! updated, thanks @ashleydraper

**Comment by ashleydraper** [comment]
Okay, looks like all of these are ready for your review @abquirarte. I've lost sense of what is actually due today, so please let us know if we're publishing any of this today.

**Comment by abquirarte** [comment]
@ashleydraper made a couple of tweaks, looks great! I think this can go live tomorrow (after we go live with the new page). :)

**Comment by abquirarte** [comment]
@ashleydraper @orielgomez @LizNobriga 
We'll have to update your pages respectively (moving away from the term farmworkers to be more inclusive if the industry)

**Comment by ashleydraper** [comment]
I was thinking that the whole time, wasn't sure if there was any sensitivity around that term. Would agricultural worker suffice? I haven't published yet, so if we could not be offensive to start, that would be best!

**Comment by abquirarte** [comment]
I think it should @Ashley!
It's not going live until tomorrow anyway :)

**Comment by LizNobriga** [comment]
- [x]  housing for farmworkers 
- [ ]  immigrant guide 
- [x]  housing and homelessness 
- [x]  workers

**Comment by thepegisin** [comment]
Link to this page is now added to the **Working and living safely** menu. Awesome work, team!

@abquirarte, if you have no changes, this can be closed.

**Comment by abquirarte** [comment]
Sweet!
