### ISSUE TITLE
Update to business page- EIDL Advance was discontinued as of 7/17

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1063]
## Context: 

I noticed that https://covid19.ca.gov/business-and-employers/#top needs a quick set of changes regarding the EIDL Advance.

Please note that as of this past Friday, 7/17, the EIDL Advance (not the EIDL itself, just to clarify!) was discontinued, because all funds for that have been allocated.

Please see update on U.S. SBA page -- scroll down a bit:  https://www.sba.gov/page/disaster-loan-applications#section-header-0

**EIDL Advance Discontinued**

Please note that all available funds for the EIDL Advance program have been allocated. By law, SBA is not able to issue EIDL Advances once program funding has been obligated and is no longer available. EIDL loan applications will still be processed even though the Advance is no longer available.

## Timeline 
End of day/tomorrow

**Comment by LizNobriga** [comment]
staging doc (will add)
- [ ] peggy review
- [ ] angie sign off
- [ ] publish/live

**Comment by LizNobriga** [comment]
this is live

**Comment by abquirarte** [comment]
Yay, thank you!
