### ISSUE TITLE
Updates to Healthcare Workers page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1064]
Due to some inquiries from OAs, we are hoping to update the Hotels for Healthcare Workers website (https://covid19.ca.gov/hotel-rooms-for-california-healthcare-workers/) to reflect the addition of Correctional staff and first responders.

The website currently reads:

**Work in a California healthcare facility** 

- This includes medical transport providers and non-medical staff within health care facilities.
- This also includes workers in California’s Health Corps or CAL MAT, as designated by the State.
 
-------
We would like to change it to read:

**Work in a California healthcare facility, including:**

- Medical transport providers and non-medical staff within health care facilities.
- Workers in California’s Health Corps or CAL Mat, as designated by the State.
- Correctional facility staff
- First responders

**Comment by LizNobriga** [comment]
[staging doc](https://docs.google.com/document/d/1g5EU4yPOahBRmERCkSQxXkYU2z03FDWl1p9556gE2LQ/edit#heading=h.115ta5df3vxb)

**Comment by abquirarte** [comment]
✔️ looks good and ready to go live!!

**Comment by LizNobriga** [comment]
published/live

**Comment by abquirarte** [comment]
Fantastic, thank you!
