### ISSUE TITLE
Was this page useful widget bug

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1069]
The Was this page useful widget is recording a negative button press response in the comments database if no button is ever pressed.

If a positive response is made before a comment is posted that is recorded fine

The button press alone being sent to GA is being recorded correctly both positively and negatively

**Comment by aaronhans** [comment]
API fixed so it is no longer recording false negatives

**Comment by aaronhans** [comment]
Can close this now, doing some admin tool upgrades in a related ticket: https://github.com/cagov/covid19/issues/1093

**Comment by abquirarte** [comment]
cool thanks @aaronhans
