### ISSUE TITLE
Latest news page in English has broken links in Select language button

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1081]
First detected today, 7/24.

Select language button on English **Latest news** page has broken links. Might need to be manually fixed after Carter's reorg of the translated pages.

<img width="525" alt="2020-07-24_14-59-35" src="https://user-images.githubusercontent.com/63249920/88439021-e2286580-cdbe-11ea-845d-c4224a722e91.png">
<img width="646" alt="2020-07-24_15-00-52" src="https://user-images.githubusercontent.com/63249920/88439025-e6ed1980-cdbe-11ea-9ab5-36a96a1358d6.png">
<img width="652" alt="2020-07-24_15-01-26" src="https://user-images.githubusercontent.com/63249920/88439030-e94f7380-cdbe-11ea-8372-b1da4b60eafd.png">

**Comment by abquirarte** [comment]
Interesting. This section is typically not translated and the content comes from the Governor's Office website and CDPH (We crawl their latest news)

**Comment by carterm** [comment]
RIght now we are hard-redirecting /es/latest-news/ to the english one.  We should add those redirects for the other translations.

**Comment by carterm** [comment]
added redirects for the latest news pages.  Would be nice to have an stub translated page for each language that at least has the title in the correct langauge.

**Comment by carterm** [comment]
Continuing the work for this here...
https://github.com/cagov/covid19/pull/1083
