### ISSUE TITLE
New broken links in translated pages after 7/23 migration

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1082]
In today's SiteImprove broken links report, there are 112 new broken links.

[https://my2.siteimprove.com/QualityAssurance/979071/Links/Pages/1](https://my2.siteimprove.com/QualityAssurance/979071/Links/Pages/1)

- [x] 6 are links to PDFs on English pages, which I manually fixed
- [x] 106 are in translated pages, which may be related to their recent migration

Some, but not all, are broken links to PDFs which happened to be in the wrong directory (/img instead of /pdf, so automated redirects broke them). 

Others are links to pages, including a very noticeable broken link on the Chinese Traditional homepage (button to County page).

**Comment by carterm** [comment]
I don't have a login for SiteImprove.  Can you post the list here?

**Comment by thepegisin** [comment]
Closing this as the majority have been fixed. Opening a new issue for this week's broken links (far fewer!).
