### ISSUE TITLE
Pledge form

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1086]
Create pledge form where people can pledge to be safe

launch blockers form:
- [x] create form
- [ ] form design reviewed by Konstantin
- [ ] finalize form content
- [ ] add social share links
- [ ] translate form
- [x] setup new cosmos container in existing cosmos db
- [x] create and deploy new cosmos endpoint to accept form data
- [x] form submits data to cosmos successfully
- [x] separate script into new module included only on pledge page
- [ ] form sends events to GA
- [ ] cross browser review (add script to es5.js for IE11)

responses:
- [x] create new container with counts of pledges by zip code
- [ ] form submit api needs to update counts after submitting to pledges
  - retrieve from counts
  - update object
  - handle not yet existing zip code
  - update record
- [ ] create new api to retrieve data
  - runs on cron regularly and writes json to blob storage
- [ ] create web component that reads blob storage json on the page and displays table with info maybe overflow:scroll

not launch blockers:
- [ ] form data serialization to endpoint can be a useful reusable web component
- [ ] make some neat graphs of the data received

**Comment by abquirarte** [comment]
This may not longer be necessary.  So removing from backlog

**Comment by kenbasart** [comment]
No longer necessary per AQ 8-19-20
