### ISSUE TITLE
Translated Checklists!

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1089]
[Tracking sheet 
](https://docs.google.com/spreadsheets/d/1EKFgkjBaQKrV6ePgBFLjOGuxFqVVaIv0zjX1QknKNlI/edit#gid=721764354)

~- [x] Save all of them~
~- [x] Publish~
~- [x] Track URL in sheet~
~- [x] Post in the right translated pages~ 
~- [x] Rethink design if needed~

# 9/01/2020 Context
I'm repurposing this issue to track the new list of guidance we have received. 
## Places of worship 📥 inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Fitness Facilities 📥 inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Real Estate ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Limited Services ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Outdoor personal services  ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Hair Salon 📥 inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Expanded personal services 
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Life sciences 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Food Packing 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Logistics and Warehousing  ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Energy and utilities  ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Office Workspace ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Public and private transit 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## mining and logging 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## retail 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Shopping centers 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Dine-in restaurants   ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Family entertainment  📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## restaurants, bars, wineries 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## zoos, museums 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Manufacturing 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Ports  ✅ uploaded
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## outdoor museums 📥 in your inbox
Arabic
Armenian
Chinese (Simplified)
Chinese (Traditional)
English
Hmong
Khmer
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

--------
# Guidances
#### Email 1
1.       Arabic
2.       Armenian
3.       Chinese Simplified
4.       Chinese Traditional
5.       English
6.       Hmong
#### Email 2:
1.       Khmer (Cambodian)
2.       Korean
3.       Russian
4.       Spanish
5.       Tagalog
6.       Thai
7.       Vietnamese

## Small cohorts/groups of children and youth 
1.       Arabic
2.       Armenian
3.       Chinese (Simplified)
4.       Chinese (Traditional)
5.       English
6.       Hmong
7.       Khmer
8.       Korean
9.       Russian
10.   Spanish
11.   Tagalog
12.   Thai
13.   Vietnamese

## Case and contact management within Child care facilities (CDPH guidance, not standard to our guidance, need to figure out to add) 

1. Arabic
2. Armenian
3. Chinese (Simplified)
4. Chinese (Traditional)
5. English
6. Hmong
7. Khmer
8. Korean
9. Russian
10. Spanish
11. Tagalog
12. Thai
13. Vietnamese

----

**Comment by orielgomez** [comment]
@abquirarte the documents have been saved into our drive in the translations folder under the "Guidance PDFs" folder. 

Files have been uploaded and URLs can be found in the translations tracking sheet.

**Comment by abquirarte** [comment]
Can we please update this issue with the latest status? 

we were fixing some links?

**Comment by orielgomez** [comment]
To do's:

- [ ] upload updated English docs, w/ --en.pdf format
- [ ] fix links to be aligned with 
- [ ] Compile and send links of redirects for english documents

**Comment by LizNobriga** [comment]
:ballot_box_with_check: Renamed and uploaded English guidance PDFs (with `--en.pdf`)
:ballot_box_with_check: New urls staged on Industry guidance page - awaiting green light ~6 pm to publish
:ballot_box_with_check: List of redirects needed has been updated - @orielgomez will provide the latest

:bookmark: Any PDFs needing to be updated before redirects are created will need to be uploaded with both the old and and new filenames.

**Comment by orielgomez** [comment]
Final step:

- [ ] Receive updates w/ new links to translated Industry Guidance pages from Avantpage

**Comment by abquirarte** [comment]
Also tracking #1182

**Comment by abquirarte** [comment]
# 8/24/2020 re-purposing this original issue to track the received translated checklists

**Comment by LizNobriga** [comment]
Ignore the checklist for hair salons providing outdoor services - that is no longer a thing with new dimmer framework.

**Comment by LizNobriga** [comment]
Liz is doing Employer playbook and Cohort guidance.

**Comment by LizNobriga** [comment]
@abquirarte Are we supposed to host the translated case and contact management for childcare facilities? The English version of this is on CDPH, not ours: [https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/contact-management-childcare-facilities.aspx](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/contact-management-childcare-facilities.aspx)

**Comment by LizNobriga** [comment]
English checklists renamed and uploaded to github, and url changed in WP:
- [x]  family entertainment centers
- [x]  fitness 
- [x]  public transit
- [x]  restaurants, wineries, and bars
- [x]  energy

**Comment by m-sullivan7** [comment]
@abquirarte Uploaded translated versions of the following:

- [ ] ports
- [ ] dine-in
- [ ] personal care outdoors
- [ ] energy
- [ ] limited services
- [ ] offices
- [ ] real estate
- [ ] logistics

**Comment by LizNobriga** [comment]
We have blockers for posting translated PDFs for two items:

1. [guidance related to cohorts of children and youth](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/small-groups-child-youth.aspx) 
2. [case and contact management guidance related to cohorts for childcare facilities](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/contact-management-childcare-facilities.aspx)

As described in email, these are CDPH links (for English), not PDFs, so posting translated PDFs using language suffix method will not work.

**Comment by LizNobriga** [comment]
FYI, this won't be complete by the target date of 9/4.

**Comment by abquirarte** [comment]
> FYI, this won't be complete by the target date of 9/4.
> 
> Translated checklists posted:
> 
> * [x]   family entertainment centers
> * [ ]   fitness
> * [x]   public transit
> * [ ]   restaurants, wineries, and bars
> * [x]   energy
> * [ ]  places of worship
> * [x]  life sciences
> * [ ]  museums and zoos
> * [ ]  outdoor museums
> * [x]  dine-in
> * [ ]  hair salons
> * [x]  offices
> * [x]  mining
> * [x]  ports
> * [ ]  manufacturing
> * [x]  limited services
> * [ ]  food packing
> * [x]  logistics
> * [x]  retail
> * [x]  shopping
> * [x]  real estate
> * [x]  personal care services provided outdoors
> 
> Other translations posted:
> 
> * [x]  employer playbook

amazing, thank you. That's OK. I changed the target date to `whenever feasible`

**Comment by thepegisin** [comment]
Checklists above :point_up: in Armenian, Hmong, Khmer, Russian, and Thai now posted to **[Industry guidance in other languages](https://covid19.ca.gov/guidance-languages/)** page.

**Comment by thepegisin** [comment]
- [ ] Employer playbooks in Armenian, Hmong, Khmer, Russian, and Thai now posted to **[Industry guidance in other languages](https://covid19.ca.gov/guidance-languages/)** page.

**Comment by kenbasart** [comment]
New tickets created in Jira with new work. Closing ticket.
