### ISSUE TITLE
Was this page useful reporting upgrades

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1093]
Want to:

- [x] Be able to retrieve comments by page groups
- [x] Create preset page groups for each content captain
- [x] Is begin data filter broken
- [x] Show Useful false now that we aren't recording false negatives

**Comment by aaronhans** [comment]
I didn't find a way to speedup so there remains an intermittent cold start problem. I am calling it on this iteration, let's close this task and revisit after the content captain team has used it for a few days and has a new set of requirements

**Comment by abquirarte** [comment]
Works for me. ✔️
