### ISSUE TITLE
Clean up search results

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#111]
Our search results show the social media image multiple times. It looks messy. Can we remove it/ clean it up?

![File (3)](https://user-images.githubusercontent.com/9556188/77487548-f730c000-6def-11ea-8b13-a7830520b5ae.jpg)

**Comment by abquirarte** [comment]
![File (3)](https://user-images.githubusercontent.com/9556188/77487532-ea13d100-6def-11ea-96a3-2844a7b4315a.jpg)

**Comment by carterm** [comment]
Boom!  Thumbnails gone.

**Comment by carterm** [comment]
![BE4054A3-A06C-48AB-B84F-A710DF9CCBBA](https://user-images.githubusercontent.com/6798999/77492249-49c4a900-6dfd-11ea-9c22-fb1558f6bf67.png)

**Comment by abquirarte** [comment]
NIIIIICE! 

We will now *really* have to make sure our metatags are clean and ready for SEO 😆 
cc: @artuoma @coreycaitlin @hilaryhb
