### ISSUE TITLE
What's open search - lookup bug

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1118]
Zip codes in California go up to 96155. But some zip code searches starting at about 94012 return an error message.

Please troubleshoot and fix.

<img width="592" alt="2020-07-28_15-48-35" src="https://user-images.githubusercontent.com/63249920/88729993-ec61a100-d0e9-11ea-95d3-e35e4edd8918.png">

**Comment by thepegisin** [comment]
Replaced by dimmer switch

**Comment by abquirarte** [comment]
always be closing issues 😄 ✔️
