### ISSUE TITLE
Update Content in the Do and Don't List

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#112]
✅  Approved by JIC

### **Change to**

**Do**
- Stay home
- Avoid people outside your household
- Wash hands with soap and water for at least 20 seconds
- Cover your cough or sneeze with a tissue
- Clean and disinfect frequently touched objects and surfaces
- Maintain a safe social distance of 6 feet whenever outside of the house

**Don’t:**

- Leave the house except for essential activities
-  Shake hands
-  Touch your face
-  Go to the doctor if you aren’t sick
-  Stockpile masks or gloves

------- Corey's Notes

This would help with a couple things we're trying to accomplish on the homepage — here's my thought process:

- "Practice social distancing" alone has a post-graduate reading level (reading-level tests are a blunt instrument, but can be a useful gut-check for stuff like this). It's a technical phrase that many of us just learned in the last month, and I suspect that folks who aren't on Twitter or following the news closely may be unfamiliar. "Avoid people outside your household" has a  much higher chance of comprehension.
- I'd recommend putting the walk one last, rather than putting it before handwashing. The hygiene do's are still important, especially for folks in essential sectors or who live/work with vulnerable people.
- For "Take a walk", I don't think we need to specify where — for some people it might be much safer to drive to a trail than to take a walk in their crowded neighborhood — and putting the caveat about staying 6" away in parentheses will make it easier to parse quickly by visually separating the clauses.
- This will keep all list items to 1 line, which will help keep the homepage feeling clean and easy to skim.

**Comment by artuoma** [comment]
This change has been pushed to staging @abquirarte

**Comment by abquirarte** [comment]
Great. Saw it. 👍 to push this to production. Close when done 😄

**Comment by artuoma** [comment]
Change published

**Comment by abquirarte** [comment]
Yay!

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
