### ISSUE TITLE
What's open search - Automate or formalize data updates

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1123]
**What's open search** is currently driven by data in a Google sheet. Manual updates happen when Peggy counts yellow and blue counties on the county map and makes changes accordingly.

Need to see if we can:

- Automate for ease/speed of updating
- Get updates from GO to prevent user error
- Store in a database for backup/versioning purposes

We would still need the ability to make changes to the data in the case it somehow conflicts with other content on the site.

**Comment by thepegisin** [comment]
Replaced by dimmer switch

**Comment by abquirarte** [comment]
🎉
