### ISSUE TITLE
Update Health care page to address, "What COVID-19 Testing and Treatments are covered by the federal goverment’s free uninsured program?"

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1137]
Update Health care page to address, "What COVID-19 Testing and Treatments are covered by the federal goverment’s free uninsured program?"

**Comment by TamaraIDEJA** [comment]
Input from SMEs on this question @JasonKarim 


·         The Families First Coronavirus Response Act gave state Medicaid programs authorization to cover uninsured individuals for COVID-19 diagnostic testing and testing-related services at no cost to the individual.
 
·         The California Department of Health Care Services, in response to this new authority, implemented the COVID-19 Presumptive Eligibility (PE) Program on April 8.  It is now available to individuals with no insurance or who currently have private insurance that does not cover COVID-19 diagnostic testing and testing-related services.  California is also seeking approval of a Section 1115 demonstration waiver to, among other things, cover medically necessary COVID-19 treatment services for those who qualify under the new uninsured coverage group.  These services would be provided at no cost to the individual.
 
·         Additionally, given the current public health emergency, COVID-19 testing, evaluation, and treatment services are deemed as emergency services under Medi-Cal.  Deeming these services as an emergency will allow all Medi-Cal beneficiaries, regardless of their scope of coverage under Medi-Cal or their immigration status, to receive all medically necessary testing, testing related, and treatment services, which may include inpatient or outpatient services related to a COVID-19 diagnosis, at no cost to the individual.

**Comment by JasonKarim** [comment]
@TamaraIDEJA @abquirarte Comment by SME ONLY address the Medi-Cal services (which is a shared cost program between state & federal government), managed by DHCS. This does NOT address what is covered under the Medicare (which is a pure federal program) & was shown in [Health care page Q/A](https://docs.google.com/document/d/1L7NZ90FdqaSnQSzfdOpttJEfyBqXFxgHBsmcUAw2ac8/edit#heading=h.xf3uojlo9njy). 

Is the DHCS asking us to remove the Medicare coverage part entirely or asking us to add Medi-Cal part to it. Medi-Cal part is currently shown at DHCS website.
