### ISSUE TITLE
Update: Great Plates Delivered program extended to September 9th 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1143]
### Content Update 
Great Plates Delivered program extended to September 9th. Please update the website with the documents (attached in the forwarded email) to reflect the new extension date:
Program Guidance 
FAQ (Participants, Food Providers, Local Administrators) 

### Timeline 
COB Friday 

### Content Captain 
@ashleydraper

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
Great plates page and guidance docs are baking

**Comment by ashleydraper** [comment]
These updates are now live
@TamaraIDEJA @abquirarte @thepegisin
