### ISSUE TITLE
Are weddings allowed? Need a more direct answer

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1157]
There are 5 questions about weddings in per-page feedback since 7/17. "Wedding"/"weddings" has been searched on 3,353 times since the site began, making it #3 among search terms. But we don't have an answer that references weddings specifically.

Propose that since weddings and funerals are considered cultural ceremonies that are allowed with restrictions under guidance for public gatherings, we add the words "(like weddings and funerals)" after "cultural ceremonies" in the **Stay home** page Q/A "Are gatherings permitted?" Then searches on "weddings" will yield a result.

- [x] Add "wedding" to appropriate Stay home page Q/A in Staging

Also propose that it be added to **What's open** data. **This will not, however, come up in site search.**

- [x] Add "Weddings" to What's open data
- [x] Get approval
- [x] Publish

**Comment by abquirarte** [comment]
this has a dependency. Moving to the backlog

**Comment by thepegisin** [comment]
- [ ] Latest approved language from stakeholders received and added to [Staging doc](https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#).
- [ ] Add links to updated gatherings guidance when released
- [ ] Publish
