### ISSUE TITLE
Add link to NIH Clinical Trials so that people can sign-up for Vaccine or Drug Trials

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1158]
Trying to address “Is this page useful?” comment about “Vaccine trials.” COVID-19 vaccine & drug clinical trials are in the news everyday and some people are interested to sign-up:

- [x] Content Drafted

- [x] Reviewed by @thepegisin 

- [x] Approved by @abquirarte

**Comment by abquirarte** [comment]
Thanks @JasonKarim ! 🚀
