### ISSUE TITLE
IA fix: Separate and simplify "Know symptoms and risks" and "Testing and treatment"

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#116]
**The current situation:**
 
Before the Stay Home order, several sections of content were collected under the page title "What you can do." Users got to sections on this page through 3 links from the homepage: "Know symptoms and risks," "Avoid group events," and "Testing and treatment." We removed _most_ of the content under "Avoid group events," along with the homepage link to that section, after the Stay Home page was built and took over that messaging. See also #104 

**The problem:**

- "What you can do" is now a confusing title for that page, because "what you can do" now means, for most users, _what is allowed under the Stay Home Order_ instead of _how you can protect yourself from coronavirus_. 
- "Testing and treatment" content needs to grow as we get more information and aim to answer more user questions about how to get treatment, including telehealth resources, testing capacity, treatment capacity, and how to take care of yourself at home.
- The "Avoid group events" is now a misleading orphan that no longer reflects the latest policy. The Stay Home Order page is the current info.

**The solution:**

- [x] Move "Testing and treatment" content to a new WP page and publish
- [x] Move "Symptoms and risks" content to a new WP page and publish
- [x] Redirect `/what-you-can-do/` to `/stay-home-except-for-essential-needs/` (only relevant for folks who had saved/linked that page; we would remove all links on the site)
- [x] Change link destinations in Homepage righthand link-list so they go to new pages
- [x] Change link destination in content page right nav so they go to new pages
- [x] Delete existing "What you can do" page in WP (Once redirect is working)

This should require no content changes, and be functionally invisible to users, except that the UX will be slightly less confusing because those two links on the right will go to different pages instead of sections of the same page.

**Comment by abquirarte** [comment]
👍

**Comment by abquirarte** [comment]
If you delete what you can do, will it mess up the re-route?

**Comment by coreycaitlin** [comment]
We'll leave the redirect to the pros like @artuoma

**Comment by abquirarte** [comment]
and @ChadABratton @carterm

**Comment by coreycaitlin** [comment]
New pages are here:

- https://covid19.ca.gov/symptoms-and-risks/
- https://covid19.ca.gov/testing-and-treatment/

**Comment by artuoma** [comment]
Ok thanks taking this from here, thanks!

**Comment by abquirarte** [comment]
@carterm the can you double confirm the re-direct is working (before we delete from WP)
