### ISSUE TITLE
Improperly formatted link

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1172]
One string of text is broken into two different links. Assumption is that this should be a single link.

<img width="735" alt="Screen Shot 2020-08-03 at 3 12 17 PM" src="https://user-images.githubusercontent.com/69167298/89218391-f0833800-d59b-11ea-9820-dab7b42afcda.png">

https://covid19.ca.gov/business-and-employers

**Comment by abquirarte** [comment]
nice @adam-little ! 

@LizNobriga can you review? :)

**Comment by LizNobriga** [comment]
fixed!

**Comment by abquirarte** [comment]
sweet, thank you!
