### ISSUE TITLE
Request for redirects

### ISSUE THREAD

**Issue by kimberlyglennTeamSuccessManager** [cagov/covid19#1175]
@carterm  - can you please add the redirects
[English Redirects.xlsx](https://github.com/cagov/covid19/files/5019058/English.Redirects.xlsx)

**Comment by aaronhans** [comment]
These are all on our blob storage. We can't setup redirects in our config like we did before. We can get these added to front door though. This is not usually something our team manages. The plan was to open a CDT ticket for Chad to set these up. I don't think creating these is incredibly urgent so we might be able to wait until Chad's return. When redirects are in place the content team can delete the older file urls.

**Comment by kimberlyglennTeamSuccessManager** [comment]
Thank you @aaronhans
