### ISSUE TITLE
IA fix: Split "Employment" and "Taxes"

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#118]
**The situation:**

Because we wanted 6 boxes in the category section of the homepage, we combined information for employers, workers, and about taxes into a single page called "Employment and taxes."

We now have a new page called "Get financial help", which will house the existing "for workers" content as well as newly-announced (as of 3/25) information on financial relief from mortgages and fees. This is great (more help for people!) but means we've outgrown the combined page and now have duplicate content on both pages, which will make it harder to maintain.

**The solution:**

- [x] Move taxes content to its own page in WP
- [x] Add category box on homepage to link to new "Taxes" page
- [x] Remove "for workers" content from "Employment and taxes" page (it's already on the new "get financial help" page)
- [x] Change page title to "Employers and small businesses"
- [x] Change homepage category link to "Employers and small businesses"
- [x] Add Small Business content to "Employers and small businesses" page once approved

**Comment by coreycaitlin** [comment]
Liz pulled the Taxes content into a [new draft doc](https://docs.google.com/document/d/1uon27XQKSJNADP8t5NIUyBffw5K1PbkNnJ-xrVCVlQ0/edit#heading=h.wp5qwujjv5tl) for tracking future edits and revisions. 👏

**Comment by abquirarte** [comment]
This is now done!
