### ISSUE TITLE
Updated guidances- "should" to "must" language

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1182]
## context 
We had to make changes to most guidance documents in English to reflect the legal change request below. **This issue will track the incoming guidances that have been received and reflect the change.**

## timeline 
End of week, rolling basis. 

> Please note that this version includes the revisions that CalOSHA’s legal requested. This revision was in the Required Use of Face Coverings section, and changed ‘should’ to ‘must’. With this revision made, the guidance reads “Employers must provide face coverings to workers or reimburse workers for the reasonable cost of obtaining them.”

## places of worship ✅ replaced
The attached guidance is in the order listed below:
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Fitness ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Hair Salons ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## personal services ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Agriculture ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Communication Infrastructure ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Auto Dealerships ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Restaurants, Bars, Wineries ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Family entertainment ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Cardrooms and racetracks  ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Campgrounds ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Outdoor museums 📥 in your inbox
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Zoos and museums ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Hotels, lodging, rentals ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Dine in restaurants 📥 in your inbox
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Shopping centers ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Retail ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Real Estate ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Office workspace  ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Logistics and warehouse 📥 in your inbox
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Manufacturing ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Life science ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Hotels  ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Food packing 📥 in your inbox
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Construction  ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Energy and utilities ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

## Delivery services ✅ replaced
Arabic
Armenian
Chinese Simplified
Chinese Traditional
English
Hmong
Khmer (Cambodian)
Korean
Russian
Spanish
Tagalog
Thai
Vietnamese

**Comment by LizNobriga** [comment]
The 12 translated pdfs received for hair salons are live now.

**Comment by LizNobriga** [comment]
12 translated fitness guidance pdfs are live now

**Comment by LizNobriga** [comment]
12 translated place of worship pdfs are live now

**Comment by LizNobriga** [comment]
Are we finished @abquirarte?

**Comment by abquirarte** [comment]
Just sent you a new batch! :) Thank you! Updated main issue above! @LizNobriga

**Comment by LizNobriga** [comment]
12 translated expanded personal care services guidance pdfs are live now.

**Comment by abquirarte** [comment]
I'll keep this open since I anticipate we will get more!

**Comment by LizNobriga** [comment]
Who will be shadowing on this?

**Comment by abquirarte** [comment]
We received 3 new ones tonight (updated main issue on original list above with 📨 in your inbox). 

Sent this to @LizNobriga @thepegisin @m-sullivan7 @JasonKarim and @ashleydraper so that we can do another round of shadowing/screensharing. 

## Timeline- by end of day tomorrow

**Comment by LizNobriga** [comment]
Auto dealerships is done

**Comment by ashleydraper** [comment]
Agriculture is done

**Comment by orielgomez** [comment]
Communications is done

**Comment by abquirarte** [comment]
- [ ] Check for date 
- [ ] Check for metadata 
- [ ] Ask if it's accessible 
- [ ] Add to tracking sheet 

Who will be working on which one?

**Comment by LizNobriga** [comment]
- [ ] Restaurants, bars, and wineries @m-sullivan7 
- [ ] Family entertainment centers @ashleydraper 
- [ ] Cardooms, racetracks
- [ ] Campgrounds and outdoor recreation

**Comment by m-sullivan7** [comment]
Restaurants, bars, and wineries PDFs are live.

**Comment by ashleydraper** [comment]
@abquirarte @thepegisin 
These guidance are now live - 
Family entertainment centers 
Campgrounds and outdoor recreation
Hotels, lodging, and rentals
Manufacturing
Hotels

**Comment by m-sullivan7** [comment]
@abquirarte The following translated guidance is live:
- Zoos and Museums
- Real Estate
- Office Workspaces

**Comment by LizNobriga** [comment]
Translated guidance PDFs below `live` and checked/tracked for `dates` and `metadata`:
- Delivery services
- Energy
- Shopping centers
- Life sciences
- Retail

**Comment by orielgomez** [comment]
@abquirarte and @thepegisin 
The following PDFs are uploaded and live:

1. Outdoor museums
2. Dine-in restaurants
3. Logistics and warehousing
4. Food packing
