### ISSUE TITLE
Translation drop down doesn't work after using Google Translate

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#1215]
To reproduce

1. Select "Select language" in the page header.
2. Select "More..."
3. Choose any language from the Google Translate dropdown
4. Attempt to click on the "Select language" button again (the text)
Result, no dropdown
Expecting, dropdown.

Note, clicking on the arrow still shows the dropdown.

**Comment by carterm** [comment]
inspecting the html after Google does it works shows a font wrapped around the text...
```
<font style="vertical-align: inherit;"><font class="" style="vertical-align: inherit;">
              Pagpili sinultian
            </font></font>
```

**Comment by kkoryaka** [comment]
Gmm, I wonder if that's google js that adding font tag into our button.

**Comment by kkoryaka** [comment]
It's adding <font> tag to every drop down button, including main menu, not only translation.

**Comment by kkoryaka** [comment]
Adding class="notranslate" to "Select Language" button fixes  the bug but that elements stays not translated which is not the result we want. Will keep digging

**Comment by carterm** [comment]
Solution was to add this to css...
```
font {
  pointer-events: none;
} 
```
