### ISSUE TITLE
site navigation in a full page overlay

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1216]
- [x] Migrate features from prototype like launch from header with animated icon into full screen overlay
- [x] do not slow down page render
- [x] present all nav links in appropriate language
- [x] add big search bar, make it functional
- [x] preserve staggered animation in the link category sections
- [x] encapsulate as custom element
- [x] remove unnecessary dependencies in prototype code
- [x] remove global DOM modifications
- [x] a11y bug in web component version: aria-hidden target is missing 
- [x] integrate into transpiled bundle for legacy browser support
- [x] add code for menu expansion on mobile

**Comment by abquirarte** [comment]
beautiful 

cc: @kenbasart
