### ISSUE TITLE
State Alert-notifications

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#122]
From: Caroline Kilvein <Caroline@politicalsolutions.us>
Sent: Saturday, March 21, 2020 10:40 AM
To: CIO Info <Info.Eservices@state.ca.gov>
Subject: I need assistance from CA.gov
Importance: High

 

Is there a way to be added to press releases via email alerts instead of having to constantly checking the website? Specifically looking for alerts on the following:

 

https://www.covid19.ca.gov/

 

Sometimes updates are happening at odd times and there is no way of knowing unless we are constantly checking the website.

Many thanks!

Caroline

 

Caroline Kilvein

Political Solutions, LLC

1414 K Street, Suite 400

Sacramento, CA  95814

916-492-2766 phone

916-443-5807 fax

caroline@politicalsolutions.us

**Comment by abquirarte** [comment]
What if we use this a way for people to subscribe to covid19.ca.gov updates? They would get notified when we push updates to the website. They could select the types of updates they want? 

- Latest news
- education
- taxes
- get financial help
- stay home order
- businesses and employers 

etc?

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
