### ISSUE TITLE
Covid 19 Google Slides Template

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1229]
Create a Google Slides template for presentations related to COVID 19 work. 

This would build off the work started here: https://docs.google.com/presentation/d/1rKL_GB362eAohFxJTriVVHHDQTxAa7L1natIsgYkJrg/edit?ts=5f2c13e4#slide=id.p1

**Comment by abquirarte** [comment]
This is now lower in our priorities, but a we will definitely still need this! I think our convos around project kennedy may inspire you on this :) 
@adam-little (keeping in our backlog for now)

cc: @kenbasart
