### ISSUE TITLE
 Guidance for Institutions of higher education

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1245]
Receiving guidance PDF for Institutions of higher education. Counties on the monitoring list must close indoor operations at institutions of higher education. 

Requires changes to multiple pages and items:
- Industry guidance
- Education
- Stay home
- Banner
- 'What's open?' search data

**Comment by LizNobriga** [comment]
Industry guidance [staging doc](https://docs.google.com/document/d/1HnIaLyk1NpfJJo00F40dS6Kbo6GgkQBDN57Ae5zmPnY/edit)

**Comment by ashleydraper** [comment]
Education [staging doc](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit#)

**Comment by LizNobriga** [comment]
Publishing is live for:
:white_check_mark: Banner 
:white_check_mark: Stay home 
:white_check_mark: Education 
:white_check_mark: Industry guidance

Content scraper updated (thanks @aaronhans)

**Comment by abquirarte** [comment]
Amazing!
