### ISSUE TITLE
Link to contribution form on "What you can do" - Give supplies or resources

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#125]
Add a an action link to the right- that points to: https://state-of-california-agency.forms.fm/non-monetary-contributions-for-california-covid-19-response/forms/7781 

Name: "Give non-monetary contributions" @coreycaitlin @hilaryhb 

- [x] Test/update language so it's not to be confused with monetary donations

![image](https://user-images.githubusercontent.com/9556188/77671120-615a7980-6f44-11ea-8dcd-4eb2fe804a12.png)

**Comment by hilaryhb** [comment]
Idea-storming:
- Is it Give? Offer? 
- resources is nice? 
"Give things" 
Donate supplies, technology, and space
I really dont like non-monetary
Is this for only large donations/contributions? What if I make 10 homemade masks that having been "meme-ing? 
Also the site should, if they can, add how long too expect a response or contact. Or even, a feedback response once submitted, thank you, we received your offer. We may not be able to get back to you soon, please excuse the delay?" something like that? @abquirarte

**Comment by abquirarte** [comment]
They have a draft response: 
__Thank you for contacting the Contributions team at Cal OES. At this time we are gathering information on all available resources. If there is a need identified by any of the offers, a Cal OES representative will contact you shortly._

_Due to the high volume of offers of assistance we are currently receiving, please be patient on our response time._

_If you are interested in volunteering your services for response efforts, please contact California Volunteers at
www.Serve.CA.Gov to register._

_Thank you.__

**Comment by abquirarte** [comment]
> Idea-storming:
> 
> * Is it Give? Offer?
> * resources is nice?
>   "Give things"
>   Donate supplies, technology, and space
>   I really dont like non-monetary
>   Is this for only large donations/contributions? What if I make 10 homemade masks that having been "meme-ing?
>   Also the site should, if they can, add how long too expect a response or contact. Or even, a feedback response once submitted, thank you, we received your offer. We may not be able to get back to you soon, please excuse the delay?" something like that? @abquirarte

I don't like that either. "Give resources to COVID19 response" ? 

@coreycaitlin what do you think?

**Comment by abquirarte** [comment]
- [ ] Angie to get final approval
- [ ] Add "Offer supplies and contributions" link to: https://contributions.covid19.ca.gov/

**Comment by artuoma** [comment]
Link in staging.

**Comment by abquirarte** [comment]
Thank you! We'll be ready.
I think this may be pushed back a day @artuoma - today's big announcement will be around education.
