### ISSUE TITLE
NCS Housing for Food and Ag Workers

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1261]
Hi All,
 
### Context

The department is getting close to launching in their first county! they would like to add a section like Great Plates has (below) for housing.
 
### Content -- Looks like they only want to stage it...!
Want to get meals? 
Learn more about the program by contacting an administrator in your city or county
 
For ours it would be in the:
**How can I apply?** 
Learn more about the program by contacting the lead administrator in your county

**The first county is:**
Fresno County: Fresno Employment Opportunities Commission, (559) 400 2881
 
### Timeline 
COB Today/Tomorrow am

### Content Captain 
@thepegisin

**Comment by thepegisin** [comment]
Added to Staging doc, ready for review: https://docs.google.com/document/d/1uTWYYSaia5AK-KDGum9Wk-ZsJHn87TIqwBYgc6vlZ9A/edit#

**Comment by abquirarte** [comment]
@thepegisin can you stage this the page on WP? 🙏

**Comment by thepegisin** [comment]
- [ ] Staged on staging server: https://staging.covid19.ca.gov/housing-for-agricultural-workers/

**Comment by abquirarte** [comment]
Comment from SME (in your inbox 📨) 

"We aren’t taking applications per se. Could we instead have:"
**How can I participate?**
_Participate in this program by contacting the administrator for your county._ (have the plus/drop down from this)

~Counties taking applications for housing agricultural workers:~
_More counties will be added to the program soon._

☝️ "Participating" may be confusing. Any suggestions @thepegisin ?

**Comment by thepegisin** [comment]
I am definitely confused. I thought this was messaging aimed at ag workers who need a hotel room.

- Who is the audience for this section?
- What are they trying to do by calling Fresno?

**Comment by thepegisin** [comment]
Clarified by meeting with Arima Zorina. Edited in Staging doc. Awaiting final approval, estimated 8/19.

**Comment by abquirarte** [comment]
Still waiting on approval. We may be adding more counties per Food and Ag SME 

cc: @kenbasart

**Comment by thepegisin** [comment]
Still holding, per Arima Zorina.

**Comment by abquirarte** [comment]
Can we send Arima the latest that we have in staging so they know what content we would be going live with once they give us the GO? 

@kenbasart / @thepegisin

**Comment by abquirarte** [comment]
@kenbasart mind updating this issue? 
I think we are live right?

**Comment by kenbasart** [comment]
Yes closing now @abquirarte
