### ISSUE TITLE
Broken link on Manage stress page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1263]
The California Surgeon General's Playbook: Stress Relief During COVID-19 is showing up as a broken link on the English **Manage stress for health** page.

<img width="566" alt="2020-08-10_15-38-06" src="https://user-images.githubusercontent.com/63249920/89838347-ddcead00-db1f-11ea-9faf-16bf40b9cf47.png">

All the translated versions of this page are showing the link as broken, too. Please make sure the translated versions are in the right place with the right name so an English update to the page fixes the translated pages.

**Comment by ashleydraper** [comment]
This link has been fixed and the [playbook is now live](https://covid19.ca.gov/manage-stress-for-health/#top) in English. 
Proposing we leave this issue open until I can ensure that the playbook link is corrected in the other languages. It is currently inaccessible in all other languages

**Comment by abquirarte** [comment]
Thank you @ashleydraper ! We'll keep this open and in to do. 

cc: @kenbasart

**Comment by ashleydraper** [comment]
Status: still awaiting translation

**Comment by ashleydraper** [comment]
This is done. Proposing to close this issue
@kenbasart @abquirarte @thepegisin

**Comment by kenbasart** [comment]
Closing per @ashleydraper
