### ISSUE TITLE
Medical Corps Volunteer List - 1st draft

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#127]
### Context
>CHHS Agency leadership requested that the CDT, Alpha and OI teams work with EMSA to find potential efficiencies in the Disaster Healthcare Volunteers and CAL-MAT processes. Typically, this process handles hundreds of volunteers, but the COVID19 effort requires the process and supporting technology to support 10,000 or more.

>Currently, applicants must complete two applications on two different sites. The first is the DHV website which collects their medical license and experience. The DHV site and backing system is run by a third party vendor. The DHV system also provides the communications system to reach and coordinate volunteers. The second is the CAL-MAT process to complete the CalHR process allowing them to be paid as employees of the state. This is cumbersome for both volunteers and staff. Typically, the review process can be sped up by adding more reviewers, but this does not easily scale up. 

- [ ] Scope and map out process: https://docs.google.com/document/d/11MKTA9SB2IP2LdElfqxfq4D6wHc2pJIMW5GFczzbhk8/edit#
- [x] Information Tracking and planning updates: https://docs.google.com/document/d/1f7-zyh8SGN7oH_HpsBdgtCt_NpHpgwUY3BT3dTe0J8w/edit
- [x] Confirm Step 1- vetting process. ~(EMSA vendor or Screendoor)~ 
_We will use EMSA's existing page_
- [x] Identify the owner of this process
- [x] Create landing Page 
- [x] Draft content for this page- Corey

**Comment by abquirarte** [comment]
Draft language from CHHS- Letter.... 
[HealthProfessionals_Letter.docx](https://github.com/cagov/covid19/files/4389853/HealthProfessionals_Letter.docx)

**Comment by coreycaitlin** [comment]
I think this letter could be edited down slightly, but I think the letter format _could_ make sense here. I'd shorten slightly:

> Dear Health Professionals,
> 
> As California responds to the COVID-19 outbreak, we are preparing for an increase in the number of people who urgently need health care in our communities. To serve Californians and support our health care system, we are preparing to open additional health care sites to provide medical services both for people who have symptoms of or test positive for COVID-19 and to relieve the pressure on our health care system by providing care for non-COVID cases.
> 
> We need your help. To ensure adequate staff for these sites throughout the state, we’re calling on health care providers, behavioral health professionals, and health care administrators. Skills we need include:
> 
> - Physician (MD, DO)
> - Pharmacist
> - Dentist
> - Nurse practitioner
> - Physician assistant
> - Nurse (RN, LPN, LVN, CNA)
> - Behavioral health professional (psychiatrist, psychologist, psychiatric nurse practitioner, LCSW, LMFT, LPCC)
> - Respiratory therapist
> - Paramedic
> - Medical assistant
> - Certified nurse assistant
> - Emergency medical technician
> 
> You have the opportunity to play a critical role in responding to this public health emergency in your region. To care for Californians who need your help, please sign up. We will contact you with information about serving in one these health care sites.

I think it's also worth addressing whether it's paid, or whether we're asking people to volunteer for a *very* hard job.
