### ISSUE TITLE
Translations documentation 

### ISSUE THREAD

**Issue by orielgomez** [cagov/covid19#1273]
Highlighting our work done in multilingual content in preparation for our translations wiki:

The working document for our translations work can be found in the translations drive [here](https://drive.google.com/drive/folders/1NVhI1qSy5zOc_Ju1WbMK4_uij2RTOXvx).

Supporting documentation for final document:

- Daily translations flow can be found [here](https://docs.google.com/document/d/1mDzrS2rCzEDoqXpdwkYVxKTo7heWK32lI3-OFHoi8DQ/edit#)

- Translations pipeline can be found [here](https://docs.google.com/document/d/1Y74qSIXeK0iW-2354ZhNxcN0VW3j1LfXPZHEYtGRB2A/edit#)

- Translations drive which holds all translated PDF guidance docs can be found [here](https://drive.google.com/drive/folders/1eHXUiLVRZ-wbo9gcmKdlh8D4rH3EcKSm)

**Comment by abquirarte** [comment]
## FYI ☝️ 
@kenbasart @hannahslee

**Comment by abquirarte** [comment]
@kenbasart Please look at this and make sure that the documentation above is properly saved in our shared folder. 
CC: @KimberlyglennTSM  @hannahslee 
Let me know if you'd like to discuss. 
Closing issue for now.

**Comment by kenbasart** [comment]
@abquirarte Yes those links go directly to the documents in the Translations folder in the Google Drive:

https://drive.google.com/drive/folders/1P79oAGZDVRWPmjSFZio_9CVvoc5xoWOi
