### ISSUE TITLE
rein in dependabot

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1279]
dependabot is opening a lot of PRs against master 
- we need to review these to make sure they don't break the build, they are all development dependencies but the build broke once
- we can only have one automatically browseable branch create dynamically from a pull request using azure static web apps
- this causes broken build messages on all master PRs because the azure browseable PR branch limit has been reached

So we want to let dependabot target a different branch and build from there automatically

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/pull/1277

**Comment by abquirarte** [comment]
🙏
