### ISSUE TITLE
homepage design: make video section data driven

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1294]
This got hardcoded in our trilogydev branch. We need to make it data driven again so it gets translated properly and can be updated by the content team

**Comment by carterm** [comment]
This is mostly structure, so a bad candidate for a Wordpress file.  I'll work on making the English headers extractable.

**Comment by aaronhans** [comment]
This might be a little tricky: We are going to want to let the content team swap in new videos at will @carterm 

Also they are going to probably need to use a different video on the translated homepages

**Comment by carterm** [comment]
Added a "VideoID" that can be changed and set per language with all the other translations in the homepages.
https://github.com/cagov/covid19/pull/1454
