### ISSUE TITLE
make the build system hella faster

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1299]
faster please

**Comment by aaronhans** [comment]
I am going to link all the PRs you've got going here @xjensen 
I'll merge them to staging, then trilogydev and do some testing

**Comment by aaronhans** [comment]
split up PRs:
https://github.com/cagov/covid19/pull/1290
https://github.com/cagov/covid19/pull/1286
https://github.com/cagov/covid19/pull/1285
https://github.com/cagov/covid19/pull/1284

big one being split into smaller ones https://github.com/cagov/covid19/pull/1250

**Comment by xjensen** [comment]
Thanks, @aaronhans! Feel free to ask any questions. 

We'll likely need additional commits and/or PRs to bring these four smaller PRs together into something resembling #1250. Next steps will depend upon what makes the cut from this first round. For example, I don't believe any of my smaller PRs include the `npm` script needed to trigger the development mode. I can add that later, for sure; it just doesn't make sense as a small stand-alone PR until a few of these other PRs are merged.

If there's anything I can do to help further, just let me know.

**Comment by aaronhans** [comment]
I've got stuff merged into trilogydev and staging. I replaced the gulp build step in the trilogydev branch because we are doing a lot of work in there.

**Comment by xjensen** [comment]
Two new PRs related to this: #1305 and #1306. Both are pretty basic. I think the `trilogydev` branch may be going without an _es5.js_ file at the moment, so #1305 (or a different Rollup/Webpack combo) may be important there.

New CSS builds are currently failing for me on the `staging` branch due to duplicate basenames between the _cagov-font.css_ and _cagov-font.scss_ files. Deleting one file or the other seems to be making different icons fail. Interesting. But I'm wondering if I should spend the time to troubleshoot since `trilogydev` will eventually solve this problem anyway.

One idea. I'm thinking we could speed up the Eleventy build process by moving some of the heavy HTML manipulation upstream, to Wordpress or some other process. I'm specifically thinking about the function that converts the Wordpress accordion into a web component. Would writing a Wordpress plug-in be off the table for any reason? I don't know much about how that part of the site works so I'm just making guesses about what's possible.

**Comment by aaronhans** [comment]
I was thinking the same thing about the 11ty build process: https://github.com/cagov/covid19/issues/1154

**Comment by aaronhans** [comment]
@xjensen can we try something like this as a strategy to get all this merged:
- open PRs from master but target trilogydev
This lets us review and understand the different upgrades, then take merge steps into our most active development branch. It will also help us keep trilogydev closer to master, I ran into some drift issues yesterday
- merge all these build upgrades into both trilogydev and staging right after approval
This should help us catch some issues that might happen in master
- close open build upgrade PRs targeting master but work to frequently synch master and trilogydev

Happy to hear entertain other approaches. We are looking at a big bang merge into master which sucks but if we clean up the open PRs against master we'll be able to take advantage of the static web app service that is currently creating a built, browseable instance of one PR against master at a time.

I will address the dependabot PRs, I fixed a dependabot.yml syntax issue that should point those at dependabotprs branch in the future.

**Comment by xjensen** [comment]
I think I understand. Just to clarify.

Step 1. When opening new PRs, use master as the base, then target into trilogydev.
Step 2. After approval, merge PR into staging and trilogydev. 
Step 3. Close PRs. Sync up master and trilogydev when possible.

I think the key for the build upgrades will be in how we handle step 3. With master as the base, I'll be unable to build on top of the stuff that's now in staging and trilogydev. Or, at least that would be the case until some of those changes make their way into master. I'm wondering which direction is favored between trilogydev and master, if we want to make trilogydev more like master, or master more like trilogydev. Apologies for the questions, I just want to make sure I understand the thinking.

**Comment by aaronhans** [comment]
This is a huge upgrade! Thank you for doing so much on your own initiative

- All build updates have been merged into trilogydev branch. This is looking great and we'll work together to solve any issues that come up. Really awesome improvements, thank you!
- We plan to try and ship the trilogy redesign in trilogydev branch at the end of next week but we still have a lot to do. If we have time it would be good to separate the build upgrades and ship those separately before the trilogy redesign updates. If not the build upgrades will go out with the design updates.
- I know you made safe, separate PRs against master. These were helpful in highlighting important pieces of the upgrade but it'll be easier to test one PR which swaps in the new build system so I closed the open PRs against master

**Comment by xjensen** [comment]
Sounds like a plan! 

I've started adding the build upgrades to a new branch, new-build-system. This branch is based off of master. All the upgrades are there and working, I think. I'll check and test it thoroughly tomorrow night.

**Comment by aaronhans** [comment]
latest build system upgrades only open PR browseable here: https://lively-river-07342ea1e-1395.westus2.azurestaticapps.net/

**Comment by aaronhans** [comment]
Shipped! Great work @xjensen!
