### ISSUE TITLE
Banner for today Friday Aug 14- Education page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1319]
Drafted language sent to GO for approval. @thepegisin 
Documented in [this Slack thread. ](https://cadotgov.slack.com/archives/G01493HF6CU/p1597420743043500)

We may also want to include in Education page @ashleydraper

**Comment by ashleydraper** [comment]
Pasting the updated [staging doc](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit#) here 

@abquirarte @thepegisin

**Comment by abquirarte** [comment]
✔️ 
Both now live!

cc: @kenbasart
