### ISSUE TITLE
new homepage: no scroll listener without debounce

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1322]
I saw a js scroll listener get added to menu/index.js

I wonder if it is necessary, maybe that drop shadow can always be there
If we want to use a scroll trigger we need to put it in the right place and debounce it

**Comment by xjensen** [comment]
I saw this Issue today, so went ahead and replaced the scroll listener with an IntersectionObserver. [Here's the commit.](https://github.com/cagov/covid19/commit/934146212c4ce6b46d071e665cd0fa67a71351da) Hope this is okay. 

It's pretty efficient on modern browsers but might need an additional polyfill for IE11. I'd need to check.

**Comment by aaronhans** [comment]
I like this. It does cause a problem in IE11 because it is not supported. It is fine to skip the feature in IE and wrap the reference in an availability check rather than bothering with a polyfill.

**Comment by xjensen** [comment]
Good idea, [I'm on it](https://github.com/cagov/covid19/commit/5bd315af366a6781bfc9bb176f238265ce24bf21).

**Comment by aaronhans** [comment]
Thanks @xjensen!
