### ISSUE TITLE
COVID 19 Site Map

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1328]
@hannahslee has requested a site map for covid19.ca.gov to create a single source of information about the site that can be used in scoping decisions. This map should include:

- Site hierarchy/navigation paths
- Page titles
- Navigation title (if any)
- Links found on page

- [x] Tool selection @kenbasart 
- [x] Information gathering @m-sullivan7
- [x] Confirmation of completeness

**Comment by abquirarte** [comment]
@kenbasart I was tracking style guide consolidation here: https://github.com/cagov/covid19/issues/1202 

Is this a different thing?

**Comment by kenbasart** [comment]
My mistake, updated ticket

**Comment by m-sullivan7** [comment]
@kenbasart I've completed [the site map](https://miro.com/app/board/o9J_knThnWY=/). Would you review to ensure that nothing's missing from your point of view before we deliver to Hannah and confirm this work is complete?

**Comment by m-sullivan7** [comment]
Reviewed

**Comment by m-sullivan7** [comment]
Completeness confirmed, @thepegisin and @m-sullivan7 to provide a heat level for each page.

**Comment by m-sullivan7** [comment]
@hannahslee "heat" levels added on how much we're touching each of these pages. https://miro.com/app/board/o9J_knThnWY=/ Key at the top of the map. Confirm we can close this ticket?
