### ISSUE TITLE
covid19.ca.gov- PD feedback- Clean up

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#133]
We've collated our feedback and some advice for the covid-19 website which I've copied below. Please take these as suggestions - we don't know your context well enough and understand you have many constraints. We think the site is brilliant and you're doing a great job.

**Consider changing the way you’re structuring your content** 

- More emphasis on the most important message - stay at home.
- Say less, for example by turning questions into statements
- Reduce the dos and don’ts - do you need to tell people to not shake hands when they should simply be staying home more than anything?
- “What you can do” panel detracts from the more important message of “Do”

**Switch ordering of content** 

- On the homepage, push marketing to the bottom (e.g. CA is working around the clock, Latest numbers, Latest news), bring services up higher. You could also spin the marketing content around (e.g. CA has “Made testing free for most Californians who are medically eligible for testing” to “How to get tested..”)
- Consider reordering content on other pages. For example, the questions on the Education page go from access to free/reduced meals, to marketing about internet access, and then back to services for students with disabilities.

On content style, we think the guide is great and the sentence length and tone you’re using is spot on. Some of the pages could still do with more work on that front, e.g. the Get Financial Help page still uses quite technical language. 

**Navigation**

- The logotype “ca.gov” unexpectedly links back to gov.ca.gov, rather than the homepage for the covid information.

**Reduce amount of emphasis on pages so as to not overwhelm reader**

- Try to limit bolding to only the single most important action or information on a page
- Reduce black text shade to a very dark grey
- On individual pages, left side navigation is very large on desktop and may be easier to use/less visually overwhelming if the size/padding was reduced to take up less width

**Search**

- Some common terms are not showing obviously useful info (there’s no exact match for “no insurance”, for example).

>Add similes / plain language
 >Some terms have no clear matches “find food bank” - it may be that the State doesn’t/can’t provide that information

- Use analytics to check whether people are using internal search / how they’re using it and prioritise appropriately.

>If most users still come from outside or seem to be confused by results, it may be better to have no search at all on the site and deprioritise that work.

**Comment by hilaryhb** [comment]
@abquirarte 

The above PD feedback is great and I am a +1 on all things they say. In addition, I would **consider** the following changes:

- Toolkit page "acts" very different from all other service pages. Consider changing it to "Media toolkit" or something that indicates it's about social media sharing and tools, not for a user coming in to find out info and services

- Q/A are going to get longer and longer. What have been the discussion around collapsing the answers and only if you click you reveal the answer. This will enable people to quickly skim the questions and click on ones they have versus finding them (especially important on mobile)

- Some of the questions fall under multiple categories, should we revisit the descriptions and what makes sense where -- ie "for the employee" under get financial help makes sense but it also makes sense under employment. 

- Moving newer information or policies to the top of the answers w an "updated date"

- Move Latest news and what CA is doing down -- on mobile its a lot to scroll through before services (PD mentioned this too -- feels way to marketing speak than direct and trying to help people get info quickly)

- Over this weekend, the numbers weren't updated at all. As of 3/30 at 830 am, it lists 3/27 2 pm w latest numbers. To a user, that feels like this site isn't representing trustworthy info (or relevant, up-to-date)

- Get local info is hosting the homeless and incarcerated questions - not sure this is where these should live - I think people think that there are State level things to do be done about homelessness even if this isn't the case

**Comment by abquirarte** [comment]
@coreycaitlin if you can + on any of these, it will help prioritize :)

**Comment by abquirarte** [comment]
- [ ]  Is it still comforting calming? Or does it add to the chaos? 
- [ ] latest news have the clickable headline and take out the summary text underneath
- [ ] Central FAQ 
- [ ] More plain language in the service and info pages

**Comment by abquirarte** [comment]
#162 clean up:
- [ ]  Public places [move content and redirect to Stay home FAQ]
- [ ] Add meta descriptions to 4 new pages: homelessness, workers, business, taxes
- [ ] Add banner (Later)

**Comment by coreycaitlin** [comment]
Right now, this (related) content is buried on the [Healthcare page](https://covid19.ca.gov/healthcare/#top), and reads:

> I am nervous or scared. What can I do?
> 
> You’re not alone. Strategies for managing stress include:
> 
> Limit your intake of information from news sources about the virus
> Maintain social contact with friends and family by phone, text, or internet.
> Treat your body kindly: eat healthy foods and move your body.
> Call your health care provider if your anxiety prevents you from being able to continue with your daily activities.
> Here are some articles with helpful advice about managing stress and anxiety about coronavirus:
> 
> Centers for Disease Control and Prevention (CDC): Mental health and coping during COVID-19
> County of Los Angeles Public Health: Coping with stress during infectious disease outbreaks (pdf)
> If you have Medi-Cal and are in need of non-crisis mental health services, contact your County Mental Health Plan.
> 
> If you are feeling overwhelmed with sadness, depression, or anxiety, or feel like you want to harm yourself or others, call 911 or the Disaster Distress Helpline (1-800-985-5990) or text TalkWithUs to 66746. (TTY 1-800-846-8517)

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
