### ISSUE TITLE
Business page iteration

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1330]
1. Existing content needs thorough review and update
2. Page structure needs some reorganization since the original purpose (financial help) has shifted to include lots of other things related to reopening safely, supporting employees, etc.
3. Move content related to small business taxes to Taxes page - @m-sullivan7 ([staging doc for Taxes](https://docs.google.com/document/d/1uon27XQKSJNADP8t5NIUyBffw5K1PbkNnJ-xrVCVlQ0/edit?usp=sharing))

**Comment by LizNobriga** [comment]
page reassigned to @ashleydraper

**Comment by ashleydraper** [comment]
Adding @m-sullivan7

**Comment by ashleydraper** [comment]
Here's the [business and employers page](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#) for reference

@m-sullivan7

**Comment by m-sullivan7** [comment]
I reviewed the [staging doc](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit?usp=sharing) for Businesses and employers. It wasn't clear what was copied and pasted as part of rearranging questions and what was new content (a failing of Google Docs). As a result, I took a deeper look at the questions and answers in the employer section and proposed further edits:

- Renamed the section "Managing COVID-19 in the workplace" as that seemed appropriate (the previous title was "Employers" which is already in the title of the page).
- Edits to make things shorter and more direct
- Changed links to mirror the title of the page they go to (in keeping with @thepegisin's observation yesterday that our links should set expectations about where people go so they know they went to the right place)

@ashleydraper let me know if you'd like to chat about my approach tomorrow or if this is OK to go to SMEs!

**Comment by m-sullivan7** [comment]
@abquirarte Drafts are ready for final review (including by SMEs!)

Staging docs:

- [Businesses and employers](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit?usp=sharing)
- [Taxes](https://docs.google.com/document/d/1uon27XQKSJNADP8t5NIUyBffw5K1PbkNnJ-xrVCVlQ0/edit?usp=sharing)

I've also attached Word Docs with changes highlighted and a summary of changes on each page in case that's easier for SME review. I am happy to correspond with them while you are out next week. :)
[Taxes 9-25-2020 revisions.docx](https://github.com/cagov/covid19/files/5284549/Taxes.9-25-2020.revisions.docx)
[Businesses and employers 9-25-2020 revisions.docx](https://github.com/cagov/covid19/files/5284550/Businesses.and.employers.9-25-2020.revisions.docx)

**Comment by abquirarte** [comment]
Thank you @m-sullivan7 ! Sending emails and will tag you so you can proceed with changes!

**Comment by m-sullivan7** [comment]
Approvals received for Taxes changes. Pertinent content moved to Taxes page, which has already been published. Confirmed publishing of Businesses and Employers page. This ticket is now complete.

**Comment by abquirarte** [comment]
beautiful coordination :)
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>
