### ISSUE TITLE
research file management process inversion

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1331]
We noticed a problem today with our pdf management process:
- The github action took 10 minutes to complete
- It was taking all the time in the checkout step of the action
- It was pulling files at < 1MiB/s
- Previous runs all completed in a minute and were communicating with github ~ 50MiB/s

The way we have out github action pipeline setup is very common. It is the recommended package to use by Azure and AWS (for S3 synching)

In order to not be subject to bandwidth issues when running our github action checkout we could invert the process:

- Have users upload the file directly to the file storage using a low permission cloud account. S3 has a really nice web interface, Azure blob storage is less nice.
- Trigger an event when the file has reached the file storage which downloads it to our github repo as a backup in case we need to recreate the system.

^ This would work with AWS, need to do more research to see how to get it to work with Azure.

This issue is probably a temporary blip but as we increase the repo size we will eventually get slower even with the usual bandwidth.

Any other ideas?

**Comment by aaronhans** [comment]
This is related to #1320 even though each issue was raised by a different symptom.

If we created a file upload form we could:

- Put the uploaded file on azure blob storage or wherever immediately without any git action checkout runs
- Review and give user immediate feedback on url structure
- Still copy the file back to github for the ability to restore whole file system

but:

We'd have to add a security layer to prevent unauthorized folks from uploading stuff to gov domains. This complexity was sidestepped by using github.

**Comment by xjensen** [comment]
I wonder if configuring [Git LFS](https://docs.github.com/en/github/managing-large-files/about-git-large-file-storage) would help here. Not sure. Might be able to preserve current process but might also introduce new problems (around archive/restore, etc.).

**Comment by aaronhans** [comment]
this problem did not reoccur, the way we push files here is pretty standard, will reopen if delay occurs again, in the meantime getting redirects working is a higher priority
