### ISSUE TITLE
DMV edit for Stay home page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1332]
May have a new content edit based on lastest DMV announcement.

[attachment_125426_8.4.20.DMV.Expands.Online.Services.with.Commercial.Drivers.License.Renewals.pdf](https://github.com/cagov/covid19/files/5078018/attachment_125426_8.4.20.DMV.Expands.Online.Services.with.Commercial.Drivers.License.Renewals.pdf)

**Comment by thepegisin** [comment]
The **Stay home Q/A** page has just one DMV Q/A. It hasn't been updated since June and is rather long. I'd like to update the info and also break this into 2 Q/As:

**- Can I go to the Department of Motor Vehicles (DMV)?
- What DMV services can I get online?**

Info source will be https://www.dmv.ca.gov/portal/.

- [ ] @abquirarte , are you okay with this?

**Comment by abquirarte** [comment]
yes! 👍 go for it @thepegisin

**Comment by abquirarte** [comment]
ha! I eagerly closed the issue 😄
