### ISSUE TITLE
redirect from blob

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1343]
We are currently hosting our pdf files on Azure blob storage which we publish to from github using a series of github actions.

Azure blob storage does not appear to allow us to set a rewrite header on a binary blob object so we cannot implement redirects in this situation.

There are several possible solutions we have already explored:

1. Using Azure Static Web App Service instead of blob storage allows limited redirects, still avoids adding a server as a Single Point of Failure into the scheme but... Azure SWA is in preview status and does not offer the usual uptime guarantee of other Azure services so CDT is not comfortable with us using it.
2. We could put a .NET server in front of our file storage and have it redirect with the web.config. This sucks because it introduces a SPOF into a currently fully distributed system.
3. We asked CDT to add our redirects to Azure FrontPage. This is technically possible but not something they want to deal with.
4. We could use AWS S3 instead of Azure blob storage. This allows us to set headers to redirect any object. This is a big change, we are exploring it.
5. We can create an HTML redirect using a folder that mimics the full binary filename and making the HTML document the default doc in the folder. This appear to work, example here https://files.covid19.ca.gov/img/15485_lores-test2.jpg. We may be able to augment with by adding logic to the Azure Gateway to send real 301s based on aspects of the retrieved file https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers

**Comment by carterm** [comment]
Option 5 could detect for a specific file size/type/header and then forward the request with the original request URL to a function handler which can process the redirect.

**Comment by aaronhans** [comment]
@ChadABratton we need some assistance here testing the gateway 301 part of option 5.

**Comment by xjensen** [comment]
I built a whole URL shortening service on top of AWS S3 redirects a few months ago. Works great, reliable, very cheap, easy to set up via click-ops and/or API. 

Big painful data migration aside, I'd be happy to answer any questions.

**Comment by aaronhans** [comment]
@xjensen would definitely like to hear more about that

**Comment by xjensen** [comment]
The URL shortener on S3 is basically just a static website with a bunch of empty, nanoid-named files. Each file is tagged with redirect metadata for the intended URL. S3 performs 301s. Here are the basic steps needed to make it work through the UI.

* Redirects are applied by adding the **Website-Redirect-Location** key to an object's _Metadata_ (found within the object's _Properties_). Value is the intended redirect URL. (This can be done via API too.)
* **Static website hosting** needs to be enabled within the S3 bucket's _Properties_.
* Ensure **Block all public access** is not enabled in the bucket's _Permissions_.
* Add the following **Bucket policy** or similar to the the bucket's _Permissions_.

```json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET_NAME_HERE/*"
        }
    ]
}
```
