### ISSUE TITLE
Anchor link for "voting" section in Stay home QA 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1344]
Can I can a bookmark hyperlink specifically for the voting section of the Q&A?

https://covid19.ca.gov/stay-home-except-for-essential-needs/

Task: 

- [x] Create an anchorlink for that section 
- [ ] Send link to Angie + Tam + Hannah

CC: @kenbasart @hannahslee 
Tagging for awareness, would be good to think through way to track these adhoc requests too..

**Comment by thepegisin** [comment]
Added anchor tag **#vote** - should be live by 5:30.

https://covid19.ca.gov/stay-home-except-for-essential-needs/#vote

**Comment by abquirarte** [comment]
👏 thank you @thepegisin !! 😄
