### ISSUE TITLE
Fix Arabic alignment in Industry guidance in other languages page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1346]
Arabic is supposed to align right. But I can't get it to do it on this page: https://covid19.ca.gov/guidance-languages/

<img width="707" alt="arabic-issues" src="https://user-images.githubusercontent.com/63249920/90460946-e2fca080-e0b9-11ea-8dab-c0484dd420c6.png">

Hoping @carterm can help as he conquered a similar issue with other Arabic pages.

**Comment by carterm** [comment]
Added `dir="rtl"` to each text statement.

**Comment by carterm** [comment]
![Screen Shot 2020-08-18 at 9 39 11 AM](https://user-images.githubusercontent.com/6798999/90540909-b76bcb80-e136-11ea-8080-1aa7b7c0ffc6.png)
