### ISSUE TITLE
California Health Corps: New content focused on participant resources

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1348]
**Completed Request on 8/18/2020:**
Added one new PDF and replaced one PDF at website for FAQs. Added five 5-new participants related PDFs to the Github but not linked to the web page. PDFs at Github can be linked to documents used by the California Health Corps team.

**Potential Future Request:**
James Regan (new Program Manager for California Health Corps at CDPH), in a meeting with web team (attended by Tracy, Kelvin, Jaine, Tamara, Peggy & Karim) advised that CDPH would like to make following changes:
 
1) Add content for participants, currently site focus on recruitment
2) Would like to add some more content related to recruitment to reduce questions the program is getting
3) Would like to include some info-graphics. Was advised that all graphics need to meet the site criteria including accessibility (& was advised to look at masks page for example). 

CDPH don't have anything drafted yet. No radical change to the web page is intended. 

**Updated on 9/1/2020:**

Replaced one PDF for California Health Corps page and added two new PDFs to the Github for access by the California Health Corps team

**Comment by abquirarte** [comment]
Reopening this issue to track SME requests on new content for the CA Health Corps page.
