### ISSUE TITLE
Health Corps Design/Content changes

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#135]
- [x] Big button for "Register Now" under step 2 & another at the bottom - both linking to the same site.
- [x] Send GO image specs for our preview graphic
- [x] Swap out preview graphic: (below)
- [x] Change domain to covid19.ca.gov/healthcorps (no hyphen) 
- [x] in homepage change "provide medical care services" to "Join the California Health Corps"

**Comment by abquirarte** [comment]
![Health Corps Website Banner](https://user-images.githubusercontent.com/9556188/77860974-12704680-71c7-11ea-9b0f-a88982905901.jpg)

**Comment by hilaryhb** [comment]
@abquirarte 

- Is the California Health Corps supposed to be like the Peace Corps? A group of people - I would indicate that somehow, like it's a call to serve Californians or is it just a way to fast track the hiring process?
- This sentence is confusing. Break it up into 2 parts but I don't think you need the second part at all. "To meet this moment, we’re opening additional health care sites to treat people affected by COVID-19 and to relieve the pressure on our health care system by providing care for non-COVID-19 cases.

- "healthcare providers, behavioral health professionals, and health care administrators" -- I would say "healthcare **professionals**, behavioral health **specialists**, and health care administrators"

- Would clarify medical students in the "we need" -- does what year they are matter? Could a first year med student join? 

- Is the State of California your employer? 

- Will pay be same as what you are used for your specific profession? ie a med student - how much will you get paid? You are in theory leaving school that you have already paid for and have no idea how much you will earn. And for other professionals, will it be hourly? Salaried? Will health insurance be included? What kind of work contract will this be?

- "Participants" is probably the wrong word -- 

- What if I want to do this but I don't want to be at a COVID site but the sites treating non-COVID - before going through the process, I want to know if I can indicate that along with location

- Step 1 -- the OR - is there another way to show this?

- Change "deployment" this feels like the peace corps part but feels un-human -- can you just use "location" or even "placement"?

- "Once verified we will refer you to submit an application" -- add comma after verified? "refer you -- just say "ask you to submit" - will they get this via email? how long will verification take in step 2? 1 hr? 1 day -- we should give a range

- Step 4 has a : -- should it?

- "We will review your skills, experience, location preferences and interests to see where they match our deployment needs." -- CHANGE: "they" to you and CHANGE deployment to placement or location or even just "site needs.

**Comment by abquirarte** [comment]
this part is now done!

**Comment by artuoma** [comment]
Changes are LIVE
