### ISSUE TITLE
Immigrant page update 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1359]
Add this back to immigrant guide page **today 8/19/2020**

> Effective July 29, 2020, a federal court ruling prohibits the application and enforcement of the public charge rule that went into effect on February 24, 2020. The ruling is currently in effect so long as there is a declared national emergency related to the COVID-19 pandemic.

> If you have questions about your specific case, please [consult qualified immigration assistance.](https://www.cdss.ca.gov/benefits-services/more-services/immigration-services/immigration-services-contractors/public-charge-contact-list)

**Comment by thepegisin** [comment]
Updated.
