### ISSUE TITLE
Update to #vote Anchor -- Stay Home page

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1361]
## Add hyperlink of the attached letter to the following text "Elections are an essential activity."

In this page:
https://covid19.ca.gov/stay-home-except-for-essential-needs/#vote

### Attachment: 
[CDPH to SOS Letter from Acting HO Aug 18 (1).pdf](https://github.com/cagov/covid19/files/5098921/CDPH.to.SOS.Letter.from.Acting.HO.Aug.18.1.pdf)

### Timeline: 
Today in the next 1-2 hours. 
Confirm when live

**Comment by kenbasart** [comment]
cc: @LizNobriga

**Comment by thepegisin** [comment]
I'm on it, @kenbasart - BTW, here are our page assignments: https://docs.google.com/document/d/1UtQJ0AqQOwfQLWrIP0NnwRg2B7s7klZR7N-gdBbEcPo/edit#

**Comment by abquirarte** [comment]
This is now live. I think we can close @kenbasart 

Thanks @thepegisin ! 😄
