### ISSUE TITLE
Revise accordion titles, so that it's meaningful in quick search

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1377]
All content captains should review their accordions to make sure that Q/As are meaningful in quick search, if not please add subject/context:

![image](https://user-images.githubusercontent.com/62369563/90801470-c7b4af80-e2ca-11ea-87b3-b1d21eae2fa0.png)

Completed by:
- [x]  @LizNobriga 

- [x] @ashleydraper (Some work tracked seperately through # 1403)

- [x] @thepegisin 

- [x] @JasonKarim

**Comment by ashleydraper** [comment]
@JasonKarim 
Proposing to close this issue as my pages are now being tracked in issue #1403
