### ISSUE TITLE
Standardize use of buttons and button states

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1380]
Creating this issue as a place to document how we standardize buttons during the redesign.

Here are some written rules to help inform choices as we work through the new designs.

Standardizing buttons:

- Button shapes should always be the same color as the label/CTA that they are situated next to
- All button shapes should have the same stroke width for the circle
- All button shapes should have the same stroke with the for the icon inside of the circle (i.e. arrow, plus)
- All buttons should be the same size, regardless of the size of the label

Standardizing hover state

- Button shapes have the same color change as the text they are paired with
- No fill color change inside button circle (color change only applies to strokes)
- No scale effect
- Each icon (arrow, plus sign) has a different behavior
    - Arrows push horizontally on hover
    - Pluses turn to deltas on click

Standardizing FAQ/Accordion titles

- The horizontal container that makes up each item in a list of accordion and FAQ links should have a consistent behavior
- Background color change

**Comment by adam-little** [comment]
in progress

**Comment by kkoryaka** [comment]
@adam-little , will you provide some visuals (style guide) of those buttons so we could use it as a reference when we make our changes to the button's code?

**Comment by adam-little** [comment]
@kkoryaka here is some further documentation about buttons. please let me know what else is helpful to see so that we can begin to build out a more detailed design system.

Figma link: https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=1894%3A0

Example applications:

**Action button**

Homepage:
![image](https://user-images.githubusercontent.com/69167298/94315706-e2b4b800-ff37-11ea-86a3-9367ef291b45.png)

Get tested page:
![image](https://user-images.githubusercontent.com/69167298/94315768-0972ee80-ff38-11ea-94ed-4ce824082f9a.png)

**UI Button**

Blueprint page:
![image](https://user-images.githubusercontent.com/69167298/94315819-1e4f8200-ff38-11ea-88b7-d2f6c436b05a.png)

State dashboard: 
![image](https://user-images.githubusercontent.com/69167298/94316007-71293980-ff38-11ea-9cdd-2116591d16a2.png)

**Link with arrow**

Homepage:
![image](https://user-images.githubusercontent.com/69167298/94316068-87cf9080-ff38-11ea-9322-8a94cbccdf3a.png)

State dashboard:
![image](https://user-images.githubusercontent.com/69167298/94317190-a33b9b00-ff3a-11ea-96f0-ebbbf4808d79.png)
