### ISSUE TITLE
New “Aging Services” content 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1392]
### Content 

CDA Resources for Older Adults

CDA is requesting a new page for people seeking info on services for older adults at home.  More info in your mailbox.. I told them that this may not be a new page but that the team will recommend where this information lives on the website. 

From CDA: 
This will fill a current gap:  there is a page for senior living in residential facilities, but no page for older adults and people with disabilities living at home.  This new page is intended to be roughly parallel to childcare page, right next to it.
Proposed New “Aging Services” Page Link Location
 
New “Aging Services” page content:
Top line heading in blue border section: “Aging Home & Community Services”
Intro Text:
“Aging services are being redesigned and expanded to continue serving older adults and people with disabilities living at home, while also staying safe during the pandemic.”
Subheading 1:
“To find aging and adult info and resources:
1.	Connect to your community’s network of aging services by calling 1-800-510-2020.
2.	Visit www.aging.ca.gov”
Subheading 2:
“For providers of aging services: You are essential.
To find the latest guidance on continuing services, visit California Department of Aging’s COVID-19 Information and Resources webpage (scroll midway down page to CDA Provider Guidance).” 

### Content Captains 
@ashleydraper @thepegisin 

### Timeline 
Monday COB first draft/proposal where this content lives so we can share with CDA and have them react to it

**Comment by ashleydraper** [comment]
This page is [staged in our drive](https://docs.google.com/document/d/1AFPiTJG-6SfjRaDN-Bbu79YWLHZcIYDGhJ03353-wWM/edit#heading=h.ia7z6o9xmtr1). Please edit away!
@thepegisin @abquirarte

**Comment by thepegisin** [comment]
Made edits to Staging doc: https://docs.google.com/document/d/1AFPiTJG-6SfjRaDN-Bbu79YWLHZcIYDGhJ03353-wWM/edit

**Comment by TamaraIDEJA** [comment]
Shared w SMEs and asked the following: 

How much of the info you drafted for us is actually new? Also, does it make sense to create a new page that links to other sections on the page? If so, this would then need to include other resources like Great Plates, or senior food services - any other content from the website that is addressing needs of our older californians. 

Lets see what they say - and if optimal schedul a meeting next week to discuss. 

### Prototype content
- [ ] If you have a proposal of what this would look like please build on the existing draft. Thank you @ashleydraper 
Also, does it make sense to create a new page that links to other sections on the page? If so, this would then need to include other resources like Great Plates, or senior food services - any other content from the website that is addressing needs of our older californians. @thepegisin

**Comment by TamaraIDEJA** [comment]
Got some feedback from SME: 

- They are open on how to structure this page. I forwarded you some comments they had on the content draft. 
- Regarding newness of content, the provider guidance that is on their website is fairly new and evolves on a flow basis. They think it would be nice to capture other resources that impact older adults – ie: great plates – and include links to those resources. Sort of like a resource round up specific to older adult needs.
 
### Next steps 
Do you want to take a stab at thinking through the proposal for the page for Senior/Older Californian based on the feedback, key questions and services in demand? Then schedule a meeting w the SME and discuss? 

@ashleydraper @thepegisin

**Comment by abquirarte** [comment]
Cc: @kenbasart @hannahslee ☝️

**Comment by TamaraIDEJA** [comment]
Thanks @abquirarte :)

**Comment by thepegisin** [comment]
Makes sense to me. @ashleydraper , would you please gather links to resources for seniors from our site and add?

**Comment by TamaraIDEJA** [comment]
@ashleydraper @thepegisin SME reached out to check in, they wants to finalize this week if possible. Can we send proposal by the end of today/tomorrow am and plan a call to go over the proposal? I will make the connection. Thank you!

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
Here is the [draft staging doc](https://docs.google.com/document/d/1AFPiTJG-6SfjRaDN-Bbu79YWLHZcIYDGhJ03353-wWM/edit) for immediate reaction. Are you comfortable with adding these changes to wordpress staging and having the SME take a look at that?

**Comment by ashleydraper** [comment]
@TamaraIDEJA @thepegisin 
Gentle nudge on reviewing this, Tam. Here is the [page in staging](https://as-go-covid19-d-001.azurewebsites.net/2020/09/14/help-for-seniors/?preview_id=5984&preview_nonce=75e61c1524&preview=true) with the hotlines resource removed. I don't see this fitting cleanly with other senior resources, so if we're all okay with this being a stand alone page, then this is good to go.

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
What's the status on this?

**Comment by ashleydraper** [comment]
@aaronhans @carterm 
This page is published, but I just added the "do-not-crawl" tag back on there so it shouldn't be searchable. Here is the url for the new **help for seniors** (https://as-go-covid19-d-001.azurewebsites.net/2020/09/14/help-for-seniors/(opens in a new tab) page. 
Can you help me update the nav?

**Comment by aaronhans** [comment]
This has been added to the nav at the end of the Get help section as approved by @ashleydraper. The code change has been pushed to production

**Comment by kenbasart** [comment]
Closing per @aaronhans comment above.
