### ISSUE TITLE
Create healthcorps.ca.gov, point to covid19.ca.gov/healthcorps

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#140]
By 11:30am 
- [x] submit request to CDT
- [x] Reroute to right link.

**Comment by abquirarte** [comment]
this is now done!

**Comment by ChadABratton** [comment]
Spoke with DevSecOps team and clarified this request. (March 30th)
There was an issue in the DNS configuration that was quickly resolved.

**Comment by abquirarte** [comment]
Thank you for following up @ChadABratton !!
