### ISSUE TITLE
Youth Gatherings Guidance "cohorting"

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#1402]
In your inbox @LizNobriga @thepegisin @m-sullivan7 

CC: @kenbasart 
## Page: Industry Guidance 
We need to consolidate the guidance. Could be into 1 accordion. Please look through the content to see if that makes most sense. This (could) affect schools and childcare content. 

- [x] Stage accordion content 
- [ ] Take our relevant questions from CFA QA document and turn into quick answers (so they don't get buried in PDF)

## dependencies

- CDPH links (1. Cohort guidance, 2. CDSS-FAQ, 3. Outbreak- CDPH)
- CDPH will send us all the PDFs (they will check for accessibility)
- Some of the content in the docs may need to be summarized in the accordion. (There is an FAQ). 

----
### Add to update education page:. (Now, and purge)
@ashleydraper @aaronhans 

- [x] Update education page with content below

**When can colleges or universities in counties on the monitoring list resume indoor lectures?**

> Institutions of Higher Education are subject to the July 13th Order [link]. Indoor operations such as lectures must remain closed, even when a county is removed from the County Monitoring List, until the State Health Officer modifies the Order and authorizes re-opening. The State of California is actively reassessing the July 13th Order in light of evolving scientific evidence regarding disease transmission and the risk of transmission in different settings.

**Comment by thepegisin** [comment]
My questions, @abquirarte :

1. When you say "consolidate the guidance," I assume you mean just guidance related to this issue (youth gatherings) - right? Not all industry guidance?
2. These documents are very different from the formatted guidance PDFs we usually get. Are we expected to conform it and make the PDF? If yes, do we have a template to start with?
3. These documents seem very internal, bureaucratic, and messy to me. Are we sure we want to expose them to the public? If not, do we have the know-how to pull out the relevant pieces and put them in industry guidance format?

**Comment by abquirarte** [comment]
> My questions, @abquirarte :
> 
> 1. When you say "consolidate the guidance," I assume you mean just guidance related to this issue (youth gatherings) - right? Not all industry guidance?
> 2. These documents are very different from the formatted guidance PDFs we usually get. Are we expected to conform it and make the PDF? If yes, do we have a template to start with?
> 3. These documents seem very internal, bureaucratic, and messy to me. Are we sure we want to expose them to the public? If not, do we have the know-how to pull out the relevant pieces and put them in industry guidance format?

1- correct! 
2. They were never intended to live on our site. GO made last min pivot. We will get final PDFs from CDPH. 
3. i agree, that's why I suggest we should at least extract these in the form of quick answers. :) leave the bureaucratic in the PDF format.

**Comment by thepegisin** [comment]
Ah, okay. Phew!

**Comment by LizNobriga** [comment]
From SME:
`FYI it sounds like GO has asked to hold off on release until tomorrow at 1pm. Will let you know if I hear anything else back`

**Comment by LizNobriga** [comment]
[staging doc](https://docs.google.com/document/d/11ZSLKfKcZhY-XMiceydj50BcoP6pEkficA2gE2CkIjY/edit)

- [x] schools cohort FAQ pdf live

- [ ] edits are live

**Comment by LizNobriga** [comment]
What content+links about `cohorts` would be useful to have on the Education page? (@ashleydraper)
