### ISSUE TITLE
Financial Help Page Accordion -- Questions

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1403]
Here is a set of questions on the financial help page in desperate need of context for accordion quick search

![image](https://user-images.githubusercontent.com/69479727/91088327-a9bab800-e606-11ea-93ae-97fabe5fbbba.png)

Peggy Gartin:computer:  1 hour ago
@Ashley Draper, take a look at each of these (and really, all your accordions) and ask yourself if the "what" of the question is not obvious. If that's the case, add it in the Staging doc. Then ping me, and I'll take a look. This shouldn't require SME approval, but we'll check with @Angie Q just in case.

Ashley Draper  1 hour ago
I agree that many are missing the what, I think I'm also battling that if I add the what, will these questions now provide value? I don't know that they will or if there is more updated information somewhere. Ex: What if I already made a payment... Okay, say I add more context around the what, is this question really still relevant or a value add. That's more what I'm thinking on these.

Peggy Gartin:computer:  30 minutes ago
I see what you're saying, and you're right to ask that. I would look at that as two separate exercises:
Is the question understandable out of context of the page? If not, what can I add to make it so?
Is the Q/A still relevant? Did a deadline pass, or is it no longer true now that more businesses are open? If so, what action should I take? (edit/remove)

Peggy Gartin:computer:  29 minutes ago
Whatever action you take, it will get checked, debated, and approved/denied in the Staging doc.

Angie Quirarte:spiral_calendar_pad:  3 minutes ago
Can we track this on a github issue and add to our to do in the board please? Fruitful comments on this thread that I don't want to lose later :pray: cc: @Ken Basart

**Comment by kenbasart** [comment]
@thepegisin

**Comment by ashleydraper** [comment]
Updated accordion/ FAQ headers to add context to the [get financial help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#heading=h.aglsxh6428gb) page. Please review
@thepegisin

**Comment by ashleydraper** [comment]
New changes are staged for [get financial help](https://staging.covid19.ca.gov/get-financial-help/#renters-homeowners-small-landlords). Please take a look and let's see if this is the style we'd like to adopt for content pages moving forward.
@thepegisin @m-sullivan7 @abquirarte

**Comment by m-sullivan7** [comment]
On my list for today! :)

**Comment by m-sullivan7** [comment]
Reviewed [staging doc](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit?usp=sharing) with changes and left comments. Happy to discuss if anything feels like it's off! :)

**Comment by ashleydraper** [comment]
Adding @thepegisin 's comment here for documentation:
Eviction protection extended to March. Looks like we need a change on the Financial help page, @Ashley Draper. https://www.gov.ca.gov/2020/09/23/governor-newsom-signs-executive-order-in-response-to-covid-19-9-23-20/

**Comment by ashleydraper** [comment]
These changes are in [staging](https://staging.covid19.ca.gov/get-financial-help/#eviction-protection). Please let me know if we're good with these, then I can publish and close this issue.
@thepegisin @m-sullivan7

**Comment by ashleydraper** [comment]
Published. Proposing to close this issue.
@thepegisin @kenbasart @m-sullivan7
