### ISSUE TITLE
Content revisions resulting from dimmer switch 

### ISSUE THREAD

**Issue by ashleydraper** [cagov/covid19#1430]
Now that we've identified the pages that will require removal/revision in the [content inventory spreadsheet](https://docs.google.com/spreadsheets/d/1ykrjgThA7jLM9W-D_I4BVieIut7M8wPi72Odc9ZpC5o/edit#gid=1718061611), let's stage our content pages and paste them here. 

Our first step will just be to highlight where revised language is needed, once we receive the language, we can stage in word press. Cc: @m-sullivan7  @hannahslee @abquirarte @TamaraIDEJA 

- [x] [Education](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit) - point to the CA school directory, CML framework remains

- [x] [Get financial help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#) - remove roadmap link

- [x] County variance - remove

- [x] Industry guidance - remove links and content related to county variance page and attestation/approvals

- [x] [Recovery-input](https://docs.google.com/document/d/1bR0XfU-DFk1oLM9XGhXaEFybw85Q8fDlXyg9FkG_xhs/edit#heading=h.eplujx1ks9mn) - language overhaul (which includes removing references to the Resilience Roadmap) and having the survey button removed. (Also tracked in [issue 1391](https://github.com/cagov/covid19/issues/1391))

- [x] [Stay home](https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#) - A LOT! 

- [x] [Public recreation](https://docs.google.com/document/d/1yTaGKCWEGF9pnscXLr_Kbx_NSYVEQLWdu3yUi6w02Vg/edit#) - replace county variance page link

- [x] [Get local information](https://docs.google.com/document/d/1uYrsDp60x1BRHi_OYNamzDqrueUMj4U-DKEZ6AEOg8U/edit) - replace county variance page link

**Comment by ashleydraper** [comment]
- [ ] [Get financial help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#) page with roadmap language highlighted in red

- [ ] [Education](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit)

**Comment by m-sullivan7** [comment]
Recovery-input is done!

**Comment by thepegisin** [comment]
Stay home staging doc now has edit points highlighted: https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#

**Comment by LizNobriga** [comment]
[staging doc](https://docs.google.com/document/d/1pxJEv1tYfKAIdG6kXMaOx43zFssBu3xOOaz4CmOUZe4/edit#) for IG page edits

**Comment by LizNobriga** [comment]
is this ready to move to Done?

**Comment by abquirarte** [comment]
Sure!
