### ISSUE TITLE
Add new Contracts to Contracts Page

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1439]
There is a new contract that needs to be added to the contracts page:

[PerkinElmer CDPH Contract v1.pdf](https://github.com/cagov/covid19/files/5133082/PerkinElmer.CDPH.Contract.v1.pdf)

Related press release:

https://www.gov.ca.gov/2020/08/26/governor-newsom-announces-major-plan-to-more-than-double-states-testing-capacity-reduce-turnaround-time/

**Comment by kenbasart** [comment]
cc: @abquirarte

**Comment by abquirarte** [comment]
Wow @kenbasart is on 🔥 today!!!! HA! 
Thank yooou! 

@LizNobriga this needs to be posted today since the Governor mentioned it earlier and there is press interest. Please share link once PDF is live so that Ken can follow-up with GO legal.

**Comment by LizNobriga** [comment]
will do

**Comment by LizNobriga** [comment]
Here is the link: [https://files.covid19.ca.gov/pdf/Perkinelmer-health-sciences-inc-CDPH.pdf](https://files.covid19.ca.gov/pdf/Perkinelmer-health-sciences-inc-CDPH.pdf)

**Comment by kenbasart** [comment]
Need to wait on this per David Sapp:

"With apologies for change in approach, is it possible to delay posting instead until tomorrow am?  It sounds like the notification to JLBC will take longer than thought and likely not until this evening. I’ll send a note tomorrow am confirming that the notification has occurred, and then we can proceed with posting."

**Comment by LizNobriga** [comment]
- [x] PerkinElmer contract removed from Contracts page (the link to the contract pdf is still live)

**Comment by kenbasart** [comment]
This is approved to go live per David Sapp email 8/27/20.

**Comment by LizNobriga** [comment]
Contract is live
