### ISSUE TITLE
fix javascript includes

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#145]
In order to utilize javascript on the covid19.ca.gov site responsibly we need to use some of the patterns we put in place on alpha.ca.gov

- [x] create targeted build pipelines that target different browser sets so larger polyfilled bundles are only used where required
- [x] add new bundle which contains both of the web components we want to use
- [x] integrate the js into 11ty using the type=module/nomodule pattern
- [x] review inline code insertion pattern vs deferred script tag for modern browsers, choose fastest

**Comment by aaronhans** [comment]
Prioritizing this because it is required to support new features @artuoma is creating

**Comment by abquirarte** [comment]
sounds good, thank you!
