### ISSUE TITLE
dimmer switch page dev

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1452]
- [x] hide matrix labels on mobile
- [x] padding between rows: 10, internal padding: 20 on matrix  
- [x] matrix is in wrong place, move it up
- [x] figure out how to open entire list on activity field focus
- [x] failure to search on iOS
- [x] view all appears but causes search fail
- [x] using zip code fails
- [x] fix button, h2 colors, increase font sizes on button, fields, spacing in form elements
- [x] make status matrix into template driven by data (@carter)
- [x] decrease card section padding on mobile (aaron)
- [x] add border between multiple activity cards
- [x] add anchor link to data below to county card (aaron)
- [x] Remove data on activity cards (aaron)
- [x] on browserstack matrix section backgrounds not showing up on iOS8 (was a dynamic class issue that appeared everywhere)

Not sure where latest data with final county risk states is:
- [x] Confirm latest county status spreadsheet is locked and ingest it

Latest tableau code just says signin because their viz isn't public, have to do this tomorrow:
- [x] integrate the map tableau embed (aaron)
- [x] make sure the tableau code doesn't delay rendering of the stuff above it: do element insert into placeholder, add script to head

this is freaking cool but might defer until after launch:
- [ ] save state in url, populate html5 history for back button updates, load based on params

Design
- [x] **Center main content column [P0]**
- [x] **Center all headers  [P0]**
- [ ] **Move “Understanding your county’s status” header and paragraph copy above the matrix [P0]**
- [ ] **Intro paragraph (“California has a new…”) should be larger (same size as H4 text)  [P0]**
- [x] **Add “Check your county website for local restrictions” to search result county header [P0]**
- [x] **Add industry guidance link to search result list item** [P0]
- [ ] Search result title (e.g. “Movie theaters in Fresno are Open”) should be smaller (the size of P text)  [P1]
- [ ] In the Activity dropdown, add horizontal rule to separate the “view all” links from the list of matching activities  [P1]
- [ ] Format dropdowns to match Figma (for hover color use F2F5FC as the bg)  [P1]
- [ ] For search results, match spacing to Figma so that the list is more compact  [P1]
- [ ] For the matrix in mobile, reduce spacing between rows of data in each tier so that each colored tier is less tall (i.e. reduce space between the tier / daily new cases / positive tests by 50% to reduce overall height)  [P1]
- [ ] Make map container full width OR centered in column [P1]
- [x] Remove county name in search result list item (Currently it says “Movie theaters in Fresno are closed” when it should say “Movie theaters are closed”) [P1]
- [ ] Remove “county” and “activity” labels that appear above search input fields (unless these are there for accessibility reason?) [P1]
- [ ] Add period after "closed" in this sentence in the county header - "Many non-essential indoor business operations are closed Understand the data."
- [ ] Update the color of text labels on the tiers (widespread, moderate, etc.) to match Figma for accessibility reasons [P1]

Functionality
- [x] **Both county and activity fields are optional. Leaving these fields blank will default to showing all.  [P0]**
- [x] **Remove "view all open" and "view all closed" options from Activity dropdown  [P0]**
- [x] Add “view all” option to Activity dropdown  [P1]
- [ ] Do not show search results until a user has pressed the "Get latest updated" button  [P1]
- [ ] Zip code search
- [ ] “Understand the data” anchor link should jump to the matrix (not the FAQ)
- [x] I think we need a way to “clear out” (i.e. remove) the search results. Seem the latest Figma for a suggestion on how to do this.  [P1+]

Content
- [x] Remove "Find the status of activities in your county” that appears above the search box
- [ ] Can industry guidance links go directly to the guidance for that industry instead of all activities having the same link?

**Comment by adam-little** [comment]
For the issues with the asterisk (*) I am going to post a comment in Slack for further discussion

**Comment by aaronhans** [comment]
@kenbasart recommended closing this. I agree, we should open new smaller focused tickets for remaining issues we want to prioritize. We changed our minds on a few of the above tasks and have been doing a lot of prioritization in google docs like https://docs.google.com/document/d/1XqwoJWVpu2y17UKMncXvcKOwzKwyv5V2UpjkL4GuP78/edit so this list is obsolete

**Comment by kenbasart** [comment]
Closing per @aaronhans. Open items from this ticket transferred to https://github.com/cagov/covid19/issues/1563
