### ISSUE TITLE
Eviction Protection Legislation

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1502]
BCSH is launching a page/website. We will link to it.
This is still for TUESDAY 9/1/20
Blocker- legislation pending approval.

- [x] Propose changes to Housing page

- [x] Propose changes to Get Financial help

- [x] Review quick answers 

cc: @abquirarte @LizNobriga

**Comment by m-sullivan7** [comment]
Housing and homelessness edits ready for review @abquirarte !

https://docs.google.com/document/d/1Ro4gz9ndW4jMM-vrudWnPwrWeSGg3njWpm_w8LNAUWQ/edit?usp=sharing

**Comment by LizNobriga** [comment]
[edits](https://docs.google.com/document/d/1h2m8qmjXlzXrhsLQL0g7WoNbBYqmXmeen0Dam6swfBY/edit#) for Financial help for review @abquirarte

**Comment by ashleydraper** [comment]
Edits for [Financial Help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#) page
@abquirarte @m-sullivan7 @thepegisin

**Comment by m-sullivan7** [comment]
Made a few additional suggestions @ashleydraper!

**Comment by ashleydraper** [comment]
I like! Thanks, Michael!

**Comment by abquirarte** [comment]
Thank you! Are all these ready to send?

**Comment by ashleydraper** [comment]
[Housing page](https://docs.google.com/document/d/1Ro4gz9ndW4jMM-vrudWnPwrWeSGg3njWpm_w8LNAUWQ/edit#) for SME review

**Comment by ashleydraper** [comment]
@abquirarte @thepegisin @m-sullivan7 
[Housing and homelessness](https://staging.covid19.ca.gov/housing-and-homelessness/) updates are live in staging. Two outstanding questions:

1. 

> **Can landlords delay their payments while their tenants cannot pay rent?** 
> Yes, there are protections in effect through **September 30, 2020** for landlords. An executive order requests lenders to halt foreclosures and related evictions during this time. Property owners should contact their financial institutions.
Is this date still accurate?

2. 

Can we find out what this link used to point to so that I can replace it with the most appropriate guidance?

> California has also stopped foreclosure sales or evictions for 60 days. Learn more about other mortgage protections and resources (PDF).

[Get financial help](https://staging.covid19.ca.gov/get-financial-help/) edits are live in staging.

**Comment by ashleydraper** [comment]
Broken links fixed 
@thepegisin

**Comment by ashleydraper** [comment]
These updates are baking, should be live in 27 minutes. Proposing to close this issue.
@abquirarte @hannahslee @m-sullivan7 @thepegisin

**Comment by kenbasart** [comment]
Closing per @ashleydraper
