### ISSUE TITLE
flaky menu on ios

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1503]
Reports of menu subsection expansion problems on iOS phones

Initial report from user via "Is this page userful" via Karim:

- "The mobile menu does not work on safari/iPhone you cannot expand the submenu items"

More details from Karim's testing:

- iPhone X, iOS Version 13.6.1 (Does NOT work)
- Ditto in iPhone XR, iOS Version 13.6.1
- Works in iPhone 8 plus, iOS Version 13.6.1 (edited)

**Comment by aaronhans** [comment]
I was able to repro this on an older iPhone reliably by clearing the browser cache everytime before the first attempted menu expansion. The bug seemed to be related to the link default behavior prevention failing and then the page would reload but then the problem wouldn't reoccur.

PR with a fix is here: https://github.com/cagov/covid19/pull/1504

**Comment by kenbasart** [comment]
I am able to access all menus on 14.0 Beta 5 in Safari on an iPhone SE (2018). Bugs:

**Comment by aaronhans** [comment]
A fix for the original major issue in this ticket was deployed promptly.

The issues listed below are different: 
- Focused elements have different highlights per the design. You have to blur by clicking elsewhere to remove focus
- The current design does not support the smallest screen widths like 420px widhth classic iOS devices.

I'd recommend opening a new ticket where the design team advises on remedies for the above issues @kenbasart

**Comment by aaronhans** [comment]
assigning to @kenbasart for decision: I recommend closing this and creating new lower priority ticket initially assigned to design team to address unchecked issues Ken reported

**Comment by kenbasart** [comment]
Closing per @aaronhans
