### ISSUE TITLE
Update NPI Survey URL

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1506]
Update URL to new NPI survey:

@jpetrucione has the new survey/link

**Comment by jpetrucione** [comment]
LINK: https://www.surveymonkey.com/r/GFDXW5B?source=covid&src=[random_value]

Thank you!!!

**Comment by aaronhans** [comment]
FYI In the rush to release the new homepage we completely removed the NPI survey so you won't be seeing much traffic to it from covid19.ca.gov. We got @abquirarte's approval for this. We will reenable it with this new url

**Comment by jpetrucione** [comment]
when was it disabled?

**Comment by aaronhans** [comment]
Friday when we launched new homepage

**Comment by aaronhans** [comment]
The NPI survey was a custom element that appeared for users sometimes, we removed the existing custom element https://github.com/cagov/covid19/blob/c7296b4711f1f604dbb2b6efbfb610936aea4cbe/pages/_includes/header.njk#L14 because it didn't work with a fixed header.

We should figure out how to integrate it responsibly with the new fixed header design.

The previous implementation wasn't optimal because it caused a lot of layout shift. It would be good if this slid out from under the header or something over other elements instead of pushing them down

**Comment by jpetrucione** [comment]
Got it. What can I do to help with this?

**Comment by xjensen** [comment]
@jpetrucione and/or @aaronhans, quick question about this. We're currently keeping our survey URLs in [this _langData.json_ file](https://github.com/cagov/covid19/blob/master/pages/_data/langData.json) for different languages. All languages are currently pointing to the same previous survey **except Spanish**. Spanish seems to have a unique survey. 

In light of this info, I'm wondering how we should handle the new survey URL posted here in this thread. Some guesses follow.

1. Do we replace all survey URLs in the file with this new one?
2. Do we replace most survey URLs in the file, leaving Spanish untouched?
3. Do we only replace the English survey URL in the file?

Pending our answer here, I've got the work pretty much done in the [reimplement-npi-survey](https://github.com/cagov/covid19/tree/reimplement-npi-survey) branch.

**Comment by aaronhans** [comment]
New implementation looks great @xjensen! Nice functional and aesthetic integration with the new design

**Comment by jpetrucione** [comment]
Hey @xjensen - thanks for working on this! Good questions, and they make me want to double check to make sure that the specs for this project are clear. I think it wld be best to have a conversation with Clara to make sure that we're all on the same page. I'll ping you on Slack.

**Comment by xjensen** [comment]
To close the loop here, we updated styles and redeployed the new NPI survey to the site.
