### ISSUE TITLE
Add clarifying language to "stay home" banner

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#151]
"The order started Thursday, March 19, 2020 and is in place until further notice."

**Comment by coreycaitlin** [comment]
@hilaryhb Also recommended clarifying "everyone" with "in California," and making it clearer what we're distancing _from_ (other people). So the revised language we'd need approved is:

> **Stay home except for essential needs**
> Everyone in California is required to stay home except to get food, care for a relative or friend, get necessary health care, or go to an essential job. If you go out, stay at least 6 feet away from other people.
> This order began Thursday, March 19, 2020 and is in place until further notice.

**Comment by abquirarte** [comment]
Will route for approvals.

**Comment by abquirarte** [comment]
@artuoma this is good to go,

replace the banner language on stay at home order with:
## Stay home except for essential needs
Everyone in California is required to stay home except to get food, care for a relative or friend, get necessary health care, or go to an essential job. If you go out, stay at least 6 feet away from other people. This order began Thursday, March 19, 2020 and is in place until further notice.

**Comment by artuoma** [comment]
Pushed this to staging @abquirarte

**Comment by abquirarte** [comment]
This is now live! thank youuu!
