### ISSUE TITLE
search improvements

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#152]
Some vendors are offering search solutions that showoff improved capabilities. As the site grows it would be good if our search were able to answer queries more smoothly than it does now. We should evaluate any vendor tech against what is available off the shelf from Azure like https://azure.microsoft.com/en-us/services/search/#features, the most recent vendor contact powers the answers box here: https://covid19.nj.gov/  which has a nice autocomplete but disappointing search results page.

Art had some good ideas about combining chatbot ability to answer queries with search results. If we do something like this we should make sure to leverage any effort spent  curating bot responses with our own search result page, whether that means integrating bot into search results or feeding both content systems the same answers via their APIs. 

Proposed steps:

- [ ] fire up azure cognitive search
- [ ] compare features available with other offerings
- [ ] see if we can populate bot content and search content via APIs or if it is easier to integrate the bot itself into azure search results

**Comment by artuoma** [comment]
Instead of the search button we could do a search box right below the blue header as another option.

**Comment by abquirarte** [comment]
Looking through analytics i see that we have a lot of traffic on the search functionality. But when I search "masks" the content still feels hidden. Outside of content updates, what else could we do to improve this functionality before we consider alternative options? 

![image](https://user-images.githubusercontent.com/9556188/79293213-f8518c00-7e87-11ea-9bf9-d2fa60abd74b.png)

**Comment by abquirarte** [comment]
@aaronhans let me know if you want to edit or close this to create something different.

**Comment by abquirarte** [comment]
Closing since I think https://github.com/cagov/covid19/issues/462 takes care of it.
