### ISSUE TITLE
Add "Data and Tools" back to the Navigation Menu

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1539]
Please add the "Data and Tools" page link back into the navigation:

https://covid19.ca.gov/data-and-tools/

Place link as the last item in the "Health Information" category (directly below COVID-19 Hotline). Text of link is "Data and Tools"

<img width="254" alt="Screen Shot 2020-09-01 at 4 30 52 PM" src="https://user-images.githubusercontent.com/69479727/91915867-8334f680-ec70-11ea-95ae-a6b40ec47fc7.png">

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/pull/1540

**Comment by aaronhans** [comment]
This update is viewable in https://staging.covid19.ca.gov/

**Comment by kenbasart** [comment]
@aaronhans approved to go live

cc: @abquirarte

**Comment by abquirarte** [comment]
Yay!!

**Comment by thepegisin** [comment]
Done, so closing.
