### ISSUE TITLE
Broken links on 9/2 report

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1547]
We have 2 outside links that are reporting as broken. @ashleydraper, both of these are assigned to you.

- [x] On all versions of the **Great Plates** page, this link is broken: https://www.sandiegocounty.gov/content/sdc/hhsa/programs/ais/sdgreatplatesdelivered.html

- [x] On all versions of **Get financial help** and **Housing and homelessness** pages, this link is broken: https://www.bcsh.ca.gov/coronavirus19/renters_mortgage_guidance.pdf

Please replace or remove on English pages, then check in a day or so to see if fix has cascaded down to translated pages.

**Comment by ashleydraper** [comment]
@thepegisin 
The broken links on the two pages that are being updated today don't need to mentioned in this git issue as they are already being addressed in #1502

**Comment by thepegisin** [comment]
Awesome. Thanks, @ashleydraper. Closing.
