### ISSUE TITLE
Daily numbers page- GO request

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#156]
Is it possible to create a new tab on the COVID site that is “Daily Numbers” and we include the numbers that are on the home page, the CDPH page & the new fact sheet that will go out? IT’s a PDF – it’s very small and will grow to a full 8.5x11 PDF in the coming weeks.

**Comment by carterm** [comment]
We have this one already...
https://covid19.ca.gov/stats/
It gets merged into the main page

**Comment by aaronhans** [comment]
We could make a new page that uses the stats include as well as some wordpress content

**Comment by abquirarte** [comment]
Ohhhh!

**Comment by abquirarte** [comment]
Public dashboard would be linked from here as well. Cool. :)

**Comment by abquirarte** [comment]
no longer relevant
