### ISSUE TITLE
Track searches made from pages that initiate them

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1560]
Per @britt we would like to see which pages searches originate from. Our current search events are focused on whether or not we are presenting quick answers so fire from the search results page and record nothing about the originating page.

If we add the following event we will have more knowledge about where searches originate:

{
	category: search
	action: initiate
	label: the user's query
}

searchbox.addEventListener('fire on form submit', function(e) {
	// is executed when the specified action occurs on the searchbox element
	// we fire a ga event here with the desired parameters including what they typed in the search field as the label
})

**Comment by xjensen** [comment]
I took a crack at this in PR #1583. The data submitted to Google Analytics looks something like this.

In the #1583 implementation, the EventAction is populated with the page's URL pathname. For example: '/', '/es/', '/ko/safer-economy/', etc. If something else would be more useful here, such as the page's title, that's easy enough to change.
