### ISSUE TITLE
translation untangling

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1562]
There are several layers of issues with our AvantPage integration. This ticket deals with a critical but top level detail: The vendor keeps translating field names in our json data files and ignoring their stated _ field prefix exemption rules. 

- Can we rely on them not to do this? They have said their system will support it but the errors continue
- Once we find a solution some hardcoded data like reopening activity matrix can be made fully dynamic
- Do we need to take extra steps like creating dynamically browseable versions of the site for incoming translations? Maybe we do because we have received several  page breaking updates.

**Comment by carterm** [comment]
Email for Claudia today states that they have tested as update that should resolve this for tomorrow's translations.

**Comment by carterm** [comment]
There is not going to be a clean way to have them translate html attributes like...
`<cagov-reopening data-counties="data/reopening-counties.json" data-status="data/reopening-status.json" data-title="Find the status of activities in your county" data-county-restrictions-advice="Counties can restrict further. Check your county website." data-industry-guidance-link-text="View industry guidance" data-view-all="View all" data-county-label="County"></cagov-reopening>`

...so we will need to find a way to tableize.

**Comment by carterm** [comment]
Perhaps we can create a "config" link in the tag and have that link generated by the page language?

**Comment by carterm** [comment]
AvantPage is still translating keys...need to connect with them.
https://github.com/cagov/covid19/pull/1610/files

**Comment by kenbasart** [comment]
Closing as obsolete -- new Avantpage issues tracked in Jira
