### ISSUE TITLE
covid19 data transparency

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1564]
## Context 
COVID-19 Data Transparency effort requires departments to make their COVID-related information resources discoverable on the CA Coronavirus Response website. We will be receiving a google sheet with itemized list of covid19 related resources and will need to post those on covid19 site. Let's discuss the best way to make this information easier to navigate and discover. We will be sharing with you google sheet with resources outline asap. 

### Deadline
The deadline we're working with is September 12

### Reference material 
Memo and implementation guidance for reference
[Implementation Guidance_ COVID-19 Data Transparency Memo.pdf](https://github.com/cagov/covid19/files/5170055/Implementation.Guidance_.COVID-19.Data.Transparency.Memo.pdf)
[Memo on COVID Data Transparency FINAL.PDF](https://github.com/cagov/covid19/files/5170056/Memo.on.COVID.Data.Transparency.FINAL.PDF)

### Content Captains 
@JasonKarim @m-sullivan7

**Comment by abquirarte** [comment]
The URLs will be[ stored here](https://docs.google.com/spreadsheets/d/1tmYFoSx5tTOUYUAoJ08NS_4V3bvq3HBRSI7EKHtXZSc/edit#gid=0) 

We should schedule a quick sync on this tomorrow Wed 9/9 with Elizabeth and the content team.

**Comment by JasonKarim** [comment]
I don't have to spreadsheet URL

[image: image.png]



Karim
CHHS Office of Innovation
Ph. 916-214-6311

**Comment by m-sullivan7** [comment]
I have access now. :)

**Comment by TamaraIDEJA** [comment]
@JasonKarim @m-sullivan7 Our data transparency leads have uploaded resources here: https://docs.google.com/spreadsheets/d/1tmYFoSx5tTOUYUAoJ08NS_4V3bvq3HBRSI7EKHtXZSc/edit#gid=0

Can you look through these and propose the best way to organize and categorize and display this data on the page. Also, I will connect you w the SMEs so, if helpful, you can get any clarifications, contact or guidance you may need. 

cc: @hannahslee @kenbasart

**Comment by m-sullivan7** [comment]
Information published to [new webpage](https://covid19.ca.gov/agency-response/). Will determine the best place in the navigation for it to live.
