### ISSUE TITLE
Add new CalREDIE contract to Contracts page

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1574]
[California COVID Reporting System (CCRS) Tech 213 - signed.pdf](https://github.com/cagov/covid19/files/5171578/California.COVID.Reporting.System.CCRS.Tech.213.-.signed.pdf)

**Comment by kenbasart** [comment]
This has been approved to post. cc: @abquirarte

**Comment by abquirarte** [comment]
> This has been approved to post. cc: @abquirarte

Awesome! Once posted let's close the loop with David. ➿

**Comment by LizNobriga** [comment]
This contract is live now

**Comment by kenbasart** [comment]
Live on site per @LizNobriga
