### ISSUE TITLE
Plasma page Analytics 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#1579]
### The Ask

Plasma SMEs asked the following:
1) would you be able to send me the numbers of visitors to the site? and 2) is your team tracking numbers of individuals who use the zip code locator?  If so, could you provide me with that number, as well?

### Team
@traintestbritt @JasonKarim @aaronhans 
(cc'ed you all in an email for context!)

### Timeline
by early next week

**Comment by aaronhans** [comment]
The pdf export of the pageviews for the page at https://covid19.ca.gov/plasma/ is attached.

[Analytics covid19.ca.gov Pages 20200701-20200903.pdf](https://github.com/cagov/covid19/files/5175693/Analytics.covid19.ca.gov.Pages.20200701-20200903.pdf)
-table.plotKeys=%5B%5D

Interesting aspects of the traffic:
- While most of the traffic was on the English language version of this page the next most popular language was Arabic. On the rest of the site Spanish is the most used translated version.
- There is a really high time on page value on the plasma page. Spending over 3 minutes on average shows that users are focusing on this content.

Report exported from view: https://analytics.google.com/analytics/web/#/report/content-pages/a154336791w217797366p214378494/_u.date00=20200701&_u.date01=20200903&explorer-table.filter=plasma&explorer

Unfortunately we did not instrument the zip code lookup form.

**Comment by abquirarte** [comment]
my gosh love this analysis.
