### ISSUE TITLE
run security scan on covid19.ca.gov

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#159]
Chad ran a security scan recommended by CDT on alpha.ca.gov. Let's run that scan on covid19 too and see if we can figure out how to run it regularly

**Comment by ChadABratton** [comment]
I have started Veracode dynamic analysis scan!

**Comment by ChadABratton** [comment]
@aaronhans  I will follow up on this today with a new scan and attach the reuslts. Other issues took priority.

**Comment by ChadABratton** [comment]
Dynamic analysis was kicked off and should be ready for review this afternoon!
![image](https://user-images.githubusercontent.com/28573666/81312163-26fff400-903b-11ea-8b08-b7e506c4b95a.png)

**Comment by ChadABratton** [comment]
![image](https://user-images.githubusercontent.com/28573666/81350543-005fae80-9077-11ea-93f8-5263163f2385.png)

**Comment by ChadABratton** [comment]
See above image, test is still running.

**Comment by abquirarte** [comment]
Duration not available? lol. Is that normal?

**Comment by ChadABratton** [comment]
@abquirarte  yes nothing to be worried about, it should end shortly!

**Comment by abquirarte** [comment]
@ChadABratton update?

**Comment by ChadABratton** [comment]
@abquirarte  sorry I was not more proactive on this ticket! There were no security flaws identified in this scan! We can close this ticket.

**Comment by abquirarte** [comment]
Thank you Chad!

From my phone

________________________________
