### ISSUE TITLE
Blueprint page: Add punctuation to results tier text

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1607]
The text that appears within the colored box of each tier needs punctuation. This does not appear to be something we can change in WordPress.

- [x] WIDESPREAD: Add period after "Many non-essential indoor business operations are closed"

- [x] SUBSTANTIAL: Add period after "Some non-essential indoor business operations are closed"

- [x] MODERATE: Add period after "Some indoor business operations are open with modifications"

- [x] MINIMAL: Add period after "Most indoor business operations are open with modifications"

**Comment by aaronhans** [comment]
We are very close to returning this to editorial control where it belongs, https://github.com/cagov/covid19/issues/1562 will solve this soon
