### ISSUE TITLE
Blueprint page: Add link to County websites within results tier text

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1608]
Want to smooth the user's path from their county's status results to a webpage which may reveal more restrictions. Updating this text and adding the link can be done in WordPress. However, I recommend reverting to text that the GO changed, so we need their buy-in.

**Current text:** 
Counties can restrict further. Check your local health department's website for local restrictions.

**Proposed text:** 
Counties can restrict further. Check your [county's website](https://covid19.ca.gov/get-local-information/#County-websites).

**Why the text change:**
Labeling the link with the same name the user sees upon arrival reduces confusion. And these are not a list of local health department websites, but county COVID-19 websites that (like ours) are made by many different departments.

<img width="631" alt="2020-09-08_16-02-37" src="https://user-images.githubusercontent.com/63249920/92541270-65303e80-f1fa-11ea-9872-717e6e8833fc.png">

- [x] Gain GO approval (@abquirarte or @hannahslee) 
- [x] Change text in HTML block in WordPress (@m-sullivan7 or @thepegisin)
- [x] Test
- [x] Publish

**Comment by abquirarte** [comment]
Followed- up with SME and GO @thepegisin. 
They may be providing us with a list of websites for the Local Health Depts websites. contact: Jake.Hanson@cdph.ca.gov 
More to come.
