### ISSUE TITLE
Add Census Bug to Footer

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1619]
Add census bug with link to footer. Hi-res png attached.

https://census.ca.gov

Design:

https://www.figma.com/file/EtaNBkGyxO7Y05MeAdDnuX/Covid19?node-id=1435%3A152

![CA_Census_Logo_300dpi_EN](https://user-images.githubusercontent.com/69479727/92629571-5cd01600-f283-11ea-9dcf-720d297043ab.png)

**Comment by kenbasart** [comment]
cc: @hannahslee

**Comment by kenbasart** [comment]
@aaronhans following up on this ticket -- @hannahslee  has more details if needed

**Comment by aaronhans** [comment]
update deployed
