### ISSUE TITLE
state dash

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1621]
Build the new version of update.covid19.ca.gov

Latest Design: https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=1646%3A5059

Big things:

- [x] Create top section boxes in HTML+CSS, thanks @koryfey 
- [x] Add all charts to page, verify initial layout
- [x] Create first toggle for group charts at bottom
- [x] Create tier level description layout
- [x] Verify we can switch between latest county charts with javascript toggle trigger
- [x] group graphs by gender, ethnicity, age are separate and need to be rendered invisibly and swapped via javascript outside of the charts
- [x] rewrite all embeds to use new js syntax so we don't request tableau infrastructure js twice
- [x] Add the search box which auto fills county with form submit button
- [x] This controls the county/statewide toggle below
- [x] implement screen size chart sizing code
- [x] why are the charts hidden awaiting toggle going into mobile layout even when passed specific dimensions?
- [ ] add clear feature to county input field
- [x] form submit without arrow select should choose first autocomplete option
- [x] error message if you type gibberish and submit form
- [x] charts don't render in IE
- [x] major mobile layout issues
- [x] mobile refinement
- [x] remove placeholder text
- [ ] move hardcoded text into translateable location
- [x] submit page for design review

**Comment by aaronhans** [comment]
[allcases.txt](https://github.com/cagov/covid19/files/5198313/allcases.txt)
 
Export from snowflake query: ```SELECT * FROM "COVID"."OPEN_DATA"."STATEWIDE_CASES"``` of all cases per date per county is attached for experiments

**Comment by m-sullivan7** [comment]
Paragraph content for page (same as in Figma design): https://docs.google.com/document/d/1nly8W_yqZCpxvaiS29xFK_IUFDAeDQ0DJPNhmF2qcHA/edit?usp=sharing

**Comment by aaronhans** [comment]
Dynamic paragraphs:

- [ ] Lock text and send data points to Slalom so they can create queryable view that contains validated data points
    - [ ] Get queryable endpoint from Slalom
        - [ ] Build API that retrieves data from endpoint daily and writes it to github
        - [ ] Update homepage to use this new API
        - [ ] Create translatable strings for all paragraphs containing variables populated by these data points
        - [ ] Protect text from AvantPage json structure rewrite shenanigans
        - [ ] handle the fewer/additional word switches

**Comment by aaronhans** [comment]
tableau links: https://tableau.cdt.ca.gov/#/workbooks/419/views
