### ISSUE TITLE
Paginate Long List of Activities -- Dimmer Switch

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1634]
Paginate long list of activities.

@hannahslee for details.

**Comment by thepegisin** [comment]
Another word for "paginating" is "hiding."

**Comment by kenbasart** [comment]
I don't write 'em, I just copy and paste 'em!

**Comment by abquirarte** [comment]
LOL ☝️

**Comment by kenbasart** [comment]
Closing as duplicate
