### ISSUE TITLE
Remove link from homepage titles: "Video Resources" and "People want to know"

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1635]
The "Video Resources" link on the homepage links back to the homepage (covid19.ca.gov) instead of a videos page.

Contact @hannahslee for correct link.

**Comment by thepegisin** [comment]
Is that supposed to go to [https://toolkit.covid19.ca.gov/](https://toolkit.covid19.ca.gov/)?

Also, should a header be a link? It wouldn't have occurred to me to even mouse over it.

**Comment by aaronhans** [comment]
Great point @thepegisin it doesn't make sense for that to be a link and we don't want to drive traffic to toolkit because it still has a lot of a11y issues. I'll unlink that to fix this unless there is any objection

**Comment by abquirarte** [comment]
I'm OK with that 👍 We can always add if there is strong objection to this. Right now they won't miss it.

**Comment by adam-little** [comment]
I didn't realize that was a link either. Let's remove it.

While we are at it, we should also remove the link from the "People want to know" title

**Comment by abquirarte** [comment]
👆🏼

**Comment by aaronhans** [comment]
fix deployed
