### ISSUE TITLE
Update formatting of "County header" in search results on Blueprint page

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1674]
This issue addresses GO's request to make the "counties can restrict further..." text more prominent. 

It also addresses the Orange County use case in which the title for the search results is "Orange" which can lead to confusion about county name vs. risk level color.

**Requested changes:**

- Change visual styling of "county header" in search results on Blueprint page (see attached screenshots)
- Change text from "Counties can restrict further. Check your county's website." to "Note: Counties can restrict further. Check your county's COVID-19 website."
- Append the word "County" to the end of the county name (e.g. "Fresno" should say "Fresno County")
- "Check your county's COVID-19 website" should link directly to the county website using the links located [here](https://covid19.ca.gov/get-local-information/#County-websites)[THIS IS DESCOPED AS PER HANNA'S DIRECTION]

**Current Design:**

![image](https://user-images.githubusercontent.com/69167298/93269729-7500d300-f764-11ea-950d-4de9a0864928.png)

**Proposed Design:**

https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=276%3A1021

![01  Roadmap Page V1](https://user-images.githubusercontent.com/69167298/93269782-8d70ed80-f764-11ea-9f50-883a9d01d1c1.png)

**Comment by kenbasart** [comment]
@aaronhans this is ready for development

**Comment by adam-little** [comment]
@kenbasart this looks complete to me. let's close it.
