### ISSUE TITLE
Symptoms & risks page: Adding question and answer about difference between Flu and COVID-19

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1680]
Adding question and answer about difference between Flu and COVID-19. We received several comments about fire vs. COVID-19 and added Q/A in response. So, trying to a Q/A for flu before the flu season start in earnest!

- [x] Content Drafted

- [x] Review by @m-sullivan7 

- [x] Approval by @abquirarte

**Comment by m-sullivan7** [comment]
Reviewed [staging doc](https://docs.google.com/document/d/1z0oUjoknPaM2_VffV4rCO3CgJ3-F6taYVdvPFHAiNyc/edit?usp=sharing) and made proposed edits after discussion with Karim.
