### ISSUE TITLE
Homepage: Have COUNTY MAP link go directly to the map

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1686]
People are having trouble finding the county map. So let's help them in a way that worked before.

- [x] Create (or find existing) anchor link that takes user to header **Understand your county's status** @m-sullivan7 

- [x] Paste that link here (BTW, capitalization matters): https://covid19.ca.gov/safer-economy/#county-status

- [ ] Change COUNTY MAP link on homepage to go to this anchor link @aaronhans

**Comment by m-sullivan7** [comment]
Existing anchor link to county map: https://covid19.ca.gov/safer-economy/#reopening-data

**Comment by m-sullivan7** [comment]
https://covid19.ca.gov/safer-economy/#county-status is now live @aaronhans
