### ISSUE TITLE
Contact tracing page: Add a link to Google-Apple Exposure Notification app pilot projects announcement

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1692]
Add a link to Google-Apple Exposure Notification app pilot projects announcement. This will address persistent feedback comment regarding where California will use Google - Apple exposure notification app.

- [x]  Content Drafted

- [x] Review by @m-sullivan7 

- [x] @hannahslee - They do not want to increase prominence to the public page, nor confuse folks between that and contract tracing

**Comment by m-sullivan7** [comment]
Reviewed [draft content](https://docs.google.com/document/d/1Oax_Pku3fMzngWY_D1jCAqPWdFbh_7PxGhBBUlqce3c/edit?usp=sharing).

Notes:
- I added who was eligible for the pilot as this felt like a natural reader question.
- Clear publication of this with @abquirarte and @hannahslee before publication. They may want to hold until our app page launches to link to that or stakeholders may not want this info on our site yet.

**Comment by JasonKarim** [comment]
Thanks!



Karim
CHHS Office of Innovation
Ph. 916-214-6311
