### ISSUE TITLE
Team Sports Update

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1700]
CDPH is updating their Youth Sports page to include a question about Adult Sports (see bottom of page):

https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Youth-Sports-FAQ.aspx

Are adult team sports allowed?

"Adult, amateur (non-professional) team sports are not permitted at this time. The state plans to issue guidance for amateur, adult team sports soon"

Per GO (Lande Ajose):

"The Governor’s office requested that the website direct users to the Guidance for Institutions of Higher Ed on the covid19.ca.gov site."

@LizNobriga and @thepegisin please coordinate and update page(s) where/if necessary. @abquirarte suggested updating the accordion.

Email thread w/info attached.

[FOR CONFIRMATION CDPH website change request college sports.pdf](https://github.com/cagov/covid19/files/5242103/FOR.CONFIRMATION.CDPH.website.change.request.college.sports.pdf)

**Comment by LizNobriga** [comment]
This update has now been made to the [CDPH page](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Youth-Sports-FAQ.aspx) (updated on 9/18). 

**Are adult team sports allowed?**
Adult recreational team sports are not permitted at this time with guidance coming soon.  The state has issued separate guidance for collegiate sports under [guidance for institutions of higher education](https://files.covid19.ca.gov/pdf/guidance-higher-education--en.pdf).

**Comment by thepegisin** [comment]
Added a sentence about adult team sports to **Stay home** Q/A "Can I still exercise?" in Staging doc:
https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#

@abquirarte or @hannahslee, is this approved for publishing?

**Comment by thepegisin** [comment]
Would like to add **Youth sports** to What's open data, but need to know:
- Tiers data
- Youth sports guidance anchor link

**Comment by LizNobriga** [comment]
[Anchor link list for IG](https://docs.google.com/document/d/1HQIg2FNAxGnjGs9jPFCrFXs1XvN17d_ojHrnfZvvLus/edit)

[Youth sports guidance anchor link](https://covid19.ca.gov/industry-guidance/#youthsports-guidance)

**Comment by abquirarte** [comment]
inquiring with Rhys at GO on the tiers @thepegisin

**Comment by thepegisin** [comment]
- [ ] Approval gained @abquirarte 
- [ ] Youth sports added to **What's open** data with link to Youth sports guidance @thepegisin
