### ISSUE TITLE
Contact tracing page: Update to match with CDPH Policy update. Statutory changes through AB 685 will be addressed once CDPH issue matching policy

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1702]
Update contact tracing page to match with:
1) CDPH update to employer requirements, and 
2) Changes made through AB 685 will be addressed once CDPH update their policy or issue regulations to match

- [x] Content Drafted

- [x] Reviewed by @m-sullivan7

**Comment by m-sullivan7** [comment]
Provided review and edits in [staging doc](https://docs.google.com/document/d/1Oax_Pku3fMzngWY_D1jCAqPWdFbh_7PxGhBBUlqce3c/edit?usp=sharing).

**Comment by m-sullivan7** [comment]
I've provided a second round of edits in the [staging doc](https://docs.google.com/document/d/1Oax_Pku3fMzngWY_D1jCAqPWdFbh_7PxGhBBUlqce3c/edit?usp=sharing) based on new PDF guidance from CDPH.
