### ISSUE TITLE
state dashboard dynamic data in paragraphs

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1714]
This is a big component of the state dashboard project: https://github.com/cagov/covid19/issues/1621

This is an abbreviated set of things that need to happen for this to work:

- Lock text and send data points to Slalom so they can create queryable view that contains validated data points
    - Get queryable endpoint from Slalom
        - Build API that retrieves data from endpoint daily and writes it to github
        - Update homepage to use this new API
        - Create translatable strings for all paragraphs containing variables populated by these data points
        - Protect text from AvantPage json structure rewrite shenanigans
        - handle any fewer/additional word switches

**Comment by aaronhans** [comment]
Paragraph content for page from @m-sullivan7  (same as in Figma design): https://docs.google.com/document/d/1nly8W_yqZCpxvaiS29xFK_IUFDAeDQ0DJPNhmF2qcHA/edit?usp=sharing

Latest Design: https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=1646%3A5059

**Comment by carterm** [comment]
Query to retrieve...
`select top 1 * from PRODUCTION.VW_TABLEAU_COVID_METRICS_STATEWIDE order by date desc`

**Comment by carterm** [comment]
PR to add stats updates to wordpress process.
https://github.com/cagov/wordpress-integration-api/pull/52

**Comment by kenbasart** [comment]
Live per Carter comment above.
