### ISSUE TITLE
Taxes & Help for Immigrants: expanded Earned Income Tax Credit update

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1716]
- [x] Determine changes in AB 1876 that should be reflected in Taxes and Help for Immigrants pages
- [x] Coordinate with @LizNobriga on updates to Workers page
- [x] Write changes
- [x] Review by @abquirarte / @hannahslee 
- [x] Publish Help for Immigrants
- [x] Publish Taxes

**Comment by m-sullivan7** [comment]
[Help for immigrants](https://covid19.ca.gov/guide-immigrant-californians/) edits published to live with @abquirarte's approval.

Also, cc:ing @kenbasart for visibility.

**Comment by kenbasart** [comment]
Closing per @m-sullivan7 's note

**Comment by m-sullivan7** [comment]
Reopening: there's still one more page (Taxes) that needs updating, but those edits are not yet approved (even though Help for immigrants is).

**Comment by m-sullivan7** [comment]
Published updates to Taxes page, the last remaining step in this issue. Closing issue.
