### ISSUE TITLE
What's open and county map quick answers

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1717]
Users searching for "tiers", "county map", or "what's open" are presented with several quick answers before they see the Blueprint for a Safer Economy search result. Even if they find the Blueprint result, they may not know this is where the information they want to find lives.

As suggested by @JasonKarim, create quick answers to help users find this information.

An initial attempt to use the <div style="display:none;" class="js-qa js-qa-question"></div> and <blockquote class="wp-block-quote js-qa js-qa-answer"></blockquote> coding to show a quick answer using the code block for the search tool and county map was unsuccessful.

- [x] Explore whether to put the search tool (which currently includes the tier matrix as well) and county map in a quick answer or to use another solution that directs people to the Blueprint page
- [x] Determine if that solution requires developer support

**Comment by m-sullivan7** [comment]
Will deploy a first iteration solution that directs users to the Blueprint page for each need. The Stay home Q&A page previously had a question along these lines that was removed in earlier content updates. We will add a new question directing people to what's open to that page.

**Comment by thepegisin** [comment]
- [ ] Draft **What's open** and **County map** Q/As for **Stay home** page  @thepegisin 
- [ ] Get approval to publish @abquirarte 
- [ ] Publish @thepegisin

**Comment by JasonKarim** [comment]
@m-sullivan7 **Suggest closing this GitHub issue** since @thepegisin is adding relevant Q/As in the Stay home Q/As page (#1717). Q/As in Stay home Q/As page will show-up in quick search, hence no need to duplicate them in the Blueprint page.

**Comment by m-sullivan7** [comment]
Yes, that's the plan! This is actually ticket #1717--I renamed it as the scope changed. :)
