### ISSUE TITLE
Industry guidance: Responding to COVID-19 in the workplace

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1722]
- [x] Posting new CDPH guidance for Responding to COVID-19 in the workplace
Link: [https://files.covid19.ca.gov/pdf/responding-to-covid19-workplace--en.pdf](https://files.covid19.ca.gov/pdf/responding-to-covid19-workplace--en.pdf)

Industry guidance:
- [x] [Edits](https://docs.google.com/document/d/1Qk-Qq4pfRX-Jglo9UCRsmP-dN2KpdZDdU0ZWkmdrOFQ/edit#) in staging doc published

Workers:
- [x] [Edits](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit?ts=5f651b90#heading=h.y39goa2rx1qt) drafted
- [x] review by @m-sullivan7 

(Related edits for Contact tracing in separate github issue)

**Comment by LizNobriga** [comment]
- [ ] review by @m-sullivan7

**Comment by m-sullivan7** [comment]
Reviewed [staging doc](https://docs.google.com/document/d/1Qk-Qq4pfRX-Jglo9UCRsmP-dN2KpdZDdU0ZWkmdrOFQ/edit?usp=sharing) and made minor suggestions (that look to already be accepted). Good to go on my end!

**Comment by m-sullivan7** [comment]
Reviewed [Industry guidance staging doc](https://docs.google.com/document/d/1Qk-Qq4pfRX-Jglo9UCRsmP-dN2KpdZDdU0ZWkmdrOFQ/edit?usp=sharing) and made a few edits and left one question to be resolved at @LizNobriga's discretion. :)

**Comment by m-sullivan7** [comment]
New round of edits completed on reorganization.

**Comment by LizNobriga** [comment]
Proposed [edits](https://docs.google.com/document/d/1Qk-Qq4pfRX-Jglo9UCRsmP-dN2KpdZDdU0ZWkmdrOFQ/edit#heading=h.3yaamvunl40m) to reorganize - no new content added. See [clean copy](https://docs.google.com/document/d/18f41D0Kl7GHsnzgc5SlSr-auOLM-4BbsdixKuTLg74M/edit#). Thanks @m-sullivan7 for reviewing!

**Comment by m-sullivan7** [comment]
Reviewed proposed revisions to Workers in [staging doc](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit?ts=5f651b90#heading=h.y39goa2rx1qt). Approved!

**Comment by abquirarte** [comment]
@LizNobriga added one comment to the Industry guidance edits. Other than that I think its good! 
Make note that we may be getting the updated version of the employer playbook PDF early next week. These look good to me! ✅ 

Cc: @m-sullivan7 @kenbasart

**Comment by LizNobriga** [comment]
Addressed @abquirarte comment (to keep in language regarding sick leave policies).
