### ISSUE TITLE
Remove Long Beach contact info from Great Plates

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1728]
Per Kelcie at Cal OES:

"Please remove City of Long Beach contact information from the Great Plates website."

**Comment by ashleydraper** [comment]
This update has been made. Might be another 20 minutes before it shows live on the site:
https://covid19.ca.gov/restaurants-deliver-home-meals-for-seniors/

**Comment by kenbasart** [comment]
Confirmation email sent to Kelcie.
