### ISSUE TITLE
Contact tracing page: Am I considered a close contact if I was wearing a mask?

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1734]
Filling a gap in close contact definition. Q/A is copied from CDC & lightly edited. This this is consistent with CDPH GUIDANCE FOR THE USE OF FACE COVERINGS.

- [x] Content Drafted

- [x] Reviewed by @m-sullivan7 and @thepegisin 

- [x] Approved by @abquirarte

**Comment by m-sullivan7** [comment]
First round of edits made. Have asked @thepegisin for a second opinion.
