### ISSUE TITLE
H3 centering 

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1768]
covid19.ca.gov currently does not support centering of H3 headers. The text shows as centered in WordPress, but does not center on either staging or live. Screenshots show WordPress (visual editing and HTML view) and live Blueprint for a Safer Economy page on September 23, 2020.

![Live view - text is not centered](https://user-images.githubusercontent.com/69169190/94082704-66df3200-fdb6-11ea-9449-8528bab2f6c6.png)

![WordPress view - text is centered](https://user-images.githubusercontent.com/69169190/94082702-66469b80-fdb6-11ea-82dc-a68f2b8e7b9e.png)

![WordPress HTML view](https://user-images.githubusercontent.com/69169190/94082763-84140080-fdb6-11ea-91b1-ec53b3bf51fe.png)

**Comment by m-sullivan7** [comment]
cc: @kenbasart and @hannahslee for visibility

**Comment by kenbasart** [comment]
Fixed.
