### ISSUE TITLE
Expanded Personal Care Services Checklist PDF

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1779]
A new version of the Expanded Personal Care Services PDF needs to be uploaded.

Per @abquirarte "This would go in the "personal services accordion" which was updated earlier this week to reflect the changes to nail salons with the combined guidance."

[guidance-expanded-personal-care-services--en.pdf](https://github.com/cagov/covid19/files/5278918/guidance-expanded-personal-care-services--en.pdf)

**Comment by abquirarte** [comment]
Quick clarification: This is to add the checklist to the combined guidance we posted.

**Comment by LizNobriga** [comment]
Edits in the [staging doc](https://docs.google.com/document/d/1ZnlUnWGEzAULRpFwDAlIj_CijRF_rcTQj6DWIebJSFc/edit#) to update personal care services `checklist` pdf. 

Thanks @m-sullivan7 for a speedy review! 

Awaiting publishing approval from @abquirarte next. 

- [ ] pdf uploaded to covid static (live)

**Comment by LizNobriga** [comment]
This update is live now.

**Comment by LizNobriga** [comment]
Received another version of checklist with metadata fixed. This pdf is live now.
