### ISSUE TITLE
Eng tasks for new Treatment and Testing pages

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1799]
Current page /testing-and-treatment is being replaced by two new pages, /get-tested and /treatment-for-covid-19.

- [x] Publish new pages: @thepegisin 
- [x] Set redirect from /testing-and-treatment to /get-tested: @thepegisin 
- [x] Update HEALTH INFORMATION nav to change **Testing sites** (/testing-and-treatment) to **Get tested** (/get-tested): @aaronhans @carterm 
- [x] Add new nav to HEALTH INFORMATION for **Treatment for COVID-19** (/treatment-for-covid-19) under **Get tested**: @aaronhans @carterm 
- [x] Delete old /testing-and-treatment page: @thepegisin

**Comment by aaronhans** [comment]
Editorial can create redirects by adding them to this table https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=1933&action=edit and delete posts at will. Are you comfortable doing that @thepegisin?

**Comment by thepegisin** [comment]
Absolutely!

**Comment by thepegisin** [comment]
All the links to translated versions of /get-tested/ are showing as broken links (since Sunday 9/27). Can you troubleshoot, @carterm ?
<img width="721" alt="2020-09-28_09-33-18" src="https://user-images.githubusercontent.com/63249920/94460690-f9dceb00-016d-11eb-8169-bca4daf0c095.png">

**Comment by carterm** [comment]
Added new menu items, deploying to prod.

**Comment by thepegisin** [comment]
Awesome! Thank you. Closing.
