### ISSUE TITLE
CONTENT - ENG: Online retail non-existent results creates friction. 

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1821]
If a participant searches for a business or activity that is not in the list, we should try to provide them helpful feedback (e.g. “we could not find matches. Trying searching using different words.”) ⭐️

**Comment by kenbasart** [comment]
linked to https://github.com/cagov/covid19/issues/1839

**Comment by m-sullivan7** [comment]
Closing this issue as this feature is no longer on the site.
