### ISSUE TITLE
ENG: Map is difficult to use on mobile On mobile, participants didn’t realize the map was clickable.  On mobile, it’s hard to navigate, specifically when you hover and it’s hard to read.

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1827]
People don't understand why the data looks outdated

**Comment by clarita1980** [comment]
Consider placing a call to action that invites people to press a county on the map. ⭐️

**Comment by kenbasart** [comment]
Revisit in next User Research round.

**Comment by m-sullivan7** [comment]
Closing this issue as this feature is no longer on the site.
