### ISSUE TITLE
Clarification on word "Activity"

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1831]
If this page is focused on activities related to business or types of businesses, then consider using a different word than “activity.”

**Comment by tallguyjenks** [comment]
Events / Gatherings? 

Both point to close proximity of people v.s. focusing on what those people are doing (activity) thereby drawing attention away from the focus: Reducing infection vectors by minimizing gatherings and events. 

or is this off base?

**Comment by m-sullivan7** [comment]
Closing this issue as this feature is no longer on the site.
