### ISSUE TITLE
CTA from Dimmer Switch to State Dashboard

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1832]
Link to the complete data visualizations for people who need/want more data.

**Comment by kenbasart** [comment]
@adam-little please add your button mock to this ticket

**Comment by adam-little** [comment]
Here is the style of button that I recommend using. I defer to @thepegisin about the label for the CTA.

![image](https://user-images.githubusercontent.com/69167298/94622568-4e17c600-0267-11eb-96d9-203d461ef24f.png)
