### ISSUE TITLE
Make Map Shareable -- (possibly linked to OpenAPI)

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1833]
what is the status of your county (map) 
what does it mean to be in that tier (versus others) (risk level tier)
what can you do and don’t / what businesses can open/ closed and why (status + first question accordion)
since when is your county in that tier and how do you move tiers  (understand your county status)
how can you help your tier move to a lower tier (safety measures)

**Comment by m-sullivan7** [comment]
Closing this issue as it is no longer on the site.
