### ISSUE TITLE
Make user select at least 1 search field and force button press on What's Open search

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1839]
Alternatively, make only county required and default to "all industries" if industry frield is left blank.

**Comment by aaronhans** [comment]
Related: as part of the state dashboard update we changed how the county search works so it no longer does anything until you submit the form. This is now different from how the industry search field works.

If we make county required we will be removing the ability to quickly review the status of a specific industry in every county which we have now and seems helpful.

**Comment by adam-little** [comment]
Here are updated requirements for this functionality

![Frame 160](https://user-images.githubusercontent.com/69167298/94961099-e355cd00-04a8-11eb-905b-021a84eeccd9.png)
This is the default state. A user must enter at least 1 field (county or activity) in order to proceed.

![Frame 85](https://user-images.githubusercontent.com/69167298/94961336-4b0c1800-04a9-11eb-805a-117030534f29.png)
If a user clicks the search button without entering any fields, they will see an error message like this.

![Frame 157](https://user-images.githubusercontent.com/69167298/94961519-a4744700-04a9-11eb-9e96-35d81a4b5bce.png)
If a user clicks the search button without entering a valid county, they will see an error message like this

![Frame 159](https://user-images.githubusercontent.com/69167298/94961568-be158e80-04a9-11eb-8cd5-661c6fcdf80b.png)
If a user clicks the search button without entering a valid activity, they will see an error message like this

**Comment by kenbasart** [comment]
Reassigning to @aaronhans per Hannah's notes re: open tickets.

**Comment by aaronhans** [comment]
This is related to #1706

**Comment by aaronhans** [comment]
CCG-123
