### ISSUE TITLE
Add "clear" button to search fields so that a user can reset the page to its default state

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1840]

**Comment by adam-little** [comment]
Here are further details:

![Frame 160](https://user-images.githubusercontent.com/69167298/94962303-16995b80-04ab-11eb-8338-3be1cb68660a.png)
If the field is empty, there is no clear buttons.

![Frame 37](https://user-images.githubusercontent.com/69167298/94962596-91627680-04ab-11eb-95f2-494e89feb6e2.png)
![Frame 161](https://user-images.githubusercontent.com/69167298/94962598-91fb0d00-04ab-11eb-8af8-6fcc8d128acb.png)
Clear buttons appear when there are values in the form fields.

Clicking "clear" will:
1) remove the values from the fields and hide the clear buttons
2) If there are search results, the search results will update accordingly

If a user clears county while an industry is selected, then the user will see all counties for that industry

If a user clears an industry while county is selected, then the user will see all industries for that county

If only one field is selected and a user clears it, then the search results will disappear

**Comment by adam-little** [comment]
Search results when only industry is selected:
![All activities - Full list truncated](https://user-images.githubusercontent.com/69167298/94962914-21082500-04ac-11eb-8532-6a3d5bb2de9d.png)

Search results when only county is selected:
![03  Roadmap Page - Full List](https://user-images.githubusercontent.com/69167298/94963007-46952e80-04ac-11eb-97fa-013cb9a6c315.png)

**Comment by adam-little** [comment]
Note that this is complete on staging for State Dashboard but not for Dimmer Switch.

**Comment by kenbasart** [comment]
Done. Jira ticket https://digital-ca-gov.atlassian.net/browse/CCG-122
