### ISSUE TITLE
Improve spacing of blueprint framework chart on mobile

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1842]

**Comment by Mark-Tyler** [comment]
@kenbasart while I do have some experience with adjusting layout based on media, I do not have a detailed CSS understanding of Covid19 website CSS structure to make this change without possible detrimental effects. If this is not mission critical that this change takes place, then I would wait until Konstantin returns.

**Comment by adam-little** [comment]
@Mark-Tyler this should be pretty easy but it's not mission critical.

Here's how it currently looks:
![IMG_3B545AE35E8B-1 1](https://user-images.githubusercontent.com/69167298/95375395-90678580-08ad-11eb-8b79-3f963a317680.png)

Here's how it should look:
![Frame 163](https://user-images.githubusercontent.com/69167298/95375414-98272a00-08ad-11eb-87c2-1316aa71bf45.png)

Basically we just want to reduce the overall height of this matrix/table by reducing the spacing between the metrics for each risk level.

**Comment by kenbasart** [comment]
Undertstand. Will put back to Konstantin.

**Comment by kenbasart** [comment]
@aaronhans assigning this to you per the meeting we just had, as Mark says this is beyond his capabilities.

**Comment by kenbasart** [comment]
Closing as duplicate with https://digital-ca-gov.atlassian.net/browse/CCG-124
