### ISSUE TITLE
Include essential businesses in What's Open search results

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1845]

**Comment by thepegisin** [comment]
Sorry, I was wrong about this. Essential businesses are in the What's open search. See [Staging sheet for search data](https://docs.google.com/spreadsheets/d/1dpnJ20cD8Ip5StWgzNxp7EZpb08BkzPxEoS-DmIn7KE/edit#gid=503035500), where they have the category **Critical Infrastructure**.

There may be holes in this data, i.e. essential businesses that didn't make it into the search data. We should sweep to find those and add as we see fit.
