### ISSUE TITLE
Outdoor playgrounds update

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1851]
Updates needed for:
- Tiers for Blueprint/dimmer "what's open"
- Industry guidance
- Stay home Q/As
- Guidance PDFs

[Coordination doc](https://docs.google.com/document/d/1eUJWXAyBxVYcaBWyD6EJU3MWpB9iQw_-bG6EnKcSKSI/edit#) for playgrounds updates (includes IG content staging)

CDPH [outdoor playgrounds guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Outdoor%20Playgrounds%20and%20other%20Outdoor%20Recreational%20Facilities.aspx) (and flyer)
CDPH [sector chart](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/Dimmer-Framework-September_2020.pdf) updated

**Comment by m-sullivan7** [comment]
Reviewed _Industry guidance_ changes in staging doc and on staging server. All changes looked good!

**Comment by thepegisin** [comment]
Published:

- [ ] Tiers for Blueprint/dimmer "what's open"
- [ ]  Industry guidance
- [ ]  Stay home Q/As
- [ ]  Guidance PDFs
