### ISSUE TITLE
Set "Understand Your County" Anchor link to jump to correct information

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1855]
Per Dr. Chen:

The "understand your county" anchor doesn't actually go to the "understand your county" title. It goes to halfway down that section.

Need to add correct anchor link.

**Comment by m-sullivan7** [comment]
The current anchor link in the what's open search for _Understand the data_ is https://covid19.ca.gov/safer-economy/#reopening-data. This goes to the county map.

I recommend we update the link to https://covid19.ca.gov/safer-economy/#county-status. This goes to the **Understand your county's status** header, which is the desired destination. I believe this change requires engineering support.

**Comment by kkoryaka** [comment]
@kenbasart @m-sullivan7 where exactly can I find that anchor link on the site?

**Comment by adam-little** [comment]
@kenbasart this looks complete to me. let's close it.

**Comment by m-sullivan7** [comment]
I'm not getting the expected behavior when I pull up a county. The "Understand your data" link still goes to #reopening-data for me (see screenshot for the link that comes up when I hover over). I cleared my cache and still got this behavior.
![image](https://user-images.githubusercontent.com/69169190/94852512-d7053d80-03de-11eb-86eb-6331164ec177.png)

**Comment by kkoryaka** [comment]
@m-sullivan7 this one is still in staging

**Comment by m-sullivan7** [comment]
Got it! Thanks! @kkoryaka It's working perfectly on staging. :)

**Comment by Mark-Tyler** [comment]
@kenbasart it looks like this issue is good to be published (and is working properly in staging), but I think it being held up do to the issues associated with the to search boxes is keeping it from moving to prod.

**Comment by kenbasart** [comment]
Ok will assign to @aaronhans for final review. Aaron, please see the above.

**Comment by kenbasart** [comment]
Closing as duplicate with https://digital-ca-gov.atlassian.net/browse/CCG-125
