### ISSUE TITLE
Anchor Link update: Check Your County

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1856]
Per Dr. Chen:

"The check your county's website anchor - when you land it looks like you should be looking at the Q&A section (takes a while to realize the accordion is at the top of the page) - maybe its better to just send them to the top of the page so that eye level is right at the accordion"

Per @hannahslee  "just send them to the page itself"

![image](https://user-images.githubusercontent.com/69479727/94596247-bbfcc700-0240-11eb-9ec0-f3f0ff6660a9.png)

**Comment by thepegisin** [comment]
Would be even better if the link could take you to an opened version of the County websites accordion. @aaronhans says this is do-able.
