### ISSUE TITLE
Shared Transportation for Agriculture PDFs: Translations (and English)

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1859]
- [ ] Arabic

- [ ] Armenian

- [ ]  Chinese Simplified

- [ ] Chinese Traditional

- [ ] English

- [ ] Hmong

- [ ] Khmer

- [ ] Korean

- [ ] Punjabi

- [ ] Russian

- [ ] Spanish

- [ ] Tagalog

- [ ] Thai

- [ ] Vietnamese

[COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--pa.docx](https://github.com/cagov/covid19/files/5301174/COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--pa.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--en.docx](https://github.com/cagov/covid19/files/5301175/COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--en.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ko.pdf](https://github.com/cagov/covid19/files/5301176/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ko.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--tl.pdf](https://github.com/cagov/covid19/files/5301177/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--tl.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--vi.docx](https://github.com/cagov/covid19/files/5301178/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--vi.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agruiculture--es.docx](https://github.com/cagov/covid19/files/5301179/COVID-19-Guidance-Shared-Transportation-for-Agruiculture--es.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hy.docx](https://github.com/cagov/covid19/files/5301181/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hy.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hmn.pdf](https://github.com/cagov/covid19/files/5301182/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hmn.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture 8.8.20--km.docx](https://github.com/cagov/covid19/files/5301183/COVID-19-Guidance-Shared-Transportation-for-Agriculture.8.8.20--km.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ru.docx](https://github.com/cagov/covid19/files/5301184/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ru.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hans.docx](https://github.com/cagov/covid19/files/5301185/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hans.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ar.docx](https://github.com/cagov/covid19/files/5301186/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ar.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hant.pdf](https://github.com/cagov/covid19/files/5301187/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hant.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agruiculture--es.pdf](https://github.com/cagov/covid19/files/5301188/COVID-19-Guidance-Shared-Transportation-for-Agruiculture--es.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hant.docx](https://github.com/cagov/covid19/files/5301189/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hant.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture 8.8.20--km.pdf](https://github.com/cagov/covid19/files/5301190/COVID-19-Guidance-Shared-Transportation-for-Agriculture.8.8.20--km.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ru.pdf](https://github.com/cagov/covid19/files/5301191/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ru.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hmn.docx](https://github.com/cagov/covid19/files/5301192/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hmn.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ko.docx](https://github.com/cagov/covid19/files/5301193/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ko.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hy.pdf](https://github.com/cagov/covid19/files/5301194/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--hy.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--th.docx](https://github.com/cagov/covid19/files/5301195/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--th.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ar.pdf](https://github.com/cagov/covid19/files/5301196/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--ar.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--en.pdf](https://github.com/cagov/covid19/files/5301197/COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--en.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--pa.pdf](https://github.com/cagov/covid19/files/5301198/COVID-19-Guidance-Shared-Transportation-for-Agriculture_9.14--pa.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--vi.pdf](https://github.com/cagov/covid19/files/5301199/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--vi.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--tl.docx](https://github.com/cagov/covid19/files/5301200/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--tl.docx)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--th.pdf](https://github.com/cagov/covid19/files/5301201/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--th.pdf)
[COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hans.pdf](https://github.com/cagov/covid19/files/5301202/COVID-19-Guidance-Shared-Transportation-for-Agriculture-8.8.20--zh-hans.pdf)

**Comment by LizNobriga** [comment]
Closing this ticket - very old, no longer relevant
