### ISSUE TITLE
Header audit

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1860]
One of the content team's style guidelines is that we do not skip header levels. Headers should proceed in numerical order: H1, H2, H3, H4. This helps screen readers interpret content for users with disabilities.

This issue is performing an audit of content in WordPress to make sure we are following this principle.

One exception is allowed: the titles of question and answers use H4 in for the question, even if they are not preceded by an H3. This is to ensure they display correctly. A conversation may need to take place about whether this should change.

Checklist for each page:

- Confirm H1 is never used in the body (this is always reserved for the page title and done automatically)
- Confirm headers progress in order
- Confirm headers do not have bold formatting (may need to check in HTML view)

**Comment by m-sullivan7** [comment]
cc: @kenbasart for visibility

**Comment by thepegisin** [comment]
**Note:** H1 is considered the page title in our environment, so headers within page content always start with H2.

**Comment by m-sullivan7** [comment]
Great additions @thepegisin! I've added them to a checklist in the ticket body so they don't get buried.
