### ISSUE TITLE
Mass Events -- PDFs

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1889]
There are 4 PDFs that need to be added

From GO:

By close of business 9/30/2020 we hope to release guidance, and update the Blueprint, to incorporate four mass event sectors:
themeparks, fairgrounds, and water parks
convention centers
live audience pro sports
live audience concerts

Documentation attached.
[mass events - website summary.docx](https://github.com/cagov/covid19/files/5307063/mass.events.-.website.summary.docx)

**Comment by LizNobriga** [comment]
[coordination / strategy doc](https://docs.google.com/document/d/1C-ovD6C4_d3wiqYB0SMn5E4KQZSSuGu85yVbnt8SdjQ/edit)

**Comment by kenbasart** [comment]
FYI the GO is expecting this to go to the very last minute: "End of day. Before midnight."

**Comment by LizNobriga** [comment]
Updating the status - we are still awaiting this guidance.

**Comment by kenbasart** [comment]
Closing as duplicate with Jira -- issue still open.
