### ISSUE TITLE
Equity page

### ISSUE THREAD

**Issue by ashleydraper** [cagov/covid19#1895]
This page describes the inequitable impacts of COVID on populations and communities. Also provides visibility on how this data informs statewide strategy on addressing  / focusing interventions re: COVID (metrics, investments, data completeness). 

Google [staging doc](https://docs.google.com/document/d/1xVJNjsq6WRvpKPaVur84SJjGot9P5Hgv39Z6D2rFrf0/edit#)

**Comment by m-sullivan7** [comment]
Sent draft content to Jason, Julie, and Brian for review.
[Health equity covid19.ca.gov content - 2020-Oct-9.docx](https://github.com/cagov/covid19/files/5357340/Health.equity.covid19.ca.gov.content.-.2020-Oct-9.docx)

**Comment by m-sullivan7** [comment]
Closing this issue as it is now being tracked in Jira: https://digital-ca-gov.atlassian.net/browse/CCG-75
