### ISSUE TITLE
Update to Employer playbook

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#1902]
- [x] Replace updated Employer playbook (dated 9/25)

- [ ] Make related content changes (affects various pages)

**Comment by LizNobriga** [comment]
Please add staging doc links to this issue when you can! Thanks in advance :pray:

**Comment by m-sullivan7** [comment]
After reviewing the redlined playbook, I did not identify any items that looked to impact my pages. Don't hesitate to let me know if I missed something! I'm still learning my pages. :)

**Comment by LizNobriga** [comment]
Agree with @JasonKarim's note above. Let's attempt to note the main areas where the playbook is not up to date with statute or current policy.

- CA COVID-19 Supplemental Paid Sick Leave - only references EO N-51-20, but changed again with recent legislation

**Comment by ashleydraper** [comment]
I didn't see any changes that would effect my content pages. 
@LizNobriga

**Comment by kenbasart** [comment]
Closing as duplicate -- tracked in Jira per Liz.
