### ISSUE TITLE
People keep typing cities into the county search blueprint box

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#1910]
During analytics analysis with @britt and @carter we noticed a ton of entries like Santa Cruz, Calaveras. The prevalence of Calaveras was immediately noticeable and pretty strange.

We were able to duplicate the probable cause:

- People are searching for city name, CA and then hitting enter which populates the form with the closest county to that string which is Calaveras...

Could be avoided by different copy? 

Should we be creating a city searchable endpoint?

We deprioritized re enabling the zip code search but maybe city search is more important, maybe not...

**Comment by xjensen** [comment]
The premium option would involve a geocoding service, like Azure Maps API. Then people could search by anything: county, city, neighborhood, street address, latitude/longitude (think auto-searching from a phone's GPS), etc. Of course, it'd be a project. But it might be worthwhile if we have other needs/uses/possibilities/wishes that could also make use of a geocoder.

(I built an [open source thing for this purpose](https://github.com/xjensen/ca-geo-search). However, the hosting situation is a beast. CDT did not like the idea of container orchestration last time I showed this to them. I doubt it'd be worth the effort if we can get access to paid services.)

**Comment by aaronhans** [comment]
Pretty impressive open source geocoder you've got there. I have similar reservations about container orchestration.

We used the Azure location resolver autocomplete for our road condition prototype in alpha and it was a great service, easy to integrate endpoints. Hitting a full service off the shelf endpoint to resolve whatever is typed in and get the county is a great idea

**Comment by m-sullivan7** [comment]
Closing this issue as this feature is no longer on the site.
