### ISSUE TITLE
State Dashboard -- Align Positivity Rate numbers

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1916]
"Testing for Covid 19" Tableau chart for Positivity Rate uses a different rolling average (14-day) than the State Map/Tier Assignments Positivity Rate (7-day), so the numbers are different.

Request is to align the numbers.

**Comment by aaronhans** [comment]
@kenbasart this seems like a tableau team issue and could have been already fixes, assigning to you for redirection

**Comment by abquirarte** [comment]
Are going to start tracking these on JIRA now? or how does the integration work @kenbasart ?

cc: @hannahslee

**Comment by kenbasart** [comment]
New ticket will be created in Jira -- issue is still open but we have received guidance. Closing as out-of-date.
