### ISSUE TITLE
Create new search results view for when no county is selected

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1922]
When a user searches for an activity _without_ selecting a county, they will see search results formatting in the following way:

![All activities - Full list truncated](https://user-images.githubusercontent.com/69167298/94961996-9a067d00-04aa-11eb-9d15-690d50863cf5.png)

- Activity name is in the header
- Link to industry guidance is in the header 
- Alphabetical list of counties
- Status for each county
- CTA to view visit county website for each county

**Comment by aaronhans** [comment]
CCG-123
