### ISSUE TITLE
Remove "View all" from the activity dropdown on What's Open search to prevent people from viewing all activities for all counties

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1923]
Please remove the option to "view all" on the activity dropdown. If a user wants to view all activities for a county, they must select a county and leave this field blank.

**Comment by adam-little** [comment]
![image](https://user-images.githubusercontent.com/69167298/94963168-94119b80-04ac-11eb-972a-075fca732a28.png)

**Comment by xjensen** [comment]
@adam-little This request should now be live on the site via #1970. Just let us know if any changes are needed.
