### ISSUE TITLE
Fix white gap between "Infections by group" and "Is this page useful?"

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1926]
https://drive.google.com/file/d/1o0RwxOA5zfD8NollyZtzEqmundLZNyLy/view?usp=sharing

**Comment by aaronhans** [comment]
put this into in progress because there was some work done on it

**Comment by kenbasart** [comment]
Closing as duplicate with https://digital-ca-gov.atlassian.net/browse/CCG-188
