### ISSUE TITLE
New Content: Behavioral Health Page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#193]
We need to create a page that is able to collect multiple sources so that people know they can access services during this stressful time. 

Key contacts: John Connolley  (CHHS), Jim Kooler (DHCS), Janne Morgan-Olsen (CHHS)

### Resources to explore/highlight:
- [x] [DHCS page template ]([BH-Resources-Page Highlighted.pdf](https://github.com/cagov/covid19/files/4435384/BH-Resources-Page.Highlighted.pdf))
- [x] [Word doc]([BH-Resources-Page Highlighted.pdf](https://github.com/cagov/covid19/files/4435384/BH-Resources-Page.Highlighted.pdf))
- [x] [Resources and hotlines for IPV and child abuse and neglect CFSD.4_6_2020 1245pm (1).docx](https://github.com/cagov/covid19/files/4440523/Resources.and.hotlines.for.IPV.and.child.abuse.and.neglect.CFSD.4_6_2020.1245pm.1.docx)

**Comment by coreycaitlin** [comment]
Right now, this (related) content is buried on the [Healthcare page](https://covid19.ca.gov/healthcare/#top), and reads:

> I am nervous or scared. What can I do?
> 
> You’re not alone. Strategies for managing stress include:
> 
> Limit your intake of information from news sources about the virus
> Maintain social contact with friends and family by phone, text, or internet.
> Treat your body kindly: eat healthy foods and move your body.
> Call your health care provider if your anxiety prevents you from being able to continue with your daily activities.
> Here are some articles with helpful advice about managing stress and anxiety about coronavirus:
> 
> Centers for Disease Control and Prevention (CDC): Mental health and coping during COVID-19
> County of Los Angeles Public Health: Coping with stress during infectious disease outbreaks (pdf)
> If you have Medi-Cal and are in need of non-crisis mental health services, contact your County Mental Health Plan.
> 
> If you are feeling overwhelmed with sadness, depression, or anxiety, or feel like you want to harm yourself or others, call 911 or the Disaster Distress Helpline (1-800-985-5990) or text TalkWithUs to 66746. (TTY 1-800-846-8517)

**Comment by coreycaitlin** [comment]
The resources listed in the PDF can be easily converted to a web page; we should watch out for choice paralysis as we craft this page. The introductory content in the PDF is a laundry list of stressful questions, which leads to an anticipatory buildup (this is a common marketing copy tactic, but in that case the anticipation is the goal; here, it's just stressful).

I'd recommend simpler introductory language, like:

> If you are worries, anxious, angry, or depressed, you can get help. Here are some of your options:

To present the options, we might consider a table, or some kind of breakdown by format / audience. For instance, the current subdivision within the PDF is "National" vs. "Crisis lines" vs. "State and local." If I'm in crisis, I'm not sure how I would choose between those three. A more user-centric subcategorization might be:

- General crisis lines
- Crisis lines for specific people
- Suicide lifelines
- Other options for getting help (including non-hotline options)

**Comment by thepegisin** [comment]
Agree with what Corey said. I would add that it seems like there's two branches of this info, and thus we need two legit ways into it. Recommend:

- "Get help if you feel unsafe" under the **What you can do** menu, which leads to the IPV/child abuse info.
- "Crisis lines" or "Mental health" under **Find services and information**, which leads to the more helpful page Corey outlines.

**Comment by thepegisin** [comment]
Maybe also "Manage your stress" under the **What you can do** menu, which leads to "I'm nervous or scared" text.

**Comment by thepegisin** [comment]
Initial drafts of the pages I mentioned, with their menu flow.
[BH-If-you-feel-unsafe.docx](https://github.com/cagov/covid19/files/4440929/BH-If-you-feel-unsafe.docx)
[BH-Manage-your-stress.docx](https://github.com/cagov/covid19/files/4440930/BH-Manage-your-stress.docx)
[BH-Mental-health.docx](https://github.com/cagov/covid19/files/4440931/BH-Mental-health.docx)
[menu flow.docx](https://github.com/cagov/covid19/files/4440932/menu.flow.docx)

**Comment by abquirarte** [comment]
This is a lot of content to sort through. We may have to for this first iteration throw it together as best as we can. 🙁 
Kayla has started the WP draft.

**Comment by abquirarte** [comment]
[Draft document is here. ](https://docs.google.com/document/d/1yJS7FmtZsQ2m3jUNvHpyHpojy1YcoP_jxOUo7V7tSd8/edit#)

**Comment by abquirarte** [comment]
We want this to stand out Art:

**Comment by abquirarte** [comment]
> Initial drafts of the pages I mentioned, with their menu flow.
> [BH-If-you-feel-unsafe.docx](https://github.com/cagov/covid19/files/4440929/BH-If-you-feel-unsafe.docx)
> [BH-Manage-your-stress.docx](https://github.com/cagov/covid19/files/4440930/BH-Manage-your-stress.docx)
> [BH-Mental-health.docx](https://github.com/cagov/covid19/files/4440931/BH-Mental-health.docx)
> [menu flow.docx](https://github.com/cagov/covid19/files/4440932/menu.flow.docx)

@thepegisin Thank you so much for these! 🙏 it really helped provide a framework for us. It will be announced today at noon. Let's catch up tomorrow morning?

**Comment by thepegisin** [comment]
Thanks, Angie! The page looks great. Yes, call me whenever you like. 

Cheers,
Peg

**Comment by abquirarte** [comment]
This is now live as of yesterday!https://covid19.ca.gov/resources-for-emotional-support-and-well-being/#top
