### ISSUE TITLE
PDF Translations -- Cohorts

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1930]
New translated Cohorts FAQs for Schools documents to be uploaded:

https://drive.google.com/drive/folders/1xRvNx59wfAhvAhTupCibGKflvRd6pbvS

FYI there is a new language (Punjabi).

**Comment by LizNobriga** [comment]
Translations have been uploaded. @thepegisin can you add the ones that need to go on the IG in other languages page?

**Comment by LizNobriga** [comment]
these are uploaded:tada:
