### ISSUE TITLE
PDF Translations -- Cardroom Checklist

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1931]
New Outdoor Cardroom Checklist translated documents to be uploaded:

https://drive.google.com/drive/folders/1lZIFYqApWl-ZoAMHC4cJkUsGuJzFKC9g

**Comment by LizNobriga** [comment]
These have been uploaded. @thepegisin The row in orange in the checklist tab of the translations pdf spreadsheet is ready to be added to the "Industry guidance in other languages" page.

**Comment by thepegisin** [comment]
Added to **Industry guidance in other languages** page.
