### ISSUE TITLE
Broken links to fix from 10/2 SiteImprove report

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1934]
The following links are verified to be broken. Please remove or replace and check off.

- [x] **[Get local information](https://covid19.ca.gov/get-local-information/)**: Link to Orange County in **Find your county's website** has changed. Update to https://occovid19.ochealthinfo.com/. @thepegisin 
- [x] **[Emotional support](https://covid19.ca.gov/resources-for-emotional-support-and-well-being/)**:  Under **Helping others > Family Support**, link to Family Resource Center is broken. Please research and replace. @ashleydraper 
- [x]  **[Treatment for COVID-19](https://covid19.ca.gov/treatment-for-covid-19/)**:  No translate tag, so never got translated. Now there are broken links to it. Add translate tag. @thepegisin  
- [x]  **[Get financial help](https://covid19.ca.gov/get-financial-help/)**: The two dial links in the last accordion are still broken. Please correct and test to be sure they work. @ashleydraper

**Comment by ashleydraper** [comment]
@thepegisin 
I'm not sure of the intent of the Family Resource Center link. Here is the paragraph in context, but I've called this place, I've poured over their directory, I've search food assistance on this site, I'm not seeing why we would send our users there.

> If you are concerned about a family in need of food or assistance, or you need resources yourself, call 211, contact your local non-profit **[Family Resource Center](https://frcnca.org/frcnca-directory/)**, or apply for public benefits, which may include health care, cash aid, and food and nutrition assistance, through your county’s Social Services or Health and Human Services department.

**Comment by thepegisin** [comment]
I think the replacement link may be this: https://frcnca.org/resources-directory/

@ashleydraper, what do you think?

**Comment by ashleydraper** [comment]
I like getting folks to the resources. I considered the front door, but couldn't reconcile it given the intent from that paragraph. 
All links are now functioning properly, proposing to close this issue!
@thepegisin

**Comment by thepegisin** [comment]
BAM! Thank you!
