### ISSUE TITLE
Callout box looks bad on Emotional support page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1936]
This callout box at the top of the page doesn't look good. Asking for a UX/ENG intervention:

<img width="757" alt="2020-10-02_14-51-22" src="https://user-images.githubusercontent.com/63249920/94972774-f2e01080-04be-11eb-8c4b-d819b10abd35.png">

**Comment by adam-little** [comment]
@thepegisin is this a custom HTML block? Or is this Wordpress content with a class attached to it?

**Comment by adam-little** [comment]
If we are looking for a quick one-off fix: left align the blue titles

If we are looking to make this a global component that can be easily re-used on other pages, let me know and I will create a component in Figma and have the developers create a class for it.

 @thepegisin @kenbasart
