### ISSUE TITLE
Stress relief playbook Page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#194]
- [x] Create a summary of the playbook contains and link to it. _At some we'd like to build the playbook into the page_ [Draft being worked on here](https://docs.google.com/document/d/1d3y5HZ70nq_22taGZt4B5n0x85o0xV__bOXyFsyOSr8/edit#heading=h.jwk3i0zhoiiz)
- [x] Playbook on stress relief 
- [x] Point to in "what you can do" section.

**Comment by coreycaitlin** [comment]
As noted in #193, we have an abbreviated version of this kind of advice in the current answer about anxiety and stress on the [healthcare page](https://covid19.ca.gov/healthcare/#top).

The playbook is lovely, but long. It feels to me like it needs its own design, really. We could certainly put it in the existing templates (better than nothing!), but I suspect it would feel best in a simpler/calmer design.

Regardless of onscreen design, this may be one worth offering as a printable download as well — it feels like a workbook.

The last section of the playbook is also a little overwhelming, and may come across as tone-deaf for many folks. For instance, it's hard to commit to eating 5 vegetables or fruits every day when you can't get to the grocery store. Recommending walking 30 min/day without noting the need for facemasks/social distancing might be tricky, as well. In general, I think paring down the recommendations to the smallest, most possible things would help keep them from feeling impossible in the circumstances.

**Comment by abquirarte** [comment]
This is now live!
