### ISSUE TITLE
Data & Tools Page: Delete Bed Surge Dashboard

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1944]
Delete [Bed Surges Dashboard](https://public.tableau.com/views/COVID-19BedSurgeDashboard/BedSurge?:embed=y&:showVizHome=no) from the [Data & tools page](https://covid19.ca.gov/data-and-tools/), since there is no patient data left. This dashboard used to show temporary bed surge (like one at Arco Arena) and the last one at Orange county is now closed. They are unlikely to ever open again, since hospitals augmented their bed surges capacity and state is unlikely to see the 12,800 peak coronavirus infections/day that we had seen a few months back.

@abquirarte will verify with GO/CDPH.

**Comment by abquirarte** [comment]
We are not removing this. Thank you! @JasonKarim !
