### ISSUE TITLE
Bring in Data and Tools CTA

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1948]
Google Doc says it is in stage but @hannahslee and @aaronhans do not see it

https://drive.google.com/file/d/1qmah9RSW8iqnS3L03hayprEYa3NZs6ff/view?usp=sharing

From the Google Doc:

No "Explore more data" CTA

Desired Treatment: "Confirm whether we want that button"

**Comment by carterm** [comment]
I don't know what this is.  What's a CTA?

**Comment by kenbasart** [comment]
@hannahslee see above can you clarify for Carter please?

**Comment by kenbasart** [comment]
@carterm but CTA is "Call To Action" so a button or link to reach the page

**Comment by kenbasart** [comment]
Verified done
