### ISSUE TITLE
10/6 tier updates to state dashboard

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1957]
Update two dates on State Dashboard page to reflect today's tier assignments:

- "Current tier assignments as of September 29, 2020" becomes "Current tier assignments as of October 6, 2020"
- "All data and tier assignments are based on results from week ending September 19, 2020." becomes "All data and tier assignments are based on results from week ending September 26, 2020."

Screenshots also attached.
![10-6 Update 1](https://user-images.githubusercontent.com/69169190/95226311-a1cb6780-07b1-11eb-9924-8a3d2b59c6fe.png)

![10-6 Update 2](https://user-images.githubusercontent.com/69169190/95226314-a263fe00-07b1-11eb-9607-68495b357883.png)

**Comment by m-sullivan7** [comment]
cc: @kenbasart

**Comment by carterm** [comment]
(Fixed in this PR, moving to staging)
https://github.com/cagov/covid19/pull/1955
