### ISSUE TITLE
Update information on workers page regarding More benefits for workers receiving UI or PUA

### ISSUE THREAD

**Issue by clarita1980** [cagov/covid19#1964]
Information is outdated

**Comment by abquirarte** [comment]
Can we specify this more? And tag the content lead/owner?

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Closing this issue as the current page is up-to-date.
