### ISSUE TITLE
Update Wording in Content Box

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1966]
Please change the words "Total People Tested" to "Total Tests" in this data box (image attached)

Found here: https://covid19.ca.gov/state-dashboard/

![image](https://user-images.githubusercontent.com/69479727/95253750-b4569880-07d3-11eb-99b8-8ef2f35215b8.png)

**Comment by Mark-Tyler** [comment]
@kenbasart Change was made. Please review production and close if fix met issue.

**Comment by kenbasart** [comment]
Looks great! Closing as complete.
