### ISSUE TITLE
Update labels on positivity rate on state dashboard

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#1974]
Per @hannahslee, in the next rev of state dashboard, we will move the positivity rate data from a 14-day average to a 7-day average, which syncs it with the map on _Blueprint for a Safer Economy_ (also featured later on in this page). This will require an update to the labels for the  _Positivity rate in California_ graph.

![image](https://user-images.githubusercontent.com/69169190/95367655-da3e7480-0889-11eb-84f3-f0b82508f642.png)

Updates (in bold) to be made to chart content by charts team (Slalom or otherwise) when the chart is changed:
- In header: #.#% test positivity (**7**-day average)
- In subheader: #.#% change from **7** days ago
- In hoverover of trend line (as pictured in screenshot): **7**-day test positivity rate (as of MM/DD): #.#% _(note that it would be good to decapitalize Positivity Rate while we're in there)_
- In hoverover of header (not pictured): Total number of positive cases in the last **7** days out of the total number of tests reported in the last **7** days based on testing date

**Comment by aaronhans** [comment]
assigned to Hannah for organizational purposes because this looks like a tableau change. Let me know if that was not the right move

**Comment by m-sullivan7** [comment]
Being tracked in JIRA.
