### ISSUE TITLE
Great Plates extension through Nov. 8

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1987]
The Great Plates program has been extended through November 8. Please update the site.

Updated documents attached.
[FINAL_Great Plates Delivered_Program Guidance_07May2020_v20.pdf](https://github.com/cagov/covid19/files/5356089/FINAL_Great.Plates.Delivered_Program.Guidance_07May2020_v20.pdf)
[FINAL_Great Plates Delivered__Local Administrators FAQs_COVID-19_05072020v12.pdf](https://github.com/cagov/covid19/files/5356090/FINAL_Great.Plates.Delivered__Local.Administrators.FAQs_COVID-19_05072020v12.pdf)

**Comment by ashleydraper** [comment]
Extension has been posted.
