### ISSUE TITLE
Institutions of HIgher Learning -- Translated PDFs

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1990]
Renamed PDFs have been added to Google Drive.

**Comment by abquirarte** [comment]
thank you!!

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Translated guidance PDFs for higher education have been uploaded.

**Comment by kenbasart** [comment]
PDFs live per Liz, closing ticket
