### ISSUE TITLE
Treatment for COVID-19 page: Add couple of Q/As about FDA approval and Emergency Use Authorization (EUA) 

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#1996]
Add couple of questions and answers about FDA approval and Emergency Use Authorization (EUA) in preparation for adding upcoming EUA for COVID-19 monoclonal antibody drugs and coronavirus vaccines

**Comment by abquirarte** [comment]
✔️ reviewed by AQ @JasonKarim 

> thank you! I do think we need to run this by the CDPH science branch. Want to stage email so that you and Tam can send over for approval? I made a minor edit and added one comment. Great work!
