### ISSUE TITLE
Symptoms & risks page:  Adding a Q/A about risk of children becoming sick with COVID-19

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#2039]
Parents of children going back to school pointed out in a PTA meeting that COVID19.CA.GOV website does not address the risk of children getting sick with COVID-19. Hence the addition of [Q/A from CDC website](https://www.cdc.gov/coronavirus/2019-ncov/faq.html#Children) with light edits. 

- [x] Content drafted

- [x] Reviewed by @thepegisin 

- [ ] Approved by @abquirarte

**Comment by abquirarte** [comment]
Thank you! where are you adding this?

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by JasonKarim** [comment]
Symptoms & risks page
<https://docs.google.com/document/d/1z0oUjoknPaM2_VffV4rCO3CgJ3-F6taYVdvPFHAiNyc/edit#>(State
at the beginning of the title)



Karim
CHHS Office of Innovation
Ph. 916-214-6311
