### ISSUE TITLE
SEO clean up

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#219]
We want to make sure that we are optimized for SEO as much as possible. 
We have a few recommendations that we can apply now. :) 

[CA Covid-19 Gov Site - Verily SEO 4.5.20.docx](https://github.com/cagov/covid19/files/4451649/CA.Covid-19.Gov.Site.-.Verily.SEO.4.5.20.docx)

**Comment by abquirarte** [comment]
@artuoma - have we applied some of these changes? Any of these that we need to connect on? To inform the IA convos?

**Comment by artuoma** [comment]
moving this to #290
