### ISSUE TITLE
Business Category

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#22]
- [ ] Content research

- [ ] draft content for business page

MVP- point to the business portal

https://static.business.ca.gov/wp-content/uploads/2020/03/FAQ-for-California-Small-Businesses.pdf

**Comment by abquirarte** [comment]
Per GO- They want to add guidance around the impact on businesses
GoBiz pointed us to: https://business.ca.gov/coronavirus-2019/

**Comment by abquirarte** [comment]
start at 22:22 https://www.facebook.com/CAgovernor/videos/540366033561809/

Facebook | California Governor

AngieQ:ca-black:  7:01 PM
We may have to build out a new category in business.
https://github.com/cagov/covid19/issues/37


Point to: https://static.business.ca.gov/wp-content/uploads/2020/03/FAQ-for-California-Small-Businesses.pdf

**Comment by coreycaitlin** [comment]
The GO-Biz link is largely a list of links to potentially relevant state agencies, and could leave users playing guess-and-check about which agency might have what they need. If we want to build out a more actionable page on this, we'll need to dig out the meaningful policy changes and services links so people can just get to the stuff they need. We could also wrap this link (on the new page) in a sentence like: "There are many [state agencies that can help support small businesses.](https://business.ca.gov/coronavirus-2019/)."

The relevant info in the FAQ PDF looks like:

## SBA / State of Emergency

> Following California’s fast-out-of-the-gate and immediate response to
> Presidential Emergency Declaration, the U.S. Small Business Administration (SBA) is
> offering low-interest federal disaster loans for working capital to California small
> businesses suffering substantial economic injury as a result of COVID-19.
>  For more Information about SBA disaster assistance programs, and to
> apply directly online, go to: www.sba.gov/disaster
>  Or, contact SBA’s Customer Service Center at: 1-800-659-2955 / 1-800-877-
> 8339 (TTY) Or by email at: disastercustomerservice@sba.gov

...in other words, **because CA declared a State of Emergency, small businesses in CA can apply for federal disaster loans from the SBA**.

## Loan options

> - California IBank has a Small Business Loan Guarantee Program for loans up to $1 million and a JumpStart micro lending program for loans up to $10,000 with accommodations for disasters. The program is run through local mission based lenders, the Financial Development Corporations: Small Business Finance Center
> - California Treasurer’s Office has a small business loan program with special disaster assistance that is used extensively by the CDFI community: CalCAP
> - U.S. SBA: Economic Injury Disaster Loan Program . The U.S. Small Business Administration (SBA) is offering low-interest loans of up to $2 million for both for-profit and non-profit businesses that are impacted by the coronavirus.
>  For more Information about SBA disaster assistance programs, and
> to apply directly online, go to: www.sba.gov/disaster
>  Or, contact SBA’s Customer Service Center at: 1-800-659-2955 / 1-
> 800-877-8339 (TTY) Or by email at:
> disastercustomerservice@sba.gov

...in other words, there are several ways to get loans, we should link to them. (But rephrase the question to be "I need a loan" not "are there resources".)

## Rent

> Governor Newsom’s executive order suspends all state laws that would
> prevent local governments from enacting policies to protect you as a resident or
> business owner from eviction because of nonpayment of rent due to COVID-19.
> As a resident or business owner, a financial institution holding your home or
> commercial mortgage is requested to implement an immediate moratorium on
> a foreclosure involving you, when the foreclosure or foreclosure-related eviction
> arises from economic hardship caused by COVID-19 conditions. In order to
> protect renters, homeowners and commercial tenants during this pandemic,
> Governor Newsom's executive order has removed state-law limitations on local
> governments to halt evictions in the midst of the outbreak.

...in other words, the GO did a thing that will let cities and counties protect business owners from eviction, and asked banks to pause foreclosures caused by this outbreak.

**Comment by coreycaitlin** [comment]
Question: should we move the "employers" info from the current [Employment and taxes page](https://covid19.ca.gov/employment/#top) into this page? @hilaryhb @abquirarte

**Comment by abquirarte** [comment]
Hard question. Reason why I froze on this before. lol. I'd say yes, as long as there is a way for us to point employers/employees to the appropriate content/category. 

Business/tax/employees/employers....

**Comment by coreycaitlin** [comment]
Maybe separate pages each for:

- Businesses and employers
- Workers
- Taxes

Thoughts?

**Comment by abquirarte** [comment]
Technically they could be sub-pages right? We could add a new sub-page to the existing category and broaden the category?

**Comment by hilaryhb** [comment]
sub pages make sense

**Comment by abquirarte** [comment]
Love the content.

**Comment by coreycaitlin** [comment]
I think bumping things down a level (making the structure deeper by having sub-categories) will make things harder to find, unfortunately. What's the downside to having three pages? Just the number of boxes on the homepage?

**Comment by abquirarte** [comment]
I was assuming the sub-category would also be it's own page?

**Comment by coreycaitlin** [comment]
I think this is a big enough restructuring that I should take it to GDocs — will tackle tonight!

**Comment by abquirarte** [comment]
Closing, this now documented here: https://docs.google.com/document/d/1SYQPmBNFjWtruABzQei1MpIIFIXzk8ddmhHzKaAUCGw/edit
