### ISSUE TITLE
Feedback: make updates more prominent, updates to number of confirmed cases 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#223]
>Website - make updates more prominent, updates to number of confirmed cases (9%)
>Example feedback: Please let the public know when the Governor is going to speak!

We continue to hear from feedback survey that people want to be able to have the ability to see/get updates/announcements. Some particularly like to know when the Governor will speak. 

I suggest we move up the numbers toward the top and maybe add somewhere there that the Governor provides updates every day at noon with a link to the livestream?

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
