### ISSUE TITLE
Update: Resource needs to be uploaded to emotional support page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#224]
#### Context: 
The attached roster should replace the link on this state COVID-19 page, under the section “Hotlines if you need to talk to someone” for the third bullet: “California Suicide & Crisis Hotlines: Find phone numbers and links to all the suicide and crisis hotlines by county in California.”

http://www.suicidehotlines.com/california.html

It needs to be replaced with the one below.
[County_Crisis_Services_and_Suicide_Prev._Hotlines_4-08-2020.xlsx](https://github.com/cagov/covid19/files/4454067/County_Crisis_Services_and_Suicide_Prev._Hotlines_4-08-2020.xlsx)

**Comment by KaylaPrusia** [comment]
Link updated

**Comment by KaylaPrusia** [comment]
Link is a download...how do we place on the site?

**Comment by abquirarte** [comment]
This is now live: https://covid19.ca.gov/img/wp/county_crisis_services_and_suicide_prev-_hotlines_4-08-2020.pdf
