### ISSUE TITLE
Content Update: Education section

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#226]
👉 [content here ](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit#)

got approval 4/26 

--------
GO would like us to update the Education section with new resources. 

**Category captain:** Ashley 
**Contacts:** Stacey O'Brien (SME), Lande for coordination
https://www.cde.ca.gov/ls/he/hn/coronavirus.asp
Any guidance from UC, CSU, the CA Student Aid Commission, community colleges, and the Commission on Teacher Credentialing (you’ll probably just want to Google those institutions with “COVID”).

~Timeline: by Friday~

Attachments:
[COVID 19 Education Guidances_4.7.2020.docx](https://github.com/cagov/covid19/files/4456832/COVID.19.Education.Guidances_4.7.2020.docx)
[covid19guidancewebinar.pptx](https://github.com/cagov/covid19/files/4456833/covid19guidancewebinar.pptx)
[coverletter2020mar17 (1).docx](https://github.com/cagov/covid19/files/4456835/coverletter2020mar17.1.docx)
[caresupervisionguidance.docx](https://github.com/cagov/covid19/files/4456837/caresupervisionguidance.docx)

**Comment by ashleydraper** [comment]
Test

**Comment by abquirarte** [comment]
> Test

works :) @ashleydraper
