### ISSUE TITLE
Move Spanish translations to Wordpress pages 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#230]
Our Spanish content captain (Oriel) needs help moving translations to their respective Wordpress pages. The Spanish pages are already created in WordPress, we just need to replace the content with the verified translations. 

The Spanish translations are saved here:

- [x] Workers
- [x] Testing and treatment
- [x] Taxes
- [x] Symptoms and risks
- [x] stay home order
- [x] Latest numbers
- [x] Housing and homelessness
- [x] health care
- [x] Get local information 
- [x] education 
- [x] business and employers 

In this we need to make sure that the headings work.

**Comment by aaronhans** [comment]
I'll link up the ones I published in the spanish version of the site nav. I see we are in the midst of redesigning the homepage, are we going to try and translate the current version into Spanish or launch translations with an updated homepage?

**Comment by abquirarte** [comment]
Current versions into Spanish.

**Comment by aaronhans** [comment]
We are flagging all posts for which we have not yet received human translations with the "machine-translations" tag in WP. This tag should be removed once the post content gets updated by a human.
