### ISSUE TITLE
Make the feedback and hotline content more prominent 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#233]
The call center and feedback form are a great way for us to be able to hear from Californians and identify their needs. Right now the content is buried in the footer of our main page. 

Our feedback and call center responses have also progressively decreased. 

How might we make this more prominent so that it's easier for people to find. The insights from @hilaryhb below are even more reason for us to do this sooner rather than later. :) 

>From a user POV. And for those who come and need help and can’t find it on the site, I would advocate to make it more prominent and not wait for a catchier number. Once we get a catchier number we just change it (and have the old number port into the new catchier one). I am inspired by this write in survey response. He might have called in if he had seen the number - maybe he did but he was able to find the feedback in bottom footer. “I am a 73 year old caregiver for my wife, my questions are where do I go to get my wife’s oxygen tanks refilled when the company that supplies us refuses to do it!!!! And where do I go to get nitrile gloves because my wife is bedridden and she uses a bedpan??? and last who do I contact to help bring food to us, I will pay I’m not asking for anything free!!!”

**Comment by TamaraIDEJA** [comment]
Please update the hours for the call center. New hours are:

8am-8pm on Monday - Friday
8am-8pm Saturday and Sunday 

@ashleydraper @thepegisin

**Comment by ashleydraper** [comment]
Updates are ready to review. 
Call center hours are: 8am-8pm on Monday - Friday
                                   8am-**5**pm Saturday and Sunday

https://docs.google.com/document/d/1JHbAqMYKfSZiTUzFMSX_SZEW33MtWICfjS7hxoUafqQ/edit#

**Comment by abquirarte** [comment]
Closing. New issue on this: https://github.com/cagov/covid19/issues/535
