### ISSUE TITLE
New Content/Guidelines Against Discrimination 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#234]
### Context 
Governors Office would like to include content around combating Xenophobia. They shared the content bellow. Ask: Where can we best include this?

from GO: _"If these communities don't receive information from the government, they may be more susceptible to fraud or social media posts with misinformation."_

### Timeline

By Wed

### Content Captain

@ashleydraper  / @thepegisin 

For consideration- can we see which of these make most sense to include and where? -AQ

- [ ] - Add guidelines warning against prejudice and discrimination on CDPH website and CA COVID 19 website. See sample language from the CDC website: https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/reducing-stigma.html
- [ ] - Add AG website as a resource to COVID 19 website to report hate crimes. https://oag.ca.gov/hatecrimes
- [ ] - Add Immigrant Guide to the COVID 19 website: https://immigrantguide.ca.gov/
- [ ] - Coordinate with CDE to issue existing cyber bullying guidance to school districts as students are doing distance learning. https://www.cde.ca.gov/ls/ss/se/bullyingprev.asp
- [ ] - Coordinate with CalSTA to issue guidance on passenger safety to local transportation agencies.
- [ ] - Coordinate with Labor Commissioner to issue existing guidance on worker protections. https://www.dir.ca.gov/DLSE/Know_Your_Rights.html

**Comment by abquirarte** [comment]
Additional:

**Comment by ychoy** [comment]
Hi @abquirarte! Thank you for addressing this very important topic. I made some draft fliers with Canva -- I was inspired by the design from King County, Washington. My mom helped me with the Chinese translation. I used Google Translate for the Spanish translation so it's probably not accurate.
 
Check out the draft fliers: [Viruses Don't Discriminate COVID19CA Draft Fliers - English, Spanish, Chinese (Simplified).pdf](https://github.com/cagov/covid19/files/4473561/Viruses.Don.t.Discriminate.COVID19CA.Draft.Fliers.-.English.Spanish.Chinese.Simplified.pdf)

Hope these help! Let me know if you want any edits.

**Comment by abquirarte** [comment]
> Hi @abquirarte! Thank you for addressing this very important topic. I made some draft fliers with Canva -- I was inspired by the design from King County, Washington. My mom helped me with the Chinese translation. I used Google Translate for the Spanish translation so it's probably not accurate.
> 
> Check out the draft fliers: [Viruses Don't Discriminate COVID19CA Draft Fliers - English, Spanish, Chinese (Simplified).pdf](https://github.com/cagov/covid19/files/4473561/Viruses.Don.t.Discriminate.COVID19CA.Draft.Fliers.-.English.Spanish.Chinese.Simplified.pdf)
> 
> Hope these help! Let me know if you want any edits.

Now neat 😍 Thank you! We'll have to get most of this through the approval flow, but look forward to sharing these once we are live. 😄

**Comment by ashleydraper** [comment]
Super cool fliers!! Have we decided where anti-discrimination content will live on the site? @abquirarte

**Comment by ychoy** [comment]
@abquirarte Happy to help! What's the next step with the fliers? Do you need me to make an edits, or add any logos to the bottom?

**Comment by abquirarte** [comment]
This issue isn't closed yet. :)

**Comment by JasonKarim** [comment]
Sorry! Did I close this one by mistake? This was not assigned to me. Karim

**Comment by abquirarte** [comment]
👉  Final content here: https://docs.google.com/document/d/1Q9QNYJWOQDwB-LidC-CeCHJsekXfY1dIKj8IKcQCtIU/edit#heading=h.3znysh7 

Let's publish today. 

- [ ] Figure out where to add 
- [ ] Create page in WP.

**Comment by abquirarte** [comment]
@thepegisin remind me where you think this page should reside in?

**Comment by thepegisin** [comment]
How you can help -> Fight discrimination

**Comment by thepegisin** [comment]
WP page drafted: /discrimination

**Comment by abquirarte** [comment]
@artuoma is posting to "how you can help" 
Thank you! 🙏 

@ashleydraper - @ychoy Once live I think we can start sharing the cool visuals through our personal channels :)

**Comment by thepegisin** [comment]
Links we included per AQ:

- [x]  - Add guidelines warning against prejudice and discrimination on CDPH website and CA COVID 19 website. See sample language from the CDC website: https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/reducing-stigma.html
- [x]  - Add AG website as a resource to COVID 19 website to report hate crimes. https://oag.ca.gov/hatecrimes
- [ ]  - Add Immigrant Guide to the COVID 19 website: https://immigrantguide.ca.gov/
**Note: Immigrants' rights section seems to have been edited out.**
- [x]  - Coordinate with CDE to issue existing cyber bullying guidance to school districts as students are doing distance learning. https://www.cde.ca.gov/ls/ss/se/bullyingprev.asp
- [ ]  - Coordinate with CalSTA to issue guidance on passenger safety to local transportation agencies.
**Note: Passenger safety cut in edit, no statewide source for this.**
- [ ]  - Coordinate with Labor Commissioner to issue existing guidance on worker protections. https://www.dir.ca.gov/DLSE/Know_Your_Rights.html
**Note: Worker protections cut in edit, didn't seem to naturally fit**

More links added:
- [x] Fair Employment https://www.dfeh.ca.gov/Employment/
- [x] Housing https://www.dfeh.ca.gov/housing/
- [x]  Discrimination at Business Establishments https://www.dfeh.ca.gov/unruh/
- [x]  Discrimination involving state-funded programs https://www.dfeh.ca.gov/statefundedprograms/
- [x]  Hate Violence https://www.dfeh.ca.gov/hateviolence/
- [x]  DFEH Complaint Process https://www.dfeh.ca.gov/ComplaintProcess/
- [x]  GGN Twitter statement about xenophobia https://twitter.com/GavinNewsom/status/1242198231578062848

**Comment by ychoy** [comment]
> @ashleydraper - @ychoy Once live I think we can start sharing the cool visuals through our personal channels :)

Let me verify the Spanish translation. Once confirmed, I'll post the JPEG version of the fliers if anyone wants to share on their social media :-)

**Comment by ychoy** [comment]
Verified and edited the Spanish flyer, thanks to my friend Jeanette's edits. 

Feel free to share these around :) 

Fliers in PNG format (good for sharing on social media)
- ![Viruses Don't Discriminate COVID19 CA Flyer in English.png](https://user-images.githubusercontent.com/20962963/80270783-e766fe80-866f-11ea-96bf-25f8fbca6ff4.png)
- ![Viruses Don't Discriminate COVID19 CA Flyer in Spanish.png](https://user-images.githubusercontent.com/20962963/80270784-e7ff9500-866f-11ea-9c59-4940385cde59.png)
- ![Viruses Don't Discriminate COVID19 CA Flyer in Chinese.png](https://user-images.githubusercontent.com/20962963/80270781-e46c0e00-866f-11ea-9e6b-d1fdd25c234f.png)

Fliers in PDF format
- [Viruses Don't Discriminate COVID19 CA Fliers in English, Spanish, Chinese.pdf](https://github.com/cagov/covid19/files/4532337/Viruses.Don.t.Discriminate.COVID19.CA.Fliers.in.English.Spanish.Chinese.pdf)

**Comment by ychoy** [comment]
There was a small typo in the last flyer, so I'm sharing these updated versions! Thanks to everyone for sharing these!



I'm concerned about the rise in hate crimes and discrimination related to #COVID19. I was inspired by the King County (Washington) flyer. I made these multi-lingual fliers. Thanks to my mom and my friends Jeanette and Juan for helping me review and edit my translations!  



Viruses don't discriminate, and neither should we. Sharing accurate information will help us fight the coronavirus. We are in this together! For more information, check out the State of California website http://covid19.ca.gov



Los virus no discriminan, nosotros tampoco deberíamos hacerlo.

El prejuicio y la discriminación no lucharán contra el coronavirus, compartir la información precisa lo hará.

Estamos juntos en esta lucha.

Para más información: http://covid19.ca.gov



病毒不歧視, 我們也不應該。

偏见与歧视不能與冠狀病毒抗爭,

共享正确的信息将帮助我们控制疫情。

我们一起努力!

了解更多信息: http://covid19.ca.gov

![Viruses Don't Discriminate Flyer - English](https://user-images.githubusercontent.com/20962963/80728719-1b04b700-8abc-11ea-9965-da2598ed53e3.png)
![Viruses Don't Discriminate Flyer - Spanish](https://user-images.githubusercontent.com/20962963/80728723-1b9d4d80-8abc-11ea-8512-7a564f02de27.png)
![Viruses Don't Discriminate Flyer - Chinese](https://user-images.githubusercontent.com/20962963/80728707-17713000-8abc-11ea-9526-43b03619ec68.png)


[Viruses Don't Discriminate COVID19CA Fliers - English, Spanish, Chinese (Simplified).pdf](https://github.com/cagov/covid19/files/4559268/Viruses.Don.t.Discriminate.COVID19CA.Fliers.-.English.Spanish.Chinese.Simplified.pdf)
