### ISSUE TITLE
New page: Health care workers

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#236]
### context
We may have to create a new page dedicated for health care workers. This would provide regular updates for the healthcare workers working in covid-19 response. I think this could be added to Health care page consolidation or as part of the Health corps page. 

### hemingway score
Grade 15, according to SME there are legal/policy reasons to use specific language as part of this. We'll need to work with them in simplifying what we can. 

SME lowered it to 12. @KaylaPrusia / @thepegisin can you take a stab at lowering? 

### timeline 
Wed 

- [x] Moved the "new" banner language to the working doc

### dependencies
Needs GO/Policy approval, we have a draft to start with. 

👉  Content [staged here](https://docs.google.com/document/d/1g5EU4yPOahBRmERCkSQxXkYU2z03FDWl1p9556gE2LQ/edit#)

**Comment by KaylaPrusia** [comment]
Made some suggestions and added some comments. @thepegisin let me know when you have time to review and I can jump back in.

**Comment by abquirarte** [comment]
@KaylaPrusia and @thepegisin can we prioritize this one tomorrow? We have the ability to clean it up a bit and run through Krista our SME 😄

**Comment by thepegisin** [comment]
Yes. Sorry, I didn't see this yesterday. Taking a look now.

**Comment by abquirarte** [comment]
🤗

from my Samsung Work Device

**Comment by thepegisin** [comment]
Edited it to a Grade 8 read. @KaylaPrusia and I are both happy with it. Ready for your review in Staging.

**Comment by abquirarte** [comment]
Amazing 😭
@Hilary Hoeber<mailto:hilary.hoeber@alpha.ca.gov> can you take a look?

Sent from my T-Mobile 4G LTE Device

________________________________

**Comment by abquirarte** [comment]
Can someone send a link?

On Thu, Apr 16, 2020 at 12:50 PM Quirarte, Angelica@GovOps <
Angelica.Quirarte@govops.ca.gov> wrote:

> Amazing 😭
> @Hilary Hoeber <hilary.hoeber@alpha.ca.gov> can you take a look?
>
> Sent from my T-Mobile 4G LTE Device
>
> ------------------------------
> *From:* Peggy Gartin <notifications@github.com>
> *Sent:* Thursday, April 16, 2020 12:12:00 PM
> *To:* cagov/covid19 <covid19@noreply.github.com>
> *Cc:* Quirarte, Angelica@GovOps <Angelica.Quirarte@govops.ca.gov>; Author
> <author@noreply.github.com>
> *Subject:* Re: [cagov/covid19] New page: Health care workers (#236)
>
>
> Edited it to a Grade 8 read. @KaylaPrusia
> <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKaylaPrusia&data=02%7C01%7Cangelica.quirarte%40govops.ca.gov%7Cbf692c2a1e3e4d5aac3508d7e23a0a92%7C68a88534151d4e79804609be7890656c%7C0%7C0%7C637226611229910191&sdata=G43Fg3DQCI%2FpsZD%2FtOIFf4BwnxxN1j1TAMNDObmHYac%3D&reserved=0>
> and I are both happy with it. Ready for your review in Staging.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcagov%2Fcovid19%2Fissues%2F236%23issuecomment-614843332&data=02%7C01%7Cangelica.quirarte%40govops.ca.gov%7Cbf692c2a1e3e4d5aac3508d7e23a0a92%7C68a88534151d4e79804609be7890656c%7C0%7C0%7C637226611229910191&sdata=xcCiHWxiAIwCMsJ3O4v%2BFXE5Y6mQ8GUrxSO11lYXGaw%3D&reserved=0>,
> or unsubscribe
> <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACI5BXH2IXMJ6Q4SKWQDAHDRM5KABANCNFSM4MFRTFXQ&data=02%7C01%7Cangelica.quirarte%40govops.ca.gov%7Cbf692c2a1e3e4d5aac3508d7e23a0a92%7C68a88534151d4e79804609be7890656c%7C0%7C0%7C637226611229920146&sdata=tsGgliYH1HV7TPngb7shSLcEWArVyw7zcu57D75yays%3D&reserved=0>
> .
>
-- 
Hilary Hoeber
Lead Researcher
(916) 270-4718
hilary.hoeber@alpha.ca.gov <luke.fretwell@alpha.ca.gov>
Alpha.CA.gov <http://alpha.ca.gov/>

**Comment by abquirarte** [comment]
https://docs.google.com/document/d/1g5EU4yPOahBRmERCkSQxXkYU2z03FDWl1p9556gE2LQ/edit


Angelica Quirarte, "Angie"
Assistant Secretary- GovOps
c: 916-526-5510
angelica.quirarte@alpha.ca.gov
Product Owner: Alpha.CA.gov <http://alpha.ca.gov/>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by KaylaPrusia** [comment]
@thepegisin , Kristin and I have reviewed and is ready for review: https://docs.google.com/document/d/1g5EU4yPOahBRmERCkSQxXkYU2z03FDWl1p9556gE2LQ/edit#heading=h.115ta5df3vxb

**Comment by abquirarte** [comment]
- [ ] Publish to WP page- go live @KaylaPrusia 
- [ ] @thepegisin / @hilaryhb - recommend where this fits

**Comment by abquirarte** [comment]
wohoo! 🎉
