### ISSUE TITLE
News Category- what is the state doing?

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#24]
# What is CA doing? How to track Exec Orders? News section? (feature- scraper?)

Ideal: pull timestamp + link + headline from both CDPH newsroom and GO newsroom — avoid anything that will require someone from CHHS or alpha teams to manually create an item every time there’s news
Updates module on homepage for latest news?
Executive Order authorizing local governments to halt evictions, slows foreclosures, and protects against utility shut offs (https://www.gov.ca.gov/2020/03/16/governor-newsom-issues-executive-order-to-protect-renters-and-homeowners-during-covid-19-pandemic/)
More about what CA is doing to help people experiencing homelessness (GO) / hotels and motels usage
More about how CA is expanding healthcare capacity - could go in healthcare Q&A and pull talking points from GO presser

Options documented here: https://docs.google.com/document/d/1XDpMy56EfK3x8FMKud895sYHUg1N_zr1_qg5Z70-X9E/edit?ts=5e7277d0#

**Comment by artuoma** [comment]
CDPH Newsroom: https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx
- stories are consistent in using the COVID19 keyword
Governor's Newsroom: https://www.gov.ca.gov/newsroom/
- also very consistent in using the COVID-19 keyword

**Comment by aaronhans** [comment]
I am going to write something that creates structured data from those two feeds, the governor's newsroom has json feed already. We can combine this with a feed of posts on our WP instance we publish with a specific tag

**Comment by artuoma** [comment]
That would be awesome for an MVP. This way we have social media and newsrooms! I can start on a layout to see what it would look like.

**Comment by aaronhans** [comment]
sounds good, thanks @artuoma

**Comment by abquirarte** [comment]
Just learned this @artuoma and @aaronhans 

http://www.oesnews.com/

Link to the OES News site – over on the right hand side there is a box to enter your email address under “Don’t Miss a Thing” – this will allow you to sign up for OES news alerts. OES has been sending out CDPH and GO releases related to the emergency as well as their own news.

**Comment by abquirarte** [comment]
@aaronhans possible additionally sources: https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx

**Comment by aaronhans** [comment]
OK, I have the gov newsroom feed flowing into github now. Looks like oesnews has announcements that duplicate the gov newsroom. I have a scraper for the cdph newsroom and that content will be reaching github soon

Then we need to work with @artuoma to build the views

**Comment by aaronhans** [comment]
build new service that
- [ ] scrapes CDPH newsroom
- [ ] pulls articles from gov newsfeed
- [ ] dedupes pulled info against already collected ones
- [ ] commits new articles to github

- [ ] build new feed page on site
- [ ] add feed fragment to homepage
