### ISSUE TITLE
Update "New" banner language

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#242]
Currently says: 

Starting April 10, frontline health care workers who are exposed to or test positive for COVID-19 can find hotel rooms through the CalTravelStore. Visit this website on April 10 for the phone number to book a room. If hotels want to participate, they can email covid19lodging@dgs.ca.gov.

Suggested:
Starting April 10, frontline health care workers who are exposed to or test positive for COVID-19 can find hotel rooms through the [CalTravelStore](http://caltravelstore.com/ca-healthcare-workers-lodging). Call 1-877-454-8785 to validate[ your eligibility ](https://www.travelstore.com/sites/default/files/cal_oes_hotels_for_hc_workers_04092020.pdf )and make your reservation. If hotels want to participate, they can email covid19lodging@dgs.ca.gov.

**Comment by rahulkgupta** [comment]
Seems like it was fixed in https://github.com/cagov/covid19/pull/243

**Comment by abquirarte** [comment]
Correct! I need to clean up our project board. 😅

From my phone

________________________________
