### ISSUE TITLE
Mobile Feedback

### ISSUE THREAD

**Issue by rahulkgupta** [cagov/covid19#245]
Currently the mobile experience looks like the following:
<img width="386" alt="Screen Shot 2020-04-11 at 11 19 01 AM" src="https://user-images.githubusercontent.com/610372/79076169-d3ed8800-7cac-11ea-8cce-57e86a4432a6.png">

Some other feedback / questions:
- The menu content has similar information as the "What you can Do" section. Is it possible to consolidate?
- The desktop view suggests that the "Do's" section should have be higher on the visual hierarchy than the "What you can do" section but that isn't the case in the mobile experience.
- Similarly, in the mobile experience, there is a lot of information on the home page. Is there a way to reduce the amount of content on the home page?
- What percentage of traffic is mobile? 

Would it be possible to reduce the amount of header content to bring the main content above the fold?
Something like the following would be cool (understand that it might not be exactly like this and that the home link is gone, but I just wanted to show the benefit of reducing the header content):
![Screen Shot 2020-04-11 at 11 48 00 AM](https://user-images.githubusercontent.com/610372/79076182-f384b080-7cac-11ea-9420-4746d67cf7ef.png)

**Comment by abquirarte** [comment]
Thank you @rahulkgupta! We are in the process of cleaning up the content in the homepage. This is great feedback. 👍

**Comment by abquirarte** [comment]
@artuoma working on this? :)

**Comment by abquirarte** [comment]
Closing, assuming this is done @artuoma
