### ISSUE TITLE
Update content- Workers page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#246]
- [x] Draft
- [x] Angie to share for review with policy SMEs (sent 4/13)
- [x]  @LizNobriga to update based on the feedback
- [x]  Flag for translation team 
- [x] FYI to JIC 
- [x] Publish

We updated the top section to reflect recent changes (extra $600 for UI and new Pandemic Unemployment Assistance program). We also cleaned up the Q&A section. 

Draft: https://docs.google.com/document/d/1Xnt64vlzuJaLJg1tgJbAO4lLsMKJtE37LkVviVw0-MM/edit#

**Comment by abquirarte** [comment]
[Workers_draft (002) DIR Comms 4-15-20_JR.docx](https://github.com/cagov/covid19/files/4495775/Workers_draft.002.DIR.Comms.4-15-20_JR.docx)

**Comment by LizNobriga** [comment]
Published updated content.

**Comment by abquirarte** [comment]
Thank you, @LizNobriga !
