### ISSUE TITLE
more translations

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#252]
We are getting more content translated into more languages now from our partners. In order to launch human curated translations other than Spanish we need to do the following:

- [x] move all HTML with translations in it into WordPress
- [x] make language switch pulldown to choose between available translations of each page
- [x] Define new language launch requirements. Do we launch a new language if we have most of the pages translated by humans or wait for all?
- [x] add all received translated content into WordPress
- [x] ~~create draft publishing flow so WP posts can be flagged as drafts *even if they are already pu blished* and deployed to a real site without changing what is in production~~ (this should be done as part of integration with vendor's API, we can launch languages without it)

**Comment by orielgomez** [comment]
Languages:
OI Content team is currently in the process of uploading the new language translations into Wordpress. Will update to reflect progress of languages where all pages have been uploaded to Wordpress

- [] Arabic
- [] Korean
- [] Chinese (Simplified)
- [] Vietnamese

**Comment by aaronhans** [comment]
If we want to launch before we finish the full integration with the new vendor we can fill in our content holes in wordpress. I think remaining content blockers for launch are:

- [ ] get content up to date with english in all languages, english updates since 4/10 are represented here https://github.com/cagov/covid19/pull/354/files
-  [ ] translate the missing new fragments in wordpress, these all currently have the tag "needs-translation": https://as-go-covid19-d-001.azurewebsites.net/wp-admin/edit.php?tag=needs-translation we can remove the tag after that content is translated in wordpress
- [ ] add translated pages which do not yet exist in the new language in wordpress. You can see these by browsing the translated sites in staging, pages that do not exist in those languages will have links in english in the sidebar site navigation: https://as-cdt-pub-acovid-w-p-001-staging.azurewebsites.net/get-financial-help-tl/

**Comment by aaronhans** [comment]
Issues found after all content from Avant in two Chinese dialects has been imported:

zh-hant
- [ ] metadata showing on 2 homepage sections
- [ ] missing page: get-local-information-zh-hant/
- [ ] blank section in nav on stay-home-except-for-essential-needs-zh-hant/ because anchor links are missing

zh-hans
- [ ] homepage header is not translated

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/pull/412
