### ISSUE TITLE
Sign up for local alerts- in covid19.ca.gov

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#26]
Counties are pushing notifications and guidance.

Can we bring over the code from https://www.alpha.ca.gov/sign-up-for-local-emergency-alerts/ to covid19.ca.gov

Add *Get local information* page

**Comment by abquirarte** [comment]
http://www.oesnews.com/

Link to the OES News site – over on the right hand side there is a box to enter your email address under “Don’t Miss a Thing” – this will allow you to sign up for OES news alerts. OES has been sending out CDPH and GO releases related to the emergency as well as their own news.

**Comment by abquirarte** [comment]
@aaronhans we do want to deploy this

**Comment by aaronhans** [comment]
@artuoma I'll create this new page replicating current alpha functionality and send it for your review. Let me know if you have other guidance.

**Comment by aaronhans** [comment]
creating new page at /sign-up-for-local-emergency-alerts is that the desired url @abquirarte?

**Comment by abquirarte** [comment]
/sign-up-for-county-alerts

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronhans** [comment]
- [ ] create new page in 11ty
- [ ] add this page to WP Service white list
- [ ] add HTML components to page
- [ ] create new rollup process for js
- [ ] copy over missing styles
- [ ] create new watch process that rebuilds on css and js change
- [ ] create synchronized build process with both watch commands split
- [ ] get art to review new page

**Comment by abquirarte** [comment]
https://cadotgov.slack.com/archives/C010AJ5A3ME/p1585787982023400 

Nice! How much room do we have to add more content to this? ie: _Stay informed on local updates by signing up to your county alert_. (or something along those lines)

**Comment by artuoma** [comment]
I provided feedback to Aaron. Looks great! @aaronhans

**Comment by abquirarte** [comment]
Add action link: within the current Get local information page: 
"Sign up for county alerts"
![image](https://user-images.githubusercontent.com/9556188/78290524-b2d0ae80-74d8-11ea-9add-8d97cf29fe70.png)
