### ISSUE TITLE
Document publishing flow of content team 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#266]
We need to better document our internal process so that folks are clear on our process. It would also help with tracking. 

We could start by documenting the whiteboard items we covered last Monday. 

![Image from iOS (13)](https://user-images.githubusercontent.com/9556188/79191021-8111ee80-7dda-11ea-9854-891973b7cb43.jpg)

- [x] Move content to Google Doc
- [ ] Create Wiki
- [ ] Clean up content folder

**Comment by KaylaPrusia** [comment]
Team began documenting above into google doc: https://docs.google.com/document/d/1zZI_NozHmONP6kdp_0t5gPhuWbb25sYeZbEkfHQReic/edit#

**Comment by abquirarte** [comment]
Updated last night- we need to add more https://docs.google.com/document/d/1zZI_NozHmONP6kdp_0t5gPhuWbb25sYeZbEkfHQReic/edit#heading=h.q4069654y09o 

cc: @KimberlyglennTSM 

Thank you @KaylaPrusia and team for proactively starting this!! 

I'll close this issue for now
