### ISSUE TITLE
Add accordions to current "questions and answers" in pages

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#267]
### context
As a quick win, we could add accordions to the current "questions and answers." @artuoma has standardized this. The example is in the [Resources for support](https://covid19.ca.gov/resources-for-emotional-support-and-well-being/#top) page. 

![image](https://user-images.githubusercontent.com/9556188/79193024-aa347e00-7dde-11ea-9003-fb3a93bfc3cf.png)

Can the respective content captains update their pages where there are questions and answers that we could clean up with an accordion? 

### dependencies
**Art**-you may need to show us how, I don't see anything different on the WP page and I don't want to mess things up. 😆

**Comment by artuoma** [comment]
I have updated the accordions on the two pages that use it. Currently, only one content type block is supported directly under the title. To use multiple content blocks such as a list and a paragraph, those elements must be grouped together. Additionally, a certain CSS class must be applied. 

We are currently working on a solution to negate this complicated process. We will track this in issue #301
