### ISSUE TITLE
New content- price gouging

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#269]
New request below. We need to make sure it's not already covered through other content we are publishing this week. 

I'll update issue later. Tracking for now. 

Pasting email below:

During the ongoing COVID-19 public health emergency, California Attorney General Xavier Becerra has issued consumer alerts to warn Californians about fraudulent charities and price gauging.  We have created a public awareness tool kit for your offices to share with your constituencies.  The tool kit includes the following:

 

Consumer Alerts

Attached you will find a consumer alerts on price gouging and fraudulent Charities.
In English and Spanish
 

Graphics/Social Media

Included in this kit is a link with graphics in 12 languages on where to report price gauging and general donations tips that can help consumers avoid charitable giving scams.  The graphics are ready to use and are ADA compliant in the event you want to post them on your website.  Here is the link to the files:  https://www.dropbox.com/s/uf161xfbyk8lzdr/Consumer%20Alerts.zip?dl=0
Suggested social media language

**Comment by mediajunkie** [comment]
was this ever addressed?

**Comment by m-sullivan7** [comment]
@mediajunkie I'm not aware of this ever being addressed. I'm not sure it's still needed.
