### ISSUE TITLE
Add resources to Mental Health Page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#270]
### Context
Add missing resources to [Emotional health resources](https://covid19.ca.gov/resources-for-emotional-support-and-well-being/#top) page 

- [ ] Clean up, turn into pdf. 

### content captain 
Kayla 

### Timeline
End of the week

[Sexual Assault & Human Trafficking Victim Service Provider List.xlsx](https://github.com/cagov/covid19/files/4477097/Sexual.Assault.Human.Trafficking.Victim.Service.Provider.List.xlsx)

[Child Abuse and Youth Victim Service Providers.xlsx](https://github.com/cagov/covid19/files/4477098/Child.Abuse.and.Youth.Victim.Service.Providers.xlsx)

**Comment by KaylaPrusia** [comment]
Sexual Assault & Human Trafficking Victim Service Provider List (PDF)
[Sexual.Assault.Human.Trafficking.Victim.Service.Provider.List -  IPV Programs Info.pdf](https://github.com/cagov/covid19/files/4483259/Sexual.Assault.Human.Trafficking.Victim.Service.Provider.List.-.IPV.Programs.Info.pdf)

**Comment by KaylaPrusia** [comment]
Child Abuse and Youth Victim Service Providers
[Child.Abuse.and.Youth.Victim.Service.Providers -  IPV Programs Info.pdf](https://github.com/cagov/covid19/files/4483924/Child.Abuse.and.Youth.Victim.Service.Providers.-.IPV.Programs.Info.pdf)

**Comment by abquirarte** [comment]
Thank you @KaylaPrusia !
Let's add to the page, please :) 
Need us to walk you through it?

**Comment by KaylaPrusia** [comment]
@abquirarte both resources added to the page :)

**Comment by abquirarte** [comment]
Wohooo! Thank you @KaylaPrusia
