### ISSUE TITLE
Update Spanish PDF- essential workforce

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#273]
### context
Replace current link: https://covid19.ca.gov/img/wp/essential-workforce-document-spanish-03222020.pdf

in Spanish sections of Stay at home order essential workforce pdf section. 

With this attachment 
[Essential Workforce_Espanol_FINAL.pdf](https://github.com/cagov/covid19/files/4477760/Essential.Workforce_Espanol_FINAL.pdf)

- [x] upload pdf to WP library
link: /wp-content/uploads/2020/04/Essential-Workforce_Espanol_FINAL.pdf 

### Timeline
Today Tues 4/14

### Dependencies
Do we need a re-route since the other pdf has been live @carterm

**Comment by carterm** [comment]
Yes, if the other document was live, we should redirect to keep the old search traffic from crashing.

**Comment by abquirarte** [comment]
Good. That's what I've been flagging for folks. Thank you @carterm !!
