### ISSUE TITLE
Test accordions  

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#289]
### Need to ensure accordions work for everyone

- [x] Test in browserstack
- [x] Test in various mobile devices 
- [x] Test in MacOS and Windows desktops

**Comment by abquirarte** [comment]
Same with this one @artuoma feel free to combine. Or make sure to track
https://github.com/cagov/covid19/issues/267

**Comment by KaylaPrusia** [comment]
Website feedback for 4/15 had 3 instances of FAQ accordions on Stay at Home page: "None of the FAQ topics is opening. I clicked on the topic name and I clicked on the "+" sign...nothing. I closed and reopened the browser...nothing."

**Comment by KaylaPrusia** [comment]
Comment left 4/18: Webpage sections don't expand when using Microsoft Edge. For example, at https://covid19.ca.gov/stay-home-except-for-essential-needs/#top , the topics such as "What can I do? What's open?" only select (change to blue box), but don't display the info under it (the + never changes to a - ). When I changed to Internet Explorer or Brave browser, and they all expanded correctly. Not a complaint - just letting you know of a site functionality issue.

**Comment by abquirarte** [comment]
Good find @KaylaPrusia ! (And thank you for tracking on Github). 👌

**Comment by artuoma** [comment]
Testing complete: Seems like we have people that are using older browsers than the last three supported versions. @aaronhans and I have some ideas on how we can still make the content viewable to these people.

**Comment by abquirarte** [comment]
lovely! thank you! 🙏
