### ISSUE TITLE
New Categories

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#29]
# 
- MORE DATA (about testing, medical supplies, capacity, etc.)
- More clarity on what the Stay Home order means and how to cope
- Business info (we already have that underway)
- Homelessness info
- How to help (volunteering, etc.)

# Insights Funnel
- Incoming questions
- Trends / google analytics data / impacted populations
- County needs tracking (websites/social media)

## Alpha
- Category Content Captains--- steer content in the top categories, draft content, fact check
- User testing

## CDPH 
- Coordination with CDPH 
- Guidance Documents 
- Call center

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
