### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#290]
### Review SEO recommendations 
[CA Covid-19 Gov Site - Verily SEO 4.5.20.docx](https://github.com/cagov/covid19/files/4451649/CA.Covid-19.Gov.Site.-.Verily.SEO.4.5.20.docx)
- [x] Share report with @thepegisin 
- [x] Review/change page metadata in WordPress pages, [see draft](https://docs.google.com/document/d/1fs-5587a55pXxDzsuP-2a8V73l15IJ-qqkXT0rBEn5E/edit?ts=5e9d1c0b#) Peggy started. 
- [x] Review/change page metadata in static pages
- [x] Develop custom 404 page Thanks! @carterm 
- [x] Image asset compression
- [x] Image asset cashing (working with tech team) (Will create separate Github Issue)
- [x] Tap targets
- [x] Image metadata
- [x] Ensure social media profiles defined (Essential meta-tags in place, social media accounts belong to CDPH)
- [x] Apply micro data where applicable (Need to research further, required plugin)(Will add new Github Issue)

**Comment by abquirarte** [comment]
I had this open for you. Feel free to close it:

**Comment by artuoma** [comment]
@abquirarte I saw that after I created this lol thanks!

**Comment by artuoma** [comment]
@abquirarte to answer your question: have we applied some of these changes? Any of these that we need to connect on? To inform the IA convos?

**Comment by artuoma** [comment]
@thepegisin Do you think the page description for the homepage should be improved? Currently it is: "California is issuing daily coronavirus updates. COVID-19 is a new illness that can affect your lungs and airways. Check this website for the latest updates and resources.

**Comment by artuoma** [comment]
@thepegisin Also they are recommending a longer title for the homepage:

Current: 40 characters (California Coronavirus COVID-19 Response)
Recommend: Title tag can go up to 70 characters: 
Example: California Coronavirus COVID-19 Response, Education & Prep | CA.gov
 
Recommend to add longer title to include what the page is about. Keywords are in the title for Coronavirus and COVID-19 A title tag is the most important single tag in the page. It tells the search engines what your page is about so I recommend to take the full characters title will allow.

**Comment by thepegisin** [comment]
Here are the new metadescriptions and keywords I recommend for our top 10 pages all-time (as of 4/16/20): https://docs.google.com/document/d/1fs-5587a55pXxDzsuP-2a8V73l15IJ-qqkXT0rBEn5E/edit#heading=h.jyhoypdxt0d3. I didn't tackle titles in this iteration.

**Comment by thepegisin** [comment]
Metadescriptions are now updated.

**Comment by artuoma** [comment]
Ready to close this issue, here is a PR: https://github.com/cagov/covid19/pull/327

**Comment by artuoma** [comment]
@abquirarte

**Comment by abquirarte** [comment]
AMAZIIIING! 🌮 @artuoma
