### ISSUE TITLE
Further details of the Crisis Standard? e.g. organizational redundancy

### ISSUE THREAD

**Issue by plocket** [cagov/covid19#292]
[The Crisis Standard](https://github.com/cagov/covid19/wiki/Crisis-standard) is an amazing document. Not every detail, not even every important detail, can be captured in it, of course. Are there more details captured elsewhere? If it's in the linked document, that document requires permissions to view.

For example, organizational redundancy wasn't directly addressed in scalability. That seems particularly relevant right now. That is, which members of the government and technology team hold crucial knowledge about these services and how is that knowledge being captured? Or, alternatively, who is being prepared to take over the role if needed?

Maybe it's an obvious question, though, and has already been accounted for.

Thank you for your work!

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
