### ISSUE TITLE
Content suggestion: update stay at home language- move above the fold (blue)

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#293]
The messaging has changed since we went live with this.  We should elevate our call to action toward the top of the page. 
-------

![image](https://user-images.githubusercontent.com/9556188/79672543-ee7da080-8187-11ea-9601-432b5c536981.png)

Got 👍 on this the language below

>**Stay home, save lives.**
>  People can spread virus even if they never have symptoms. 
Stay home except for essential needs. If you go out, stay 6 feet away from others and wear a cloth mask.

~>People can spread the virus even if they never develop symptoms. 
Stay home except for essential needs.  If you go out, stay at least 6 feet away from other people and wear a cloth face covering.~

[Stay home order FAQ]-link to [Stay home order page. ](https://covid19.ca.gov/stay-home-except-for-essential-needs/#top)
[Essential needs] link to[ essential worker pdf](https://covid19.ca.gov/img/EssentialCriticalInfrastructureWorkers.pdf)

- [x] Move logos to bottom right corner. Make them smaller. 
- [x] Make "last updated" smaller too

**Comment by abquirarte** [comment]
Moved to: https://github.com/cagov/covid19/issues/215

**Comment by abquirarte** [comment]
Closed it to move under IA issue, but it makes more sense to keep as its own.

**Comment by abquirarte** [comment]
From @thepegisin :
I like "Stay home, save lives"

11:57
I'd change the next text to People can spread virus even if they never have symptoms. (edited) 
11:58
Stay home except for essential needs. If you go out, stay 6 feet away from others and wear a mask.
12:01
I say "mask" because it's a word people understand. Also, cloth vs. paper vs. surgical is going to continue to change. This word doesn't take us into that debate. Cloth or N95, it's a mask.

**Comment by artuoma** [comment]
Update @abquirarte I have pushed the Spanish and English version of the new banner and homepage. Please review on the live site and close issue if looks good!
