### ISSUE TITLE
Improve Accordion editing process

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#301]
- [x] Update accordions on resources for emotional support and well-being
- [x] Update accordions on Stay home order
- [x] Update code to support new "wp-accordion" class
- [x] Simplify WordPress editing process (Thanks @carterm !)
- [x] Update WordPress pages that have accordions
- [x] Update documentation

**Comment by artuoma** [comment]
Currently, only one content type block is supported directly under the title. To use multiple content blocks such as a list and a paragraph, those elements must be grouped together. Additionally, a certain CSS class must be applied. 

We are currently working on a solution to negate this complicated process.

**Comment by artuoma** [comment]
Working with @aaronhans and @carterm to simplify editing further.

**Comment by carterm** [comment]
https://github.com/cagov/covid19/pull/307

**Comment by artuoma** [comment]
[Documentation updated](https://covid19.ca.gov/stay-home-except-for-essential-needs/#top) and WP pages updated. Thanks all!

**Comment by carterm** [comment]
Done with the old accordion code yet?  I'd like to remove it.
