### ISSUE TITLE
new page/content- my child care page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#304]
## Context
Folks would like us to have a place to point to a new site: mychildcare.ca.gov.
This seems like a great service for essential workers. 

👉 [Content draft in folder](https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit)

### hemmingway score
Original draft: Grade 12
Current- grade 8

### timeline
By this afternoon

- [x] Need to add FAQ from document here. Add anything critical we may have missed from draft attached. 

[MyChildCare.ca.gov One Pager and FAQ 041720 (1).docx](https://github.com/cagov/covid19/files/4507330/MyChildCare.ca.gov.One.Pager.and.FAQ.041720.1.docx)
---------
- [x] Move [content](https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit) to wordpress. Save as draft. 
- [x] Add action link when ready

**Comment by KaylaPrusia** [comment]
@thepegisin and I had a chance to review and have several questions: https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit#

**Comment by abquirarte** [comment]
Reviewed, sent over for edits. 4/20 pm

**Comment by abquirarte** [comment]
Received draft back! Sending to @thepegisin , @hilaryhb and @KaylaPrusia for final review.

**Comment by abquirarte** [comment]
Awaiting final approval from GO/JIC.

**Comment by abquirarte** [comment]
Wohoooo!
