### ISSUE TITLE
Content update: Homelessness resources 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#305]
Let's verify which of these are missing from our current homelessness page and create content. 

### timeline
By tomorrow

👉 [Staging doc](https://docs.google.com/document/d/1lQ8hiUpSGQeW-JL5mmKcBrfKyTYSTOtMGoTYU3mDez0/edit?usp=drive_web&ouid=104723002211678314176)

### Documents for homeless assistance providers:
- [x] [Updated State Guidance for Homeless Assistance Providers](https://www.bcsh.ca.gov/hcfc/documents/covid19_homeless_guide.pdf) (March 18, 2020)

~- [ ] [State Guidance for Homeless Assistance Providers](https://www.bcsh.ca.gov/hcfc/documents/covid19_guidelines.pdf) (March 10, 2020)~
This one is replaced by the one from March 18. 

- [x] $100 million COVID-19 Emergency Homelessness Funding [allocation chart](https://www.bcsh.ca.gov/hcfc/coronavirus19/allocations.pdf)

- [x] [COVID-19 Emergency Funding Frequently Asked Questions](https://www.bcsh.ca.gov/hcfc/documents/covid19_funding_faqs.pdf)

### Consumer-facing Infographics:
We'll send it to the Governor's Digital team. 
Are You Struggling to Pay Your Mortgage?[ pdf](https://bcsh.ca.gov/coronavirus19/graphic_home.pdf)

Are You Struggling to Pay Your Rent? [pdf](https://bcsh.ca.gov/coronavirus19/graphic_rent.pdf)

¿Tiene dificultades para pagar la hipoteca?[ pdf](https://bcsh.ca.gov/coronavirus19/graphic_home_sp.pdf)

¿Tiene dificultades para pagar el alquiler? [pdf](https://bcsh.ca.gov/coronavirus19/graphic_rent_sp.pdf)

**Comment by ashleydraper** [comment]
@abquirarte 
Currently this is the only doc we link to from our site:
- [$100 million COVID-19 Emergency Homelessness Funding](https://www.bcsh.ca.gov/hcfc/coronavirus19/allocations.pdf) 

I'm not sure when we decided not to link to the March 18th guidance, but there is no need to include both March 10th and March 18th. March 18th superseded March 10th.
- [Updated State Guidance for Homeless Assistance Providers](https://www.bcsh.ca.gov/hcfc/documents/covid19_homeless_guide.pdf) (March 18, 2020)
- [State Guidance for Homeless Assistance Providers](https://www.bcsh.ca.gov/hcfc/documents/covid19_guidelines.pdf) (March 10, 2020)

I will draft changes in the content staging document to include what we're missing.

**Comment by abquirarte** [comment]
Closing.

**Comment by abquirarte** [comment]
@ashleydraper found this:
