### ISSUE TITLE
Fix last accordion type Q/A under stay @ home (hiking or visiting state parks)

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#310]
The last question on https://covid19.ca.gov/stay-home-except-for-essential-needs (hiking in or visiting state parks) is not readable--the box doesn't expand and the text is cut off.

**Comment by aaronhans** [comment]
This commit fixes the height problem by applying the card-body class to the group of elements https://github.com/cagov/covid19/compare/c122dccfb7d7...6078a6e1a7a2 

We are working on making using accordions in WordPress easier and more flexible so this will get easier and safer

**Comment by abquirarte** [comment]
Thank you Aaron!
