### ISSUE TITLE
make accordion component behave as progressive enhancement

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#312]
Right now we include web component polyfills for older browsers but there are still visitors with old versions who get left out.

We could rewrite our accordion so that it includes all of its css and include alternate css in a polyfill fail check so that if web components are not supported they just get non collapsed plain HTML

**Comment by aaronhans** [comment]
I added a conditionally loaded polyfill which will get sent to browsers without customElement support https://github.com/cagov/covid19/pull/331

**Comment by abquirarte** [comment]
still need this? @kkoryaka

**Comment by aaronhans** [comment]
We can close this and open other tasks to explore a radical build simplification: **Make everything work without giving IE any javascript** which is crazy but has a lot of potential benefits which other sites are realizing by just dropping IE support.
