### ISSUE TITLE
e2e tests for alerts, homepage, and other top pages

### ISSUE THREAD

**Issue by ChadABratton** [cagov/covid19#319]
I am starting to write end to end tests for alerts, homepage, and other top pages.

**Comment by ChadABratton** [comment]
Finished homepage test and started test for stay home except for essential needs.

**Comment by abquirarte** [comment]
yAY!!!

**Comment by ChadABratton** [comment]
I hit a snag finding a good test for: https://covid19.ca.gov/stay-home-except-for-essential-needs/
I will continue on this today as time allows.

**Comment by ChadABratton** [comment]
Added PR: https://github.com/cagov/Cron/pull/1/files
