### ISSUE TITLE
Update business FAQ 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#323]
### context

- We received content from GoBiz. 
Can we please update these FAQs with the approved content? 

### content captain
@LizNobriga 

### Timeline
By COB Wed

👉 [Updated content](https://docs.google.com/document/d/1e74utNp_Ou15h2zzFuIm8Zv9DnO2eTy7/edit?dls=true)

**Comment by LizNobriga** [comment]
Revisions reviewed by @thepegisin and ready for your review, @abquirarte. 
[Business FAQs](https://docs.google.com/document/d/13O8pre4BvNJOJWmZgdnai436cWlhFVXOXgyr_r9tf1o/edit#heading=h.jwk3i0zhoiiz)

**Comment by LizNobriga** [comment]
@abquirarte, updates live.

**Comment by abquirarte** [comment]
👉  [New updated language](https://docs.google.com/document/d/1c3aIw4M-7NPVFk6KKrrbK0zzW-uukShmZia0VPlj5S4/edit)

**Comment by LizNobriga** [comment]
Edits completed. Thanks, @thepegisin and @abquirarte!
