### ISSUE TITLE
Translation Cutover - Release Planning 

### ISSUE THREAD

**Issue by KimberlyglennTSM** [cagov/covid19#325]
- [x] Award Translation Contract - Reference Ops Repo #41

- [x] Develop - [Technical Translation Pipeline Flow](https://docs.google.com/document/d/1Y74qSIXeK0iW-2354ZhNxcN0VW3j1LfXPZHEYtGRB2A/edit#)

- [x] Deploy Translations Connector

- [ ]  Tracking sheets for the language translations

- [ ] Develop and Document Translation workflow process from Content Team to Vendor Translation Management System #252

**Comment by carterm** [comment]
Remaining work...

From AvantPage

- [ ] Descriptions (Excepts) translated.
- [ ] Final meta structure (JSON header that includes title/description)
- [ ] Separate Simplified Chinese and Traditional Chinese languages, right now we only have zh_TW.


Remaining work for us

- [ ] "Do not translate" tag
- [ ] "Priority translation" tag
- [ ] Code Content Aggregation
- [ ] Code JSON header structure for titles/description (Waiting on AvantPage)
- [ ] Strategy for migrating from WP pages to AvantPage pages
- [ ] Code Solution for migration
- [ ] Determine if we are missing anything else

**Comment by carterm** [comment]
Claudia says we can use underscores around table data headers.

**Comment by abquirarte** [comment]
@carterm is this good to close? or are we still sorting through the checklist above?

**Comment by abquirarte** [comment]
Closing this. Assuming it's done... 
@carterm @KimberlyglennTSM
