### ISSUE TITLE
perf fix CDN rule change

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#332]
Can we conditionally change caching behavior from 1 minute to a much longer time to cover the filetypes png, svg and woff2. 

This is an issue flagged by our performance tools.

I think changing the CDN rules based on filetype is easier than reconfiguring our deploy pipeline to serve static assets from the different CDN Eric mentioned recently but please confirm @ChadABratton 

Files served from homepage to chrome with cache times that need to be extended:

/img/cdph-logo.png(covid19.ca.gov)
/img/california-for-all.png(covid19.ca.gov)
/fonts/publicsans-regular-webfont.woff2(covid19.ca.gov)
/img/Ca-Gov-Logo-White.svg(covid19.ca.gov)
/fonts/CaGov.ttf?ocljyw(covid19.ca.gov)
/fonts/publicsans-bold-webfont.woff2(covid19.ca.gov)

**Comment by aaronhans** [comment]
cc @artuoma

**Comment by ChadABratton** [comment]
@aaronhans  @artuoma  I will plan to check on this today

**Comment by ChadABratton** [comment]
Met with @aaronhans 
We are going to set custom caching rules for these file types:

png, woff2, svg, ttf

New caching rule:
Override, png, woff2, svg, ttf, 1 year

**Comment by ChadABratton** [comment]
Applied CDN changes today, and got the desired results confirmed from @aaronhans 
We are good to close this issue.

**Comment by abquirarte** [comment]
:ballot_box_with_check: yay!
