### ISSUE TITLE
IA fix: Consolidate local info pages

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#333]
Right now, there are two pages where people might expect to get local information, which is super confusing. We should make them one page by moving the alert sign-up to the top of the [local info page](https://covid19.ca.gov/state-local-resources/#top). This will also save a click for folks who want to sign up for alerts but accidentally landed on the list of links.

In other words, move this:

<img width="624" alt="Screenshot 2020-04-22 07 39 41" src="https://user-images.githubusercontent.com/1450354/79995774-7c010f00-846c-11ea-9ff5-6cc8c3e837b3.png">

To replace this link: 

<img width="282" alt="Screen Shot 2020-04-22 at 7 40 24 AM" src="https://user-images.githubusercontent.com/1450354/79995819-8ae7c180-846c-11ea-9b7d-fa46cdd025c2.png">

This will also help with the page bloat we're seeing in the left-hand nav. We can avoid disruption to users and decouple this from other changes by setting up a redirect from https://covid19.ca.gov/sign-up-for-county-alerts/ --> https://covid19.ca.gov/state-local-resources/ temporarily.

Thoughts @abquirarte?

**Comment by abquirarte** [comment]
👍 agree we should combine. Documented some of this in one of the IA
drafts.

from my Samsung Work Device

**Comment by KaylaPrusia** [comment]
@abquirarte sign up for county alerts has been added to [Get Local Info page](https://covid19.ca.gov/state-local-resources/#top)

**Comment by abquirarte** [comment]
Yay cleaning!
