### ISSUE TITLE
Make updates to Alpha website

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#336]
- [x] Fix grammatical typos on thew ODI page
- [x] Add link to COVID19 website
- [x] SWAP all changes to PROD

**Comment by aaronhans** [comment]
@abquirarte please let us know how we should be linking to the covid19 site. Did you mean something like below or were you thinking of adding it to the links on the homepage?

<img width="857" alt="Screen Shot 2020-04-23 at 2 36 25 PM" src="https://user-images.githubusercontent.com/353360/80152066-ddf66d00-856f-11ea-8432-f811c160f557.png">

**Comment by abquirarte** [comment]
Good question. I was thinking the banner. 
Though would be interesting to add coronavirus response to the disaster section.

**Comment by artuoma** [comment]
The banner can't have two different messages. I would vote for making it part of the Disaster section.

**Comment by artuoma** [comment]
SO are we adding a link to the COVID19 website and the [PUA](https://unemployment.edd.ca.gov/guide/) app?

**Comment by artuoma** [comment]
@abquirarte the ODI page fix and the COVID link is in staging[](https://staging.alpha.technology.ca.gov/)

**Comment by abquirarte** [comment]
Looks good!

**Comment by abquirarte** [comment]
Browser testing good?

**Comment by aaronhans** [comment]
We have some IE issues due to partially completed refactoring we got pulled away from. Will have everything sorted out sometime tomorrow

**Comment by aaronhans** [comment]
We are clear for swap

**Comment by ChadABratton** [comment]
Swap is complete, we can close this.
