### ISSUE TITLE
Content update: Testing- Spanish page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#337]
The Spanish page doesn't have the latest from English. 
Can we at least machine translate for now to keep it up to date? Or how do you want to go about the content consolidation?

This came up when trying to document a quick fix, the testing page in Spanish. Verily project now has Spanish link and I wanted to replace the English one realizing the content is not there at all. lol. 

Verily Spanish page: https://www.projectbaseline.com/intl/es-419/study/covid-19/  

This is what we have on the Eng page:

### Drive-through testing (Project Baseline)
The California community-based COVID-19 testing program is a state-directed, federally-supported program in collaboration with Verily’s Project Baseline which will expand access to COVID-19 screening and testing for high-risk individuals in certain areas of the state.

**Complete the screener** [This is the link we want to point to] to see if you qualify for testing through this program. You will need internet access and a Google account.

Drive-through testing sites are now open in the following locations:

Northern California

Sacramento (Sacramento County)
Stockton (San Joaquin County)
San Mateo (San Mateo County)
San Jose (Santa Clara County)
Salida (Stanislaus County)
Southern California

Sherman Oaks (Los Angeles County)
Lake Elsinore (Riverside County)
Long Beach (Los Angeles County)
Testing is expanding to more locations. See the Project Baseline website for the current testing locations.

**Comment by kenbasart** [comment]
Close per AQ
