### ISSUE TITLE
Feedback from usertesting.com - content and design

### ISSUE THREAD

**Issue by hilaryhb** [cagov/covid19#341]
- [x] make "latest numbers" clearer, simple. Lots of text that's not needed

- [x] Consider moving latest numbers up on the page

- [x] FAQ on Testing page - it's not clear that the FAQ is specifically for Project Baseline  - it's at the same level as the rest of the info on the page And can it be accordioned?

- [ ] Drop down list for the Get local info page: county list

- [ ] "How you can help" (except maybe health corps sign up) should be lower on the home page - does not seem as important as other info

- [x] People really like do and don't section - can we clean it up but I suggest leaving it in

- [ ] Many people felt like the pages are very text heavy - suggestion of graphs or other visuals

- [x] Stay home order FAQ page has "essential" pdf referenced 3x on the page - we can clean this up?

- [x] Stay home order FAQ page: "what can i do? what's open?" - the content is really just what's open. I propose taking out "what can I do" -- it also conflicts with the home page "what can I do?"

- [x] Stay home order FAQ page: Under business and taxes, we refer to exempt - and then link out to the essential pdf - suggest: calling it the same as where we reference it in other places "essential jobs" like on the home page - also - what are we trying to say by "Exempt?" - it's the same as essential - let's use that language

- [ ] Emotional health page: simplify, create bullets or break up the text, this page does not abide by our content guidelines

- [ ] Update public places info: at least revisit the why is everything canceled content

- [ ] Financial help page: follow PD's advice and organize this by needs

- [ ] Financial help page: under California Eviction Moratorium - link to how someone can find a legal aid provider

- [ ] Financial help page: use simpler term than forbearance

- [x] people still click on ca.gov thinking it will take them to the home page. NO one realizes the response title bar gets them to home page

- [x] Quick edit: Home page: "Maintain a safe social distance of 6 feet whenever outside of the house" update to physical distance and use same language everywhere on site

- [ ]

**Comment by hilaryhb** [comment]
Add'l comments as of 4/23, second set: 

- [ ] reporting - people want a place to report a business 

- [ ] add Hotline in st faq - more questions? call ...

**Comment by abquirarte** [comment]
Closing this. Mover the outstanding tasks here: https://github.com/cagov/covid19/issues/529
