### ISSUE TITLE
Banner content update: Protecting COVID-Related Financial Relief

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#347]
### Title

Protecting COVID-Related Financial Relief

### Content

Today, Governor Newsom issued an executive order to stop debt collectors from garnishing any COVID-related relief. This includes federal, state, or local relief, including the Recovery Rebates under the CARES Act. Funds may still be garnished to pay for child support, family support, spousal support, or criminal restitution for victims.

Learn more about other [financial help](https://covid19.ca.gov/get-financial-help/) the state has made available.

###
@KaylaPrusia @orielgomez

**Comment by orielgomez** [comment]
This is done

**Comment by KaylaPrusia** [comment]
English is also updated

**Comment by abquirarte** [comment]
🎉
