### ISSUE TITLE
SEO - Add PDF documents to the sitemap

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#352]
Every PDF file in the project should be included as searchable content in the sitemap.

**Comment by aaronhans** [comment]
What is the benefit of this?
- Is this going to increase pagerank transfer to the pdfs?
- Is there a concern that we link some pdfs, then remove the link to them inside a page but still want them found?
- Will this help ensure indexing if a pdf is really low on a page with tons of links?

How could we accomplish it?
- It might be hard to make sure we keep this list in synch with the pdfs we want linked...
- If this list is useful can we generate it from the files.covid19.ca.gov repository?
- Now that all the pdf files are on a different subdomain does this still make sense?

**Comment by carterm** [comment]
This was accomplished on the files.covid19.ca.gov site.
https://files.covid19.ca.gov/sitemap.xml
