### ISSUE TITLE
Food for seniors page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#361]
Fire drill! :fire: :female-firefighter: 

New page. Will launch as is. Food for seniors. 

- We will have to incorporate into the actual food page afterward. Which is yet to be announced. 
- This will not be translated. (today). 
We'll link to if from the banner for now. 

👉  [Language for page in our content folder](https://docs.google.com/document/d/1l0aHeVbJxnmilF8roTLlj9zH82pd1o3yhIfIvXv5BAI/edit)

- [x] publish to WordPress @thepegisin @LizNobriga 
- [x] Add banner language @KaylaPrusia 
- [x] Link page in banner language

#### banner language:
**Restaurants Deliver: Home Meals for Seniors**
Today, Governor Newsom announced a new program for local governments to provide restaurant delivery service to older Californians. More information is available here and sign-up details for older Californians will be available soon.

Older Californians who need someone to talk to can call the new statewide Friendship Line at 888.670.1360

**Comment by abquirarte** [comment]
🎉 💧 @thepegisin @KaylaPrusia @LizNobriga 💪

**Comment by TamaraIDEJA** [comment]
Add Spanish translation - content here: https://docs.google.com/document/d/11jM_6kHJKIbNmx6mOO8ZsXnxRDGbL671CUlg50VkGhg/edit 

@thepegisin

**Comment by LizNobriga** [comment]
@abquirarte @TamaraIDEJA @thepegisin Spanish is ready in WP now.

**Comment by LizNobriga** [comment]
For Spanish:
- [x] Publish to WP
- [x] Add banner language
- [x] Link page in banner language

**Comment by abquirarte** [comment]
🎉
