### ISSUE TITLE
Add content to get financial help page (student loans)

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#364]
### Ask
We were asked to add content around student loan relief to our page. They suggested to add to /get-financial-help page. 

Let's review what they provided and come up with suggested language. 

👉 Staging doc.

### timeline 
Early next week

- [ ] Draft content
- [ ] note as translation need (tag this github issue in the translation spreadsheet)

### context

>Here is a link to the Governor’s news release (I figure you probably know how to find this, but it never hurts to be helpful 😊 ):  https://www.gov.ca.gov/2020/04/23/governor-newsom-announces-additional-relief-for-californians-impacted-by-covid-19/

>Here’s a link to the Department of Business Oversight release that followed the Governor’s release – it has a bit more detail:  https://dbo.ca.gov/2020/04/23/california-provides-expansion-of-student-loan-relief-most-private-loan-servicers-agree-to-help/

>The following links are going to be the most helpful to borrowers:

>FAQs are here: https://dbo.ca.gov/private-student-loans-faq/

>A list the loan servicers with contact information is here: https://dbo.ca.gov/contact-information-for-private-student-loan-servicers/

**Comment by abquirarte** [comment]
@ashleydraper anything we can look at? :)

**Comment by ashleydraper** [comment]
@abquirarte @thepegisin Attaching the Get Financial Help and Education pages, proposing that both should change to reflect these updates.

**Comment by abquirarte** [comment]
:ballot_box_with_check:
