### ISSUE TITLE
Clean up: Add accordions to FAQs in all our pages. 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#369]
The dev/design team made it easy for us to add accordions to pages. 

Content captains, please go through your pages and add accordions to the FAQs in your respective categories/pages.

👉 [Follow these instructions](https://docs.google.com/document/d/1lDYTRFflRHiITA_TeSDYAcYzTeShAhAfUhz0p3wcLJM/edit#heading=h.fm14jf2dj7id)

**Comment by LizNobriga** [comment]
Accordion status by page:
- [x] Education
- [x] Get testing and treatment
- [x] Get local information
- [x] Taxes
- [x] Stay at home
- [x] Public places
- [x] Workers
- [x] Health corps
- [x] Housing and homelessness
- [ ] Health care
- [ ] Get financial help
- [ ] Telehealth (removing/adjusting)

Don’t need accordions:
-  Know symptoms and risks
-  Emotional health resources (no additional)
-  Manage stress for health
-  Guide for immigrant Californians
-  Sign up for alerts
-  Fight discrimination

**Comment by abquirarte** [comment]
Will close this. Yay!!!
