### ISSUE TITLE
Symptoms & Risks: Revise Section to Match with CDC & CDPH

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#374]
Symptoms and Risks section is revised to match with CDC. This will make more people eligible for free testing and provide some earlier access to treatments, when appropriate.

**Comment by thepegisin** [comment]
- [x] Staging doc edited: https://docs.google.com/document/d/1z0oUjoknPaM2_VffV4rCO3CgJ3-F6taYVdvPFHAiNyc/edit

**Comment by TamaraIDEJA** [comment]
Our SME approved the edits  on this page. 

His note for your context: 

Yes, we discussed this morning with Dr. A.  We should all move to updating key guidance documents to reflect the expanded CDC symptom list:
 
•Fever
•Cough
•Shortness of breath or difficulty breathing
•Chills
•Repeated shaking with chills
•Muscle pain
•Headache
•Sore throat
•New loss of taste or smell
 
Also concur with changes to the high-risk conditions.

@thepegisin @JasonKarim @abquirarte

**Comment by abquirarte** [comment]
Good to publish!! Once live let's flag for JIC as FYI @TamaraIDEJA :)
