### ISSUE TITLE
Daily updates- Wednesday 11/21

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#386]
### Daily updates @orielgomez @KaylaPrusia 
publish 11:50am 

- [x] Update banner:
> **Food Resources**
If you or someone you know is struggling to afford groceries or prepared meals, there is help available. Use the new[ food resources page](https://covid19.ca.gov/food-resources/) to learn more about food assistance programs, including the new Pandemic-EBT program announced today.

- [x] Banner in Spanish
- [x] Latest numbers English
- [ ] Latest numbers Spanish 

### Other clean up
**Child care** @KaylaPrusia @thepegisin 
- [x] Change childcare page url from: ~find-child-care-options-near-you~ to /childcare so it's ready for announcement tomorrow
- [x] Update metadata tags of childcare page 

**Immigrant guide docs** @orielgomez @thepegisin 
- [x] Replace Immigrant guide documents in English and Spanish with the following:

[LISTOS_COVID_19_immigrant_guidance_ES_dAf.pdf](https://github.com/cagov/covid19/files/4553583/LISTOS_COVID_19_immigrant_guidance_ES_dAf.pdf)

[LISTOS_COVID_19_immigrant_guidance_EN_dAf.pdf](https://github.com/cagov/covid19/files/4553586/LISTOS_COVID_19_immigrant_guidance_EN_dAf.pdf)

**Essential workers page**
- [x] Update link on banner so it points to new page (not pdf) 
![image](https://user-images.githubusercontent.com/9556188/80632166-b427c500-8a0b-11ea-8f03-ea8a67590c18.png)

**Comment by thepegisin** [comment]
Other clean up
Child care @KaylaPrusia @thepegisin

- [x]  Change childcare page url from: find-child-care-options-near-you to /childcare so it's ready for announcement tomorrow

- [x] Update metadata tags of childcare page

**Comment by thepegisin** [comment]
- [x] Update link on banner so it points to new page (not pdf)

Publishing now (11:52), should be live within 10 minutes.

**Comment by abquirarte** [comment]
wohooo!
