### ISSUE TITLE
www redirect

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#387]
The covid19 website allows for "www." and non-"www." requests.  That affects our analytics.  We need to pick one.

- [ ] Decide on www. or non-www.
- [ ] Set up redirect for www

**Comment by abquirarte** [comment]
Was this decided? 
I like non-www. But will defer to best practice lol.

**Comment by ChadABratton** [comment]
@abquirarte  @carterm  I am meeting with Shamal to discuss this now.

**Comment by ChadABratton** [comment]
Just to follow up, www redirect is complete. visiting www.covid19.ca.gov will now remove the WWW automatically. We completed this using redirects in Azure Front Door and a new DNS entry. The change was very smooth, zero downtime!

**Comment by carterm** [comment]
Did some testing this morning and everything checks out.  Thanks Chad!
