### ISSUE TITLE
Google search console, claim property via DNS

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#388]
The Google search console is currently claimed via a Google HTML site verification file.  It's a file in the GitHub project (pages/rootcopy/google6429122b33c9a925.html).  That type of claim does not include www. and non-www data combined, so we aren't able to see search traffic on www.

This will require adding a TXT record to the domain for google-site-verification.

**Comment by carterm** [comment]
This is also a problem because this claim ticket can be seen in our repo.

**Comment by aaronhans** [comment]
I don't think this is still relevant because we redirect from www.covid19.ca.gov to covid19.ca.gov which is excellent.
