### ISSUE TITLE
New Content: Family_and_Friends_Caregiver_Resources

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#392]
### Content
We received new request from CHHS Undersecretary and Director of Department of Aging to add these important resources to our website: 
https://www.aging.ca.gov/covid19/Family_and_Friends_Caregiver_Resources/

FAQ for Families and Friends with a Loved One in a SNF and RCFE:
https://www.aging.ca.gov/download.ashx?lE0rcNUV0zaaXLD5JZ%2f6Uw%3d%3d
 
### Content Captain
@LizNobriga @thepegisin, please work to determine where and how we want to display this content and resources. 

### Timeline 
COB Friday

**Comment by LizNobriga** [comment]
5/1:
- [x] Drafted by @LizNobriga in [staging g-docs](https://docs.google.com/document/d/1rQ2CkcTbQKUwZ114yLGHTFyF-qnZmqJqiGeV0ykdY5s/edit) (multiple)
- [x] Reviewed by @thepegisin 
- [x] Reviewed by @abquirarte and approved for WP live
- [x] Updated [content/translations tracker](https://docs.google.com/spreadsheets/d/1l6xzPk9lES4W9gU7CNQeteJj2jrX9GzU4jerzMMvJb0/edit#gid=1035669658)

**Comment by abquirarte** [comment]
:tada:
