### ISSUE TITLE
Content (housing) for Anti-discrimination page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#393]
We have some fliers from the Department of Fair Employment and Housing regarding housing discrimination during the COVID-19 pandemic that you might find useful for the “Fight Discrimination” page. In addition to the links below, DFEH will be producing another flier regarding hate violence and COVID-19, and I can send that to you once it has been approved.

https://www.dfeh.ca.gov/wp-content/uploads/sites/32/2020/04/DFEH-Housing-Information-on-COVID-19-FAQ_ENG.pdf

 

https://www.dfeh.ca.gov/wp-content/uploads/sites/32/2020/04/DFEH-Housing-Information-on-COVID-19-FAQ_SP.pdf

**Comment by TamaraIDEJA** [comment]
Please add this new resource to the “fight discrimination” page. @thepegisin 

[Combatting Hate Crimes During the Coronavirus Pandemic.pdf](https://github.com/cagov/covid19/files/4583294/Combatting.Hate.Crimes.During.the.Coronavirus.Pandemic.pdf)

**Comment by abquirarte** [comment]
@thepegisin did we end up doing this?

**Comment by thepegisin** [comment]
- [ ] Learn the file upload/URL generation process
- [ ] Link Combatting Hate Crimes PDF to Fight discrimination page and publish

**Comment by abquirarte** [comment]
thank you! 🙏
