### ISSUE TITLE
Create a /jobs page

### ISSUE THREAD

**Issue by phae** [cagov/covid19#399]
Using the existing page template, create a new alpha.ca.gov/jobs 

Content would be:
* Introductory paragraph to explain the team 
* A list of open positions (can use an accordian or link to separate pages to show job descriptions)
* A big obvious "apply here" linking out to https://state-of-california-agency.forms.fm/california-digital-were-hiring/forms/7721

Myself and @KimberlyglennTSM can provide copy.

**Comment by phae** [comment]
Actually, if someone just sets up the empty page for me, I can PR in the content.

**Comment by aaronhans** [comment]
I created a new page in the jobs branch of the news site: https://github.com/cagov/news/tree/jobs
This is an 11ty site so can be run locally, that post doesn't have the news tag so it will be a standalone page and won't be part of the main feed on the homepage

**Comment by phae** [comment]
I think cagov/news is a private repo, so I don't have access to that one.

**Comment by aaronhans** [comment]
That seems wrong, thanks for pointing that out. I added you and made the repo public. I don't see any secrets in there we shouldn't let be public

**Comment by phae** [comment]
:heart: ty. I'll have a poke around.
