### ISSUE TITLE
Education page: Change link re: students with disabilities

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#40]
Per feedback:

Change link in FAQ on students with disabilities to link to California K-12 guidance on distance learning (https://www.cde.ca.gov/ls/he/hn/distancelearning.asp) rather than the US Department of Education resource currently linked. The federal guidance is unhelpful and, as framed, suggests that K-12 schools should suspend all instruction to avoid potential liability, rather than continuing to serve all students as best as possible.

**Comment by coreycaitlin** [comment]
The current answer reads:

> If a school keeps teaching during a physical closure (by moving classes online, for example), the school must ensure students with disabilities have equal access to the same opportunities. More information is available via the Department of Education.

Sounds like we should change it to:

> The California Department of Education has released [guidance on distance learning](https://www.cde.ca.gov/ls/he/hn/distancelearning.asp) to support schools in serving all students through this outbreak. This guidance includes recommendations to ensure equity and access for all students.

@abquirarte, does that sound good?

**Comment by abquirarte** [comment]
👍

**Comment by abquirarte** [comment]
So was the other feedback in fact innacurate?

**Comment by coreycaitlin** [comment]
no, but it didn't need an issue!

this change is done, should be live soon
