### ISSUE TITLE
Azure FAAS for e2e testing

### ISSUE THREAD

**Issue by ChadABratton** [cagov/covid19#400]
- [x] Create new FAAS for e2e testing. 
- [x] Verify 3 existing tests than run locally also work in the FAAS

**Comment by ChadABratton** [comment]
Created hello world service in Azure Cloud. Now we need to link code from here: 
https://github.com/cagov/End-to-End-Testing-Svc

**Comment by aaronhans** [comment]
Sample test running inside function and notifying slack of results: https://github.com/cagov/End-to-End-Testing-Svc/commit/2e1dcf3b1937afdaefbcb154bc54a8ee3f89ba62

**Comment by ChadABratton** [comment]
I plan to work on this story more today.

**Comment by abquirarte** [comment]
Thanks @ChadABratton !

**Comment by abquirarte** [comment]
@ChadABratton update?

**Comment by ChadABratton** [comment]
1. @aaronhans  and I successfully linked the code in https://github.com/cagov/End-to-End-Testing-Svc to our new Azure FAAS 
2. We now are in the process of converting tests and writing new tests with Playwright. https://github.com/microsoft/playwright
3. Once I am able to write a few more tests, we can close this. This ticket has shifted priorities a few times but I hope to have at least a few more tests ready for review by Friday

**Comment by abquirarte** [comment]
Lovely, thank you!

From my phone

________________________________

**Comment by aaronhans** [comment]
We took this initial set of action items to their conclusion and verified that playwright will not run in Azure FAAS. It can run on AWS FAAS.

I have a new idea:
- We can use github actions triggered by webhooks which run the playwright tests pointed at the step in the pipeline awaiting verification. This lets us avoid introducing a new platform and still runs the tests against the target build in an environment that mirrors production.

**Comment by aaronhans** [comment]
I got the playwright tests running in a github action both with a cronjob syntax and via webhook trigger. The POST payload to trigger via webhook is in the readme: https://github.com/cagov/End-to-End-Testing-Svc

I think we have accomplished the goal of this task.

We can look into integrating this into the new production pipeline if we can do the POST in the readme and get a callback at a different url with the results

**Comment by aaronhans** [comment]
I think we should close this task @ChadABratton

**Comment by aaronhans** [comment]
Moving this task to done, additional E2E suite work should be addressed in https://github.com/cagov/covid19/issues/960
