### ISSUE TITLE
Link child care content on another page

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#407]
Child care content/page needs a place to live.

Per user feedback:
>It is unclear whether individuals who do not work in essential industries can have babysitters come to their homes.  One answer states that babysitters can still go to individuals' homes with no further caveats. Another states that child care is available only to individuals working in essential industries."

>I also saw multiple comments about this via a MomsinTechnology and a parents group in SF  that I am part of.
People are confused about if they can have nannies or babysitters come, whether they are essential or not, and which order they follow, the county SIP or the State new guidance (which as mentioned is not clear) -- someone even linked to covid-19.ca.gov site where they were not able to clearly answer this question.

We should consider updating our content to clarify. [Peggy's edits](https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit#)
Let's route by GO legal and policy.

**Comment by thepegisin** [comment]
Kayla and I made this clear in the language of **Stay home** and **Child care** on Staging. If these could get approved and published, we could close this issue.

Stay home: https://docs.google.com/document/d/1ufrKsLu5-mk3GYibszFQvXnO4NMFLlTtLrF0NtBP_I8/edit#

Child care: https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit

**Comment by abquirarte** [comment]
- [x] AQ sent child care edits to GO policy and SME for review 5/5/2020

**Comment by abquirarte** [comment]
@KaylaPrusia and @thepegisin FYI:

There was an executive order that expanded child care. We should find it. More policies will be updated by the end of the week. We'll hear more from Director of DSS. 

Below from her:

>Child care can currently be utilized for more than just essential workers.  

>For example, the new child care subsidies the state issued can support vulnerable families such as those at risk of abuse and neglect, those experiencing homelessness, those with a child with a disability or special health care need, and more.

>The policies are being updated in the next day or so.  Will circle back by the week’s end.

**Comment by KaylaPrusia** [comment]
Original [EO on child care](https://www.gov.ca.gov/wp-content/uploads/2020/04/4.4.20-EO-N-45-20-text.pdf)
DSS [guidance released April 7](https://www.cdss.ca.gov/Portals/9/CCLD/PINs/2020/CCP/PIN_20-06-CCP.pdf)
CDE guidance on child care for [essential workers and at-risk populations](https://www.cde.ca.gov/sp/cd/ci/mb2006.asp)

Will make suggested edits in child care staging document.

**Comment by KaylaPrusia** [comment]
Additionally, applications to apply for child care at this time:

**Comment by KaylaPrusia** [comment]
Additionally, applications for emergency child care for essential workers and at-risk children:
[COVID-19 Self-Certification Form](https://www.cde.ca.gov/sp/cd/re/documents/covidselfcert.pdf)
[COVID-19 2020 Confidential Application for Emergency Childcare Services](https://www.cde.ca.gov/sp/cd/re/documents/covidecsapplication.pdf)
[COVID-19 Temporary Waiver Request](https://www.cde.ca.gov/sp/cd/re/documents/covidtempwaiver.pdf)

**Comment by abquirarte** [comment]
Closing this. I think we covered part of it with today's updates. We should have @KaylaPrusia 's update above saved in the staging doc somewhere, they're good resources.
