### ISSUE TITLE
Remove timestamp from search page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#409]
The time stamp on search confuses users. It makes it seem like the website has not been updated when they search. 

Can we remove it? 

![Screenshot_20200501-124830_Chrome](https://user-images.githubusercontent.com/9556188/80836688-22a28980-8baa-11ea-90df-f4e7c8cde58e.jpg)

**Comment by aaronhans** [comment]
https://github.com/cagov/covid19/pull/412
