### ISSUE TITLE
Education page: Check FAQ on standardized testing to ensure it's consistent with latest EOs

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#41]

**Comment by coreycaitlin** [comment]
It's not. The current content is:

> Will there be standardized testing? When?
> 
> There are protocols if schools close before or during CAASPP and ELPAC testing. The California Department of Education will work with schools and the US Department of Education to facilitate test administration for schools affected.

Per [today's executive order](https://www.gov.ca.gov/2020/03/18/governor-newsom-issues-executive-order-to-suspend-standardized-testing-for-students-in-response-to-covid-19-outbreak/):

> To reduce the strain on students, families and educators during the COVID-19 outbreak, Governor Gavin Newsom issued an executive order today to waive, pending federal approval, this year’s statewide testing for California’s more than 6 million students in K-12 schools.
> 
> “This time is stressful enough for students, families and educators without the additional burden of annual testing,” said Governor Newsom. “This is an unprecedented time, and our main focus is on supporting the mental and socioemotional health of students, while continuing to provide educational opportunities such as distance learning.”

**Recommended replacement content:**

> Will there be standardized testing? When?
> 
> Probably not: on March 18, 2020, Governor Newsom issued an executive order to waive this year’s statewide testing for California’s more than 6 million students in K-12 schools, pending federal approval.

(I don't love the use of "pending" but I want to get this corrected ASAP, so I think it's worth taking this live and doing a better plain-language pass later if possible.)

**Comment by coreycaitlin** [comment]
Ready for you @abquirarte

**Comment by abquirarte** [comment]
👍 let's push it to live

**Comment by abquirarte** [comment]
And link the EO

**Comment by coreycaitlin** [comment]
whoops, good call — will link the EO news item (the EO itself is an inaccessible pdf 🤷‍♀)

**Comment by coreycaitlin** [comment]
updated on the site.
