### ISSUE TITLE
Update Testing & Treatment page to two new drive through testing sites & OptumServe test sites

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#415]
Update is limited to addition of two new drive through testing sites Verily’s Project Baseline activated over the weekend.

**Comment by abquirarte** [comment]
- [ ] Add content and new map (make it an action link): 

https://arcgis.com/apps/Nearby/index.html?appid=43118dc0d5d348d8ab20a81967a15401

**Comment by TamaraIDEJA** [comment]
[Testing and Treatment page 5520 - gfc AB.docx](https://github.com/cagov/covid19/files/4588689/Testing.and.Treatment.page.5520.-.gfc.AB.docx

**Comment by abquirarte** [comment]
now live
