### ISSUE TITLE
Make Select language button on homepage match other buttons

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#416]
The **Select language** button is slightly misaligned with the **Search** button. Also, it's the same color as the background, where the **Search** button is slightly darker. These should be aligned and match in color.

![TranslationsbuttonPC](https://user-images.githubusercontent.com/63249920/80991725-4e618180-8ded-11ea-9d02-855afae83bd1.png)

Noted on PC: Laptop running Google Chrome Version 81.0.4044.129 (Official Build) (64-bit).
Noted on mobile: iPhone Xs Max iOS 13.3.1 running Chrome v 81.0.4044.124

Assigned to: @aaronhans, @artuoma

**Comment by artuoma** [comment]
I will fix this thanks!

**Comment by artuoma** [comment]
This has been fixed.

**Comment by artuoma** [comment]
@abquirarte

**Comment by abquirarte** [comment]
yAY!
