### ISSUE TITLE
SEO - Fix case of search items

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#417]
SEO is reporting that some pages are being served with mixed case, causing canonical conflicts.

Example...
https://covid19.ca.gov/img/essentialcriticalinfrastructureworkers.pdf
should be...
https://covid19.ca.gov/img/EssentialCriticalInfrastructureWorkers.pdf

possible solutions are to serve a canonical response with the file, or redirect to the correct case.

**Comment by carterm** [comment]
Google Search console index complaint here...
https://search.google.com/search-console/inspect?resource_id=https%3A%2F%2Fcovid19.ca.gov%2F&id=is0grXuGXXxmfXFoZJFDyg&hl=en

**Comment by aaronhans** [comment]
We have implemented redirects to the final file destination which is case sensitive. We corrected the case of all the uppercase urls we found before we implemented the redirect. This task is complete. If we missed anything it will show up as a broken link in siteimprove's broken link reports
