### ISSUE TITLE
Add to Meals for seniors page (now)

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#419]
Deputy Director Buras has asked us to expedite this task. It would be great to get this done as soon as possible in case the governor mentions during his press conference today. Please note that these POCs range from hotlines, to individuals.

 

City of Los Angeles (Dept of aging Hotline: 213-263-5226) (hrs of operation 0900-1700 PDT)
County of San Mateo (Hotline: 1-800-675-8437)
Orange County (Info/Referral Contact Center: 714-480-6450)
City of Sacramento (Hotline: 916-330-1444)
City of Elk Grove (Housing Dept: 916-478-2254)
San Bernardino County (Hotline: 888-743-1485)
City of Moreno Valley (Hotline: 951-413-3280)
City of San Jose (Dolan Beckel: 408-745-9696)
Contra Costa County (Tracy Murray: 925-608-4805)
City of Seaside (Senior Svcs Office: 831-899-6809) – Backup Dan Meewis – 831-899-6821

**Comment by thepegisin** [comment]
- [x] Added to Staging and published on WP

**Comment by abquirarte** [comment]
Update: 

- [ ] Please remove Tracy Murray’s contact information from the website for Contra Costa County. Instead, use: Helpline (800) 510-2020

- [ ] Please update San Jose information again, Sourcewise. 408-350-3200 – Option 1

**Comment by LizNobriga** [comment]
Info updated in wp
