### ISSUE TITLE
Health care page: Clarify that testing/screening are free no matter who regulates them

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#42]
DMHC noted that our Health care page, in the Q&A section, accidentally implies that only plans regulated by CDI have the zero-cost-sharing mandate.

**Comment by coreycaitlin** [comment]
We should clarify that testing/screening are free no matter who regulates them, but I don't think most folks know or care which state agency regulates their health care plan.

Here's the content I propose (including the question for context):

> **I want to get screened or tested for COVID-19. I have insurance, but what will this cost me out-of-pocket?**
> It should be free. The state agencies that regulate health care in California have mandated that all full-service  insurance plans (including Medi-Cal) waive copayments, coinsurance, and deductibles for medically necessary screening and testing for COVID-19. This includes emergency room, urgent care, or provider office visits when the purpose of the visit is to be screened and tested for COVID-19.

**Comment by coreycaitlin** [comment]
Ready for review @abquirarte 🎉

**Comment by abquirarte** [comment]
👍 I agree, i don't think people care who regulates them. (except when they want to complain?) This other question may be addressed elsewhere.

**Comment by coreycaitlin** [comment]
Great, moved it to wordpress
