### ISSUE TITLE
Telehealth page updates 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#422]
2nd follow-up to this issue: https://github.com/cagov/covid19/issues/79 

[Content staged here](https://docs.google.com/document/d/1Zy99QTvfSRtjBTkMb75utlA0VejoyYm2XmErFZH5X-o/edit#)

**From SME receive 5/4/20**
[Updated Content for Telehealth webpage_5.4.20.docx](https://github.com/cagov/covid19/files/4578394/Updated.Content.for.Telehealth.webpage_5.4.20.docx)

- Someone was able to find the telehealth page. 
- They noted the search does not work
- We are awaiting content updates 
- And new data to reflect medicare 

This is scheduled to go live Wednesday 5/6

- [x] Can we "disable" the page (make it private for now, or add tag for do-not-crawl if missing).
- [x] Can we check the functionality? I also tested and it didn't work.

**Comment by LizNobriga** [comment]
Added PW ("telehealth")

**Comment by abquirarte** [comment]
New changes in staging. (per peggy and SME)
Aaron fixed functionally

**Comment by LizNobriga** [comment]
Moved updates into WP.

**Comment by TamaraIDEJA** [comment]
[Updated Content for Telehealth webpage_5.8.20.docx](https://github.com/cagov/covid19/files/4600636/Updated.Content.for.Telehealth.webpage_5.8.20.docx)

Telehealth SME was concerned that the flow of this page wasn’t intuitive to the a consumer, so she included the following changes to the landing page. @LizNobriga @thepegisin

**Comment by thepegisin** [comment]
Updated Staging doc with their edits:
https://docs.google.com/document/d/1Zy99QTvfSRtjBTkMb75utlA0VejoyYm2XmErFZH5X-o/edit#heading=h.ar9cv6yy5wzs

This is more convoluted, IMHO. The 3 major additions they made are graded by Hemingway as "very hard to read." But the overall readability score is grade 9 (from 8 at last edit).

**Comment by abquirarte** [comment]
Track changes download from 05-11-2020 for our reference below.

Peggy will resolve and update the content on WP page so that we can go live and announce in banner today. 
[Telehealth- content draft_CLEAN.docx](https://github.com/cagov/covid19/files/4611302/Telehealth-.content.draft_CLEAN.docx)

**Comment by TamaraIDEJA** [comment]
SMEs reviewed and provided the following updates to the page: 
https://docs.google.com/document/d/1Zy99QTvfSRtjBTkMb75utlA0VejoyYm2XmErFZH5X-o/edit?pli=1#

@thepegisin @LizNobriga

**Comment by abquirarte** [comment]
Did we make these edits? ☝️

**Comment by TamaraIDEJA** [comment]
Additional updates on this page from SMEs:

For testing we’d like to link to the map feature:
https://www.arcgis.com/apps/Nearby/index.html?appid=43118dc0d5d348d8ab20a81967a1540
For treatment it can link to the current link:
https://covid19.ca.gov/testing-and-treatment/#top

@LizNobriga @thepegisin

**Comment by aaronhans** [comment]
Vishaal sent me an additional text update via email: Display the phrase "See insurance card" when there is not nurse advice phone number in the dataset and this was deployed to production

**Comment by abquirarte** [comment]
@LizNobriga @thepegisin ☝️

**Comment by LizNobriga** [comment]
Published SME's edits from 5/11 afternoon.

**Comment by abquirarte** [comment]
### Action
heard from SME. At this moment we do not link to telehealth page from our site. 

- [ ] Check where does it make sense to link to it across existing pages?

- [ ] Perhaps replace in the"what you can do" section `manage your stress` with `find telehealth`

### Timeline End of day Friday/Early next week

@LizNobriga @JasonKarim @thepegisin

**Comment by JasonKarim** [comment]
Content drafted and reviewed by Peggy. Waiting on final approval before posting.

**Comment by abquirarte** [comment]
@JasonKarim I viewed and made comments on the docs. These edits should be good to go live. 

Did we determine if we are adding telehealth to the "what you can do section? @thepegisin (see comment: https://github.com/cagov/covid19/issues/422#issuecomment-628975773)

**Comment by thepegisin** [comment]
That list is pretty long. It seems like it's covered under Get testing and treatment. Also "telehealth" without explanation may be unhelpful. I don't recommend putting it on that menu.

**Comment by LizNobriga** [comment]
@abquirarte  Telehealth-related edits to [stay home Q&As for health care](https://covid19.ca.gov/stay-home-except-for-essential-needs/#health) completed in WP. Thank you @JasonKarim for making this easy for me! :iphone::woman_health_worker::pill:
