### ISSUE TITLE
Health care page: Improve concerns/complaints answer

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#43]
Per feedback from state agencies, we shouldn't send people to CDI because for many of them it's not the right contact.

Suggested replacement content was:

> If you are having trouble accessing care, or inappropriately charged cost-sharing for medically necessary screening and testing for COVID-19, or experiencing other issues with your health plan, you should first follow up directly with your health plan by calling the member phone number listed on your health plan card. If your health plan does not resolve the issue, then you should contact the DMHC Help Center for assistance at 1-888-466-2219 or www.HealthHelp.ca.gov. If your health plan is not regulated by the DMHC, the Department will connect you with the appropriate entity to assist you.

Needs an edit before updating.

**Comment by coreycaitlin** [comment]
Suggested edit:

> If you are having trouble accessing care, or were inappropriately charged cost-sharing for medically necessary screening and testing for COVID-19, follow up directly with your health plan by calling the member phone number listed on your health plan card. If your health plan doesn't resolve the issue, contact the [California Department of Managed Health Care](www.HealthHelp.ca.gov) (DMCH) Help Center for assistance at 1-888-466-2219.

**Comment by coreycaitlin** [comment]
ready for review @abquirarte 🎉

**Comment by abquirarte** [comment]
👀 ✅ approved 👍

**Comment by coreycaitlin** [comment]
changed, should be live soon

**Comment by TamaraIDEJA** [comment]
how cool, glad we are trying this 😄 -aq
