### ISSUE TITLE
Taxes page updates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#432]
[Content staged here](https://docs.google.com/document/d/1uon27XQKSJNADP8t5NIUyBffw5K1PbkNnJ-xrVCVlQ0/edit#heading=h.f93ut18z0gb8)

**Real Property Taxes**
Penalties for property taxes paid after April 10 are waived through May 6, 2021, for taxpayers experiencing financial hardship due to the COVID-19 pandemic. This applies to residential properties and small businesses that meet certain criteria. Contact your county for details.

**Business Personal Property Tax Statements**
Businesses have until May 31, 2020 to file Business Personal Property Tax Statements to avoid penalties.

**Comment by abquirarte** [comment]
Update: @thepegisin 

Add H2 header:  Property taxes 

Followed by what is live. lol. 

![image](https://user-images.githubusercontent.com/9556188/81234527-c9719600-8fad-11ea-95ab-a8c3c8f78cd0.png)

**Comment by LizNobriga** [comment]
Header fixed.
