### ISSUE TITLE
Businesses and employers updates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#438]
[Content staging here](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#)

Creating this for a record of changes related to small agricultural businesses being able to apply for EIDL.

[Content received from SME on 5/5](https://docs.google.com/document/d/1SqSwSEf2qBBSo13KUa8vNxNegwJWtqZ925hmiK7-2m8/edit).

**Comment by abquirarte** [comment]
- [ ] Content approved by SME 5/6
- [ ] Published 5/7 AM
