### ISSUE TITLE
PPE page and guidance 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#442]
### Background 

Director Ghilarducci has asked that we develop and publish public facing products to help folks understand what the PPE needs are by sector and solutions for how they can address those. They shared with us process maps and matrixes that address these various needs, and asking our help to make them easily navigable by the general public.

We met with them and baselined - we said that MVP would be the right content addressing top questions from public and businesses. 

###  Content/Reference docs

Please review and see how we might simplify. What questions do we have for the SMEs - we will be circling back in the afternoon with them. 

All files received are saved in our [content folder. ](https://drive.google.com/open?id=1rrCnslcbWfmAnp3BBzxTojRxpNR9Xkc0)

### Content Captain
@thepegisin @KaylaPrusia @hilaryhb 

### Timeline 
MVP- Tuesday 5/12

**Comment by thepegisin** [comment]
Here's the first draft of the Masks page: 
https://docs.google.com/document/d/1bWqX_UscgiDbYyFsqavgB1FhX6KWGPEuXiK-BLG1RoU/edit

**Comment by abquirarte** [comment]
[Content for PPE page](https://drive.google.com/file/d/1CaMvZ767A3-2diur078v3puPc-rHk_YL/view?usp=sharing)

Should have this attached. 
![PPE-Process-03](https://user-images.githubusercontent.com/9556188/81597744-0c02ec00-937b-11ea-9f0e-3f407d7dca69.png)

**Comment by abquirarte** [comment]
This page is now live. We will iterate on this. 

Currently at Grade 14. 

https://covid19.ca.gov/masks-and-ppe/

**Comment by TamaraIDEJA** [comment]
If suppliers are unable to provide for your needs, and the PPE is urgently required, submit a request for assistance to your _local Medical Health Operational Area Coordinator_ **or county emergency management agency or county public health department**. If local emergency management is unable to address the PPE shortfall, they can relay it to the State Operations Center. If the state is unable to address it, they can submit a request for support to their FEMA Regional Response Coordination Center.

@thepegisin please delete the link (in italics) _local Medical Health Operational Area Coordinator_
and add instead (what is in bold) : **or county emergency management agency or county public health department**
