### ISSUE TITLE
public recreation- new page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#448]
### context
We will be publishing content on public recreation places. 
I don't think we need a new page, we can actually just replace what is currently listed in "Public Places."

### deadline: Publish Friday 5/8

- [x] Draft [content here](https://docs.google.com/document/d/12D0gLG9I51USwaderhBsg_DkMzsilRbN6YoBi2Kbu-k/edit)

- [x] Content draft in WP for preview purposes only (we will get rid of this draft page once finalized)
has PW. 

- [x] Copy draft  content into current "Public Places" page before noon

- [x] Delete draft other WP page 

- [ ] Index for translation, non-priority- next week is ok

**Comment by thepegisin** [comment]
**Public places** has been renamed **Public recreation** and page copy replaced.

- [ ] Need the icon on the homepage to change from a building to a tree or something outdoors-y. Paging @artuoma.
