### ISSUE TITLE
make all translated stats fragments data driven

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#461]
Once #460 is done we can use that technique in all translated fragments so editors no longer have to updates stats in multiple places.

We already have the OK(per @angie) to modify the design to simplify it a little so we don't have to handle descriptive language related to the data like increase. Translated versions of this fragment are already way behind the english design anyway

**Comment by carterm** [comment]
Adding support -> https://github.com/cagov/covid19/pull/454

**Comment by carterm** [comment]
Almost done.  Need a solution for Arabic month names.  Changing it to Gregorian date format YYYY/MM/DD should be ok.
