### ISSUE TITLE
New Page: Contact Tracing 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#463]
This is an emerging effort that will be announced on Wednesday (w Orange County being the first county to pilot our joint initiative) The objective for Wednesday is to introduce this effort, broad strokes, high level - and well be adding more details as they come as well as prioritize key questions from the public. So the MVP page is high level intro of the effort. 

### Content
The [content that we have already received ](https://docs.google.com/document/d/1BBfDuXwYOmzvXR7k37mwAg76yX-a-luCtqZyGcmIJSs/edit)- we are in touch with SMEs and will add any new content as it comes. 

[Staging doc](https://docs.google.com/document/d/1nQACCs3eoiMX8AZlyMGfBu1Q8h5vYM1tYXQ0_901j_g/edit)

### Content Captain 

@thepegisin will take a lead on the content. @JasonKarim please help Peggy anticipate key questions and issues that we might need to address and support her in content design. 

### Timeline
 
First draft by COB today.

**Comment by thepegisin** [comment]
- [x] Content drafted
- [x] Edits by Angie, Lande, Karim

**Comment by abquirarte** [comment]
Received updated content today. Peggy adding to staging doc. 

## Deadline: 

- Publish by end of day Monday
- Need translations by end of day Tuesday or Wed.

**Comment by thepegisin** [comment]
- [x] Staging doc updated: https://docs.google.com/document/d/1nQACCs3eoiMX8AZlyMGfBu1Q8h5vYM1tYXQ0_901j_g/edit

- [x] Clean copy created for easy reading: https://docs.google.com/document/d/1OFm3tEdY7s53ltaFHSzCYN8AsZc_dVVmBzkxIwriXmI/edit

**Comment by abquirarte** [comment]
"Final" attached. 
[GO  Contact Tracing FAQ_FINAL 5.16.20.docx](https://github.com/cagov/covid19/files/4639481/GO.Contact.Tracing.FAQ_FINAL.5.16.20.docx)

I will upload to folder and update in WP page.... Some content will need to be modified.

**Comment by abquirarte** [comment]
- [ ] Published in WP based on content we received this weekend. Uploaded in[ content folder here. ](https://docs.google.com/document/d/1cNlPddOrbVJgW6VEjwIuznFbPhlkxuq4/edit)

URL: covid19.ca.gov/contact-tracing

### Next:

- [ ] Trigger translation process
- [ ] Re-route californiaconnected.ca.gov, coordinate with CDT @ChadABratton

**Comment by abquirarte** [comment]
- [ ] Add accordions to questions in WP

- [ ] Embed image: 
![ContactTracing-Infographic-v5](https://user-images.githubusercontent.com/9556188/82368802-da1d0580-99ca-11ea-92a3-72c9213cbae2.png)

**Comment by abquirarte** [comment]
- [ ] For the first bullet point under “If you test positive for COVID-19”, we need to edit to say: “If necessary, you will be connected to medical care and other supportive resources, regardless of your income, health insurance, or immigration status.”

New graphic: 
![CaliforniaConnected_Infographic_English_05192020](https://user-images.githubusercontent.com/9556188/82384012-c92cbe00-99e3-11ea-8953-27561c92358c.png)

**Comment by abquirarte** [comment]
I _think_ this is the last update. We want to make sure we are providing content that is accessible. 

So I've asked GO to send us at least pdf versions of the image above. 

@thepegisin can you take a stab at replacing the image with the pdf. Then make the image a link to the PDF?

- [ ] Upload logo. Add to top of page. 

- [ ] Upload pdf to wordpress library. Alt text should be: California _Connected: How does contact tracing work? [Infographic]_

- [ ] Replace image with pdf. Link

[CaliforniaConnected_Infographic_English_05192020 (1).pdf](https://github.com/cagov/covid19/files/4653880/CaliforniaConnected_Infographic_English_05192020.1.pdf)

![CAConnected_Logo-01](https://user-images.githubusercontent.com/9556188/82390097-a0f88b80-99f2-11ea-9c36-b46e24ae3012.jpg)

**Comment by abquirarte** [comment]
One content edit from CDPH:
_You will have access to COVID-19 related treatment, regardless of your income, health insurance, or immigration status._

**Comment by abquirarte** [comment]
Deadline: Before 9am 5-20. 

Update content with these edits. (Not significant) 
Edits in content folder.  
https://docs.google.com/document/d/1rbzeY6w6rympJkQDVcdKkc3GpnjcxlMHZMTKYVzpkpM/edit?usp=drivesdk

Update in staging doc
Apply edits to live page in WP 
Ping AQ when live 

Ty!!

**Comment by abquirarte** [comment]
Add translated logos to respective pages. 

[Translated Tagline.zip](https://github.com/cagov/covid19/files/4664177/Translated.Tagline.zip)

**Comment by thepegisin** [comment]
- [ ] Latest edits from GO added to Staging/WP page
