### ISSUE TITLE
New: Guidance as it's own sub-page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#464]
### context 
The roadmap page is losing a lot of context because the page is so long. We've been asked to put the guidance accordions into it's own page. We will be adding 4 new guidance docs **for tomorrow, Tuesday 5/12** 

- [x] Create subpage that hosts only the accordions with the guidance pdfs. (save as draft, do not crawl, with PW)
- [x] Update content in draft to remove references to the guidelines. 
- [x] Add accordions
- [x] Update accordion text (awaiting, from GO SME) 
- [x] Upload guidance docs to Drive, then publish in Github

**Comment by LizNobriga** [comment]
@abquirarte Drafting changes to resilience roadmap page [here](https://docs.google.com/document/d/1w-DbOvyvcYqNmoNOJQFtKOc_lZJ327xR/edit#) to coordinate with new guidance subpage ([see draft](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit)).

**Comment by LizNobriga** [comment]
This page is currently tagged as "do not crawl" and the PW is "industry."

**Comment by abquirarte** [comment]
Complete
