### ISSUE TITLE
Improve JIC and Publishing Coordination

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#47]
Angie, JP and Tamara to work with Mike and ensure we create a process for content curation through being extended members of the JIC as the digital team. 

- [x] Follow up with Mike

- [x] @abquirarte to give Julie Lee a head up

> As part of the roll out of COVID19.ca.gov, we want to make sure departments (love the @CAGovernor tweet!) are aware of the new website and ask them to promote it.

> I am wondering how best to accomplish this and want to make sure we're aligned with JIC protocol. 

> There are two asks:
> 1) Direct to COVID19.CA.gov from department/agency website (replacing current link to CDPH page)
> 2) Promote COVID19.CA.gov on department social media

**Comment by abquirarte** [comment]
### Actions
- [ ] Identify key JIC contacts 
- [ ] Set up a schedule with shifts (Content captains, 1 back-up) to monitor the inbox request
- [ ] Give inbox request access to content captains, request that people submit edits there
- [ ] Train Lande on WP publishing  
- [ ] Share our process with key JIC contacts
- [ ] create better info flow with GO and JIC contacts
- [ ] Participate in daily JIC calls

### Questions
- Can our team be part of the process earlier? 
- Will CZI always manage the campaign page?
- Who are the "final' JIC approvers?
- Can we have the key contacts at JIC to help filter them questions, trends and insights (Homelessness Guidance example) 

### Features 
- Map?
- Search?
- New info architecture?
- New services highlighted? 
- Push for county alerts
- Glossary

**Comment by abquirarte** [comment]
I will follow-up via email.
