### ISSUE TITLE
Update to Stay home FAQ/QA page

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#470]
[DMV extended driver license learning permits and commercial learner permits](https://www.dmv.ca.gov/portal/dmv/detail/pubs/newsrel/2020/2020_21)

Driver license permits expiring between March and June 30, 2020 are extended six months or to a date 24 months from the date of application, whichever is earlier. Commercial learner’s permits expiring between March and June 2020 are now valid through June 30, 2020, consistent with federal guidance. The extensions require no individual action on the part of drivers.

**Comment by KaylaPrusia** [comment]
Updated [staging document for stay home FAQ](https://docs.google.com/document/d/14IL8TJMfBCZXcZ8lMph7aastRl3o7ym3/edit#) with updated information

**Comment by KaylaPrusia** [comment]
Brought up by GO up last week (5/15):
GO legal thinks this may be a better way to structure the policies in the SH FAQ page.

1. i thought we only had 2? Do we have links to all 4?
2. does this make sense ? Perhaps better way to explain?

“Stay at Home” Orders
The Governor has issued executive orders requiring Californians to obey public health directives. These include the following:

- Executive Order N-33-20 (requires Californians to heed state public health directives)
- March 19, 2020 Public Health Order (initial “stay-at-home” order, since modified)
- Executive Order N-60-20 (reiterates requirement to heed state public health orders; sets out framework for Stages 2 and 3)
- May 7, 2020 Public Health Order (begins to implement Stage 2)

**Comment by abquirarte** [comment]
Closing as this is now live. Thank you @KaylaPrusia
