### ISSUE TITLE
Homeless Californians

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#49]
Need to dig out the salient points from [this news](https://www.gov.ca.gov/2020/03/18/governor-newsom-takes-emergency-actions-authorizes-150-million-in-funding-to-protect-homeless-californians-from-covid-19/) and find a home for them on the site.

**Comment by abquirarte** [comment]
Ashley has some initial research. I sent her more yesterday. @TamaraIDEJA can you share?

**Comment by abquirarte** [comment]
Fact sheet
[Project Roomkey Fact Sheet.pdf](https://github.com/cagov/covid19/files/4406665/Project.Roomkey.Fact.Sheet.pdf)

**Comment by abquirarte** [comment]
![image](https://user-images.githubusercontent.com/9556188/77984952-ebe60480-72c7-11ea-94b9-99ee43df6d40.png)

**Comment by abquirarte** [comment]
Latest draft in Google Doc:
https://docs.google.com/document/d/1lQ8hiUpSGQeW-JL5mmKcBrfKyTYSTOtMGoTYU3mDez0/edit#

**Comment by abquirarte** [comment]
- [x] Publish page : https://as-go-covid19-d-001.azurewebsites.net/2020/04/02/housing-and-homelessness/
- [ ] Add to staging 
- [ ] Add as category "Housing and Homeless"

**Comment by abquirarte** [comment]
closing as addressing in #162
