### ISSUE TITLE
Archive Help for immigrants

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#4909]
Before archiving:

- [x] Remove from navigation
- [x] Check for links to the page
- [x] Create redirects
- [x] Remove from per page feedback filters
- [x] Alert developers by creating a Jira ticket

[Full process available in internal docs](https://teamdocs.covid19.ca.gov/teams/content/editing.html#archiving-content)

This archiving is driven by reducing content around the green tier. This removal has been approved by the Governor’s Office.

Original Jira ticket: https://digital-ca-gov.atlassian.net/browse/CCG-2244

**Comment by m-sullivan7** [comment]
Relevant Google Docs:

- [Highlights of current page to ensure nothing gets missed](https://docs.google.com/document/d/15hfEH0F3rRGfwoHeHoff_YtMNMGQLf97mpywygbdziY/edit?usp=sharing)
- [Suggestions for CDT team maintaining immigrant guide solution](https://docs.google.com/document/d/1LI-Z9LfCGX46UVNv9OtJMmjpPnzMIqRZDRbDWpuDpHQ/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
Checked in with Gina at the governor's office about public charge rule information to move to the Immigrant Guide page.

**Comment by m-sullivan7** [comment]
@mediajunkie [one more review](https://docs.google.com/document/d/1LI-Z9LfCGX46UVNv9OtJMmjpPnzMIqRZDRbDWpuDpHQ/edit?usp=sharing) (specifically of the public charge section) in light of Gina's response.

**Comment by mediajunkie** [comment]
looking now...

**Comment by mediajunkie** [comment]
Looks good to me. Ready to share with Art!

**Comment by mediajunkie** [comment]
(reassigned to ticket to you) -- please move it to the External review column when appropriate.

**Comment by m-sullivan7** [comment]
Draft page created by CDT and sent to Gina in the Office of the Governor for approval before publishing.

**Comment by m-sullivan7** [comment]
Alerted Britt to remove the page from the per page feedback filters and Jim to remove from his bot before I do the actual archiving.

**Comment by jbum** [comment]
No need to remove pages from bots anymore (it uses the sitemap now).

**Comment by m-sullivan7** [comment]
Thanks for the confirmation @jbum ! The page has been archived in WordPress, so translations can be removed.
