### ISSUE TITLE
State dashboard: navigation updates

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#4920]
Per page feedback from July 13 to July 21 showed that significant numbers of visitors are not finding:

- County data
- Link to vaccination data
- Age breakdowns

This information is all on the site. This ticket is to improve the navigation of the page to make it easier for people to find this info.

**Comment by m-sullivan7** [comment]
Reassigning this to @mediajunkie for shepherding through any stakeholder approvals.

**Comment by mediajunkie** [comment]
is the relevant document linked to this issue? I can find it from email threads most likely but just checking?

**Comment by mediajunkie** [comment]
I think it's [this doc](https://docs.google.com/document/d/1daoUhuRyU0uq42SGuO0uYKPDT1TCcOxT0wQ6Lydzqeo/edit), please confirm?

**Comment by m-sullivan7** [comment]
I must have passed it along outside of github while navigating the switchover.

For the navigational changes, it's this Google Doc: [State dashboard 2021-7-23 organization changes](https://docs.google.com/document/d/1bL-orOeOTtaYVXNqoIt_L1A92dn6F467mi5EVWy8Kes/edit?usp=sharing). It's got a summary of changes at the top to help stakeholders/you in review (the other doesn't right now).

**Comment by mediajunkie** [comment]
thank you!

**Comment by mediajunkie** [comment]
These look ready for stakeholder review to me. Checking with @abquirarte for who needs to approve.

**Comment by mediajunkie** [comment]
@m-sullivan7 please go ahead and stage & I will submit for approval. (Angie took a look and told me to "share track-change version, staged version, a summary of what changed/ and why, then tell them when we plan to publish."

All I need to do that is the staged version, as you've provided the rest, thanks!

**Comment by mediajunkie** [comment]
(assigning to you, plz reassign to me when done)

**Comment by m-sullivan7** [comment]
New version published.
