### ISSUE TITLE
State dashboard: Vaccinated vs. unvaccinated data content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#4921]
Per @mediajunkie "no. 1 top priority from Dr. Pan's office right now is to report cases (and hospitalization and deaths) in terms of vaxed vs. unvaxed. ...but first cases"

This ticket is for creating content to support that, presumably on the state dashboard page.

[Draft Google Doc](https://docs.google.com/document/d/1daoUhuRyU0uq42SGuO0uYKPDT1TCcOxT0wQ6Lydzqeo/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
For initial launch, this ticket is just for launching cases data.

**Comment by mediajunkie** [comment]
Content should be locked now for launch.

**Comment by m-sullivan7** [comment]
I think so. Barring anything that comes up in QA with extra eyes, I consider it good to go.

**Comment by m-sullivan7** [comment]
Content published this morning with charts.
