### ISSUE TITLE
Equity page

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#4924]
The health equity page contains references to the Blueprint for a Safer Economy, which is no longer in effect.

![image](https://user-images.githubusercontent.com/69169190/126845426-c5deab67-4210-4ede-9091-7656033d84d4.png)

This ticket is to remove these references.

**Comment by m-sullivan7** [comment]
@mediajunkie Liz helpfully pointed out that the equity page got missed in our June 15 updates. OK to remove the language I've deleted in suggested mode in this [Google Doc](https://docs.google.com/document/d/1r7o9Huf8AiJfAjluhz6YR7EL22OjIxSJChHNGRxbp-0/edit?usp=sharing)?

**Comment by mediajunkie** [comment]
Yes, please do!

**Comment by m-sullivan7** [comment]
I removed the content from the website and confirmed it's off the public site. Closing this ticket.
