### ISSUE TITLE
Get financial help - Golden State Stimulus update

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4935]
Bringing over from Jira
Golden State Stimulus (GSS) program is expanding (e.g., [GSS II](https://www.ftb.ca.gov/about-ftb/newsroom/golden-state-stimulus/gss-ii.html)) and info has been updated on FTB

See [Google doc with draft edits](https://docs.google.com/document/d/1pnfEvDK2d-8JK6cBomnYH1NB0oOLe1vSTcuYT6E0ot8/edit#)

- Michael and Christian have reviewed
- Edits with @abquirarte for review

**Comment by abquirarte** [comment]
@LizNobriga good with these.

**Comment by LizNobriga** [comment]
These edits are published.
