### ISSUE TITLE
Education - updates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4936]
Edits will:
- Add link to [Resources for Colleges & Universities to Reduce COVID Risk](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Resources-for-Colleges-Universities-to-Reduce-COVID-Risk.aspx) (released 7/15/21)
- Improve readability of lead class text and content in Higher education section
- Add link to [K-12 Schools Guidance 2021-2022 Questions & Answers](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Schools-FAQ.aspx) (released 7/29/21)
- Add link to [What Parents Should Know About the Updated COVID-19 School Guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/UpdatedCovid19SchoolGuidance.aspx) (released 7/20/21)
- Add link to [Answers to Frequently Asked Questions about Reopening Schools](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/AnswersFAQsReopeningSchools.aspx) (released 7/15/21)
- Add link to [The Science Behind Safely Reopening Schools](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Science-Behind-Safely-Reopening-Schools-Article.aspx) (7/15/21)

**See [DRAFT EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)**

Stakeholders for approval/awareness:

- [x] David Sapp
- [x] Naomi Bardach
- [x] Kristal DeKleer
- [x] Carlos Sanchez
- [x] June Hunter

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you do an initial review? [Edits in google doc](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)

**Comment by m-sullivan7** [comment]
@LizNobriga I left some edits. I noticed that the reading level is up at 10 with my edits, but Hemingway is pretty clean with those edits. It would probably take some deep work to get the reading level down, but I thought I'd flag it. 🙂

**Comment by LizNobriga** [comment]
@mediajunkie Could you review the [proposed edits](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#) next?

**Comment by LizNobriga** [comment]
@m-sullivan7 I made changes to the K-12 section. Can you review that part again?

**Comment by mediajunkie** [comment]
edits look good to me

**Comment by m-sullivan7** [comment]
Yes, good here too! Just found a couple extraneous spaces.

**Comment by LizNobriga** [comment]
@abquirarte Could you review these edits next? Michael and Christian have both reviewed. 

[DRAFT EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)

**Comment by LizNobriga** [comment]
Angie has reviewed and given initial approval via slack. The next step is for stakeholders (CDPH and GO Legal) to review. Assigning to @mediajunkie.

**Comment by LizNobriga** [comment]
@mediajunkie Are these edits out for stakeholder review?

**Comment by mediajunkie** [comment]
I think not yet. Was catching up on other items last night. Will update asap.

Re "Improve readability of lead class text" what is "lead class text"?

**Comment by mediajunkie** [comment]
sent for review/approval, asked for any concerns before cob today

**Comment by LizNobriga** [comment]
Lead class text refers to the first sentence on each page that explains the topic.

**Comment by LizNobriga** [comment]
These edits are ready in staging. @mediajunkie Could you review?
[https://staging.covid19.ca.gov/education/](https://staging.covid19.ca.gov/education/)

Can share with stakeholders if that's helpful.

**Comment by LizNobriga** [comment]
Edits are published.
