### ISSUE TITLE
Safely reopening - update to Current safety measures

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4937]
- People aren't looking for _Safely reopening_ anymore because that has passed
- Refresh page so users can find the current safety measures in place

Proposed edits include:
- Renaming page to _Current safety measures_
- Changing order of sections to reflect what's most relevant now (move reopening and BTB stuff down the page)
- Improving readability throughout
- Changes to menu navigation

See [early draft](https://docs.google.com/document/d/1iEHsf9KTCTCFzXYFWlKu_4FdckCOqPqDGzMMYy3DDB4/edit)
See [draft with stakeholder comments](https://docs.google.com/document/d/1gh8w0gWcPZkdcGBum6bu97Iae9CHm8hi/edit#heading=h.gjdgxs)
See [later/current draft](https://docs.google.com/document/d/17wRxqnHkwLxpj9hVxvybwqJXR9fOY9-23X1Ocfg35w8/edit)

**Comment by LizNobriga** [comment]
FYI @thepegisin

**Comment by LizNobriga** [comment]
Hi @mediajunkie. Can you review the edits that @thepegisin and I have proposed to update _Safely reopening_? 

You can leave questions and suggestions directly in the google doc, or lmk if it would help to have a quick discussion about updating this page. 

Thank you!!

[DRAFT FOR REVIEW](https://docs.google.com/document/d/1iEHsf9KTCTCFzXYFWlKu_4FdckCOqPqDGzMMYy3DDB4/edit)

**Comment by abquirarte** [comment]
These are great! I added some comments. I think we'll need to route by GO to make sure we are consistent with their messaging. LMK when you think we are ready to route for approvals @mediajunkie @LizNobriga @thepegisin

**Comment by LizNobriga** [comment]
Responded to all comments. Any final thoughts? @mediajunkie @thepegisin @abquirarte

**Comment by mediajunkie** [comment]
i don't know if mentioning us all made us assignees but let's try to keep tickets assigned to only one person at a time, plz!

**Comment by LizNobriga** [comment]
Will do

**Comment by LizNobriga** [comment]
Update: this is with @thepegisin to update the Masks section

**Comment by LizNobriga** [comment]
@mediajunkie Can you update this ticket to document stakeholder approvals?

@thepegisin Can you indicate on this ticket that the approved edits were published today?

Then I think we can close this one out!!

**Comment by mediajunkie** [comment]
Stakeholders approved this and it went love today around noon.
