### ISSUE TITLE
Content Update: Emotional support resources page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#494]
### context
Attached are updated Victim Service provider directories for to update or add to the State COVID-19 website resources page (https://covid19.ca.gov/resources-for-emotional-support-and-well-being/).

Here are the requested changes or additions:

- Replace current "Domestic Violence and House First Programs" listing with the attached (and requested renamed) Domestic Violence Service Providers list
- https://tinyurl.com/ycz2sy3x
- Replace "Sexual Assault and Human Trafficking Provider List" with the attached Sexual Assault & Human Trafficking Service Providers list
- https://tinyurl.com/yctyfttd
- Replace "Child Abuse and Youth Victim Service Providers" list posted, with the attached Child Abuse and Homeless Youth Service Providers List
- https://tinyurl.com/yb3u47x9
- Add County Victim Service Providers list (attached) and a link to the California Victims Compensation Board (CalVCB) website (https://victims.ca.gov/) beneath the listing for the Victims of Crime Resource Center notation in the "If You Feel Unsafe" section

### timeline- by end of week

**Comment by KaylaPrusia** [comment]
- [ ] Replace current "Domestic Violence and House First Programs" listing with the attached (and requested renamed) Domestic Violence Service Providers list

- [ ] Replace "Sexual Assault and Human Trafficking Provider List" with the attached Sexual Assault & Human Trafficking Service Providers list

- [ ] Replace "Child Abuse and Youth Victim Service Providers" list posted, with the attached Child Abuse and Homeless Youth Service Providers List

- [ ] Add County Victim Service Providers list (attached) and a link to the California Victims Compensation Board (CalVCB) website (https://victims.ca.gov/) beneath the listing for the Victims of Crime Resource Center notation in the "If You Feel Unsafe" section

**Comment by KaylaPrusia** [comment]
@abquirarte missing County Victim Service Providers list from CalVCB - wasn't attached in email chain.

**Comment by abquirarte** [comment]
Let's add the reference to CalVCB and then we can inquire about the missing attachment. Thank you @KaylaPrusia !

**Comment by KaylaPrusia** [comment]
Updated staging [document](https://docs.google.com/document/d/1yJS7FmtZsQ2m3jUNvHpyHpojy1YcoP_jxOUo7V7tSd8/edit#) and it is live on the site. 

If we could get clarification on the CalVCB ask, that would be great. Both sentences seem to be offering the same programs/PDFs

**Comment by abquirarte** [comment]
thank you!

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by KaylaPrusia** [comment]
@abquirarte have they provided a County Victim Service Providers list to add to this page?

**Comment by abquirarte** [comment]
No! Thanks for flagging. Feels like a lifetime ago. What do you need me to help clarify? :)

**Comment by KaylaPrusia** [comment]
We mentioned and included a link to CalVCB, just wondering if they have a PDF for County Victim Service Providers list (as mentioned, wasn't provided) or if the link to CalVCB is sufficient.

**Comment by abquirarte** [comment]
Closing this for now.
