### ISSUE TITLE
Workers and businesses: vaccine verification and testing requirements for some workplaces 

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4946]
New state public health order requires workers in healthcare and congregate settings to verify vaccination status or get tested regularly. Same for state workers. 

- [State public health order](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Order-of-the-State-Public-Health-Officer-Unvaccinated-Workers-In-High-Risk-Settings.aspx) for healthcare facilities and congregate settings like senior care facilities, shelters, and jails
- [CalHR memo](https://www.calhr.ca.gov/Documents/Vaccine-Verification-and-Testing-Requirements.pdf) for state worker requirements

[DRAFT EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by LizNobriga** [comment]
@m-sullivan7 Can you review the [draft edits](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)?

**Comment by m-sullivan7** [comment]
Reviewed! Also, feel free to assign a git ticket to me when you'd like me to review it. 🙂

**Comment by LizNobriga** [comment]
@mediajunkie @abquirarte  Could you review the [draft edits](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)?

**Comment by LizNobriga** [comment]
These edits are live.
