### ISSUE TITLE
Food resources: CA P-EBT website

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4965]
These _Food resources_ edits will:
- Add the link to the new CA Dept of Social Services' Pandemic-EBT website ([https://capandemic-ebt.org/](https://capandemic-ebt.org))
  - Reduce duplicative content now easily found on new P-EBT site
- Rename the current H2 for "Families with school-aged children" to "Families with children" (because P-EBT now includes 0-6 year olds that are not school-aged)
- Move WIC program content from "Emergency food and food benefits" to go under "Families with children"
- Add three action link buttons
- Make improvements for readability (e.g., using bullets for the CalFresh food benefits content to bring down reading level by two grades)
- Move the 211 content to go under "Emergency food and food benefits" (anyone who needs to access food quickly can call 211 for help)
  - The "Older adults" content will still include a brief 211 reference

[DRAFT EDITS](https://docs.google.com/document/d/1zZ1VtWL8SbOEVfjB55f5F8L5jyZpmq3Jb-C8RV7DyZw/edit#)

**Comment by m-sullivan7** [comment]
Just a couple of minor plainer language edits. Looks good!

**Comment by LizNobriga** [comment]
@mediajunkie Could you review these edits?

**Comment by mediajunkie** [comment]
Edits look good to me!

**Comment by LizNobriga** [comment]
@abquirarte Can you review today?

**Comment by LizNobriga** [comment]
@mediajunkie Does this need any further approvals before publishing?
