### ISSUE TITLE
Add dataset level date stamps to the first two Health Equity charts

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4978]
Right now only the third and fourth charts on the [Health equity](https://covid19.ca.gov/equity/) have date stamps in their notes:
![image](https://user-images.githubusercontent.com/3227378/127549474-db826f8b-078a-4634-a2a5-7b2389812fda.png)
and
![image](https://user-images.githubusercontent.com/3227378/127549502-13eed5fd-ec96-46cb-9585-c8f695d9e3a1.png)

We need to add similar dynamic “updated on” dates to the notes for the first two:
![image](https://user-images.githubusercontent.com/3227378/127549583-6f4df53f-4f30-48c1-8395-27593f66d833.png)
and
![image](https://user-images.githubusercontent.com/3227378/127549603-6b77b583-b659-4539-9c00-8f9a769f1230.png)

**Comment by mediajunkie** [comment]
(testing to see if mentioning @jbum "adds" him to the ticket)

**Comment by mediajunkie** [comment]
ok it didn't but temporarily sharing the assignment with jim added him to the "involved" list: 
![image](https://user-images.githubusercontent.com/3227378/127939272-80bc849c-ac4b-45ab-8998-9a320feb607b.png)

**Comment by m-sullivan7** [comment]
As mentioned on https://github.com/cagov/covid19/issues/5016, the dates on the existing charts are built into the D3 chart code. While I can see it as a content editor, adding it to the charts where we don't have this data would be tricky. I recommend an engineer make this update as this is outside my skills as a content editor.

**Comment by mediajunkie** [comment]
prioritywise I would put this behind cases-by-vax-status & trackerbox

**Comment by mediajunkie** [comment]
@jbum can we revive this next week?

**Comment by mediajunkie** [comment]
or next week?

**Comment by jbum** [comment]
Currently live on production.
