### ISSUE TITLE
New "Variants" page - charts (data & eng)

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4981]
[(one pager)](https://docs.google.com/document/d/1YmgWRkw8fgThkYpT8Dp3UIw5OJSNf37sBmfQmXIgQ28/edit)

![image](https://user-images.githubusercontent.com/3227378/128264301-44cbd233-3adb-4ec4-8b6b-5c0ab2a2dc94.png)

Critical path right now is data hygiene.

**Comment by mediajunkie** [comment]
@m-sullivan7 there is a request for better explanatory text above the chart indicating that the data ends at such and such a date (currently Dec 7, tomorrow December 14, for example), and potentially incorporating framing talking points that Carlos is gathering for us.

**Comment by m-sullivan7** [comment]
Thanks! I've staged language to that effect. I've added in dynamic date fields per Jim, so once he builds those that should hook up automatically.
