### ISSUE TITLE
State dashboard anchor link visual improvements

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#4989]
As part of https://github.com/cagov/covid19/issues/4920, we propose adding a page index and anchor links to the state dashboard to help people find information on the site. Per page feedback indicates some users are not finding information on the page.

Our method of adding anchor links is to add separators between sections and assign the anchor link to the separator. This provides some breathing room between the top of the window and the H2 header for the section for a more visually pleasing experience.

The state dashboard page uses some custom color blocks to create visual interest on the page. Using these with the separators creates extra white space on the page that disrupts the visual flow of the page.

With separator:
![image](https://user-images.githubusercontent.com/69169190/127685810-dc8b051b-0e39-41ec-83a8-6a6daaa7eb94.png)

Without separator:
![image](https://user-images.githubusercontent.com/69169190/127685859-59907b16-6871-49e1-a3ee-738d31c03dea.png)
(Identical blocks are not compared due to a reorganization of sections also taking place in these changes.)

This ticket asks engineering if there is a way to make the page look better. The requirements from the content team side is the ability to insert anchor links that provide breathing space for the H2.

**Comment by jbum** [comment]
@m-sullivan7 , does this still need to be addressed?

**Comment by m-sullivan7** [comment]
@timothyshambra helped with this. This is done!
