### ISSUE TITLE
Get financial help: updates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#4990]
Edits to:
- Update eviction protection content
- Improve readability of CA covid-rent relief content
- add link to financial help for businesses
- add link for worker benefits
- add link to FEMA funeral assistance (#4966) 
- add content for homeless (#4968)
- consolidate links for "more help" into set of six buttons at end of page (this helps us keep the Page Index to our preferred max of six anchors per page) 

Should we use anything in the [rent relief digital toolkit](https://www.dropbox.com/sh/68zoyqb1ztjs9yq/AAAvBWnxHG7ca-FJLUlPse06a?dl=0)? Most items are available in multiple languages.

[DRAFT EDITS](https://docs.google.com/document/d/1pnfEvDK2d-8JK6cBomnYH1NB0oOLe1vSTcuYT6E0ot8/edit#)

Stakeholders need to review:
- [ ] ~Lynn.VonKoch-Liebert@bcsh.ca.gov~ Myles.White@bcsh.ca.gov 
- [x] Russ.Heimerich@bcsh.ca.gov
- [ ] ~Karen.Naungayan@hcd.ca.gov~ Nurulain.Kausar@hcd.ca.gov
- [x] Veronica.Harms@bcsh.ca.gov

Additional reviews by:
- [x] Corrin.Buchanan@dss.ca.gov

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you do an initial review?

**Comment by m-sullivan7** [comment]
Great job finding the funeral cost info and adding it in!

I left a question about how renters and landlords work together on a relief application. I feel like we could give more guidance on this point.

**Comment by LizNobriga** [comment]
@m-sullivan7 @mediajunkie These [edits](https://docs.google.com/document/d/1pnfEvDK2d-8JK6cBomnYH1NB0oOLe1vSTcuYT6E0ot8/edit#) are now in staging for our continued internal review. I think we can make it easier to understand the connections between eviction protection and rent relief. Would appreciate your feedback (in doc or via slack are both fine).

[https://staging.covid19.ca.gov/get-financial-help/](https://staging.covid19.ca.gov/get-financial-help/)

**Comment by m-sullivan7** [comment]
I think you're right that there's a better way. I'm going to explore alternate approaches in [another document](https://docs.google.com/document/d/1Tmoid2T92vF-7rvM8tsEQM8Zgt9j4XVD0SljYA6nerw/edit?usp=sharing) where I can edit without messing up what's there to see what I can come up with.

**Comment by m-sullivan7** [comment]
I thought I'd [share the results of my free thinking](https://docs.google.com/document/d/1Tmoid2T92vF-7rvM8tsEQM8Zgt9j4XVD0SljYA6nerw/edit#) before I finished for the day, @LizNobriga. This is grade 7 content (I was surprised I got it so low given the topic). What do you think of this direction? Any better? Any parts you think still need more explanation?

**Comment by LizNobriga** [comment]
I think it looks good! Are you thinking this would still be followed by the "help for renters" info, or that this covers both eviction and rent relief?

**Comment by m-sullivan7** [comment]
Yes. It does mean we say some things twice on the page. I'd have to do more deep thinking about how to blend the two if we wanted to combine them (and I can definitely do that if you'd like--today looks like a good day for it). It'll be easier to do that on November 1 when the current eviction protection ends and it gets tied to rent relief applications.

**Comment by LizNobriga** [comment]
I made edits in the [separate doc](https://docs.google.com/document/d/1Tmoid2T92vF-7rvM8tsEQM8Zgt9j4XVD0SljYA6nerw/edit#) to get rid of a couple HTR sentences, and then incorporated all of the separate doc edits into the [DRAFT EDITS](https://docs.google.com/document/d/1pnfEvDK2d-8JK6cBomnYH1NB0oOLe1vSTcuYT6E0ot8/edit#). I will update staging to match.

**Comment by LizNobriga** [comment]
@mediajunkie I think we may be ready for stakeholders to review the **Get financial help** page in staging: [https://staging.covid19.ca.gov/get-financial-help/](https://staging.covid19.ca.gov/get-financial-help/)

**Comment by LizNobriga** [comment]
@mediajunkie The current link to [Project Roomkey](https://www.cdss.ca.gov/Portals/9/FEMA/Project-Roomkey-Fact-Sheet.pdf) isn't a good place to send someone who has heard about the program and is looking to find out if they're eligible or how to get a room. Thinking stakeholders might be able to help us address this.
<img width="1035" alt="link" src="https://user-images.githubusercontent.com/58706834/128575345-5e8750c3-60f3-4b5d-ab4d-519ff5548beb.png">

**Comment by LizNobriga** [comment]
I updated the project roomkey content in the [DRAFT EDITS](https://docs.google.com/document/d/1pnfEvDK2d-8JK6cBomnYH1NB0oOLe1vSTcuYT6E0ot8/edit#) and in [staging](https://staging.covid19.ca.gov/get-financial-help/):
![image](https://user-images.githubusercontent.com/58706834/128762138-3ac817b7-9342-474a-b8f9-1dd7a594f7bb.png)
Because people are asking about project roomkey, we want to include those words on the page for now.

**Comment by LizNobriga** [comment]
Approved to publish via email chain.

**Comment by LizNobriga** [comment]
Published
