### ISSUE TITLE
Feedback: need clearer info on which businesses should close and which can stay open

### ISSUE THREAD

**Issue by coreycaitlin** [cagov/covid19#50]
Notes from site feedback:

- Please suggest that cosmeticians and hairstylists/barbers close.
- Unable to find out what business and service types are required to be closed.  Where is this important information?
- I was looking for a reason why child care centers are still open when we are in a state of emergency? The CDSS is keeping child care centers open.

This would probably fit best on the [Public places page](https://covid19.ca.gov/safety-in-public-places/#top) and/or [Employment/workers/businesses/taxes page](https://covid19.ca.gov/employment/#top).

**Comment by coreycaitlin** [comment]
Key question: is this consistent statewide, or does this vary wildly depending on whether there's a shelter-in-place in order?

**Comment by abquirarte** [comment]
it should be consistent statewide (with more consistent guidance for those counties that have been directed to stay home. 

The department to regulate this is Department of Consumer Affairs. They have a million boards and bureaus.

**Comment by abquirarte** [comment]
This may no longer be as relevant.
