### ISSUE TITLE
Housing for agricultural workers update

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5000]
The *Housing for the Harvest* program no longer offers housing. Working with the stakeholder to update page so it stops appearing to offer housing. Working with Kirsten Raschko at DSS and original stakeholder, Jay Van Rein at CDFA.

**Comment by thepegisin** [comment]
Staged this per Angie's approval 7/26, then published to PROD. Rolled back from PROD after stakeholder (Kirsten Raschko) requested that. Asked for approval a few days later, but was explicitly told no.

Unstaged 8/19 to prevent accidental publishing. Changes we recommended are in the draft: https://docs.google.com/document/d/1jjKCVAizHzZTEHojQrpgSnf9YgBS5faBpKD0y5AxB68/edit#heading=h.soeie12216wl

**Comment by abquirarte** [comment]
Email sent 8/31. Stakeholder is OOO. AQ will escalate.

**Comment by thepegisin** [comment]
Approval received per Angie 9/2. Page updated and renamed **Help for agricultural workers**. Menu updated to reflect page name change, and moved link from _California's response_ grouping to _Services_.
