### ISSUE TITLE
Health equity: Factors chart 100k/100K

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5013]
On the health equity page in the [Factors that increase risk of infection and severe illness section](https://covid19.ca.gov/equity/#factors) there is a chart titled _Community case rate by median annual household income bracket_. In the labels for each bar, we inconsistently use k to denote multiples of 1,000.

![image](https://user-images.githubusercontent.com/69169190/128386402-e2619cce-6752-4ff4-b3b9-67c38c2f6165.png)

This ticket is considered done when all uses of K in this graph are a capital letter.

**Comment by m-sullivan7** [comment]
@mediajunkie Assigning to you for eventual reassignment to an engineer for this work. I labeled it as a P3 as it's definitely a nice to have. Nothing broken, just a small inconsistency. I checked WordPress to confirm that I cannot update chart labels on my side.

**Comment by mediajunkie** [comment]
assigning to @jbum to see if he or @zakiya can tackle this in the week ahead

**Comment by jbum** [comment]
Fixed. Baking.

**Comment by mediajunkie** [comment]
yay
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by jbum** [comment]
@m-sullivan7 I also notice that the zero does not have a dollar sign on it.  Lemme know if you want one.

**Comment by m-sullivan7** [comment]
Thanks @jbum ! The fix looks great. After discussing with the content team, we'd like to add the `$` to the zero. Thank you for your eagle eye!

**Comment by m-sullivan7** [comment]
I would go with the first one since zero is just "zero" as opposed to "zero thousands". The side effect of "OK" helps make up my mind. I appreciate the thought for consistency though!

**Comment by jbum** [comment]
I agree.  Baking.

**Comment by jbum** [comment]
Published.
