### ISSUE TITLE
State dashboard: remove references to weekend update cadence

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5017]
In July 2021, CDPH moved to a data reporting cadence of Monday through Friday for everything except vaccines administered. The content work for this change was done on [CCG-2448](https://digital-ca-gov.atlassian.net/browse/CCG-2448).

This weekend, CDPH will begin reporting 7 days a week again. This ticket is considered done when we have removed the language from the July change from the state dashboard page.

[Draft Google Doc](https://docs.google.com/document/d/1mken0qiYUzJ8HLhH5CwKISHlLbo8lc-7ruHhtIjUsnw/edit?usp=sharing)

**Comment by jbum** [comment]
Note: No engineering changes needed to remove the hyphens.

**Comment by m-sullivan7** [comment]
Language updated and live on the production site.
