### ISSUE TITLE
Workers and businesses: vaccine and testing requirements for healthcare facilities

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5030]
Edits to update _Workers and businesses_ to reflect the new state public health officer [order of August 5, 2021](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Order-of-the-State-Public-Health-Officer-Health-Care-Worker-Vaccine-Requirement.aspx), which requires workers in healthcare facilities and similar settings to be vaccinated with limited exceptions. 

[DRAFT EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

Reviewed by

- [x] Michael
- [x] Christian
~- [ ] Stakeholders~

**Comment by m-sullivan7** [comment]
Looks good to me! Passing to @mediajunkie.

**Comment by LizNobriga** [comment]
This published yesterday. Closing issue.
