### ISSUE TITLE
equity dash staging update needs to trigger stage build

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#5036]
We update the data for the equity dash in staging and open a PR for CDPH to review. There isn't an automated trigger that links this event to the staging build process. We need one because the 11ty build process is what creates the HTML for the boxes at the top of the page. Having the boxes at the top of the page be part of the initial HTML is nice because they render as fast as possible.

We need to figure out the best way for the data update event to trigger a staging build and implement it so we can avoid the CDPH team reviewing stale data when they look at the links in the PR.

**Comment by jbum** [comment]
A bit preoccupied at the moment. Will trigger a manual build this week.

**Comment by jbum** [comment]
Added a cron-style trigger to staging deploy workflow.
