### ISSUE TITLE
State dashboard: county search box improvement

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5038]
In looking at the increased per page feedback on the state dashboard, I've seen continued notes about "county data not working" (there were 55 comments to this effect from July 31 to August 5, 2021, out of 267 total--20% of the total feedback during the period). In almost half (26) of those cases, people used the anchor link in the page index to get to the [County and statewide data](https://covid19.ca.gov/state-dashboard/#county-statewide) section but said they couldn't get county data. 

In the 32 comments where someone selected a county (as shown by Google Analytics), only 5 (15%) reported a problem getting county data.

Based on Google Analytics events tracking, it does not look like these 55 visitors successfully selected a county. In testing this myself, if you type in a county name but do not select the county from the drop down menu, you will not get county data, even if you select **Get county data**. If you select a county from the drop down menu, you do not need to select **Get county data**. The county data is automatically loaded upon selecting the county in the drop down. This may be worthy of additional research with users.

I propose we provide more guidance for people attempting to get county data. Potential ideas:

- Remove the **Get county data** button and provide instructions to select your county from the drop down menu when it appears.
- Add explanatory text when selecting **Get county data** and no county is recognized that you must select a county from the drop down.
- Add text on selecting **Get county data** that asks the user to select a county from the drop down menu.
- Make the county list an actual drop down menu that people choose from. (This may be more mobile friendly as it does not require typing and eliminates user error.)
- Add standing instructions through regular text (no engineering effort, but is essentially a workaround).

Submitting this for consideration and prioritization with other engineering work.

**Comment by aaronhans** [comment]
Fantastic analysis @m-sullivan7! Good recommendations

**Comment by m-sullivan7** [comment]
After some testing while doing a screenshare with @aaronhans on Tuesday, this is no longer an issue. @mediajunkie I propose we mark this issue as done.
