### ISSUE TITLE
Add in-home testing to Testing page per CDC

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5044]
As of 8/2/21, the CDC has added in-home test kits to its list of how you can get tested for COVID-19. Propose we do the same.

Draft: https://docs.google.com/document/d/18NG21vDRhqR4Y795Mi1ibYhcuJd1F_EGHiVJKIZrKyo/edit#

No change other than this, so should need minimal CDPH approval cycle.

**Comment by mediajunkie** [comment]
Getting name of Testing Task Force stakeholder from Carlos, possibly Rob McAndrews. Will update once we have approval.

**Comment by mediajunkie** [comment]
ok, confirmed. running by rob.mcandrews@csd.ca.gov

**Comment by thepegisin** [comment]
Published.
