### ISSUE TITLE
Triage P2 and P3 design improvements

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5046]
Then prioritize them for the next sprint (if we still think we need them)

**Comment by mediajunkie** [comment]
comment from retro:
> I think the site would benefit from a P2/P3 decision session, especially as we consider what might be needed if we see a fall surge. It would also help populate a git issue list as we transition away from Jira.

**Comment by m-sullivan7** [comment]
This seems like this has happened by this point. Closing this issue.
