### ISSUE TITLE
Education: add new links

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5048]
Add new links:

- [Schools Can Safely Open Despite Delta Variant](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Schools-safely-open-despite-Delta.aspx)
- [COVID-19 Testing at Schools](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/COVID19-Testing-at-School.aspx)

Or, link to [Parents](https://schools.covid19.ca.gov/pages/parent-page) page of the Schools Hub instead

Add childcare [guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Child-Care-Guidance.aspx) and links to this page

[DRAFT EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)

**Comment by m-sullivan7** [comment]
Reviewed!

**Comment by LizNobriga** [comment]
@mediajunkie Your turn for review. 
[DRAFT EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)

**Comment by mediajunkie** [comment]
Edits looks good to me.

**Comment by LizNobriga** [comment]
@mediajunkie [Edits](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#) to the **Education** page are staged. Okay to publish? 
https://staging.covid19.ca.gov/education/
