### ISSUE TITLE
Improve navigation between data pages

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5056]
In reviewing per page feedback, I noticed that people are often looking for information in the wrong places. Here are examples from August 6 to August 8.

- Equity: "Yuba County vaccination rate" (available on _Vaccination progress data_)
- Equity: "Wanted to see vaccination by age group Vaccination status by age group Cases, severe, death by age group  To roughly estimate vaccine efficacy" (also available on _Vaccination progress data_)
- State dashboard: "How many kids age 12-15 in San Diego were hospitalized for COVID-19 ?" (available in part on _Vaccination progress data_)
- State dashboard: "Please add "vaccination status" as a category in the section called "cases and deaths by ethnicity, gender, and age"." (available on _Vaccination progress data_)

I recall we considered adding some kind of header to the data pages to allow people to navigate between them, like we have on the homepage.

![image](https://user-images.githubusercontent.com/69169190/128744888-a5e95582-7efb-4d40-a02c-e908f51e3877.png)

This could be useful because a lot of state dashboard traffic comes in directly. In from July 31 to August 5, 111,023 of the 171,023 (65%) of the state dashboard views were landing page views. They probably aren't even seeing the options on the homepage.

There's a similar percentage for Vaccination progress data (51%). Equity, on the other hand, has a much lower percentage of landing page views (15%).

28,943 people used the links out of the 395,808 homepage views. This 7% rate is comparable to June 8-14 when these links were above the fold on the homepage and the rate was 8%. However, the homepage audience probably has broader interests than data. People looking for data may use these links more if they're in the context of data pages.

I'd like us to consider serving these landing page visitors more directly with some top links to help people get to all of our data. This would include _Variants_ when we launch that page.

**Comment by m-sullivan7** [comment]
@mediajunkie assigned to you for considering with sprint planning. I'd estimate this is a P2 as nothing is broken, but we could help people find info that's already there more easily.

Side note: all three data pages have per page feedback comments about seeing vaccinated vs. unvaccinated cases. This says providing equity and _Vaccination progress data_ pages a path to the state dashboard may be important when we launch that info.

**Comment by mediajunkie** [comment]
I like this idea. This way we can still show these various dashboard or subdashboard pages in context while giving a clear way to move among them

**Comment by m-sullivan7** [comment]
In looking at this week's per page feedback, I've seen continued comments about people looking for data that's not on the page they're viewing, but is on another data page. Just building the case for this improvement. 😄

**Comment by adam-little** [comment]
@m-sullivan7 one thought is to reuse the "card" design that we use on [Current Safety Measures](https://covid19.ca.gov/safely-reopening/) and the upcoming Financial Help update.

In this case, we could replace the "More data and tools" component at the bottom of the State Dashboard with a layout like this: 
![image](https://user-images.githubusercontent.com/69167298/135162908-b19addb1-67cc-42e4-90c0-bb5024f5ba58.png)

Do you think this addresses the issue?

**Comment by m-sullivan7** [comment]
Interesting idea! I think it could. I like the ability to add some details about what can be found on each page so people know where to look.

How flexible do you think we could be in placement on the page? I'd initially thought about putting something at the top of each page. This design probably wouldn't fit at the top. That said, putting it at the bottom as in this example could be a good first iteration to see if there's any decrease in comments.

**Comment by adam-little** [comment]
Here's another low-tech solution:

- Leverage the [Data and Tools](https://covid19.ca.gov/data-and-tools/) page and update the content in a way that elevates the dashboards on covid19.ca.gov
- The State Dashboard already has a prominent CTA to the Data and Tools page. We could apply the same CTA to the Vax Progress Dash and the Equity Dash

**Comment by m-sullivan7** [comment]
I like the idea of a standard, final section on each of the chart pages that highlights the existence of other pages and provides detail about what they'll find.

We get some traffic to _Data and tools_ of people looking for info available on the chart pages. A little less than half this traffic comes in the form of people's landing page. Based on that, I think placing content at the top of _Data and tools_ that highlights the existence of the chart pages could be useful in getting people to where the data they want is.

**Comment by m-sullivan7** [comment]
[First draft](https://docs.google.com/document/d/17T88FpKENXXCMhHMBbdoe_Gr52MGpRstorHO4pIZoqU/edit?usp=sharing) of what this section would look like on the state dashboard. I'll work on the other pages tomorrow (which just need a section for state dashboard).

**Comment by m-sullivan7** [comment]
More first drafts of what this implementation would look like on other data pages:

- [Vaccination progress data](https://docs.google.com/document/d/17M9ymRidkNDCDwl0azd2VwtrO1I-FJpyvmK0acL240Q/edit?usp=sharing)
- [Health equity](https://docs.google.com/document/d/1vfuYv_iZzSkDxt1vRb69XDZnBWALzKa18Lw8VJsIhlA/edit?usp=sharing)
- [Data and tools](https://docs.google.com/document/d/1kjvGa3c4QGWL4NHJC7DHde_RQQeHS9ewN4dWmkiwaVQ/edit?usp=sharing)

On these pages (including [state dashboard](https://docs.google.com/document/d/17T88FpKENXXCMhHMBbdoe_Gr52MGpRstorHO4pIZoqU/edit?usp=sharing)) I went with the bottom placement and a page index link to surface the section. There's no styling, but @adam-little and @mediajunkie (since I know he was part of the conversation too) what are your thoughts? Worth staging on _Data and tools_ (the lowest touched page of the three) to see how it looks?

**Comment by adam-little** [comment]
Looks good to me

**Comment by abquirarte** [comment]
Same. I like the approach!

**Comment by m-sullivan7** [comment]
Thanks for the review! I'll go work on staging on _Data and tools_.

**Comment by m-sullivan7** [comment]
[Here it is!](https://staging.covid19.ca.gov/data-and-tools#more) Thoughts?

(PS--big thanks to Jim, who I'm not tagging since it's Tech Debt Tuesday, for showing me how to play around with the top and bottom margins to eliminate white space. We did that together on state dashboard and I was able to play around here with that to clean things up!)

@abquirarte with @mediajunkie and @adam-little copied

**Comment by adam-little** [comment]
Looks good to me!

A few small comments:

- I don't think it *needs* to go in the page index just because it's an h2, but i'm ok with leaving it there if you think it adds value
- Are you able to remove the gray horizontal line above the component? Since this section has a different background color, the line is not needed
- On Chrome, i see empty white space between this component and the footer. That white space should not be there.

**Comment by m-sullivan7** [comment]
Thanks for the comments Adam!

- I put the link in the index to help people who might enter the site via one of these pages. However, now that I think about it we could launch without and see if we continue to see comments in page feedback.
- I might be able to change the line's color so it's not as obvious. Thanks for pointing that out!
- I'll need to get an engineer's help to see if we can get rid of that line. We have one on state dashboard now that Jim wasn't able to get rid of when we implemented that box. I think we could launch with it and tackle later.
