### ISSUE TITLE
Tracking end dates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5064]
Track end dates of covid related benefits and programs

[Dates tracking doc](https://docs.google.com/document/d/1JCBncO1Xswp3knVnnJncpc-7PHWl5zV8A9yq3PuGUPs/edit)

**Comment by LizNobriga** [comment]
@m-sullivan7 @thepegisin Here's the [date tracker doc](https://docs.google.com/document/d/1JCBncO1Xswp3knVnnJncpc-7PHWl5zV8A9yq3PuGUPs/edit) I showed you briefly. Feel free to add, update, and make corrections. 
cc @mediajunkie

**Comment by m-sullivan7** [comment]
I don't have access to the document. However, I reviewed my pages and didn't find any dates on them. A few questions came up. They may already be in the document.

- When does protection against utility shut-offs (power and water) end? We reference that on the _Help for immigrants_ page right now. Though it's going away, maybe that program lives on other pages too.
- When do Golden State Stimulus distributions end?

**Comment by LizNobriga** [comment]
Oops, fixed the doc location so everyone can access it now.

**Comment by m-sullivan7** [comment]
And you covered both of those points in what you've got. Nicely done!

**Comment by LizNobriga** [comment]
We know the deadline to "apply" for Golden State Stimulus (AKA, submit your 2020 tax return). Not sure about when the money gets distributed. 

We will need to dig a little more to get clarify on water and utility shut offs. 

I added one bullet about the CA Public Utilities Commission, but idk if that covers everything. There might be more info buried in this (but I haven't read through yet): [CPUC utility protections during covid](https://www.cpuc.ca.gov/news-and-updates/newsroom/covid-19/utility-consumer-protections-during-california-covid-19-outbreak)

For water, I found where you can [submit a report of water being shut off](https://watershut-off.covid19.ca.gov) to the CA state water resources control board. Didn't find this water [service of process during covid](https://www.waterboards.ca.gov/laws_regulations/#service_during_covid-19) info useful. Found nothing about a moratorium or end date.

**Comment by LizNobriga** [comment]
@mediajunkie Since we now have a running [list](https://docs.google.com/document/d/1JCBncO1Xswp3knVnnJncpc-7PHWl5zV8A9yq3PuGUPs/edit) for tracking any start/end dates relevant for covid, I'm moving this to done and closing for now. If you think of anything else we might add to it, just ping me. :slightly_smiling_face:
