### ISSUE TITLE
State dashboard 8/11 data note

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5069]
Post the following note on the state dashboard for the publication of today's data:

_The negative count of deaths reported today is due in part to Santa Clara County reporting -417 deaths due to data cleaning._

Remove the note when data updates again on August 12, 2021.

**Comment by mediajunkie** [comment]
is that a tilde instead of a minus sign?

**Comment by m-sullivan7** [comment]
I was just looking at that. It is, which is incorrect!

**Comment by m-sullivan7** [comment]
Note is live on the [state dashboard](https://covid19.ca.gov/state-dashboard/). I will remove it after the data updates tomorrow.
