### ISSUE TITLE
Education: requiring vaccine or testing for teachers

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5073]
GGN announcement today, awaiting link for details

[EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#)

**Comment by m-sullivan7** [comment]
Reviewed with one suggestion. 😄

**Comment by LizNobriga** [comment]
Published
