### ISSUE TITLE
Workers and businesses: requiring vaccine or testing for teachers

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5076]
Awaiting details and link

Add links to the Q&As for healthcare worker vax requirements

[EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by m-sullivan7** [comment]
Looks good! No changes from me. (Nice slipping in a readability edit too.)
