### ISSUE TITLE
H5 styling

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5077]
The H5 header is small compared to the H4. It feels small, perhaps because the space beneath the header and above the text is small.

![image](https://user-images.githubusercontent.com/69169190/129087055-b18b5556-96dd-438f-ae1c-c614bf449393.png)

Here's Adam's specs for H5s in Figma. Are these loaded into the site? If so, does our visual design standards support using H5s with body content? It's unclear if _(for labels)_ means it's only approved for use in labels.

![image](https://user-images.githubusercontent.com/69169190/129087656-ea70bb0c-d1f2-4187-8559-a5702d27783b.png)

**Comment by adam-little** [comment]
I don't think this is relevant anymore. This content no longer exists. Correct, @m-sullivan7?

**Comment by m-sullivan7** [comment]
We do not have this content anymore. When we did, we wrote around the lack of an H5. I think the question now is if we want to create an H5 style for covid19.ca.gov and/or the Design System or just cut it off at H4?

If we do, for the covid19.ca.gov site I think this issue is better assigned to an engineer to implement Adam's existing style from the screenshot in the description.

**Comment by m-sullivan7** [comment]
Closing this issue since this is no longer needed and we are transitioning the site to CDPH.
