### ISSUE TITLE
Education PHO swirl

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5078]
[on swirlbase](https://airtable.com/tblmIs67DpOt3B72M/viwT6BqRMBjSxoQ7k?blocks=hide)

going live:
- [x] Banner
- [x] Current safety measures
- [x] Education (Liz)
- [x] Workers and businesses (Liz)
- [x] Vaccines
- [x] (not needed) Masks

stakeholders notified (xian):
- [x] Current safety measures
- [x] Education
- [x] Workers and businesses 
- [x] Vaccines

**Comment by thepegisin** [comment]
No change needed for Masks page. Everyone in K-12 schools already has to wear a mask, no matter their vaccination status. 
 https://cadotgov.slack.com/archives/C01AS2EU5N3/p1628699981037100?thread_ts=1628696354.034800&cid=C01AS2EU5N3

**Comment by thepegisin** [comment]
No mask rule change for vaxed teachers.

**Comment by thepegisin** [comment]
Vaccines update now live.
