### ISSUE TITLE
Workers and businesses: return to work

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5090]
Trending topic in page feedback about quarantine protocol and returning to work

Examples from PPF:
- how long to quarantine if exposed? what if I tested positive and am fully vaccinated?
- return to work? covid waiting period to return back to work? when can a worker come back to work after having covid
<img width="814" alt="Screen Shot 2021-08-11 at 6 35 53 PM" src="https://user-images.githubusercontent.com/58706834/129231857-1d85d5ca-852d-4771-aa71-0329754524da.png">

[~~DRAFT EDITS~~](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

[DRAFT EDITS](https://docs.google.com/document/d/18fvtpl-pJetLrmQHy-N6AlD-xXkK02typ5_-tx3-brg/edit?usp=sharing) (moved edits to this section into a separate doc)

**Comment by m-sullivan7** [comment]
Left some comments in the Google Doc.

One general question: as the pandemic progresses and people have more questions, this page grows longer. At what point would you consider breaking this page back into two pages, one for workers and one for businesses?

**Comment by LizNobriga** [comment]
Agree with considering whether to split up this page. 

A couple notes:
- The current content that benefits most from the merged page is the _COVID-19 workplace safety standards_ and the _Vaccination and testing for some workplaces_ since it applies to both workers and employers.
- The _Financial help for businesses_ content only applies to businesses. This content could live on its own page. It could also fit on the Get financial help page, but that page is also currently dealing with length issues.
- The _Benefits for workers_ content mainly applies to workers, although employers are responsible for providing many of those benefits, so there is some overlap.

**Comment by m-sullivan7** [comment]
Excellent analysis! Sounds like the answer is no for right now, but something to continue thinking about. I could see us implementing three pages at some point:

- Workplace requirements
- Help for workers
- Help for businesses

**Comment by LizNobriga** [comment]
@m-sullivan7 I made revisions to the [Return to work draft edits](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#) based on stakeholder feedback. Can you review this revised content section? There's likely more opportunity to improve readability (without sacrificing accuracy). 

Summary of stakeholder feedback:
- Under CDPH guidance, all the “musts” on isolation and quarantine should be “shoulds.”  That guidance is not mandatory.  
- There is a modified quarantine process identified as an option for asymptomatic unvaccinated people, that specifies only 7 days if the person has a negative test from at least 5 days after exposure.  
- There is a difference between isolation (when someone has tested positive) and quarantine (when someone is a close contact).

Stakeholder comments: 
> I don’t know if the rules are different on this under ETS, but ETS applies to employers not individuals, and this is framed as information for individuals.
>  
> This area is pretty complicated, so I think it’s important to work with CDPH folks on how to explain as simply and accurately as possible.

**Comment by m-sullivan7** [comment]
Thanks for giving me the verbatims so I could have those in mind! The reading level of the _Return to work criteria_ section is 6 and my edits didn't change that. Great job bringing it down!

I took a swing at a couple of improvements to help ease the friction of having recommendations coexisting with requirements. What do you think?

**Comment by LizNobriga** [comment]
I put the [revised section](https://docs.google.com/document/d/18fvtpl-pJetLrmQHy-N6AlD-xXkK02typ5_-tx3-brg/edit?usp=sharing) into its own doc to make it a little easier to review. The section for review is titled, "Returning to work after getting sick or exposed to COVID-19."

After @mediajunkie has a chance to review, it may be ready to go to stakeholders again.

**Comment by LizNobriga** [comment]
Re-nudged stakeholder

**Comment by LizNobriga** [comment]
@mediajunkie Do we want to ask Labor/DIR folks to review [these edits ](https://docs.google.com/document/d/18fvtpl-pJetLrmQHy-N6AlD-xXkK02typ5_-tx3-brg/edit?usp=sharing)since they are based on the covid prevention emergency temporary standards?

**Comment by LizNobriga** [comment]
@mediajunkie The [edits](https://docs.google.com/document/d/18fvtpl-pJetLrmQHy-N6AlD-xXkK02typ5_-tx3-brg/edit?usp=sharing) are ready in [staging](https://staging.covid19.ca.gov/workers-and-businesses/#workplace-safety-standards).

**Comment by LizNobriga** [comment]
(these edits were taken out of staging so we could publish on this page)

The return to work edits were sent as a word doc to stakeholders last week.

**Comment by LizNobriga** [comment]
Revised [edits ](https://docs.google.com/document/d/18fvtpl-pJetLrmQHy-N6AlD-xXkK02typ5_-tx3-brg/edit#)based on external review feedback (see attachment: [Workers and businesses - return to work section _ mp ah mp.docx](https://github.com/cagov/covid19/files/7131716/Workers.and.businesses.-.return.to.work.section._.mp.ah.mp.docx)).


The revised edits score a grade 5 with one hard-to-read sentence:

> If a worker does not have symptoms, but tests positive, they must not return to work for at least 10 days after they first tested positive.

**Comment by m-sullivan7** [comment]
They look good to me! Only a couple minor edits, one of which you can dispense with if it seems appropriate in the context of your knowledge of the subject and stakeholders. :smile:

**Comment by LizNobriga** [comment]
Edits are published
