### ISSUE TITLE
begin using new static file infrastructure

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#5092]
Moving from azure buckets in production for static files to AWS S3+Cloudfront is better because:

- We can setup redirects on our own without opening a ticket for CDT
- Redirects can be created without modifying frontpage rules which have caused problems in the past
- We can easily synch to S3 buckets if we need to bypass github actions for deploys

Next step:

- Change how covid-static deploys to target our static.covid19.ca.gov S3 bucket + cloudfront cache clear
- Verify production setup by testing changing links on site to use static. instead of files.
- When verified we can point the files. domain at our static site too (This requires a new cert but will help us preserve any google rank for these files)

**Comment by jbum** [comment]
Done.
