### ISSUE TITLE
Health equity: reduce learn more links

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5096]
When the [health equity](https://covid19.ca.gov/equity/) page was created, stakeholders didn't want people to leave the site before they read everything, but also wanted to hyperlink to info. We compromised by creating a _Learn more_ section.

This approach adds an unnecessary click for people who want information on these topics. A better experience is to send them directly to the page at the first click.

This solution also does not work. People likely still skip information by going to the bottom of the page.

I propose with this ticket that we remove the anchor links to the _Learn more_ section and replace them with direct links to that content.

**Comment by m-sullivan7** [comment]
Here's a draft of how I would edit to remove the anchor links that lead to the _Learn more_ section.

@mediajunkie Stakeholders may not care about making this change at this point. (They may not even remember why we did it this way in the first place.) If you want to run this by them, the big point to make is that we're turning what currently takes two clicks for a user into one click. That said, I'm happy if you want to approve this change without consulting them.

We may also want to consider a larger project to evaluate what we're trying to do with this page. We may not need as much content and storytelling at this point. That's a conversation that would definitely include stakeholders.

**Comment by m-sullivan7** [comment]
Following up on whether we can make this change now without stakeholder approval or whether to send it up the chain. (I'm optimistic it can be the first!)

**Comment by jaredwyee** [comment]
@m-sullivan7 I think we can move fwd and keep an eye out for any feedback. thanks
