### ISSUE TITLE
Improve analytics reporting

### ISSUE THREAD

**Issue by ChadABratton** [cagov/covid19#51]
**Analytics Improvements for Covid19.ca.gov**

**What is the need:**
Share key anayltics defined below every morning in slack so the whole team has access to important analytics. 
Note: Present the following data in a repeatable, shareable format:

**Key Analytics:**
Total hits
Avg Total Users - Live
Trends
Top Pages
Device Type

**Comment by jpetrucione** [comment]
Additional analytics I'm interested in:
Unique sessions
Total sessions
Bounce rate
Page views
Time on site
Demographics
Referrals - top sites

**Comment by abquirarte** [comment]
☝️ agree.

**Comment by ChadABratton** [comment]
I have compiled what could be a daily report. Let me know if you have any questions or suggestions for improvement!!
https://drive.google.com/open?id=1gJDAJlyy9Fuwtr_ZPGtXzNUqvzboRrYI

**Comment by abquirarte** [comment]
@artuoma see Kimberly's email. For some reason Scott wants you to be the one to make the ask. thanks!

**Comment by artuoma** [comment]
I am on this, let you know if I am able to add the website under the existing contract.
