### ISSUE TITLE
Workers and businesses: Shuttered Venue Operators Grant applications close 8/20

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5114]
Feds just announced [end date of 8/20 for Shuttered Venue Operators Grant application period](https://www.sba.gov/funding-programs/loans/covid-19-relief-options/shuttered-venue-operators-grant#section-header-0)

- [ ] Update **Workers and businesses** page, [Financial help for businesses](https://covid19.ca.gov/workers-and-businesses/#financial-help-businesses) section, to reflect 8/20/21 end of application period for this grant program

[DRAFT EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)
NOTE: This draft includes proposed edits for separate issues: #5090 and #5128.

**Comment by m-sullivan7** [comment]
@LizNobriga Is there a Google Doc to review?

**Comment by m-sullivan7** [comment]
Simple, straight-forward addition. Good here!

**Comment by LizNobriga** [comment]
Hi @mediajunkie, this ticket/review is for a simple edit just to add the end date for applications to the Sheltered Venue Operators Grant:

![Screen Shot 2021-08-18 at 2 27 27 PM](https://user-images.githubusercontent.com/58706834/129974697-d84b45d9-a877-405d-9731-ee06fa05ef48.png)

The current **Workers and Businesses** [draft doc](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#) has proposed edits that are related to separate tickets.

**Comment by mediajunkie** [comment]
Am I right that this change does _not_ address that fact that operators previously awarded grants will have an opportunity to apply for a supplement? I saw that mentioned in the issue description but no reference to it in the copy.

**Comment by LizNobriga** [comment]
Yes, that's right. The SBA hasn't announced the details yet, so I didn't add that info now. I will update that in the summary.

**Comment by LizNobriga** [comment]
Published
