### ISSUE TITLE
Create card layout for Current Safety Measures page

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#5117]
Build layout for [Current safety measures](https://covid19.ca.gov/safely-reopening/) page'

![image](https://user-images.githubusercontent.com/69167298/129777296-55b906a1-bf4a-4dba-bd39-485e3658a456.png)

**Design:**

- Three-column card grid 
- Each card has an image, a title with link, and description
- [Figma](https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=7918%3A38061)

**Content:**

- [Draft content](https://docs.google.com/document/d/1AUcqlSFcKZ0DCbTN0o3gko-7dfCdcXg4rZ0UbVJJZCc/edit#)
- Photos: [Current Safety Measures - Photos.zip](https://github.com/cagov/covid19/files/7002050/Current.Safety.Measures.-.Photos.zip)

**Comment by mediajunkie** [comment]
@kkoryaka - can you let me know your availability for tackling this?

**Comment by kkoryaka** [comment]
THis is now in staging: https://staging.covid19.ca.gov/safely-reopening/

**Comment by kkoryaka** [comment]
THis one is now live on covid19.ca.go production site.
