### ISSUE TITLE
google indexing error on redirect

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#5119]
The page https://covid19.ca.gov/contact-tracing/ is now a redirect.

Google Search Console is complaining about this url being indexed with no content.

Does it need to be removed from the sitemap?

**Comment by jbum** [comment]
I don't see it in the site map at the moment.

**Comment by jbum** [comment]
Perhaps the issue is that we are linking directly to it from a menu.  Will fix.

**Comment by aaronhans** [comment]
nice, thank you
