### ISSUE TITLE
Workers and businesses: improve content for employers requiring vaccinations

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5120]
Trend in feedback: 
- Can I be fired if I don't get the vaccine and don't do the weekly testing? 
- Can I collect unemployment if I'm fired or quit because I don't want to get the vaccine?

Improve content in _Employers may require employees to be vaccinated_ to address this area. 

The current links to [CA Department of Fair Employment and Housing’s FAQ PDF](https://www.dfeh.ca.gov/wp-content/uploads/sites/32/2020/03/DFEH-Employment-Information-on-COVID-19-FAQ_ENG.pdf) and the [EEOC](https://www.eeoc.gov/wysk/what-you-should-know-about-covid-19-and-ada-rehabilitation-act-and-other-eeo-laws#K) have some answers about this topic, but could be more clear.

**Comment by LizNobriga** [comment]
@mediajunkie Okay to close this ticket?

**Comment by mediajunkie** [comment]
Yes!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>
