### ISSUE TITLE
Reorganizing Vaccines page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5135]
- [x] Draft a reorg of Vaccines page
- [x] Review with Xian for approval to stage
- [x] Stage and notify Xian, giving him language
- [x] Let him notify stakeholders
- [x] Publish
- [x] Celebrate

**Comment by thepegisin** [comment]
Draft: https://docs.google.com/document/d/1upSAaN-n4idaetIjIAMrHO6g6TL_Zkt7ulRHzP4n-EE/edit#heading=h.s70rmws9iz4b

**Comment by m-sullivan7** [comment]
I've published these edits with Christian and Jared's go ahead. I'll leave formally closing the ticket (and celebrating!) to Peggy as the person who did all the work. 😄

**Comment by thepegisin** [comment]
Thank you, @m-sullivan7!
