### ISSUE TITLE
Review menu items

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5136]
As part of June 15 work, some pages were archived and their place in the menu taken by a link to an external site.

In a recent content crit where we discussed implementing a different menu, @thepegisin suggested that we review what's in the menu. Some items may no longer be needed or could be put on a page rather than take up space in the menu. This would free up space in the menu for links to other content or reorganizations of the menu.

Copying @LizNobriga as she was part of the original discussion too.

Peggy--I forget which of us owns the navigation. I feel like I passed it to you, but I'm still listed as owning it on the Google Sheet. I am happy to lead this if you've got plenty on your plate. Thankfully, this one isn't urgent.

**Comment by m-sullivan7** [comment]
Here are the links in our menu that go to other sites and are candidates to be removed from the menu (with or without being moved into pages). I've noted whether they're currently in any page content.

- Contact tracing (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19-Contact-Tracing.aspx) (not in any page)
- Symptoms and risks (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Symptoms-Risks.aspx) (not in any page)
- California Health Corps (https://emsa.ca.gov/ca-health-corps/) (not in any page)
- Hotels for health workers (https://www.dgs.ca.gov/OFAM/Travel/Resources/Page-Content/Resources-List-Folder/COVID-19-Obligations-of-Health-Care-Workers) (not in any page)
- Childcare (https://mychildcare.ca.gov/#/home) (will be in a page once the Education edits in https://github.com/cagov/covid19/issues/5098 are made)
- Help for immigrants (https://immigrantguide.ca.gov/en/covid19/) (not in any page)
- Manage stress for health (https://osg.ca.gov/additional-information-and-links-for-support/) (in _Resources for emotional support and well-being_)

**Comment by LizNobriga** [comment]
Just noting we are also proposing to put the Hotels for healthcare workers link back on the Workers and businesses page in #5128

**Comment by LizNobriga** [comment]
Update: 

- Page title has been changed to :sparkles:_Education and childcare_:sparkles:
- _Childcare_ has been removed from site menu navigation.

**Comment by m-sullivan7** [comment]
Updated list:

- CA Notify (https://canotify.ca.gov/) (in footer, but not in any page content)
- Contact tracing (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19-Contact-Tracing.aspx) (not in any page)
- Symptoms and risks (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Symptoms-Risks.aspx) (not in any page)
- California Health Corps (https://emsa.ca.gov/ca-health-corps/) (not in any page)
- Hotels for health workers (https://www.dgs.ca.gov/OFAM/Travel/Resources/Page-Content/Resources-List-Folder/COVID-19-Obligations-of-Health-Care-Workers) (not in any page)
- Help for immigrants (https://immigrantguide.ca.gov/en/covid19/) (not in any page)
- Manage stress for health (https://osg.ca.gov/additional-information-and-links-for-support/) (in _Resources for emotional support and well-being_)

**Comment by mediajunkie** [comment]
No problem removing those. 

What's the decision on things like Symptoms and risks, that used to be pages here?

**Comment by m-sullivan7** [comment]
We're keeping all the other external links currently in the menu navigation. We thought about our users and their needs and determined that providing them a path to this info from our site was still useful.

I'll coordinate removing these two links from the menu. Thanks for the review!

**Comment by m-sullivan7** [comment]
Menu update published.
