### ISSUE TITLE
Education: testing and vaccine record links

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5138]
[DRAFT EDITS](https://docs.google.com/document/d/1xMzjiasenpZe6D7nrhXS9_0Sj5woLTf-8BPk9qaYRJo/edit#) to address page feedback trends

Summary of edits:
- Add H3 for **vaccination and testing requirements** for k-12 staff
- Add button links:
  - **Find a testing location**
  - **Get your digital vaccine record**

**Comment by m-sullivan7** [comment]
Good stuff! Just took out a couple of spaces in your button code. 😄

**Comment by LizNobriga** [comment]
Published 8/20/21
