### ISSUE TITLE
Sept 4 end of most unemployment benefits / find ongoing benefits available

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5142]
People are looking for available benefits after September 4. Reorganize content about financial benefits and other topics across multiple pages. 🐙

Breaking this into smaller, independent chunks, and prioritizing content reorganization. Doing this first makes it easier to update content going forward. 

1. Launch **Financial help for businesses** page - published ✅ 
  - [x] Reuse the old /business-and-employers/ slug
  - [x] Move _current_ content to this page - [draft](https://docs.google.com/document/d/1n_mQl1AjpdP2I7_9MIEptRqfxPu8clYhYIKDaNwn-j4/edit#), see [staging](https://staging.covid19.ca.gov/business-and-employers/)
  - [x] Remove content currently on Workers and businesses page - see [staging](https://staging.covid19.ca.gov/workers-and-businesses/)
  - [x]  Update redirects for /business-and-employers/ slug
  - [x] Add new page to menu nav
  - [x] Add link to this page to the current Get financial help page - [draft](https://docs.google.com/document/d/1Q3BJIOXtGiUlvkn6RxP-u-pkCMIm-1k104nh_3dX0zM/edit), see [staging](https://staging.covid19.ca.gov/get-financial-help/#more-financial-help)
  - [x] Identify approvers / people to be informed (Chris Dombromski at GO-Biz, Samantha and Daniel at Labor)
  - [x] Let stakeholders know
 
2. Launch **Housing and rent** page, and update **Get financial help** page with card design (9 boxes)
  - [x] Reuse the old /housing-and-homelessness/ slug
  - [x] Move _current_ content (from Get financial help page) to Housing and rent page - [draft](https://docs.google.com/document/d/1grKJIV0MBC4c7fWvytsvlkZ16WvAO-l1cpprzLgSyUg/edit#), see [staging](https://staging.covid19.ca.gov/housing-and-homelessness/)
  - [x] Remove existing content from **Get financial help** page, and update with links to Housing and rent - implement initial card design with 9 boxes on **Get financial help** page - see [draft](https://docs.google.com/document/d/1MUEJ_zVTne01xSseOmEP_TI97eSI57dpaWGd-_sSzq0/edit#) showing edits; see [staging](https://staging.covid19.ca.gov/get-financial-help/)
  - [x] Update page redirect table in wordpress (this slug currently redirects to /get-financial-help/)
    - [x] Update redirects in languages other than English after 24 hours once translated pages are live
  - [x] Add new page to menu nav
  - [x] Identify approvers / people to be informed (BCSH: Russ.Heimerich@bcsh.ca.gov, Veronica.Harms@bcsh.ca.gov, interim contact Myles.White@bcsh.ca.gov; HCD: interim contact is Nurulain.Kausar@hcd.ca.gov; also Rei.Onishi@gov.ca.gov)
  - [ ] Let stakeholders know

3. Launch **Help for individuals and families** page* (3 and 4 need to be launched close together since some content is moving from Workers and businesses to this new page) - [draft](https://docs.google.com/document/d/1IFdCizJVkwGHzXAUUnS7BwOT4-EO-l5ikyWEyuPeCBE/edit) and [staging](https://staging.covid19.ca.gov/help-for-individuals-and-families/)
  - [x] Use new slug /help-for-individuals-and-families/
  - [x] Move _current_ content to this page
  - [x] Two new content sections need stakeholder review and approval
  - [x] Identify approvers / people to be informed
  - [x] Add new page to menu nav
  - [ ] Let stakeholders know

 4. Launch **Safety in the workplace** page* (3 and 4 need to be launched close together) - [draft](https://docs.google.com/document/d/1BERmYI9Y4ilQpI3SiXAC7AcBq-P-nsII5vSCBODEc1c/edit#heading=h.3yfedl33pn4i) and [staging](https://staging.covid19.ca.gov/workers-and-businesses/)
   - [x] Use current **Workers and businesses** page (/workers-and-businesses/ slug)
   - [x] Keep _current_ content on this page
   - [x] Update page  name in menu nav
   - [ ] Update page redirects table in wordpress
   - [x] Identify approvers / people to be informed
   - [ ] Let stakeholders know
  
5. Launch full card design on the **Get financial help** page - [draft](https://docs.google.com/document/d/1jNtQMqcFW7PjswSFnQbe9f-O74vCctWfGWJE5oxyjH4/edit#) and [staging](https://staging.covid19.ca.gov/get-financial-help/)
- [x] Add last two cards (11 cards in total)
  - Benefits for children
  - Healthcare and health insurance
- [x] Update anchors for Stimulus payments, Sick leave, etc. as needed
See details in #5243 
 
6. Proceed with planned updates to each page. Make separate tickets to track these. 
  - Housing and rent #5427
  - Financial help for businesses #5426 
  - [Safety in the workplace](https://docs.google.com/document/d/1-royo1BDXvdZBHjbLiDyiM6Ybs6q0IAzRUp_fgQqi24/edit#)

**Comment by LizNobriga** [comment]
@m-sullivan7 I've got some pages drafted based on our last content meeting where we landed on new buckets. What do you think of this direction overall, and the structure and organization of these proposed pages? 

There's some work to do on readability. I haven't checked the all of the new and revised content in Hemingway. Feel free to make those edits now and I'll get them incorporated. I expect that there will be another round of internal review though.

**Comment by abquirarte** [comment]
Lots of pages indeed!

**Comment by mediajunkie** [comment]
@LizNobriga for each program we need to know:
- what is it
- where is it currently
- what is the plan for it (where is it going)
- who is the approver

so let's go over that together

**Comment by m-sullivan7** [comment]
@LizNobriga Thank you! I found one past date (the GSS tax filing due date) that I suggested a fix for. I also saw one opportunity for a paragraph break around the California EITC that is optional--accept or reject at your pleasure.

The content looks good to me--especially considering the huge effort this work represents. Excellent work!

**Comment by LizNobriga** [comment]
@m-sullivan7 The GSS section has been updated to incorporate stakeholder feedback, Could you review?

**Comment by m-sullivan7** [comment]
Just a couple thoughts in there and one addition that I thought added clarity. 😄

**Comment by LizNobriga** [comment]
@mediajunkie I've incorporated stakeholder feedback on the Golden State Stimulus (GSS) payments section. 

Michael has reviewed, and the [google doc](https://docs.google.com/document/d/1IFdCizJVkwGHzXAUUnS7BwOT4-EO-l5ikyWEyuPeCBE/edit) and staging are both updated. 

Could you review and let me know if you have any questions about edits to the GSS section?

**Comment by mediajunkie** [comment]
GSS changes look good to me.


-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you review the edits to the paid sick leave section? These edits are based on stakeholder review. 
[google doc](https://docs.google.com/document/d/1IFdCizJVkwGHzXAUUnS7BwOT4-EO-l5ikyWEyuPeCBE/edit)

**Comment by LizNobriga** [comment]
@m-sullivan7 Revisions for review in the content about:
- Federal CTC
- CalEITC

[Google doc with edits](https://docs.google.com/document/d/1IFdCizJVkwGHzXAUUnS7BwOT4-EO-l5ikyWEyuPeCBE/edit#heading=h.d1n3mlm89plj)
[Staging](https://staging.covid19.ca.gov/help-for-individuals-and-families/)

**Comment by m-sullivan7** [comment]
All good with no changes from me. Thanks @LizNobriga !

**Comment by LizNobriga** [comment]
@mediajunkie These changes reflect what information people are looking for and where they expect to find it. 

### New page: Help for individuals and families
This page includes:
- Existing content being relocated with no changes
- Content being updated:
  - Golden State Stimulus payments
  - Supplemental paid sick leave
- New content sections covering:
  - Benefits for families with children, including CalWORKs, federal Child Tax Credit, and CA child tax credits
  - Healthcare and health coverage

See this page in staging: https://staging.covid19.ca.gov//help-for-individuals-and-families/

### Updating page: Safety in the workplace
This set of changes also includes renaming the _Workers and businesses_ page to _Safety in the workplace_. In addition to the title change, we are removing the content that is being relocated to the _Help for individuals and families_ page. There are no updates or changes to content meaning. 

See this page in staging: https://staging.covid19.ca.gov/workers-and-businesses/

### Updating page: Get financial help
As the changes above are published, we will update the cards on the _Get financial help_ page to add two new cards:
1. Benefits for children 
2. Healthcare and health insurance

See this page in staging :https://staging.covid19.ca.gov/get-financial-help/

### WIC
Stakeholder feedback received about the **WIC program** affects the _Food resources_ page. We are tracking these edits in a separate ticket: #5577 . These are ready for review in [staging](https://staging.covid19.ca.gov/food-resources/#families-with-children) and can be published when approved (i.e., they are not dependent on anything else). 

### LIHEAP
Stakeholder feedback received about the **LIHEAP program** is being incorporated into the ticket to update the _Housing and rent_ page. See ticket: #5427 . These edits are available for in staging for review (look for "more help with utilities"). The rest of the page updates are not completed, but stakeholders are very welcome to start providing feedback as that assists with making the needed updates!

**Comment by LizNobriga** [comment]
I think everything in this ticket has been published!
