### ISSUE TITLE
Workers and businesses: add link for vaccine requirement for healthcare workers at correctional facilities

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5147]
Add link for [State and Local Correctional Facilities and Detention Centers Health Care Worker Vaccination Requirement](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Order-of-the-State-Public-Health-Officer-Correctional-Facilities-and-Detention-Centers-Health-Care-Worker-Vaccination-Order.aspx) under **Vaccination and testing requirements** on the **Workers and businesses** page. 

[Draft edits](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by LizNobriga** [comment]
These are the edits in the google doc:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/58706834/130486666-745ee570-2c49-49b8-9d8d-dde8fbce5eca.png">

**Comment by m-sullivan7** [comment]
I added one word. I think there's a difference between "correctional workers" and "correctional facility" workers. Even if "facility" gets added in someone's mind to "healthcare" I think it doesn't harm comprehension.

**Comment by LizNobriga** [comment]
Published
