### ISSUE TITLE
Sports and recreational activities - update Education and childcare page

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5194]
Proposed edits:
- Add link for [universal masking indoors at k-12 schools](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Requirement-for-Universal-Masking-Indoors-at-K-12-Schools.aspx)
~~- Update content for [Camps and supervised youth activities](https://covid19.ca.gov/education/#camps)~~
~~- Change H3 title~~
 ~~- Remove current content and links for day camps and overnight camps guidance~~
~~- Include link to new recommendations for organized recreational sports and activities that are not school-based (unless overnight?)~~
~~- Delete bullet "does not apply to youth sports" under the K-12 schools guidance~~
- Updates based on updated K-12 [guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/K-12-Guidance-2021-22-School-Year.aspx?_hsmi=140200600&_hsenc=p2ANqtz-8cZEb_WyPukRtJtsx8NMxG__AEFJMzo8KZP53waQeqSnjS6gpxm7iGyAbsQVE6hnFL5yRYJbA0frcDEJvW6lUn0LcHnA) and related [Q&A](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Schools-FAQ.aspx)

~~Proposed edits are based on the draft version shared via email.~~
~~This update is dependent on the content of the final version of these recommendations, and the timing of that release.~~

(FYI, more details about wearing masks during sports and rec activities are in the Masks [Q&A](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Face-Coverings-QA.aspx))

[DRAFT EDITS](https://docs.google.com/document/d/1CLJog8FLVz1yvs2MrZJ2ScOLgXEYpH9RydPIZ9Ze-z8/edit#)

**Comment by m-sullivan7** [comment]
No edits from me, @LizNobriga ! You nailed it in one!

**Comment by LizNobriga** [comment]
@mediajunkie I pinged you in slack yesterday to review these [draft edits](https://docs.google.com/document/d/1CLJog8FLVz1yvs2MrZJ2ScOLgXEYpH9RydPIZ9Ze-z8/edit#), but I realized I didn't assign this ticket over to you. Lmk if you have any feedback or questions.

**Comment by LizNobriga** [comment]
Updated issue summary and revised the edits based on the actual changes that CDPH published.

**Comment by mediajunkie** [comment]
Please stage this for review or let me know if it is already staged, thanks, @LizNobriga

**Comment by LizNobriga** [comment]
Edits are published
