### ISSUE TITLE
Mega-events page: align with page style template

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5195]
[DRAFT EDITS](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#)

**Comment by m-sullivan7** [comment]
Looks great Liz! No changes from me. 😄

**Comment by LizNobriga** [comment]
Hi @mediajunkie Could you review these [draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#)? We want to align this new page to follow our page style template. No substantial changes to content or meaning. Let me know if you have any feedback. Thanks!

**Comment by LizNobriga** [comment]
Edits are ready in staging

**Comment by LizNobriga** [comment]
Edits are now published
