### ISSUE TITLE
California Venues Grant Program - add to Workers and businesses page

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5199]
Proposed [edit](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit) to add this bullet under _[Financial help for businesses](https://covid19.ca.gov/workers-and-businesses/#financial-help-businesses)_:
- California Venues Grant Program (available between October 12 and 21, 2021)

Background:
> The California Venues Grant Program is set to launch in October. This program will provide grants in larger amounts to live-events spaces that could not open to the public in 2020 and 2021 and that gain most of their revenue through ticket sales and event promotion.
> 
> Grant amounts for this initiative will be based on the business’s gross earned revenue in 2019 and will be capped at $25 million. The application period will be October 12-22, 2021. More information about this new program will be announced soon.

https://business.ca.gov/coronavirus-2019/

**Comment by m-sullivan7** [comment]
Looks good to me! No changes.

**Comment by mediajunkie** [comment]
looks good. please publish.

**Comment by LizNobriga** [comment]
Published
