### ISSUE TITLE
Content Request: include counties where State Hospitals in our list

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#52]
### Request 
It would because it would be very helpful to include counties that our hospitals are in and then we can link directly to this ‘one stop’ website. DSH can benefit from this!  

https://dsh.ca.gov/
Under Hospitals

The cities are Patton (San Bernardino Co), Norwalk (LA Co), Coalinga (Fresno Co), Atascadero (San Luis Obispo Co) and Napa (Napa co)

Contact: crystal.favareille@chhsinnovation.com 

### Question
What is the need on this?  I'm not clear on the need.

**Comment by abquirarte** [comment]
Context: At DSH we have the 5 hospitals that serve our patients with mental health disorders. Our hospital staff do not have the same resources as hospitals treating ‘physically ill’ patients (or so they feel) even though we also treat physically sick individuals with mental health disorders. We are trying to provide local updates to our staff as well as family members of patients and loved the roll out of the website but realized that the counties that the hospitals are in, are not listed (which is good because it means they aren’t as impacted yet). We want to provide our hospital worker with local resources in these time of needs.

**Comment by m-sullivan7** [comment]
Closing this issue as will not do.
