### ISSUE TITLE
standardize naming conventions for documents needing translations moving forward

### ISSUE THREAD

**Issue by orielgomez** [cagov/covid19#522]
To ease our translations efforts for documents on the site, use the following convention for translations moving forward :
 - name of document - language code

Ex: for Tagalog immigrant guide : COVID_immigrant_guidance-tl

**Comment by aaronhans** [comment]
The first use case is making the links inside the immigrant guide pages point to the translated versions of the pdfs

What if we created a table-data which recorded the urls of the english version of any pdf that was also available in all other languages.
Then al 11ty build step could replace that url with a translated pdf url when processing a non english post

@carterm let us know if you have a better idea

**Comment by aaronhans** [comment]
We consulted and implemented an 11ty filter which does the following:

- Looks for image or pdf link with urls starting with files.covid19.ca.gov and ending with --en.(pdf,png)
- When the url pattern is found in a translated page the corresponding language code file extension is checked for on our binary file server files.covid19.ca.gov
- If a relevant translated file is found the url is replaced in the HTML document during the 11ty build process that runs on every change in github

The result is that if we have a localized pdf or image file on our binary file server we will link to it reliably and the link will survive manipulation by our translation partners.

**Comment by aaronhans** [comment]
This task is complete, dynamic file linking instructions have been added to the https://github.com/cagov/covid-static readme
