### ISSUE TITLE
trackerbox 3.0 fit and finish (design QA)

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5234]
A few things I noticed that need attention. First for @adam-little and then for @jbum 👍 

@adam-little
- [x] at certain widths, vertical baseline grid rhythm is breaking because text is wrapped and stacking. I think the like elements should vary in the same height row of the grid though I'm not sure of the CSS logic to align things as such, but mainly please look at that and give @jbum guidance on how to handle this situation: 
![image](https://user-images.githubusercontent.com/3227378/132542429-2486ba4d-df50-446c-8b28-ea69f16472f1.png)
- [x] also please note that the box titles are orange in the live prototype right now, which matches the existing site design but which does not match your figma (below), so please clarify your intent there
![image](https://user-images.githubusercontent.com/3227378/132543035-8d597403-1944-461f-9599-5913c2152afe.png)
- [x] then assign back to @mediajunkie plz

@mediajunkie 
- [x] update spec details in ticket based on adam's answers and guidance above
- [x] assign to @jbum 

@jbum 
- [ ] implement grid guidance for layout situation per Adam's comments below
- [ ] change box headings from orange to white (on state dash -- keep them white on home page) 
- [ ] Make the key numbers in fine print above the sparklines **boldface** (as in the mock above and on the current site).

Note: did not add these items to QA sheet.

**Comment by adam-little** [comment]
**Re: box width -**

I think i'm aligned with @mediajunkie on your recommendation. Ideally, each element (title, large stats, small stats, chart) has the same height across all 4 blocks. Each element's height matches the height of the tallest element across the four blocks.

Example with no text wrapping:
![image](https://user-images.githubusercontent.com/69167298/132559903-f21b774d-d573-4eed-a044-21d36433956f.png)

Example with text wrapping:
![image](https://user-images.githubusercontent.com/69167298/132559953-bbcc66d3-26d5-4309-9b57-b77c1ce57b0a.png)

**Re: Title colors -**

The box titles on the homepage are white. That's the version I have been mocking up in Figma. 

The box titles on the State Dashboard are orange. That's the version Jim has been updating.

If we were to pick one color for the box titles, I recommend white.

**Comment by mediajunkie** [comment]
for the last point sounds like there are two choices, @adam-little :

1. follow the existing style sheet
2. change the state dash titles to white

We can do either. It's your call!

**Comment by mediajunkie** [comment]
@adam-little says to change state dash to white titles too:
![image](https://user-images.githubusercontent.com/3227378/132562719-3a87170b-79a5-48d9-9467-89f799309d7c.png)

**Comment by jbum** [comment]
I think this is working now...
