### ISSUE TITLE
Workers and businesses: masking at work

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5237]
Consider including the [Cal/OSHA announcement](https://www.dir.ca.gov/DIRNews/2021/2021-86.html) encouraging workplaces to follow updated CDPH mask guidance recommending masks indoors on the Workers and businesses page.

@thepegisin has proposed edits to add masking at work content into this page (under Preventing COVID-19 in the workplace). 

[DRAFT EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by LizNobriga** [comment]
cc @m-sullivan7

**Comment by m-sullivan7** [comment]
As usual @thepegisin is a master of improving content! This all looks great. 😄

**Comment by LizNobriga** [comment]
Edits are now published
