### ISSUE TITLE
Get financial help: card design

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5243]
### Use card design for the Get financial help page
Card design [draft doc](https://docs.google.com/document/d/14t7gyGTN9VFDuOzPXUSpIAPur1JPTR-V_pK7vwLqyRo/edit#) for the **Financial help** page
- Uses card design without images
  - With this many cards and rows, photos may not be useful
  - A lot of stock photos on one page can appear gimmicky
  - It affects page performance
  - Hard to represent ideas like insurance and mortgage

Tasks needed prior to external review:
- [x] Draft out content (toplines for each topic) - TY @thepegisin for this lift!! :muscle:
- [x] Internal review (Christian, Angie, Content team, Clara)
- [x] Consult Adam for images and overall design
- [x] Launch pages described in #5142 

:arrow_right:This ticket is dependent on #5142 (:octopus: multiple page update effort). :arrow_left:

It also partially addresses #4967 (paying covid medical expenses) by adding **Healthcare and health insurance** content.

**Comment by abquirarte** [comment]
I like where this is headed!

**Comment by LizNobriga** [comment]
Published
