### ISSUE TITLE
Vaccination progress data: content overhaul

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5250]
Review _Vaccination progress data_ and think about ways to better present this information.

Content edits agreed to with @mediajunkie :

- Change title to _Vaccination data_
- Edit opening statement
- Update header _Overview of vaccine administration_ to _Statewide vaccination data_
- Update _Vaccination status by group_ to _Vaccinations by age, race and ethnicity, and Vaccine Equity Metric_
- Add link to digital vaccine record content

**Comment by m-sullivan7** [comment]
[One hour investigation](https://docs.google.com/document/d/1HzAmumTo7E-d-YETnOFaVTRRB557RTzhePpgxrQvzmE/edit) results.

**Comment by abquirarte** [comment]
cc @adam-little FYSA.

**Comment by m-sullivan7** [comment]
@mediajunkie I modified the [Google Doc](https://docs.google.com/document/d/1HzAmumTo7E-d-YETnOFaVTRRB557RTzhePpgxrQvzmE/edit?usp=sharing) to break out recommendations by what content can do now and what we'd need help with. Some of these changes would require engineering work that I suspect is significant. Let's discuss how ambitious we want to be with these changes.

**Comment by m-sullivan7** [comment]
@mediajunkie Here's the [phase 1 content changes](https://docs.google.com/document/d/1D4_8M4zoxUQhL8oXfFDtDfjK2umEv5Iw_98-Wf8BC4w/edit?usp=sharing) we discussed in Google Doc draft.

**Comment by mediajunkie** [comment]
Edits look good. Added a comment asking about location of the digital vax record link

**Comment by mediajunkie** [comment]
This seems to be relatively straightforward, with no substantive content
changes. Perhaps the title is the most noticeable change. I think I can
primarily just inform the vax task force and CDPH comms folks vs. get their
approval, so please go ahead and stage when ready.

**Comment by m-sullivan7** [comment]
[Staged](https://staging.covid19.ca.gov/vaccination-progress-data/) and ready for sharing externally. Would a Word Doc showcasing the differences be helpful?

**Comment by mediajunkie** [comment]
Yes, please!

**Comment by m-sullivan7** [comment]
Changes published after approval from CDPH
