### ISSUE TITLE
Food page: make it easier to find food benefits

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5268]
People are asking for info that is already on this page. This may indicate that they use anchor links to jump to certain sections specific to a population, like children or older adults, and miss benefits available to everyone at the top of the page.
Improve H2s based on page feedback. Improve overall content using Hemingway. 
[DRAFT EDITS](https://docs.google.com/document/d/1EgcLVV67fgdYtXVmTuSxIyBu-a3bbo1CtuhIZCLPF2s/edit#)

- [x] draft
- [x] internal review Michael
- [x] internal review Christian
- [x] stage
- [x] external review
- [x] revise
- [x] approve
- [x] publish
- [ ] notify stakeholders

**Comment by m-sullivan7** [comment]
This is a really thorough set of revisions Liz! I like what you're doing a lot. I made some edits that, compared to the whole, are pretty small.

**Comment by mediajunkie** [comment]
These edits look good to me.

**Comment by mediajunkie** [comment]
Swirlbase says the stakeholders are Alexis Fernandez and Cassie Wagner (DSS) -- does that sound right, @LizNobriga

**Comment by LizNobriga** [comment]
@mediajunkie Alexis is the branch chief and we've typically worked directly with managers from her branch that handle different areas. This includes Kathy Yang for CalFresh, Cassie Wagner for CalFresh for college students, Hares Rahimzei for Pandemic-EBT, and Brian Kaiser for food banks and food boxes.

**Comment by LizNobriga** [comment]
The Food page edits are in staging.

**Comment by abquirarte** [comment]
Nice email to stakeholders!

**Comment by LizNobriga** [comment]
@m-sullivan7 The latest revisions incorporate feedback from stakeholders to the section for older adults ([staging](https://staging.covid19.ca.gov/food-resources/#older-adults)). I think you saw the revisions to P-EBT but not this section.

**Comment by LizNobriga** [comment]
@mediajunkie I think we are ready to publish and notify stakeholders. Sound good to you?

**Comment by LizNobriga** [comment]
Published ~10/11/21. Closing ticket.
