### ISSUE TITLE
Equity chart cosmetic review

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5278]
@jbum (+as needed @adam-little ) to provide guidance re legend placement issues.

**Comment by zakiya** [comment]
https://covid19.ca.gov/equity/

When user hovers over lines that are close together, labels are difficult to read. 

![CleanShot 2021-09-14 at 10 34 13](https://user-images.githubusercontent.com/915352/133306269-1800ecb6-e732-4105-857b-f976090742c5.png)

**Comment by zakiya** [comment]
@mediajunkie Closing as this is done.
