### ISSUE TITLE
Workers and businesses: Q&A for vaccine requirement for healthcare workers in correctional facilities

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5284]
Add link to CDPH's [Q&A](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/State-and-Local-Correctional-Facilities-and-Detention-Centers-Health-Care-Worker-Vaccination-Requirement-Order-FAQ.aspx) about the vaccination requirement for healthcare workers in correctional facilities and detention centers to the **Workers and businesses** page

**[draft edits](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)**

**Comment by m-sullivan7** [comment]
This looks good Liz. No changes from me!

**Comment by LizNobriga** [comment]
@mediajunkie This edit is a small change to add the new Q&A to the Workers and businesses page.

**Comment by LizNobriga** [comment]
Edit published
