### ISSUE TITLE
Outstanding actions from usertesting.com 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#529]
Team, please document actionable improvements based on user feedback here. 

- [x] Drop down list for the Get local info page: county list

- [x] "How you can help" (except maybe health corps sign up) should be lower on the home page - does not seem as important as other info

- [ ] Many people felt like the pages are very text heavy - suggestion of graphs or other visuals

- [ ] Emotional health page: simplify, create bullets or break up the text, this page does not abide by our content guidelines

- [x] Update public places info: at least revisit the why is everything canceled content

- [ ] Financial help page: follow PD's advice and organize this by needs

- [ ] Financial help page: under California Eviction Moratorium - link to how someone can find a legal aid provider

- [ ] Financial help page: use simpler term than forbearance

- [ ] Get financial help, we still have 90 and 60 days, we need to add date from when something is owed/due or 90 from ST order

**Comment by KaylaPrusia** [comment]
Public places and related cancellation question have been removed via replacement of public recreation page

**Comment by KaylaPrusia** [comment]
@abquirarte, for your review, updates made to the Get Local information page to address box 1 (reviewed by @thepegisin): 
Hemingway score: Grade 6
[Get Local Information Staging doc](https://docs.google.com/document/d/1gh80uDfdtHmmM79T_NfaQ8B6tqXUtS0xCtf1FOuepoE/edit#)

**Comment by abquirarte** [comment]
👍 reviewed. Added one question. Go ahead and push!

**Comment by abquirarte** [comment]
@LizNobriga did we do this one?

- [ ] Get financial help, we still have 90 and 60 days, we need to add date from when something is owed/due or 90 from ST order

**Comment by LizNobriga** [comment]
@ashleydraper is taking a look at this

**Comment by ashleydraper** [comment]
@abquirarte @LizNobriga 

Need clarification on the ask here. The [Executive Order](https://www.gov.ca.gov/wp-content/uploads/2020/03/3.27.20-EO-N-37-20.pdf) states that protections are in effect through May 31st. Does that mean that property owners and renters will have 60 days from May 31- rather a due date of July 31, 2020 to make their payments?

I can draft changes in the staging doc with this understanding, or if the SME has more context around the issue, that would be really helpful.

**Comment by abquirarte** [comment]
I think we want to add clarifying language. The current page says: 
![image](https://user-images.githubusercontent.com/9556188/83219888-672c3100-a126-11ea-9238-92f38a949cdc.png)

90 days from when? From the EO? 

I'll send this page to SME for more context. Unless you have a draft (even with current content and our questions/suggestions) that I can send them!

**Comment by abquirarte** [comment]
Outdated. Some of these have been made or will be made with future guidance coming.
