### ISSUE TITLE
State dashboard: vaccinated/unvaccinated death data content

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5295]
Publish new content around the launch of death data by vaccination status.

The content will be updated in [this Google Doc](https://docs.google.com/document/d/1F25QPNVPBi3zVAOxdDjhSjJGC0tiwCqr5GyYd5JuXyg/edit?usp=sharing).

**Comment by jbum** [comment]
Launched Wednesday 9/29

**Comment by m-sullivan7** [comment]
Thanks for closing on my behalf Jim!
