### ISSUE TITLE
State Dash postlaunch

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5299]
_Post-launch:_

**Trackerbox iteration**
- [x] Need to translate new strings
- [x] Update Tests box's sparkline bars when daily tests data is available
- [x] Potentially update weight of various data rows (decided against)

**Post vax chart iteration**
- [x] Move the note for the vaccinated vs. unvaccinated chart into a Chart information drawer (for consistency with the other charts on the page)
- [x] Consider cross-linking to CDPH's [page on post-vaccine cases](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Post-Vaccine-COVID19-Cases.aspx)

**Open Data Portal (ODP)**
- [x] Help get postvax data tables added (via Brooke & Brendan) 
     - [x] Staged (get link from Brooke to preview)
     - [x] Published
- [x] Do we need to add something for the daily test positivity data provided in tracker Tests box (NO)

**Data & tools**
- [x] Add new data dictionary for cases by vax status
- [x] Review data dictionary approach to tracker boxes

**Vaccination progress data page**
- [x] Cross-navigation updates?
- [x] Consider adding tracker box(es) here?

**Comment by m-sullivan7** [comment]
@mediajunkie I'd like to request an addition to this list: moving the note for the vaccinated vs. unvaccinated chart into a _Chart information_ drawer for consistency with the other charts on the page. I think this would be easy to do (I might even be able to do it with just an engineer review of my work in WordPress) and it would make it easier to add additional info, like CDPH's request that we consider linking to their page on [post-vaccine cases](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Post-Vaccine-COVID19-Cases.aspx).

**Comment by mediajunkie** [comment]
agreed!

would the info drawer be the best place for a link to CDPH's Q/A's? That seemed more like something for the main paragraph to me.

**Comment by m-sullivan7** [comment]
We always run a risk that people leave a page when we introduce a link. CDPH's page is more of a deep dive, especially because it starts with what, how, and why instead of foregrounding data like the chart. It comes down to how important we feel CDPH's information is. Once we set that priority, I think it'll be clear what the best place for it is (if we want the link on the page).

**Comment by m-sullivan7** [comment]
Published chart information accordion with CDPH link.

**Comment by abquirarte** [comment]
Can we better identify the blockers here so we can unblock?
