### ISSUE TITLE
Resume weekday reporting for cases, tests, and deaths.

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5345]
When: as of Saturday, September 25

Data changes (@jbum & Satya for ESS/CDPH):
- [x] for covid pages, none expected
- [x] CDPH has questions about the date of their case statement

Content changes (@michael-sullivan):
- [ ] add approved language to footnote for tracker box on state dashboard page
- [ ] find out whether to add immediately or on Friday
- [ ] Add note above chart ahead of change (similar questions re timing)

Pipeline:
- [ ] @jbum & @mediajunkie to monitor Saturday a.m. for unanticipated pipeline bugs

**Comment by m-sullivan7** [comment]
Content changes also being tracked in https://github.com/cagov/covid19/issues/5338
