### ISSUE TITLE
Add COVID-19 hotline number to the footer

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#535]
- Remove "Statewide COVD-19 Hotline" from footer.
- On new line, put "COVID-19 hotline: 1-833-422-4255 M-F 8AM-8PM, Sa-Su 8AM-5PM" 
- Make hotline number a dialable link
- Link [https://covid19.ca.gov/hotline/]((https://covid19.ca.gov/hotline/)) to **Hotline information** menu item in new IA and rename that **COVID-19 hotlines**

**Comment by TamaraIDEJA** [comment]
This is GREAT! Thank you @thepegisin for trying to make hotline info more prominent!

**Comment by abquirarte** [comment]
@artuoma can you do this? or Konstantin? 
I would try it, but don't want to break the site.

**Comment by artuoma** [comment]
Yeah we can have @koryfey try to see if there is any issues working within the established process.

**Comment by abquirarte** [comment]
perfect :) I thought about tagging him.

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by artuoma** [comment]
@kkoryfan

**Comment by kkoryaka** [comment]
Added changes to staging. Please review.

**Comment by abquirarte** [comment]
Am I looking at the wrong staging? 
https://as-cdt-pub-acovid-w-p-001-staging.azurewebsites.net/

**Comment by abquirarte** [comment]
Thank you so much @kkoryaka !

**Comment by abquirarte** [comment]
I may have closed it too early. Staging looks good. We should push to production @kkoryaka 

CC: @artuoma

**Comment by kkoryaka** [comment]
I have made the pull request to the master. Now we have to wait when someone reviews it and make it live.

**Comment by thepegisin** [comment]
It's live and looks great. Thanks, @kkoryaka! Closing this now.

**Comment by abquirarte** [comment]
Yay!!
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>
