### ISSUE TITLE
Apply grid to tracker box

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5391]
At narrow widths, text wrapping is making trackerbox content appear at different heights:
![image](https://user-images.githubusercontent.com/3227378/134955567-0b615da7-83e5-4527-b536-4c07742a62d3.png)

In the above image the white boxes show where each segment should land and the yellow boxes and numbers shows elements that are out of the desired position.

**Comment by mediajunkie** [comment]
@jbum fyi

**Comment by zakiya** [comment]
Closing since it was worked on and merged by @jbum
