### ISSUE TITLE
Workers and businesses: new PHO requiring workers to be vaccinated

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5403]
Update the Workers and businesses page to reflect changes in the new public health order requiring workers to be vaccinated

[Adult Care Facilities and Direct Care Worker Vaccine Requirement](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Order-of-the-State-Public-Health-Officer-Adult-Care-Facilities-and-Direct-Care-Worker-Vaccine-Requirement.aspx) - September 28, 2021

[DRAFT](https://docs.google.com/document/d/1AVEw98OWlVYveDqTbXcXiej1oJSG66g4Z4qBZqlVXNQ/edit#)

**Comment by mediajunkie** [comment]
Changes looks straightforward. Let's publish and I'll update involved folks along with telling them about the Vaccines page updates.

**Comment by LizNobriga** [comment]
@mediajunkie I made more edits to help improve readability, but we'll revisit this in the next update. Publishing now.
