### ISSUE TITLE
Update handbook to include adding/removing pages to PPF report

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5417]
Update to [covid internal handbook ](https://teamdocs.covid19.ca.gov/teams/content/)- process for adding/removing pages to content analytics report to collect page feedback

**Comment by m-sullivan7** [comment]
Added to the internal handbook at https://teamdocs.covid19.ca.gov/teams/content/editing.html#restoring-posts-or-reusing-url-slugs

**Comment by LizNobriga** [comment]
@m-sullivan7  I made an update to the steps for reusing a URL slug.
