### ISSUE TITLE
Financial help for businesses: EIDL program and other page updates

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5426]
[Draft](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) edits in progress to use page style template and make updates to content
Draft edits now include changes to the COVID-19 EIDL program that take effect Jan 1, 2022. 

Proposed edits to:

- Update page style to align with standards
- Update covid-19 EIDL program changes effective Dec 31, 2021
- Add content for:
  - Covid-19 disaster relief loan guarantee
  - Homeless Hiring Tax Credit, Dream fund, Rebuilding fund, Microbusiness covid relief grant, Performing arts grants, and sign up for updates from CalOSBA (mostly stakeholder requests)
- Remove outdated content (programs no longer available):
  - CA small biz covid-19 grant program
  - Shuttered venue operators grant program

- [x] Draft edits (Liz)
- [x] Internal review (Michael)
- [x] Stage (Liz)
- [x] Stakeholder approvals (Christian)
- [x] Publish (Liz)

**Comment by LizNobriga** [comment]
Using this ticket for changes that take effect January 1, 2022 to the federal COVID-19 economic injury disaster loan (EIDL) program. 

[Draft edits](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) include EIDL changes, and also update page content and style.

**Comment by LizNobriga** [comment]
@m-sullivan7 Can you do the internal review next? 
[Draft edits](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#)

**Comment by LizNobriga** [comment]
Background info from U.S. SBA email (news@updates.sba.gov):

SUBJECT: EIDL loan: there are only two actions that stop on Dec. 31

There are only two actions that stop on Dec. 31:
- SBA will no longer accept new applications for [COVID EIDL](https://www.sba.gov/funding-programs/loans/covid-19-relief-options/eidl/covid-19-eidl) loans and advances and
- SBA will no longer process applications for the [supplemental targeted advance](https://www.sba.gov/funding-programs/loans/covid-19-relief-options/eidl/targeted-eidl-advance-supplemental-targeted-advance) 

1. SBA will continue to process applications received on or before Dec. 31 until funds are exhausted, including: 
- Pending loan applications, loan increase requests, applications in reconsideration/appeal
- [Targeted advance](https://www.sba.gov/funding-programs/loans/covid-19-relief-options/eidl/targeted-eidl-advance-supplemental-targeted-advance) applications and reevaluation requests 

2. You can still make certain requests after Dec. 31 including:

- Requesting more funds
  -  If you need additional funds and have not reached your maximum loan amount that you are eligible for SBA will accept requests for loan increases for up to 2 years from the origination date of your first loan, or until funds have been exhausted. 
- Request reconsideration of a declined loan
  - You have up to 6 months from the date of decline to request reconsideration, or until funds are exhausted. 
- Request an appeal of a declined reconsideration request 
  - You have up to 30 days from the date of the declined reconsideration request to request an appeal, or until funds are exhausted. 
- Request reconsideration of a declined targeted advance decision 
  - You have up to 6 months from the date of decline to submit one request reconsideration, or until funds are exhausted.

What should you do?  

If you have already applied: 

→Don't panic and be patient. There are still billions of dollars in funds available 

→Be thorough and responsive. Monitor your portal and emails for actions and requests from SBA. When requesting reconsideration on a decline, take the time you need to craft a clear and thorough response with adequate supporting documentation. 

→Do get help. Tap into SBA's network of resource partners who can provide assistance at not cost to you. They can help you understand what is required, review your documents, and help you respond to the SBA as needed. craft a response. [Find a business advisor near you](https://www.sba.gov/local-assistance).

If you have not applied:

→ If you've been thinking about applying but haven't, don't wait any longer - [apply now](https://covid19relief.sba.gov/#/)!

**Comment by m-sullivan7** [comment]
Left some first draft edits, Liz. Looks like a full overhaul of the page!

**Comment by LizNobriga** [comment]
@m-sullivan7 Edits look great, thank you!

**Comment by LizNobriga** [comment]
@mediajunkie The COVID-19 EIDL (loan) program stopped accepting new applications on Dec 31, 2021, so we need an update to that content on the Financial help for businesses page. These [draft edits ](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) also update the rest of the page (remove outdated content and update remaining content), improve readability, and align with our page style format.
Let me know if I should stage these edits before further review.

**Comment by mediajunkie** [comment]
yes these look good to stage
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you take a look at this page in [staging](https://staging.covid19.ca.gov/business-and-employers/) and share any additional feedback?

**Comment by m-sullivan7** [comment]
I like the approach.

From a design-perspective, I don't like how the sub-bullets get a break added between them. It adds unneeded space (that might hinder comprehension). That's a styling issue, and one I could live with. The alternative would be to collapse those sub-bullets into the main ones like so:

- More funds. You have up to 2 years from the start of your first loan to request a loan increase.
- Reconsideration of a declined loan. You have up to 6 months from the date of decline to request reconsideration.
- An appeal of a declined reconsideration request. You have up to 30 days from the date of the declined reconsideration request to request an appeal.
- Reconsideration of a declined targeted advance decision. You have up to 6 months from the date of decline to request reconsideration.

**Comment by LizNobriga** [comment]
Agree! Good catch.

**Comment by LizNobriga** [comment]
@mediajunkie The [edits](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) for **Financial help for businesses** are ready for stakeholder review. I think GO Legal and GO-Biz, right?
Page with edits  in [staging](https://staging.covid19.ca.gov/business-and-employers/).

**Comment by LizNobriga** [comment]
@m-sullivan7 Can you review this round of [edits](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#)? This incorporates all of the stakeholder requests we discussed last week.

**Comment by m-sullivan7** [comment]
I left some thoughts! Good job with it!

**Comment by LizNobriga** [comment]
@mediajunkie We revised our [edits](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) to incorporate the feedback from stakeholders. [Staging](https://staging.covid19.ca.gov/business-and-employers/) is updated with these changes. 

Stakeholder suggestions were to add:

- Homeless Hiring Tax Credit to the Tax credit section
- New section for Grants with 3 grant programs
- CalOSBA newsletter sign up

In addition, for each grant program, we've tried to find the best place/link to send people looking for more info or where to apply. 

We've also added the California Rebuilding Fund in the Loans section.

**Comment by LizNobriga** [comment]
@mediajunkie Are stakeholders good with how we incorporated their suggestions to Financial help for biz page?

**Comment by LizNobriga** [comment]
@mediajunkie Incorporated stakeholder feedback to the COVID-19 EIDL content. See [draft](https://docs.google.com/document/d/1DfMh04qNBA4xn1vHJw0vPnTIN5yEGvyuqM8vbKU5ZxU/edit#) and [staging](https://staging.covid19.ca.gov/business-and-employers/). 
CC @m-sullivan7

**Comment by LizNobriga** [comment]
Published
