### ISSUE TITLE
Housing and rent: update content

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5427]
Updating content on **Housing and rent** to reflect program updates and page feedback.

Proposed edits to:
- Add new content for:
  - Mortgage relief program
  - Affordable rental housing
- Update content in these sections:
  - Help for people experiencing homelessness
  - Eviction protection
  - Rent and utilities
  - Mortgage forbearance

[Draft edits](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit#) in the google doc, and also in [staging](https://staging.covid19.ca.gov/housing-and-homelessness/)

Recent page feedback:
- help for mortgage payments past due after 12/31/2021
- help with mortgage

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you review a new section for utilities? I'll tag you at the start. 
[Draft edits](https://docs.google.com/document/d/1pQM5euvY_p2btONcEDoLt9mG6FVdu_XD-IbIlsc7uE4/edit#heading=h.2zwwf8x2h6fa)

**Comment by m-sullivan7** [comment]
Left a few edits. Great work Liz!

**Comment by LizNobriga** [comment]
Utilities content is in staging. Updates to other sections are still in progress.

**Comment by LizNobriga** [comment]
Published LIHEAP utilities edits. Other edits to this page still in progress so we'll keep this ticket open.

**Comment by LizNobriga** [comment]
FYI @m-sullivan7, I added content for the CA mortgage relief program to the [draft](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit#heading=h.c4836wull60q). **Who qualifies** needs more work but sharing it early for feedback. Also updated some content in other sections in the draft.

**Comment by m-sullivan7** [comment]
Wow, such huge edits! I left some edits and one question where I'd like to make sure I understand the process and will have some more edits once I've got that. I'll leave the assignment on me for the moment. 🙂

**Comment by LizNobriga** [comment]
I think I got to all of them now.

**Comment by mediajunkie** [comment]
who needs to approve this?

**Comment by LizNobriga** [comment]
@m-sullivan7 I needed to revise the mortgage relief program content because the link for 'create your profile' was not working anymore. Can you review it? (No changes to the bullets under the Who qualifies H3.)

Find the revised [edits](https://docs.google.com/document/d/14RZSitqD_RXyJqGfUU1lRUcgwu0C6Ox941msBF4fA7s/edit?pli=1#) in the google doc. The page is also in [staging](https://staging.covid19.ca.gov/housing-and-homelessness/) now because it's easier to see what it looks like.

I also made readability edits to:
- People experiencing homelessness H2, bullets for National Domestic Violence Hotline
- Temporary housing for Project Roomkey H2, bullets for people at high-risk for COVID-19
- Details for renters H3 (under Help with rent and utilities H2), second bullet and sub-bullets
- Eviction protection section (content prior to the first H3)

Let me know if anything else comes to your attention that we want to address before stakeholder approvals begin. 

Thanks!!

**Comment by m-sullivan7** [comment]
The Google Doc link goes to _Safety in the workplace_. I dug up [this Google Doc](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit) instead and saw edits from you yesterday. Hopefully that's the right one to have looked at!

The readability edits looked good! No changes from me.

On the mortgage relief section, I left two suggestions where I saw opportunities to be simpler. Otherwise it was great!

**Comment by LizNobriga** [comment]
@m-sullivan7 I made two more changes and tagged you with comments to make them easy to find.

**Comment by m-sullivan7** [comment]
Additional link looks good.

I found the first sentence a bit tough to understand. What do you think of the proposed revision to reorder it? I also had one suggestion and a maybe thought in a note.

**Comment by LizNobriga** [comment]
@mediajunkie The update to the **Housing and rent** page is ready for you to review and move forward. 

Here are the links to the [draft edits in the google doc](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit#), and to the [staged page](https://staging.covid19.ca.gov/housing-and-homelessness/). 

We also talked about tracking down the email threads from around Oct/Nov 2021 to figure out the most recent stakeholders connected to the programs and content on this page. I'll send you a slack with a specific name.
Let me know if I can help with anything else.

**Comment by LizNobriga** [comment]
Checking in on this one. Any updates from stakeholders? @mediajunkie

**Comment by LizNobriga** [comment]
@mediajunkie Have we heard from stakeholders for the Housing page updates?

**Comment by LizNobriga** [comment]
Approved to publish via email. Updates are live!
