### ISSUE TITLE
Update to Current safety measures adding link to translated COVID-19 guidance

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5441]
Realized today that CDPH's [COVID-19 Guidance in More Languages](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/COVID19MultilingualDocuments.aspx) is not linked anywhere in our site. Proposed the best place I could think of, which is in **Current safety measures**. This would then be accessible to people who speak other languages once the updated page is translated.

@mediajunkie , draft for your approval: https://docs.google.com/document/d/1AUcqlSFcKZ0DCbTN0o3gko-7dfCdcXg4rZ0UbVJJZCc/edit

**Comment by mediajunkie** [comment]
This looks good. Please go ahead and publish.

**Comment by thepegisin** [comment]
Staged and published 10/6/21.
