### ISSUE TITLE
Add links to county variance page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#545]
Under County Variance (website: https://covid19.ca.gov/roadmap-counties/)

Please update the hyperlink on “county guidance” with the following link (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/County_Variance_Attestation_Form.aspx)
 

Please update the hyperlink on “ Learn more information on county variance criteria and to how to apply.” with the following link (https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/County_Variance_Attestation_Form.aspx)

**Comment by ashleydraper** [comment]
Done. Is there any reason that we are linking to this twice though? 
@abquirarte

**Comment by ashleydraper** [comment]
Added- 
**San Diego County:** call 1(800) 339-4661, or visit: https://www.sandiegocounty.gov/content/sdc/hhsa/programs/ais/sdgreatplatesdelivered.html
**City of Oakland:** call the voicemail system at 510-238-FOOD (3663), email: greatplates@oaklandca.gov, or visit https://www.oaklandca.gov/resources/great-plates-delivered-city-of-oakland
**Santa Cruz County:** call (831) 454-4406 or email hsd_greatplates@santacruzcounty.us.
**City of Solvang:** call (805) 588-5019 or email crystal@syvphp.org
@TamaraIDEJA @abquirarte

**Comment by abquirarte** [comment]
Thank you @ashleydraper !
