### ISSUE TITLE
Clean up of visual design for data page navigation blocks

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5456]
@adam-little highlighted two design fixes needed for the data pages in conjunction with the deployment of the card block at the bottom of each page.

There are two issues:

1. We want to remove the dividing line between the white and light blue.
2. We want to remove the white gap between the bottom of the light blue block and the beginning of the dark blue footer.

Both can be seen in this screenshot.

![image](https://user-images.githubusercontent.com/69169190/136288806-bdb4e31e-8629-4cee-b893-a0badc7c7d4e.png)

This affects:

- [State dashboard](https://covid19.ca.gov/state-dashboard/#more) (#1 may not need to be fixed here since the color is the  same as the preceding section. I trust @adam-little 's opinion on this.)
- [Health equity](https://covid19.ca.gov/equity/#more)
- [Vaccination progress data](https://covid19.ca.gov/vaccination-progress-data/#more)
- [Data and tools](https://covid19.ca.gov/data-and-tools/#more)

I attempted to fix both of these issues in WordPress, but was not successful.

**Comment by mediajunkie** [comment]
@jbum can you please either take this on or determine if it's something for @zakiya ?

**Comment by zakiya** [comment]
@m-sullivan7 @mediajunkie Ready for review at https://deploy-preview-4--nifty-turing-0ad445.netlify.app/state-dashboard/

2 Notes: 
I was able to eliminate some of the white space by deleting empty <br> tags in the markup>  However, WordPress also  creates a trailing empty <p> that can't be eliminated  from the UI as far as I can tell. I fixed it with a somewhat fragile hack.

Additionally, by default, all pages have a bottom margin on the main content area. This fix removes that margin specifically for these four pages. If any other posts have a blue bottom or if the slugs of these posts change, a dev will need to remove the margin.

**Comment by m-sullivan7** [comment]
That preview looks like it solves both issues as far as I can see. All looks good on my end, so I'll pass to Christian for his review. As always, thank you @zakiya !

**Comment by mediajunkie** [comment]
Looks good to me!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>
