### ISSUE TITLE
Quick Answers and the Call Center

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#546]
Our quick answers knowledge base has the potential to help the call center process because we can track changes to any questions and answers that we are scraping from our website. 

We have the following action items:

- [x] Compare our Knowledge base of 123 Q&A pairs with the Call Center Q&A set
- [ ] ~~Identify the expected 70% of questions in the call center doc which correlate with the covid19.ca.gov site content~~ this was attempted but didn't work out
- [x] Verify that we can automatically recrawl and regenerate the Q&A pair for each item based on the covid19.ca.gov website
- [ ] ~~Test generate a diff document showing which questions were changed each day~~ we did create a spreadsheet export linked in the last comment but the github diff based on our tab separated dataset is not helpful

**Comment by hilaryhb** [comment]
@aaronhans just checked a couple of search terms that are highlighted in our stats and ones' I've seen surface via feedback. 

Most recent should be at top? or no?
<img width="744" alt="Screen Shot 2020-05-20 at 10 41 43 AM" src="https://user-images.githubusercontent.com/58703973/82479156-d8b11300-9a86-11ea-9ae0-ddecdc14cae4.png">

Travel  - we should have at least top 15 search queries with answers? 
<img width="759" alt="Screen Shot 2020-05-20 at 10 41 22 AM" src="https://user-images.githubusercontent.com/58703973/82479240-f7170e80-9a86-11ea-9607-25ac4272770d.png">

Childcare has a dup:
<img width="779" alt="Screen Shot 2020-05-20 at 10 41 11 AM" src="https://user-images.githubusercontent.com/58703973/82479282-05652a80-9a87-11ea-8e29-541bc395468c.png">

**Comment by aaronhans** [comment]
Thanks @hilaryhb yeah let's not test until we are ready.

- This project is only concerned with the quick answer section. The search results below the new quick answer sections use the google search widget which isn't being modified. There is probably a lot of room for improvement there though. We can work on that in a separate task.

Good questions about different topics:
- We have no quick answers on restaurants in the current knowledge base. Maybe great plates should be there. I'll see if that page wasn't crawled or a restaurant related Question and Answer couldn't be parsed from that.

- The childcare duplicate is interesting. It was generated because we have two accordions with the same heading on two different pages with slightly different content https://covid19.ca.gov/stay-home-except-for-essential-needs/ and https://covid19.ca.gov/get-financial-help/ 
I think adding the url the answer was scraped from will be helpful. Is it appropriate to remove one of the child care accordions? Should they have the same content? If we want them on both pages we could make sure only one of them is crawled. @thepegisin do you have any advice on the best way to solve the duplicate childcare question?

**Comment by aaronhans** [comment]
Here is an updated task list since first priority is releasing Quick Answers to production.

Initial goals:
- We want the quick answer data to be generated as much as possible automatically from site content so we don't create another content set to keep up to date
- We want to create a process where search interactions to inform content updates which improve quick answer quality

Immediate tasks:
- [ ] Create our own crawler which includes page title and nearest header in quick answer content 
- [ ] Combine crawled data with manually curated quick answers which are for now not site content based?
- [ ] Use new crawler + manual question set to overwrite knowledge base powering search
- [ ] Add page title as link back to answer source in quick answer search results UI
- [ ] Identify everything we need to track: searches with no associated quick answers, which accordions were opened for each query

Issues:
- Current crawlers create quick answers well from accordions but haven't yet been able to do so from other parts of pages. We could add classes or other hints to content to help the crawler...

**Comment by thepegisin** [comment]
> The childcare duplicate is interesting. It was generated because we have two accordions with the same heading on two different pages with slightly different content https://covid19.ca.gov/stay-home-except-for-essential-needs/ and https://covid19.ca.gov/get-financial-help/
> I think adding the url the answer was scraped from will be helpful. Is it appropriate to remove one of the child care accordions? Should they have the same content? If we want them on both pages we could make sure only one of them is crawled. @thepegisin do you have any advice on the best way to solve the duplicate childcare question?

Hmm. The childcare question on the Financial help page should be rewritten to answer it from a money standpoint. Maybe **Are childcare subsidies available?** The answer needs to be updated anyway, as it says childcare is only available to essential workers. @KaylaPrusia has Stay home, who has Financial help?

**Comment by LizNobriga** [comment]
@thepegisin [content captain assignments](https://docs.google.com/document/d/1zZI_NozHmONP6kdp_0t5gPhuWbb25sYeZbEkfHQReic/edit#)

**Comment by ashleydraper** [comment]
The "get financial help" is now updated with the childcare subsidies.

**Comment by LizNobriga** [comment]
We are aware of many duplicate accordions since the 'get financial help' page pulled Q&As from several existing pages.

**Comment by aaronhans** [comment]
@LizNobriga We hid the ~100 or so items in the scrape v2 dataset that we knew were incorrect. These did not resurface in the latest scrape.

The entire knowledge base dataset is now in the scrape v3 and v3 new tabs. The v3 orphans represents items from v2 which were not found in v3(minus the set of hidden items).

**Comment by aaronhans** [comment]
- [ ] Test adding classes into WordPress post to help scraper identify Quick Answer Q&A pairs that aren't in accordions

**Comment by abquirarte** [comment]
Documenting @aaronhans 's option for non-accordion content: 

Option 3 would require entering a custom HTML block in WordPress above the desired answer with code like:
```
<div style="display:none;" class="quick-answer-question-123">The text of the desired question</div>
```
The classname there uses a unique identifier "123" at the end which corresponds to all block elements with the quick-answer-answer-123 class on them. The content author makes up the unique ids
^ This scheme is easily scrapeable, just want to make sure we are choosing an option that isn't making authoring more annoying unnecessarily.

**Comment by aaronhans** [comment]
I was able to slightly simplify the classname and invisible element Quick Answer management:

- Every Quick Answer question or answer content needs to have the "js-qa" class
- Every Quick Answer question should also have the js-qa-question class
- Every Quick Answer answer should also have the js-qa-answer class
- The order of the elements on the page is important, all js-qa-answer elements will be associated with the nearest js-qa-question element above them. We often have multiple elements that comprise a single answer which is fine: Add the class js-qa-answer to each separate WordPress block element
- Using invisible elements for questions or answers is fine you can use code like `<div style="display:none;" class="js-qa js-qa-question">The text of the desired question</div>`

The unique identifiers I though were required are not necessary

**Comment by LizNobriga** [comment]
[Key word tags to add noted here](https://docs.google.com/document/d/1xPkj69V8a8On7C2rXLvWGlJC8Yzlcuvtj5fBAqILiSg/edit)

**Comment by LizNobriga** [comment]
Saving this here:
`<div class="js-qa-answer"><!-- some tags separated by spaces go inside this comment --></div>`

**Comment by LizNobriga** [comment]
And saving this:
This is a good example
First we need to add the desired question as an invisible custom HTML block above the answer:
`<div style="display:none;" class="js-qa js-qa-question">Can a doctor without California license work under the California Health Corps?</div>`
Then we have a choice:
An easy way to provide an answer would be to add the class js-qa-answer to both the standalone line element above the list and the full list element using the WordPress advanced section in the right sidebar when the block is selected. This would cause the entire list to be included as the quick answer content
If we only want bullets 4 and 5 to be the answer we are going to have to add the class js-qa-answer only to those list items which requires making the whole list a custom HTML element:
`<ul class="js-qa-answer"><li>Be 18 years of age or over</li><li>Be eligible to work in the United States</li><li>Have a valid driver's license or passport, and a social security card</li><li class="js-qa-answer">Have a valid California License for clinical practice (if you are a MD, DO, etc.)<strong>&nbsp;</strong></li><li class="js-qa-answer"><strong>OR</strong> are a medical resident or nursing student&nbsp;</li><li>Have no negative licensure/certification actions (for licensed/certified professionals)</li></ul>`

**Comment by aaronhans** [comment]
We've made a lot of progress on the quick answers on the website. We've made several refinements, are feeding data into google data studio showing which queries users are making that return quick answers and which ones don't. We are pulling data from site content that is not visible to users to add keywords and phrasing specific to the quick answers format while still basing the main content on the site's visible content.

Reviewing our quick answer dataset with the call center programmatically was a failure though. I extracted 87 questions from the call center doc but wasn't able to match any of them exactly to a question in our 200 set of quick answers. If we want to do this we will need to do it manually.

We do have this set of quick answers we can export anytime, is constantly updated by a rescrape process but the diff wasn't as easy to generate as I thought it might be

**Comment by aaronhans** [comment]
Here is the set of questions and answers we scraped recently https://docs.google.com/spreadsheets/d/1ecR3d15c-zxF8ayjNdoQoOZRVej400I4sxaAB3n_EXo/edit#gid=580270840

I don't see an easy way to merge our dataset with the call center but I am open to suggestions @TamaraIDEJA
