### ISSUE TITLE
Request: Self-screener 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#55]
https://myhealth.alberta.ca/Journey/COVID-19/Pages/Assessment.aspx 

Jen is trying to build a really simple version of this from a US perspective w/ a quick alliance that's been hacked together over the weekend, so she's not suggesting that you try to build it, but perhaps put it in the pipeline as the next step - a really simplified screener. the idea is to get people directed into self-help and not to flood testing sites. anyway -- stay tuned

**Comment by abquirarte** [comment]
@TamaraIDEJA anyone in Public Health working on this?

**Comment by abquirarte** [comment]
Update from Jen P (via Ryan) 

Self-assessment tool

A simple online tool that asks individuals their symptoms, assesses whether they need to be receiving healthcare right now, and directs them accordingly. The tool takes the public through a series of questions to inform those who are concerned they may have contracted COVID-19. The [tool is live](https://covid-19.ontario.ca/self-assessment/#q0) for the City of Ontario. Other[ governments can use this github repo](https://github.com/ongov/covid-19-self-assessment) to provide their own self-assessment tool on their official websites. Here is a list of several other tools. The [CDC also now has a chat bot accessible from their main COVID-19 page.](https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/steps-when-sick.html)

Link to doc: https://docs.google.com/document/d/15mqiYK3Kemk_i_bSux0shkK84tCD9flJkOJ5vKcs92o/edit

**Comment by abquirarte** [comment]
JP and

**Comment by cscairns** [comment]
hey all...the skylight team (https://skylight.digital/) has been working on a self-screener based on the CDC criteria...it's plain language and has undergone several rounds of usability testing...please let us know the best way to demo what we've done and how we can adapt for your needs

CC: @abquirarte

**Comment by abquirarte** [comment]
@cscairns thanks Chris! Is there a link that you can point us to? I would like to connect with our department of public health on this

**Comment by m-sullivan7** [comment]
Closing this issue as this is not a project we are pursuing.
