### ISSUE TITLE
Bring back the Holidays page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5514]
Needed a place to put Halloween guidance, and other gathering advice for winter holidays.

- [x] Check with @carterm that we can safely reuse /holidays slug
- [x] Remove /holidays slug and all translated versions of it from Page Redirect Table post
- [x] Create new _Holidays_ page based on [CDPH Halloween 2021 talking points](https://docs.google.com/document/d/13BlYcFn5hv-21H8EXwXnlOppWTra2L3l/edit)
- [x] Add **translate** tag
- [x] Get approval (@mediajunkie)
- [x] Stage
- [x] Publish
- [x] Add to menu

**Comment by abquirarte** [comment]
🥳
