### ISSUE TITLE
Vaccination progress data: update vaccinated denominator to 5+

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5519]
From CDPH:

> As the 5-11 age group becomes eligible, we will need to incorporate this group into our population denominator, moving  from 12+ to 5+ for eligible population.
> We will also be changing the DOF version from April to July. July DOF versions fixes the issue with the race ethnicity and age breakdown estimates.

This issue is to update [Vaccination progress data](https://covid19.ca.gov/vaccination-progress-data/) to reflect this change in reporting.

This includes adding links and data dictionary info to the [Data and tools](https://covid19.ca.gov/data-and-tools/) page, as appropriate.

**Comment by mediajunkie** [comment]
Beyond these pages and Peggy's vaccines page, let's please also scour the entire site for any possible reference to age 12 and up or similar copy that would require updating, including in Q/A's and even potentially PDFs.

cc @thepegisin @LizNobriga @jbum

**Comment by abquirarte** [comment]
Good call!

**Comment by m-sullivan7** [comment]
I did a search for `12` in Wordpress to find places that may need updates for 5-11 vaccination approval across the site. Beyond _Vaccines_, _Vaccination progress data_, and _Data and tools_ (which are already covered), here are the pages that I found:

- [Vax for the Win](https://covid19.ca.gov/vax-for-the-win/) (probably not affected, but calling out just in case) @thepegisin 
- [Current safety measures](https://covid19.ca.gov/safely-reopening/) (definitely affected) @thepegisin 
- [Education and childcare](https://covid19.ca.gov/education/) (probably not affected as I'm not aware of an extension of the vaccination requirement for students) @LizNobriga

**Comment by mediajunkie** [comment]
Thank you!

@thepegisin and @LizNobriga please let me know if you see the need for any
changes to Current safety or Education.

**Comment by m-sullivan7** [comment]
Potential highlight box copy:

> [b]Vaccination population updated[/b]
>
> On November 10, 2021, we updated the vaccines administered population denominator to include people 5 and older. As a result, the percentage of population vaccinated declined.

**Comment by mediajunkie** [comment]
Thanks! Will run this by CDPH, as they show the same info on their
trackerbox. They have also suggested considering not having a special note,
while being more clear about the definition of eligible in the data note.
Let's discuss.

-x-

Michael wrote:

> Potential highlight box copy:
>
> [b]Vaccination population updated[/b]
>
> On November 10, 2021, we updated the vaccines administered population
> denominator to include people 5 and older. As a result, the percentage of
> population vaccinated declined.
>
>

**Comment by mediajunkie** [comment]
shared draft with Carlos. I think CDPH doesn't love "we" -- they may
suggest change

**Comment by m-sullivan7** [comment]
All content updates are live. Will remove the note from homepage, state dashboard, and _Vaccination progress data_ on November 17.
