### ISSUE TITLE
Health equity: chart accordion width

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5555]
I noticed that one chart information accordion is the width of the paragraph text above the chart, rather than the chart it serves. All the other chart information accordions are the same width as the chart.

![image](https://user-images.githubusercontent.com/69169190/139287236-0f36281b-08a5-415a-bad5-b1e9f002d181.png)

When possible, can we change this chart information accordion to be the same width as the chart?

**Comment by zakiya** [comment]
@m-sullivan7 @mediajunkie Proposed changes to equity page here:

**Comment by m-sullivan7** [comment]
Looks great to me. Thank you @zakiya !

(I even spot checked a few other things this time around and found nothing. 😉)

**Comment by zakiya** [comment]
This is merged.
