### ISSUE TITLE
dynamic case data

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#556]
High level goals:

- [x] Build API that retrieves data from snowflake
- [x] Make stats on homepage powered by API
- [x] Create first D3 version of clickable county map, compare weight vs tableau

Task limits:

We don't plan to spend much time experimenting with different data visualizations but we can use the version the GO is happy with as an example and build a faster, more web safe version that is easily embedded, doesn't risk the tableau bug where the numbers disappear at different screen widths

The source of some data points like PPE distribution is still a mystery, going to leave that out of v1

**Comment by abquirarte** [comment]
This will be great, thank you!

**Comment by aaronhans** [comment]
More action items, when confident API powered stats will continue to work:

- [ ] Delete the table-data file in WP
- [ ] Delete the unused stats-lang files in translated-posts unless those are better versions, then replace the WP versions with those...
