### ISSUE TITLE
Make age 5-11 vax changes to Vaccines page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5561]
Told by Devon Keeler that we should get talking points today about vaccinations for kids 5-11. Tentatively scheduled to publish 11/4.

- [x] Draft changes to _Vaccines_ page
- [x] Get approval from CDPH/PM
- [x] On publishing date, stage
- [x] Publish

**Comment by thepegisin** [comment]
Draft: https://docs.google.com/document/d/1upSAaN-n4idaetIjIAMrHO6g6TL_Zkt7ulRHzP4n-EE/edit

**Comment by mediajunkie** [comment]
These edits look good. Have we surveyed the full site for age references?
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by thepegisin** [comment]
Checked all my pages for age references, and advised the rest of the content team to do so as well.

Staged per @mediajunkie 1:30PM 11/3.

**Comment by thepegisin** [comment]
Published 2:30PM on 11/3.
