### ISSUE TITLE
Homepage banner about age 5-11 vaccinations

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5562]
Vaccinations for ages 5-11 are tentatively scheduled to be announced 11/4/21. Write and publish homepage banner about this when CDPH makes their announcement.

- [x] Get talking points from CDPH (Devon, MJ)
- [x] Draft banner
- [x] When announced, stage
- [x] Publish
- [x] Edit and re-publish 11/4 when My Turn scheduling becomes available

**Comment by thepegisin** [comment]
Draft: https://docs.google.com/document/d/1T-sKeNUY1DaUJqpXQXzcv_FIzIXc1BG18YdTrMgtlAo/edit#heading=h.ah68pjhj93yw

**Comment by mediajunkie** [comment]
Banner copy and link CTA look good to me. Do you think we need to run it by
Devon et al. at CDPH?
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by thepegisin** [comment]
Staged per @mediajunkie 1:30PM 11/3.

**Comment by thepegisin** [comment]
Published 2:30 11/3.

**Comment by thepegisin** [comment]
Edited and republished 9:30AM 11/4.
