### ISSUE TITLE
State dashboard: remove vax/unvax hospitals date note

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5563]
The [state dashboard](https://covid19.ca.gov/state-dashboard/#postvax-status) chart for vaccinated vs. unvaccinated data contains the following note:

> The date range for hospitalization data begins on July 24, 2021, as a result of enhanced reporting by hospitals.

This is because the chart begins on July 24, which is later than the cases and deaths charts. Somewhere around November 24, the hospitalization chart will have a full range of data. This renders the note no longer needed.

This issue is to remove this note after confirming that the hospitalization date range has moved to begin on July 25, 2021 or later.

**Comment by m-sullivan7** [comment]
@mediajunkie Now that the 12+ population denominator is behind us, there's one other edit we can make to state dashboard.

We were previously limited to July 24 as the start date for hospitalization chart in vaccinated vs. unvaccinated. With today's date update, both the cases and hospitalization charts begin at July 24. (The deaths chart actually pulls more data, going back to July 10.) I propose we remove this line from the _Chart information_ accordion:

> The date range for hospitalization data begins on July 24, 2021, as a result of enhanced reporting by hospitals.

Here's a [Google Doc with that change](https://docs.google.com/document/d/1be_G080QrLPC9342l-FYQzih_-7tJindBESCf3O4tbY/edit?usp=sharing).

It's a small thing, but it's one less sentence and that's a good thing. 😄

**Comment by mediajunkie** [comment]
yes, let's please do this.

**Comment by m-sullivan7** [comment]
Update published.
