### ISSUE TITLE
Food page: WIC update

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5577]
Edits based on WIC stakeholder/SME input:
[Draft doc](https://docs.google.com/document/d/1XL0M9CDiANBEsU2hdxukYWQCb8UClgc8piy0tDgjxo0/edit#)

- [x] Draft
- [x] Internal review
- [x] Stage
- [ ] External review
- [ ] Revise if needed
- [ ] Publish
- [ ] Notify

**Comment by LizNobriga** [comment]
@m-sullivan7 Can you review the draft doc?

**Comment by m-sullivan7** [comment]
Reviewed! One structural comment and one edit to eliminate some repetition.

**Comment by LizNobriga** [comment]
@mediajunkie The feedback from stakeholders for the WIC content has been incorporated and reviewed by Michael. The edits are not word-for-word but remain close to the input received. 

Can you review the proposed [draft edits](https://docs.google.com/document/d/1XL0M9CDiANBEsU2hdxukYWQCb8UClgc8piy0tDgjxo0/edit#)? Lmk if you have any concerns and if they are ready to be staged.

**Comment by LizNobriga** [comment]
@mediajunkie Ready for your review. Lmk if these are okay to stage. [Edits in google doc](https://docs.google.com/document/d/1XL0M9CDiANBEsU2hdxukYWQCb8UClgc8piy0tDgjxo0/edit#)

**Comment by mediajunkie** [comment]
edits looks clean to me. please do stage
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
@mediajunkie The WIC section [edits](https://docs.google.com/document/d/1XL0M9CDiANBEsU2hdxukYWQCb8UClgc8piy0tDgjxo0/edit#) are [staged](https://staging.covid19.ca.gov/food-resources/#families-with-children).

**Comment by LizNobriga** [comment]
@mediajunkie It was feedback that came through Alisa.

**Comment by mediajunkie** [comment]
ok, let's keep it staged and I will include it in the final email

**Comment by LizNobriga** [comment]
Published 11/9/21
