### ISSUE TITLE
Food page: update Apply for CalFresh link

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5581]
DSS stakeholder request to update the "Apply for CalFresh" button to the new online portal, [https://benefitscal.com/](https://benefitscal.com/)

[Draft doc](https://docs.google.com/document/d/18fnPqdHueTE-EfYwrwgv-hjXfpX1AKvi8PIsUE3V_70/edit#)

**Comment by LizNobriga** [comment]
@mediajunkie Received a request from the DSS CalFresh acting branch chief, Kat Yang, to update the "Apply for CalFresh" link to the new online portal at https://benefitscal.com/. 

[See edit in doc](https://docs.google.com/document/d/18fnPqdHueTE-EfYwrwgv-hjXfpX1AKvi8PIsUE3V_70/edit#). Is this okay to publish? 

cc @m-sullivan7

**Comment by mediajunkie** [comment]
yes!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Published
