### ISSUE TITLE
State dashboard: Update vaccinated/unvaccinated to 12+ age group

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5590]
[Within a few weeks of]* November 10, the population for the unvaccinated/vaccinated chart on the state dashboard will change 12+. It is currently 16+.

This issue is to:

- Update the state dashboard note for this chart
- Update the associated data dictionary in _Data and tools_
- Create highlight box text if we want to put a note up with the change (this language will also cover the 5+ population change to vaccines administers from https://github.com/cagov/covid19/issues/5519)

* originally present as "On November 10..."

**Comment by m-sullivan7** [comment]
[Google Doc](https://docs.google.com/document/d/1aPxL79Wvysp95YSrbCKqEJP4Bt57x9Mn9BJ3eTLwBzU/edit?usp=sharing) with the change (only one content change needed)

Potential language for a highlight box:

> **Vaccination data updated**
> On November 10, 2021, we updated the vaccines administered population denominator to include people 5 and older. As a result, the percentage of population vaccinated declined.
> We also updated the unvaccinated and vaccinated cases, deaths, and hospitalization charts to include people 12 and older. The current charts vary slightly from the previous versions.

cc: @mediajunkie for a look at state dashboard edits for 11/10 and highlight box copy we could keep in our back pocket. Regarding the unvaccinated and vaccinated charts, I don't know what the impact to those charts will be when we add the 12-15 age group in. We can update the general language if we determine specific impacts.

**Comment by m-sullivan7** [comment]
Thanks for the update on timing and the changed description. I edited the potential highlight box content so it's limited just to this change to the data. I moved the 11/10-specific note content to https://github.com/cagov/covid19/issues/5519

**Comment by mediajunkie** [comment]
New target date for this is week of November 29. Brooke and Lauren are getting sample data ready for @jbum

**Comment by m-sullivan7** [comment]
@mediajunkie Here's a Google Doc with associated edits for [Data and tools](https://docs.google.com/document/d/16UxF8zSoyFzy-BFuipqexrQRDsV8M6LNVy4xwaEcWO4/edit?usp=sharing). I updated the description of the issue to include this in the scope.

**Comment by m-sullivan7** [comment]
Edits to both pages have been published.
