### ISSUE TITLE
Health equity: timescale edits

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5645]
From @mediajunkie 

- Make sure our chart and the CDPH charts have different titles so they are distinct in a way that clarifies that ours is a more recent trend summary.
- Make sure that each chart offers a link to the other in its surrounding content so that someone looking for the answer to the other question (recent vs. all-time) can find it regardless of which chart they find first.

**Comment by jbum** [comment]
Random @wrendo tag.

**Comment by m-sullivan7** [comment]
@mediajunkie It looks like the only change we need to make is adding the 30 day reference to the introductory info to the charts. I suggest we also remove the 30 day reference from the _Chart information_ accordion as that is supplemental information. Here's a [Google Doc with those changes](https://docs.google.com/document/d/190NXej-3sXL7j4xO-1Xo-n7pijAbXRg27Do46sBsKWc/edit?usp=sharing).

_Chart information_ already contains a link to the CDPH page with breakouts by age bracket, so the second point is covered.

**Comment by mediajunkie** [comment]
comment in doc - we need to help people who want data beyond 30 days also
to find the CDPH link

**Comment by m-sullivan7** [comment]
Thanks. I like your solution. :smile:

**Comment by jbum** [comment]
@m-sullivan7 -- take your pick:

![image](https://user-images.githubusercontent.com/287977/142301456-3131c7a4-f896-4b64-a041-43ffbb263385.png)

![image](https://user-images.githubusercontent.com/287977/142301504-6e5cc094-079b-4474-97a6-e241bbee0c5e.png)

(Second one is more consistent, but also reads as "OK")

**Comment by m-sullivan7** [comment]
[Page](https://covid19.ca.gov/equity/#community-impact) updated with new content.
