### ISSUE TITLE
Update main homepage CTA "GET VACCINATED -->" to point to My Turn

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#5668]
The GET VACCINATED --> link on our homepage currently points to the _Vaccines_ page. We think it would be more helpful to users if it pointed to My Turn.

- [x] Get approval from @mediajunkie 
- [x] Find out where this can be edited
- [x] Stage change in WP
- [x] Publish

**Comment by jbum** [comment]
Staged and published.

**Comment by thepegisin** [comment]
Thank you, @jbum! Note for historical purposes: Updating the homepage CTA is not currently within content team editorial control. Requires an engineer. Jim did it last.
