### ISSUE TITLE
Mega-events update (exempt under age 2)

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5679]
See [draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#)

- [x] draft
- [x] internal review
- [x] stage
- [ ] external review
- [x] publish

See [CDPH guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Beyond-Blueprint-Framework.aspx)

**Comment by LizNobriga** [comment]
[Edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) for your review, @m-sullivan7. CDPH has clarified that children 2 and under don't need to provide a negative test for mega-event entry.

**Comment by m-sullivan7** [comment]
These are simple and clear edits to me. All good here @LizNobriga !

**Comment by mediajunkie** [comment]
please stage!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Mega-events is ready in [staging](https://staging.covid19.ca.gov/mega-events/), @mediajunkie.

**Comment by mediajunkie** [comment]
looks good -- please publish.

(and i gather children age 3-4 would need a test as they could not possibly be vaccinated yet)

**Comment by LizNobriga** [comment]
@mediajunkie Published https://covid19.ca.gov/mega-events/

Yes, I believe that's an accurate interpretation.
