### ISSUE TITLE
Per PR preview sites in AWS for covid19

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#5692]
Work with @xjensen to implement the techniques pioneered here on covid19 https://github.com/cagov/odi-engineering/issues/53

**Comment by xjensen** [comment]
I've already done this, pretty much, for Covid. I used Covid to help me write the [documentation](https://github.com/cagov/odi-engineering/wiki/Set-up-PR-preview-sites).

Still to-do:
* Wait for CDT to implement the DNS entries for the PR preview sites.
* Finish Cloudfront set-up for the verified SSL certificate after that's done.
* Implement the GitHub Action.

@jbum, I'd be happy to walk you through all of this if desired, and/or/not hand off the last remaining tasks. Just lemme know your level of interest.

**Comment by aaronhans** [comment]
Please walk both @jbum and me through these steps. I'd like to go through the setup steps on a remaining site. I believe we still have cannabis and digital to setup

**Comment by jbum** [comment]
Yes please :)

**Comment by xjensen** [comment]
Meeting invite sent for later this morning.

**Comment by jbum** [comment]
Implemented and working.
