### ISSUE TITLE
Food page update: last round of Pandemic-EBT 2.0 benefits

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5712]
### Last round of P-EBT 2.0 benefits will be issued in December 2021
- Cards will be reloaded with $375
- Cards for newly eligible children will be mailed out

### P-EBT 3.0 coming in 2022
- The USDA’s Department of Food and Nutrition Service has authorized another round of P-EBT benefits for the 2021-22 school year.
- The California Department of Social Services and the California Department of Education are currently working together to draft plans for young children under six and school-age children in California.

[Draft doc](https://docs.google.com/document/d/1vCgDthlJtoTsXlJGr_JZ4yx2y24s4IJWs4tCZcHaTD8/edit#)

- [x] Draft edits
- [ ] Internal review
- [ ] Stage
- [ ] External review
- [ ] Publish

**Comment by m-sullivan7** [comment]
Good update! I left a few comments.

**Comment by LizNobriga** [comment]
Thanks @m-sullivan7! Resolved comments.

**Comment by LizNobriga** [comment]
@mediajunkie [Edits](https://docs.google.com/document/d/1vCgDthlJtoTsXlJGr_JZ4yx2y24s4IJWs4tCZcHaTD8/edit#) to the P-EBT section of the _Food resources_ page are ready for review in [staging](https://staging.covid19.ca.gov/food-resources/#pandemic-ebt).

**Comment by mediajunkie** [comment]
looks good to publish!

**Comment by LizNobriga** [comment]
Published
