### ISSUE TITLE
State dashboard: testing note fixes

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5759]
Update state dashboard as appropriate to include:

- Appropriate lag times (if any)
- Any exclusions

[Google Doc with updates](https://docs.google.com/document/d/1TqdEmfoYsTSa16X4ALUMThu6MtgsAtUj2U3t-trstNw/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
@mediajunkie Here's the change coming out of today's meeting on state dashboard testing notes. I didn't catch your final suggestion since I was flipping between windows. Could you confirm that [this is the edit](https://docs.google.com/document/d/1TqdEmfoYsTSa16X4ALUMThu6MtgsAtUj2U3t-trstNw/edit?usp=sharing) before I publish?

**Comment by mediajunkie** [comment]
looks good!

**Comment by m-sullivan7** [comment]
[Change made and live.](https://covid19.ca.gov/state-dashboard/#county-statewide) Closing issue!
