### ISSUE TITLE
Add date-range selection to the histogram charts on the /state-dashboard/ page.

### ISSUE THREAD

**Issue by jbum** [cagov/covid19#5762]
Work is currently being done in the branch jbum-dashboard-date-range-picker and is being previewed at

https://preproduction.covid19.ca.gov/state-dashboard/#county-statewide

**Comment by zakiya** [comment]
https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/COVID19.ca.gov-screens?node-id=8399%3A41798

**Comment by jbum** [comment]
Shipped!
