### ISSUE TITLE
Content updates for roadmap 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#578]
Content for the design of the bottom of the roadmap page. 

Art is building the design components. Some saved in preview page. 

Content is below:
https://mail.google.com/mail/u/0/#inbox/FMfcgxwHNVxDSTlZdDdcxQjhMvccrKMW?projector=1&messagePartId=0.1 

adding @peggy as content owner for awareness!

**Comment by artuoma** [comment]
I'm on it!

**Comment by TamaraIDEJA** [comment]
### Content Update 

See in red: 
https://drive.google.com/file/d/1JtRpnL6T3ZAn_7yZpG1nFc3-TykK2esj/view?usp=sharing 

### Timeframe 
asap 

### Content Captain 

@thepegisin
