### ISSUE TITLE
Mega-events: negative test result timeframe

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5785]
[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#)
Reference: [CDPH mega-events guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Beyond-Blueprint-Framework.aspx)

- [x] Draft
- [x] Internal review
- [x] Stage
- [x] Stakeholder review
- [x] Publish

**Comment by LizNobriga** [comment]
The [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) for the Mega-events page can be viewed in [staging](https://staging.covid19.ca.gov/mega-events/). 

@m-sullivan7, there are 3 sentences that Hemingway flags as very-hard-to-read in the _Outdoor events_ section.

**Comment by m-sullivan7** [comment]
Thanks for highlighting that Liz. Any changes you'd like to propose in response to that Hemingway finding or would you like to stand pat?

**Comment by LizNobriga** [comment]
I don't have any quick fixes.

**Comment by LizNobriga** [comment]
Hi @mediajunkie. We have the [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) for Mega-events in [staging](https://staging.covid19.ca.gov/mega-events/). Let me know if you have any thoughts or if stakeholders have feedback.

**Comment by mediajunkie** [comment]
confirming with testing task force and will get back to you.
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Request to convert hours to days is complete. See [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit) and [staging](https://staging.covid19.ca.gov/mega-events/).

**Comment by m-sullivan7** [comment]
They look good to me!

**Comment by LizNobriga** [comment]
Request to change "age 3" to "age 2" is complete. See [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit) and updated [staging.](https://staging.covid19.ca.gov/mega-events/)

**Comment by LizNobriga** [comment]
Forgot to close this ticket. These edits were published 12/17/21.
