### ISSUE TITLE
Stop showing suspected hospitalizations

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5820]
We want to stop showing confirmed plus suspected hospitalizations on the state dash chart and instead want to plot just confirmed hospitalizations, to stop including "and suspected" in the intro, and to show dynamic data based on confirmed totals and daily changes, not on the sum of confirmed and suspected

![image](https://user-images.githubusercontent.com/3227378/147009949-fc4b38ad-893b-432b-8b5f-394ad12be408.png)

to

![image](https://user-images.githubusercontent.com/3227378/147010736-1a8e13d4-e855-4b92-a515-65af21655cbe.png)

**Comment by mediajunkie** [comment]
- remove "and suspected" from three locations
- replace use of `HOSPITALIZED_COVID_CONFIRMED_PATIENTS`+`HOSPITALIZED_SUSPECTED_COVID_PATIENTS` 'hospitalized patients'  with just `HOSPITALIZED_COVID_CONFIRMED_PATIENTS` 'hospitalized patients'
- replace use of `HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY` (more/fewer etc,) with `HOSPITALIZED_COVID_CONFIRMED_PATIENTS_DAILY`

**Comment by mediajunkie** [comment]
@jbum for the first week of next year!

**Comment by mediajunkie** [comment]
updated mock of 
- where to cut the phrase "and suspected" in three places
- plus highlight where the dynamic numbers will change (as well as in the chart not least of which)
- and also lest we forget, the chart itself would need to change:
![image](https://user-images.githubusercontent.com/3227378/147509873-bae4ca56-d87b-4cae-8c69-f2e52bcde352.png)

**Comment by mediajunkie** [comment]
@m-sullivan7 there are some small copy changes needed before we can stage this for quick review and approval

**Comment by m-sullivan7** [comment]
Content changes look good and are staged! Here's a [Google Doc showing those changes](https://docs.google.com/document/d/1ObR6kPseuWvD7wjWyPPOlRI2IYtwf5rDme_HIbHYTnY/edit?usp=sharing).

**Comment by m-sullivan7** [comment]
I'm taking over the assignment of this ticket for publishing. I will keep the ticket open through January 12, 2022, at which point I will remove the reference to January 5, 2022, in the hospitalization note and close the ticket.
