### ISSUE TITLE
12/22 governor press conference

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#5822]
Update homepage with video livestream of governor's press conference scheduled for 10:40.

**Comment by mediajunkie** [comment]
TY

-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Video published in the morning and removed in the afternoon. Closing the issue.
