### ISSUE TITLE
Safety in the workplace - booster requirement

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5845]
Workers required to be fully vaccinated and boosted in healthcare and congregate settings.
[Draft](https://docs.google.com/document/d/14RZSitqD_RXyJqGfUU1lRUcgwu0C6Ox941msBF4fA7s/edit#)

- [x] Draft edits (Liz)
- [x] Internal review (Michael)
- [x] Stage (Liz)
- [ ] Stakeholder approvals (Christian)
- [ ] Publish (Liz)

These edits are linked to #5857.

**Comment by LizNobriga** [comment]
@m-sullivan7 Draft edits are ready for your review.

**Comment by m-sullivan7** [comment]
Just one minor opinion thought. Looks great!

**Comment by LizNobriga** [comment]
@mediajunkie [Edits](https://docs.google.com/document/d/14RZSitqD_RXyJqGfUU1lRUcgwu0C6Ox941msBF4fA7s/edit) are ready for your review. Let me know when I should stage these changes.

**Comment by mediajunkie** [comment]
edits look good to me

**Comment by LizNobriga** [comment]
@mediajunkie Should I stage these edits now? Or wait until we hear back from stakeholders?

**Comment by LizNobriga** [comment]
Updating this ticket to show these [edits](https://docs.google.com/document/d/14RZSitqD_RXyJqGfUU1lRUcgwu0C6Ox941msBF4fA7s/edit) are ready in [staging](https://staging.covid19.ca.gov/workers-and-businesses/) (along with the edits in #5857).

**Comment by mediajunkie** [comment]
renudged along with https://github.com/cagov/covid19/issues/5857

**Comment by LizNobriga** [comment]
(closing this ticket since we're now tracking all edits to this page as a group in #5857)

**Comment by LizNobriga** [comment]
Published edits (see https://github.com/cagov/covid19/issues/5857).
