### ISSUE TITLE
Mega-events: lower attendee thresholds

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5852]
CDPH may revise mega-events guidance to lower attendee thresholds to 500 people for indoor events and 5,000 people for outdoor events. Need to wait until CDPH has published their updated guidance before we can publish an update to our mega-events page. 

[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#)

- [x] Draft (Liz)
- [x] Internal review (Michael)
- [x] Interview review (Christian)
- [x] Stage (Liz)
- [x] Stakeholder approvals (Christian)
- [x] Publish

**Comment by m-sullivan7** [comment]
Straight forward edits to me! All good!

**Comment by LizNobriga** [comment]
@mediajunkie FYI - These [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) to **Mega-events** are ready for review (if CDPH decides to move forward with lowering the attendee thresholds for mega-events).

**Comment by LizNobriga** [comment]
[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) are [staged](https://staging.covid19.ca.gov/mega-events/). Waiting for [CDPH mega-events guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Beyond-Blueprint-Framework.aspx) update to publish before we publish updates to our Mega-events page.

**Comment by LizNobriga** [comment]
CDPH published updated [mega-events guidance](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Beyond-Blueprint-Framework.aspx) on December 31, 2021. The guidance is not effective until January 15, 2022 (including the lower attendee thresholds). 
@mediajunkie Should we plan to publish the Mega-events page we have ready in [staging](https://staging.covid19.ca.gov/mega-events/) at the end of the day on Jan 14 (or start of day on Jan 15)?

**Comment by mediajunkie** [comment]
how did we handle this sort of "anticipated date of the thing
taking effect" in the past?

**Comment by LizNobriga** [comment]
I made revisions to the [draft](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) and in [staging](https://staging.covid19.ca.gov/mega-events/) to show what it could look like to include what's in effect now, and what will change on Jan 15. Thoughts @mediajunkie @m-sullivan7 ?

**Comment by m-sullivan7** [comment]
I think it's a good solution. I support this approach. Nice work Liz!

**Comment by LizNobriga** [comment]
@mediajunkie Do you think it's ready for stakeholder approvals? 

- [Mega-events edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) in google doc
- [Mega-events page in staging](https://staging.covid19.ca.gov/mega-events/)

**Comment by LizNobriga** [comment]
Made revisions based on stakeholder input, along with additional improvements to content. Revised draft is back out for approval to publish. Also awaiting stakeholder input on masks at outdoor mega-events.

**Comment by LizNobriga** [comment]
Received more stakeholder feedback and proposed new revisions including highlight box. See [staging](https://staging.covid19.ca.gov/mega-events/) and [google doc](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#).

**Comment by LizNobriga** [comment]
Approved to publish.
