### ISSUE TITLE
Update contracts page: More contracts for Thurs/Friday

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#589]
We expect to get about 15 contracts to add to covid19.ca.gov/contracts tomorrow. 
With another 12 potentially ready to go Friday afternoon.

While we work on a long term hosting solution for these PDFs, perhaps we can start adding accordions by letter?

**Comment by LizNobriga** [comment]
Added @KaylaPrusia

**Comment by LizNobriga** [comment]
@abquirarte, could you take a quick peek at the [content staging doc](https://docs.google.com/document/d/18CYotMzjPfc-F-MTjFaQGni1_yytUWYxrBa-0u8A3-I/edit#) and let us know if the proposed accordion breakout works? (@kalvinwang

**Comment by LizNobriga** [comment]
@abquirarte, could you review the accordions proposed for Contracts page in [staging doc](https://docs.google.com/document/d/18CYotMzjPfc-F-MTjFaQGni1_yytUWYxrBa-0u8A3-I/edit#)?

**Comment by LizNobriga** [comment]
(please ignore my accidental 'close')

**Comment by LizNobriga** [comment]
This is done/live for Thursday's round. Thank you for teaming up with me, Kayla!

@KaylaPrusia will be covering for contracts coming in Friday afternoon.

**Comment by abquirarte** [comment]
Thank you ladies!!! 😄

**Comment by LizNobriga** [comment]
Added four EDD contracts (lag in WP)
[staging for contracts](https://docs.google.com/document/d/18CYotMzjPfc-F-MTjFaQGni1_yytUWYxrBa-0u8A3-I/edit#)
