### ISSUE TITLE
Update to 'Getting food' page with Pandemic-EBT application portal link

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#590]
Update start date to May 22 for Pandemic-EBT application and add link to application portal:

[https://ca.p-ebt.org/en/](https://ca.p-ebt.org/en/)

Source: [CDSS Pandemic-EBT page](https://www.cdss.ca.gov/home/pandemic-ebt)

[Content staging doc](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit#)

**Comment by abquirarte** [comment]
Tracking. Did we close the loop on this?

**Comment by LizNobriga** [comment]
yes, this is done/live

**Comment by abquirarte** [comment]
🎉
