### ISSUE TITLE
Mega-events: Update on January 15, 2022

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5907]
Lower thresholds for mega-events take effect. Remove outdated content and alert box. Sync with @thepegisin for #5878.

[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#)

- [x] Draft
- [x] Internal review
- [x] Stage
- [ ] Stakeholder approval
- [x] Publish

**Comment by m-sullivan7** [comment]
Solid edits. No changes from me!

**Comment by LizNobriga** [comment]
@mediajunkie This update to Mega-events would ideally publish end of day this Friday (January 14, 2022) since the lower attendee thresholds take effect on January 15. Can we run this update through stakeholders by Friday?

See [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) in google doc and in [staging](https://staging.covid19.ca.gov/mega-events/).

**Comment by LizNobriga** [comment]
@mediajunkie Actually, I think we are okay if this update cannot happen by this Friday. The current page is clear on what takes effect on Jan 15, so I think we have more time than I initially thought. Maybe this update can get in the queue for publishing sometime next week. I'm not expecting stakeholder concerns since we did the related update of "what's coming on Jan 15" with them last week (but you never know). 

- [Mega-events current page](https://covid19.ca.gov/mega-events/)
- [Mega-events page in staging](https://staging.covid19.ca.gov/mega-events/). This reflects rules in effect after Jan 15, 2022. [See these edits ](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#)in the google doc.

**Comment by LizNobriga** [comment]
Published afternoon of Jan 14.
