### ISSUE TITLE
Update retail guidance PDF (libraries and drive-ins) for Statewide industry guidance page

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#591]
New PDF dated 5/19 received from SME to replace existing PDF on [statewide industry guidance page](https://covid19.ca.gov/industry-guidance/). 

Suggested edits for retail accordion in [content staging doc](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit).

**Comment by abquirarte** [comment]
One more for this page actually, can you check this out?! :) @LizNobriga 

Checklist for Office Workspaces document has a broken link in it. The link to the Guidance for Office Workspaces (https://covid19.ca.gov/pdf/checklist-office-workspaces.pdf) should point to the Guidance document here: http://covid19.ca.gov/pdf/guidance-office-workspaces.pdf.

**Comment by LizNobriga** [comment]
@abquirarte, I'm not finding this issue on [this page](https://covid19.ca.gov/industry-guidance/). The links for guidance PDF and the checklist PDF both work for me, and seem to be the latest versions we've received via email.

**Comment by abquirarte** [comment]
☝️ mhm. same. Must have been when we were replacing them and the user must have this cached. 

✅ edits to retail accordion approved!!! @LizNobriga

**Comment by LizNobriga** [comment]
This is done/live

**Comment by KaylaPrusia** [comment]
Added libraries and drive-in information to "What's Open" accordion on [stay home QA](https://docs.google.com/document/d/14IL8TJMfBCZXcZ8lMph7aastRl3o7ym3/edit)

**Comment by LizNobriga** [comment]
@abquirarte, this is done (still waiting for live due to github lag issue)

For [Stateside industry guidance page](https://covid19.ca.gov/industry-guidance/):

- Added "Interior stores in shopping malls can do curbside pickup with modifications." to the 'Retail' accordion

See [content staging doc](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit)

@KaylaPrusia, @ashleydraper, @thepegisin,  tagging you all in case it affects your pages or anything you're working on today.

**Comment by ashleydraper** [comment]
removed "libraries" from the list of places that are not open on the **[County variance](https://covid19.ca.gov/roadmap-counties/#top)** page
