### ISSUE TITLE
Safety in the workplace: indoor mask requirement through Feb 15

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5912]
DIR provided clarification on how the CDPH face mask order affects the ETS workplace requirements in their [FAQs](https://www.dir.ca.gov/dosh/coronavirus/COVID19FAQs.html#controls):
> Q: What impact does CDPH’s Guidance for the Use of Masks, revised as of December 13, 2021, have on the COVID-19 Prevention Emergency Temporary Standards (ETS)?
> A: Cal/OSHA’s face covering requirements are detailed in the ETS. The ETS requires that employers “provide face coverings and ensure they are worn by employees when required by orders” of the California Department of Public Health (CDPH). (8 CCR § 3205(c)(6)(B).) The December 13, 2021 CDPH guidance is such an order.

Update content for **Masks at work** on the [Safety in the workplace](https://covid19.ca.gov/workers-and-businesses/#workplace-safety-standards) page. One option is to link to the [Masks in the workplace](https://covid19.ca.gov/masks-and-ppe/#Masks-in-the-workplace) anchor on Masks page. 

- [x] Draft
- [x] Internal review
- [ ] Stakeholder approval
- [ ] Stage
- [ ] Publish

This issue is linked to the other edits in the queue for this page. See #5857 and #5845.

**Comment by mediajunkie** [comment]
my last nudge to Trudy did not get a reply, but will now nudge with all three changes together to try to cleat these.

**Comment by LizNobriga** [comment]
The proposed edits for masks required indoors through Feb 15 have been removed. I'm going to close this ticket because we've incorporated this into our overall set of updates to _Safety in the workplace_ (see #5857).
