### ISSUE TITLE
Mega-events: remove highlight box

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5939]
Remove the highlight box around the end of January 2022 (~2 weeks)

**Comment by LizNobriga** [comment]
@m-sullivan7 [Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) to remove highlight box next week. Another straightforward one.

**Comment by m-sullivan7** [comment]
All good with me!

**Comment by LizNobriga** [comment]
Hi @mediajunkie We're planning to remove the current highlight box on _Mega-events_  next week. It's the one that announced Jan 15 changes (see screenshot below). I don't think we'll need to get stakeholder approval to do this. 
![mega-events_highlightbox](https://user-images.githubusercontent.com/58706834/151637891-af1eead2-677a-4b99-a67b-2977dc3db1c3.png)
[Edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) in google doc.

**Comment by mediajunkie** [comment]
agreed!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Published
