### ISSUE TITLE
Update to Food Resource page 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#594]
### Content Update

Update GetCalFresh URL to https://www.getcalfresh.org/?source=cagov

Update CSFP language to say:
“These Food Banks distribute the CSFP boxes. Please call the listed food bank in your area for more information on how you can participate in the program.”

### Content Captain

@LizNobriga cc' @abquirarte

**Comment by LizNobriga** [comment]
[content staging doc](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit#) ready for your review @abquirarte

**Comment by LizNobriga** [comment]
FYI, the "new" url is already live on the site now (points to the same place).

**Comment by abquirarte** [comment]
interesting!

Saw the edits. Good to go! :)

-Angelica Quirarte, "Angie"

**Comment by LizNobriga** [comment]
Publishing now.

**Comment by LizNobriga** [comment]
Changes are live

**Comment by LizNobriga** [comment]
This done/live
