### ISSUE TITLE
Optimize Masks page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#598]
Split current **[Masks and PPE](https://covid19.ca.gov/masks-and-ppe)** page into two pages: **Masks** for general public, **Request PPE** for requesting PPE from the state.

- [x] Draft in Staging, improve readability for both through the Hemingway app.
**Masks:** https://docs.google.com/document/d/1-7dSwuitgDWrB3mJ45yW-NG3ADA4N60CoUbXi1BL_vQ/edit
**Request PPE:** https://docs.google.com/document/d/1fUJMnbxK1BhkvmPU-2D_AA6n9orl66EBnC6SWo3hADU/edit

- [x] Get stakeholder approval

- [x] Publish

- [x] Link into rest of site as appropriate

**Comment by abquirarte** [comment]
Sending a nudge on this!!

**Comment by TamaraIDEJA** [comment]
SMEs approved the content - we can make this live: 
Request PPE: https://docs.google.com/document/d/1fUJMnbxK1BhkvmPU-2D_AA6n9orl66EBnC6SWo3hADU/edit

**Comment by abquirarte** [comment]
@thepegisin we only need to link to site right?

**Comment by thepegisin** [comment]
It’s already linked. Masks uses /masks-and-ppe/ URL, and /request-ppe/ is linked within the Masks page. Should we update the menu link to just say Masks?

**Comment by thepegisin** [comment]
Menu link updated.
