### ISSUE TITLE
Food page: WIC fruits and vegetables benefits through March 2022

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5993]
Update December 2021 to March 2022 for the WIC benefits for fruits and vegetables

From [WIC website](https://www.myfamily.wic.ca.gov/Home/FruitsVegBenefits#FruitsVegBenefits):
> What is the latest update to the WIC Fruits and Vegetables Benefit?
> 
> The benefit increase that started in October 2021 has been extended through March 2022!

[Draft edits](https://docs.google.com/document/d/1vCgDthlJtoTsXlJGr_JZ4yx2y24s4IJWs4tCZcHaTD8/edit?pli=1#)

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you review this one? Pretty straightforward but you might spot something.

**Comment by m-sullivan7** [comment]
It looks straightforward! I take it this doesn't impact any of the December 2021 dates in the P-EBT section? That was the only thing that caught my attention. I noticed this line:

> There are more P-EBT benefits coming for the 2021-2022 school year.

I thought perhaps the WIC update could be part of that.

If no impact to P-EBT, all looks good!

**Comment by LizNobriga** [comment]
The WIC change has no impact on P-EBT. 

I checked the P-EBT websites (https://capandemic-ebt.org/ and https://www.cdss.ca.gov/home/pandemic-ebt) earlier for any updates and I did not find anything new. But now that you pointed this out, I've looked again and noticed any mention of benefits coming for the 2021-2022 school year has been removed. I'll add an edit to remove that line.

**Comment by LizNobriga** [comment]
@mediajunkie These edits to the Food page are pretty straightforward:

WIC section:
- Change the end date for the extra WIC fruits and veg benefits from December 2021 to March 2022, and add a [link to the fruit and veg benefits info](https://www.myfamily.wic.ca.gov/Home/FruitsVegBenefits#FruitsVegBenefits)

P-EBT section:
- Remove sentence ("There are more P-EBT benefits coming for the 2021-2022 school year.") because the P-EBT websites do not say that anymore. 

Are these edits okay to publish or do we need stakeholders to approve first?

**Comment by LizNobriga** [comment]
@mediajunkie These edits are ready in [staging](https://staging.covid19.ca.gov/food-resources/). Okay to publish?

**Comment by mediajunkie** [comment]
Yes, go ahead!

-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>
