### ISSUE TITLE
Switch "Janssen" to "Johnson & Johnson"

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6002]
Per @thepegisin, we've moved sitewide to saying "Johnson & Johnson vaccine" instead of "Janssen vaccine." This ticket is to update all instances of Janssen.

This work may overlap with other changes on the state dashboard: https://github.com/cagov/covid19/issues/5992

**Comment by m-sullivan7** [comment]
Found two instances in my pages. Here are Google Docs for each:

- [State dashboard](https://docs.google.com/document/d/1Jaw5pG_BR8oNJ0oFd8Wn2uOYIi1pGqeCItPAE8mKoJ4/edit?usp=sharing)
- [Vaccination data](https://docs.google.com/document/d/1z7QsaVANJbHIJh7cfLzbylDXAUjFP-CXcEYgvyVLQ9M/edit?usp=sharing)

**Comment by mediajunkie** [comment]
please go ahead and update

**Comment by m-sullivan7** [comment]
Changes made and published!
