### ISSUE TITLE
Content edits to reflect Monday-Friday reporting of vaccination data

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6003]
CDPH has indicated they are looking to move from daily reporting of vaccine numbers to Monday-Friday reporting.

This task is to review impacts to content. This will likely impact:

- Homepage
- State dashboard
- Vaccination data

cc: @mediajunkie so he knows there's a ticket for this

**Comment by mediajunkie** [comment]
Thanks! I think this will mainly affect footnotes?

**Comment by m-sullivan7** [comment]
I think so, but I'll poke around to test my assumptions.

**Comment by m-sullivan7** [comment]
After review:

- No impact to homepage as we do not have any notes about publishing cadence on that page.
- State dashboard impact is to shorten the first bullet in the _Data notes_ to: "Data is not reported on weekends or state holidays. This data is processed on the first day following the weekend or holiday and updated here on the following day." [Google Doc with this change.](https://docs.google.com/document/d/1n7IZdxvbadgI2kHC_6F9XWtejKgzG1bLWNorj1hIFIE/edit?usp=sharing)
- _Vaccination data_ impact is to remove the second sentence in the _Statewide vaccination data_ section and replace it with a note in the accordion. [Google Doc with this change.](https://docs.google.com/document/d/1cZI37VC3QU3Fa4OAR9X8jHxW_FeNLXLGK2f2vwy-8yo/edit?usp=sharing) If we want to keep the update frequency outside the accordion (which, given some feedback about supposedly out-of-date data, may be a good idea), I'd update the second sentence to "This data is updated Monday through Friday, state holidays excepted. Data is processed on the first day following the weekend or holiday and updated here on the following day." We should definitely check the accuracy of these edits.

**Comment by m-sullivan7** [comment]
Updates made to state dashboard and _Vaccination data_ in advance of this reporting frequency going into effect this weekend.
