### ISSUE TITLE
Main menu - Collapse menu on click away

### ISSUE THREAD

**Issue by zakiya** [cagov/covid19#6012]
From @jaredwyee on slack: Think i've mentioned before. It would be nice if you could click off into any non-menu negative space for it to close. It's a convention a like... vs having to aim at the right button to collapse again. But at least you don't have to click the caret. You can click the words too.

Our language picker exhibits my desired behavior

![image](https://user-images.githubusercontent.com/915352/151444089-e9ee4055-05bd-4790-a8fd-3213abad407c.png)

**Comment by zakiya** [comment]
Preview site available at [6012-main-menu-click-collapse.pr.covid19.ca.gov](https://6012-main-menu-click-collapse.pr.covid19.ca.gov/). @jaredwyee @mediajunkie 

cc @jbum

**Comment by jaredwyee** [comment]
Thanks @zakiya  looks good for desktop. 

Assuming the equivalent behavior isn't needed for the main nav on mobile since the hamburger menu drawer slides out to cover most of the phone screen, with the large HOME and CLOSE buttons?

**Comment by jbum** [comment]
Looks good. Ready to merge?  I'll approve the PR...

**Comment by zakiya** [comment]
@jaredwyee I think the mobile behavior is okay but I'm open to other opinions.

**Comment by zakiya** [comment]
@jaredwyee @mediajunkie Can we merge?

**Comment by mediajunkie** [comment]
Yes, please!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by zakiya** [comment]
This is merged. Closing.
