### ISSUE TITLE
Contracts Page- Friday 5/22 contracts EDD/CDT

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#606]
### EDD 
4 in your inbox. 
- Enterprise
- Veteran Enhanced Technology solutions
- Optiv Security
- Deloitte 

**5 more coming**

- Contract number M53530 (Deloitte Consulting LLP) – Call Center
- Contract number M53409-7100 (The iFish Group, Inc.) – IT / Mainframe Consulting
- Contract number M53917 (Eventus Solutions Group, LLC) – Communications Consulting
- Contract number M53564-7100 (The iFish Group, Inc.) – IT / Project Management Consulting
- Contract number M53952-7100 (Outreach Solutions as a Service) –SalesForce

### CDT 
Coming- PUA-NAVA

**Comment by abquirarte** [comment]
Did we get all of these posted? Or are we missing anything?

**Comment by KaylaPrusia** [comment]
These are up and live on the site.

**Comment by abquirarte** [comment]
thank you!
