### ISSUE TITLE
Data and tools: Wastewater dashboard

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6070]
CDPH created a wastewater testing dashboard. They expect to launch it soon. This issue is to evaluate the dashboard and determine whether to add it to _Data and tools_.

**Comment by mediajunkie** [comment]
update is this may be live later this week. will be/include a Tableau
dashboard either on its own page or on the CDPH main covid page

**Comment by m-sullivan7** [comment]
CDPH has released the [wastewater dashboard](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/CalSuWers-Dashboard.aspx). However, I've tested it on two browsers (Firefox and Chrome) and on both of them I cannot see the graph portion of the dashboard, which is the key part. I've cleared my cache as Carlos suggested, but still no luck.

I've sent a screenshot to Carlos to see if we can figure out what's going on. Until that's resolved, I will continue to hold on implementing this.

However, based on the instructions in the page, I do not think that variant types are included in this reporting, just the overall amount of COVID-19 found in wastewater for an area. If that's true, then my recommendation will be to just add this to _Data and tools_. I'll confirm when I actually see and interact with the data.

**Comment by mediajunkie** [comment]
approved
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Link published.
