### ISSUE TITLE
Face coverings and mega-events updates for 2/16

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#6089]
CDPH is rescinding the mask mandate, and reinstating the former threshold for mega-events. Both changes are effective 2/16/22. 

- [x] Draft mask mandate changes to _Masks_ page: https://docs.google.com/document/d/1W5c0cW81W54_GOaTW5FFupznnIiFCKmhJv_Kls3ALBs/edit#
- [x] Draft mega-events changes to _Current safety measures_ page: https://docs.google.com/document/d/1AUcqlSFcKZ0DCbTN0o3gko-7dfCdcXg4rZ0UbVJJZCc/edit
- [x] Draft a homepage banner about lifted mask mandate which points to _Masks_ page
- [x] Get approval through @mediajunkie 
- [x] Stage
- [x] Check
- [x] Publish on 2/15/22
- [x] Check

Source material:
[Attachment 1 Face Coverings Guidance Update FINAL 2.7.2022.docx](https://github.com/cagov/covid19/files/8019699/Attachment.1.Face.Coverings.Guidance.Update.FINAL.2.7.2022.docx)
[Attachment 2 Updated Mega Events FINAL 2.7.2022.docx](https://github.com/cagov/covid19/files/8019701/Attachment.2.Updated.Mega.Events.FINAL.2.7.2022.docx)

**Comment by m-sullivan7** [comment]
Beat me to making this issue! 🙂 Thank you!

**Comment by thepegisin** [comment]
I'm leaving writing the banner to you, @m-sullivan7. Have @mediajunkie run it past the usual suspects for approval.

**Comment by m-sullivan7** [comment]
@mediajunkie Here's a masks-only banner that @LizNobriga and I collaborated on based on the edits Peggy prepared for the _Masks_ page (also part of this issue). We could use this if we publish the afternoon of February 15 or merge with another banner desired by the governor's office.

Note: `mask mandate` is a top search term, so I thought we could best help people by including that somewhere in our banner.

> **Mask mandate ends**
> CDPH no longer requires masks in indoor public spaces if you’re vaccinated. Everyone still needs to wear a mask in some places, like airports and hospitals. Your area may still require masks indoors.
>
> [Find out when masks are still required](https://covid19.ca.gov/masks-and-ppe/#Masks-in-daily-life)

**Comment by m-sullivan7** [comment]
Both pages published. Waiting for approval to publish the banner.

**Comment by m-sullivan7** [comment]
Published banner. All content published and complete.
