### ISSUE TITLE
Mega-events: attendee thresholds and mask requirements changing back

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6095]
Attendee thresholds for mega-events will be 1,000 indoors and 10,000 outdoors effective February 16, 2022. Masks requirements also change on Feb 16, 2022. 

[Proposed edits for _Mega-events_ in google doc](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1)

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you review [proposed edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1) to _Mega-events_ reflecting changes that take effect Feb 16?

**Comment by m-sullivan7** [comment]
I picked up one bit that was probably duplicated by accident. Otherwise, it looks good!

**Comment by LizNobriga** [comment]
@mediajunkie These [proposed edits for _Mega-events_](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1) are ready for stakeholders to review. The edits reflect the changes that take effect on February 16, 2022 for mega-event attendee thresholds and mask rules. 

Ideally these would be approved and ready to publish either end of day on Feb 15 or first thing on the morning of Feb 16. 

These _Mega-events_ edits could be packaged for review with Peggy's edits to _Masks_ and _Current safety measures_.

**Comment by LizNobriga** [comment]
@mediajunkie Forgot to include that these edits are also in [staging](https://staging.covid19.ca.gov/mega-events/).

**Comment by mediajunkie** [comment]
Thanks. I'm meeting with Devon from CDPH and Tonya from GO by Monday to
coordinate this rollout and will try to get all our related edits approved
together.

**Comment by mediajunkie** [comment]
in review with Trudy (CDPH G&P)

**Comment by LizNobriga** [comment]
Published
