### ISSUE TITLE
Hotlines and local info: update some county links

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6102]
Review county links on [_Hotlines and local info_](https://covid19.ca.gov/get-local-information/) and update websites that are outdated.

[Draft](https://docs.google.com/document/d/122Ykc18Y7XeQik856nsGovi7hv9iydy8jynX39amO5o/edit#)

**Comment by LizNobriga** [comment]
@mediajunkie Okay to make these [edits](https://docs.google.com/document/d/122Ykc18Y7XeQik856nsGovi7hv9iydy8jynX39amO5o/edit#) to update some of the county links?
cc @m-sullivan7

**Comment by mediajunkie** [comment]
Yes!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>
