### ISSUE TITLE
Banner: paid sick leave

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6125]
We will need a new banner for after the Super Bowl. I propose one highlighting the passage of supplemental paid sick leave for COVID. This bill was signed by the governor on February 9, 2022.

[Google Doc with draft banner](https://docs.google.com/document/d/1pGhrWHVUgXVNfPETptRe1jayH38jlbaV6eyNKjL7qSw/edit?usp=sharing)

**Comment by m-sullivan7** [comment]
@mediajunkie Here's a potential banner we can use on Monday to replace what will be an outdated Super Bowl banner.

> **Supplemental sick leave now available**
> Most Californians can get up to 80 hours for time off work as a result of COVID-19. It is retroactive to January 1, 2022.
>
> [Read the details](http://cert1.mail-west.com/3Wyj3J/uzjanmc7rm/sqt96m813Wgtmy/Wqvnq3Wq1xgjhz/6m813/ocya/fzm9ayklyz?_c=d%7Cze7pzanwmhlzgt%7C18z6nlpbxln9zms&_ce=1644599632.9f43065fa8e9110d2ed366324af43367)

There could be a minor complication: Liz shared that the [Industrial Relations COVID site](https://www.dir.ca.gov/covid/) says the "law is expected to take effect on February 19, 2022." That might make Monday premature. If so, I can stash this for February 21, 2022, (since the 19th is a Saturday) and think on another banner for Monday.

**Comment by mediajunkie** [comment]
approved for Monday

**Comment by m-sullivan7** [comment]
New banner published. Thanks!
