### ISSUE TITLE
Holidays: Remove Super Bowl info

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6136]
With the Super Bowl over, @thepegisin and I propose reverting the _Travel_ page to the previous version with the added tweak of removing the previous image, which was fall-themed.

**Comment by mediajunkie** [comment]
approved
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Actually, now that I'm in the _Travel_ page (and seeing nothing Super Bowl-related), I realized this is actually about _Holidays_. 🙃
