### ISSUE TITLE
Testing: add isolation guidance for under 2

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6156]
We received upcoming new guidance for childcare facilities. Included were recommendations for isolation for children. They had the following differences from the standard recommendations:

- If under 2: end isolation on day 5, no negative test required
- If 2 or older: end isolation on day 5, testing recommended

This issue is to add this detail to our _Testing_ page.

**Comment by thepegisin** [comment]
Published 3/9/22.
