### ISSUE TITLE
Endemic plan page updates

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6168]
The endemic plan may result in updates to other pages. This issue is to review other pages assigned to Peggy and me for impacts and to edit them as necessary.

Pages with edits (links to Google Docs with changes):

- [Current safety measures](https://docs.google.com/document/d/1AUcqlSFcKZ0DCbTN0o3gko-7dfCdcXg4rZ0UbVJJZCc/edit?usp=sharing)
- [Testing](https://docs.google.com/document/d/18NG21vDRhqR4Y795Mi1ibYhcuJd1F_EGHiVJKIZrKyo/edit?usp=sharing) (there may not be any changes--I've called out a few areas via notes where current and proposed edits run contrary to a statement in the plan summary doc)
- Health equity is a page that could possibly be impacted by the endemic plan, but there's nothing that is specifically out-of-date (it's more generally out-of-date). The CDPH edits that are part of #5113 will probably address this, but flagging it here just in case.

**Comment by m-sullivan7** [comment]
@mediajunkie I reviewed Peggy's and my pages for potential impacts based on what we know about the plan right now. The description of the issue contains where there are possible impacts. Right now, the only page I know for sure is impacted is _Current safety measures_.

**Comment by mediajunkie** [comment]
Checking again.

**Comment by thepegisin** [comment]
Approved and published 3/11/22.
