### ISSUE TITLE
Current safety measures: update images

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6171]
There are four images on _Current safety measures_ that could be updated.

- [x] **Masks**
Education and childcare - keeping
Travel - keeping
- [x] **Mega-events**

**Masks**

CDPH pointed out that some people in this image are not using recommended respirators.

![image](https://user-images.githubusercontent.com/69169190/154546032-6afb0cc9-1d61-410f-92a7-2e73748c3382.png)

They provided two possible replacements from Getty Images.

- [Single person wearing a KN95](https://www.gettyimages.com/detail/photo/woman-wearing-kn95-protective-mask-outdoors-royalty-free-image/1312564093?adppopup=true)
- [Group of people wearing KN95s](https://www.gettyimages.com/detail/photo/group-of-college-students-wearing-protective-face-royalty-free-image/1268509639?adppopup=true)

**Education and childcare**

@LizNobriga points out that masks are required for everyone in education and childcare settings and our current image does not feature anyone wearing a mask.

**Travel**

CDPH also highlighted the person in this image is not wearing a recommended level of respirator.

![image](https://user-images.githubusercontent.com/69169190/154546285-bbe5b7ee-938d-44b6-874c-2204e0035d66.png)

They provided an [image of a person on a bus wearing a KN95](https://www.gettyimages.com/detail/photo/woman-in-public-bus-transport-royalty-free-image/1305287595?adppopup=true).

**Mega events**

The card depicts Staples Center. This venue has changed its name to Crypto.com Arena. This issue is to update the image with:

- One that reflects the new name of the venue
- A different venue in California (preferably an indoor venue) to reflect the many venues throughout the state. Potential alternates include:
  - SAP Center in San Jose
  - Golden 1 Center in Sacramento
  - Honda Center in Anaheim
  - Chase Center in San Francisco

This is not an urgent issue (especially with endemic plan work going on), but a nice to do item.

**Comment by m-sullivan7** [comment]
@adam-little Definitely not urgent, but did you assist Peggy in creating the mega-events image on _Current safety measures_? We should probably replace it since Staples Center has been renamed.

![image](https://user-images.githubusercontent.com/69169190/154372114-74e4daac-1c2e-47b4-8f34-b25b72b5bd10.png)

**Comment by m-sullivan7** [comment]
I've added a fourth image that should probably be replaced: the _Education and childcare_ image, based on thoughts from @LizNobriga

**Comment by adam-little** [comment]
> @adam-little Definitely not urgent, but did you assist Peggy in creating the mega-events image on _Current safety measures_? We should probably replace it since Staples Center has been renamed.
> 
> ![image](https://user-images.githubusercontent.com/69169190/154372114-74e4daac-1c2e-47b4-8f34-b25b72b5bd10.png)

The image came from Unsplash (https://unsplash.com/photos/cBWgXg-hYNs).

More recently, Jared has been asking RSE (agency) to provide images because they have a stock photo license for Getty images.

**Comment by m-sullivan7** [comment]
Thanks for providing info about where they came from @adam-little and how we're sourcing images now! That's helpful.

@jaredwyee alerting you that there are four images on _Current safety measures_ that could use updating. A couple of them were pointed out by CDPH. I don't think any of these are super urgent, but leave it to you to discern the ultimate priority. 🙂

**Comment by jaredwyee** [comment]
For the masks ones, can update to the new hero banner. The masks image is from the prior hero. And nice that they supplied a travel/bus example.

@mediajunkie leaving to you

**Comment by m-sullivan7** [comment]
I'd appreciate some assistance getting the image sizing correct for the masks banner. The most sophisticated tool I have for that is Microsoft Paint. 😉

**Comment by kmbrlygl** [comment]
@m-sullivan7 here ya go :) I matched the file name (card-masks.jpg) and size (1308x888) to the one on the website:
![card-masks](https://user-images.githubusercontent.com/20393247/154762526-ccd109dc-44d3-4588-84b3-b6f305f41125.jpg)

**Comment by m-sullivan7** [comment]
@mediajunkie Do you want me to stage this updated image for masks for approval before publishing or is it OK to publish if all looks good when staged?

**Comment by mediajunkie** [comment]
OK to publish if staging looks fine.

**Comment by thepegisin** [comment]
I will publish the masks image, and check on the status of the other images.

**Comment by thepegisin** [comment]
Masks image now replaced.

**Comment by thepegisin** [comment]
I don't think we need to change the education & childcare image. We intentionally chose a photo that shot people from behind so their masked or unmasked state wouldn't be an issue. And masks will no longer be required in two days. Recommend we leave the current image as-is.

**Comment by thepegisin** [comment]
Travel image: 
- Not sure what's wrong with the mask in the current image. It's a well-fitted surgical mask, which offers the same level of protection as the KN95 mask in their suggested new image, and also in our Masks image.
- Nice that CDPH pointed to an image they like, but it's something we'd have to buy/source through RSE, and it's less obvious that the person in the photo is traveling, IMO.

**Comment by thepegisin** [comment]
Mega-events image:

- This should definitely change. The old venue name makes it outdated.
- @kmbrlygl , could you source us images based on Michael's list above?

**Comment by kmbrlygl** [comment]
It's hard to get free photos of the Centers and Arenas. Even on Adobe Stock, their license only allows for editorial use.  

Would we be open to something more ambiguous? Here's [a photo](https://unsplash.com/photos/XmYSlYrupL8) I found. I can't tell where it's at and surprisingly no clear endorsements or ads (except for the tiny Nike swooshes if you look closely).

**Comment by kmbrlygl** [comment]
@thepegisin here's the photo to spec:

![card-events](https://user-images.githubusercontent.com/20393247/157924361-1b1e4e04-04dc-4374-aef5-9282d3aa6899.jpg)

**Comment by thepegisin** [comment]
Thank you, @kmbrlygl! This image is now replaced on _Current safety measures_. Closing this ticket.

**Comment by kmbrlygl** [comment]
@thepegisin no problem! I noticed the alt text still references Staples Center
