### ISSUE TITLE
Potential vaccines content improvements

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6174]
I noticed a few things on the _Vaccines_ page that might need to be updated:

- In the _How COVID-19 vaccines work_ section, the language about no one dying during the vaccination trials and the chance of dying after vaccination seems like it might be out-of-date based on recent data from the Omicron surge. I recommend taking another look at it to see if we should suggest updates. Here are the sentences that caught my eye:
  - "No fully-vaccinated person died due to COVID-19 during clinical trials of the vaccines."
  - "That means it is possible you could still get COVID-19 after vaccination."
  - "[Post-vaccination cases](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Post-Vaccine-COVID19-Cases.aspx) are rare, but happen."
  - "COVID-19 vaccines are effective against many [variants](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/COVID-Variants.aspx) of the virus, including Delta."
- The _Vaccines and variants_ section also feels like it may be in need of updating now that we know more about Omicron.
  - "We don’t yet know how effective it will be against emerging variants like Omicron."
- I noticed some use of negative contractions, like in the example above. Also:
  - "If you couldn’t get your vaccine record, you may need to correct or add some information."
  - "Your vaccination site didn’t report your vaccination"
  - "The information you entered doesn’t match your record in the registry"
  - "If you can’t get it at the recommended interval, you can get your second dose up to 6 weeks (42 days) after the first dose."

I leave this issue for @thepegisin as she may know reasons why this content is the way that it is that I'm unaware of as the temporary caretaker of this content. These edits are not urgent.

**Comment by mediajunkie** [comment]
I'm fine with these changes if @thepegisin is

**Comment by thepegisin** [comment]
Will stage and publish

**Comment by thepegisin** [comment]
Actually, I may not make all these changes. Some are still accurate, though I will likely update any statement that seems to point to Delta as the most recent variant.

As for the negative contractions, they mostly track with the language people have used when talking about these issues, so I'll keep them.

**Comment by m-sullivan7** [comment]
I have total trust in the direction you go with them. Like I said, there could be good reasons things are done the way they are! I just thought I'd leverage an outsider's perspective to let you know what I saw. 🙂

**Comment by thepegisin** [comment]
Appreciate your keen eye, as always @m-sullivan7 !

**Comment by thepegisin** [comment]
Changes published 3/9/22.
