### ISSUE TITLE
Housing and rent: Rent relief  and eviction protection ends March 31, 2022

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6178]
End of rent relief program and eviction program on March 31, 2022.

[Draft](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit)

**Comment by m-sullivan7** [comment]
These are great edits. No changes or suggestions from me!

**Comment by LizNobriga** [comment]
@mediajunkie Do you want to share this with stakeholders first or is it okay to publish and send a heads up?

View _Housing and rent_:
- In [staging](https://staging.covid19.ca.gov/housing-and-homelessness/)
- [Edits](https://docs.google.com/document/d/1vvbvdMJLP9LZ5KQwKJ1WY-bHez675MtFp1QUFhEFZns/edit#heading=h.22b8311ev4ze) in the google doc

**Comment by mediajunkie** [comment]
I think it's OK to publish and then let them know. I'm trying to do that more with straightforward and factual stuff. 

OK to push Monday given how late it already is on Friday.

**Comment by LizNobriga** [comment]
Ok, will publish on Monday and let you know.

**Comment by mediajunkie** [comment]
+1
