### ISSUE TITLE
Education and childcare: update masks requirement for K-12

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6184]
[2/28/22 announcement](https://www.gov.ca.gov/2022/02/28/governors-newsom-brown-and-inslee-announce-updated-health-guidance/): 

> After March 11, in schools and child care facilities, masks will not be required but will be strongly recommended. 

See [edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#). 

Related tickets:
- #6269 
- #6270 

Summary of edits (for all 3 tickets):
- Update to reflect release of updated schools guidance effective after March 11
- Update mask policy change for both schools and childcare effective after March 11
- Add childcare links:
  - [Decision Tree for Sick Child or Positive COVID Test in Child Care](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/Child%20Care%20Guidance%20When%20Child%20Is%20Sick%20or%20Tests%20Positive.pdf)
  - [Decision Tree for COVID-19 Exposures to Children in Child Care](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/COVID-19-Exposure-For-Children-In-Child-Care.pdf)

**Comment by LizNobriga** [comment]
@m-sullivan7 I updated this ticket in preparation for March 12 mask policy changes for k-12 and childcare. I incorporated notes/edits into the current [draft](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#) awaiting approval to publish (but did not move these newer edits/comments into staging since they cannot publish before March 12).

For higher ed, it's not totally clear what applies. I think it would be the same as the March 1 policy (masks strongly recommended for everyone indoors).

**Comment by m-sullivan7** [comment]
The March 12 edits look good to me!

**Comment by LizNobriga** [comment]
FYI @m-sullivan7 @mediajunkie Added a highlight box for the school mask policy change to the [google doc edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#) and to [staging](https://staging.covid19.ca.gov/education/). Screenshot included:
<img width="974" alt="image" src="https://user-images.githubusercontent.com/58706834/156680558-e75bb668-66f0-465c-8638-82faaf8f2102.png">

**Comment by mediajunkie** [comment]
These are approved.

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you review the [edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#) when you have a chance? Lmk if you have any questions.

**Comment by LizNobriga** [comment]
@mediajunkie Here are the [proposed edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#) for _Education and childcare_. 

Summary of edits:
- Update to reflect release of updated schools guidance effective after March 11
- Update mask policy change for both schools and childcare effective after March 11
- Add childcare links:
  - [Decision Tree for Sick Child or Positive COVID Test in Child Care](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/Child%20Care%20Guidance%20When%20Child%20Is%20Sick%20or%20Tests%20Positive.pdf)
  - [Decision Tree for COVID-19 Exposures to Children in Child Care](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/COVID-19-Exposure-For-Children-In-Child-Care.pdf)

I'll get these in staging and let you know.

**Comment by LizNobriga** [comment]
@mediajunkie _Education and childcare_ [edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#) are ready in [staging](https://staging.covid19.ca.gov/education/).

**Comment by LizNobriga** [comment]
Published:smiley:
