### ISSUE TITLE
Mega-events: update testing location link

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6192]
CDPH stakeholders have requested that we now point to MyTurn when helping people find testing locations. We've made this change on the _Testing_ page (https://github.com/cagov/covid19/issues/6055).

I searched WordPress for `arcgis` and noticed that we use this link on _Mega-events_ in this content in the _Indoor events_ section:

> [Find a testing location](https://www.arcgis.com/apps/Nearby/index.html?appid=43118dc0d5d348d8ab20a81967a15401) in your area.

I believe you can update this content whenever you have a moment @LizNobriga. I do not think this is on CDPH's radar.

cc: @mediajunkie for visibility

**Comment by m-sullivan7** [comment]
Updating based on a good suggestion from Christian: here's the link to use that takes people directly to the testing section of MyTurn:

https://myturn.ca.gov/testing.html

**Comment by LizNobriga** [comment]
Published link update.
