### ISSUE TITLE
Masks: Unvaccinated mask requirement

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6224]
From governor press release:

> In California, starting March 1, masks will no longer be required for unvaccinated individuals, but will be strongly recommended for all individuals in most indoor settings. After March 11, in schools and child care facilities, masks will not be required but will be strongly recommended. Masks will still be required for everyone in high transmission settings like public transit, emergency shelters, health care settings, correctional facilities, homeless shelters and long-term care facilities. As always, local jurisdictions may have additional requirements beyond the state guidance.

This issue is to update unvaccinated mask requirements on _Masks_ and to draft a banner for the homepage.

I reviewed _Holidays and COVID-19_, _Travel_, _Vaccines_, and _Testing_, but did not find any content that talks about mask requirements for the unvaccinated.

**Comment by m-sullivan7** [comment]
@mediajunkie  Here are my [preliminary recommended edits to the Masks page](https://docs.google.com/document/d/1W5c0cW81W54_GOaTW5FFupznnIiFCKmhJv_Kls3ALBs/edit?usp=sharing) to respond to today's announcement. (Apologies for the multiple edits, some of which are live. This is Peggy's preference while she's out. I can send you a clean version if needed.)

I think I need to check my suggestions against any guidance that Carlos gets. Specifically:
Is the requirement for employers to require unvaccinated workers (minus certain exceptions) ending too?
Is the requirement for unvaccinated workers in state offices ending too?

I also [wrote a banner](https://docs.google.com/document/d/1pGhrWHVUgXVNfPETptRe1jayH38jlbaV6eyNKjL7qSw/edit?usp=sharing) for tomorrow to go live with these edits. (If the edits lag, we could link to the press release, but it wouldn't be as good of a link.)

**Comment by mediajunkie** [comment]
TY
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Banner and changes published.

**Comment by m-sullivan7** [comment]
Reopening issue to deal with additional changes as a result of the governor's executive order.

@mediajunkie: I think that this is what the updated copy should be for the section highlighted by the governor's office. I am unsure about the last bullet. It does not appear to be explicitly repealed by the executive order.

> **Masking at work**
> Cal/OSHA has aligned workplace mask requirements with general mask guidance from the CDPH.
> 
> - **Masks are strongly recommended indoors.** 
>   - In outbreaks, all employees must wear masks indoors and outdoors when six feet of physical distance cannot be maintained.
> - **Masks are not required outdoors** (except during outbreaks). Workers should be trained for outdoor use of face coverings.
> - **Employers must provide unvaccinated employees with NIOSH-certified respirator masks** for voluntary use when:
>   - Working indoors, or 
>   - In a vehicle with others.
> - **Unvaccinated workers must wear masks in state offices.**

I have questions about this associated content in _Masks_. I can ask this directly of the governor's office if you want.

> **Which employers must require employees to wear masks under certain conditions?**
> 
> The [Cal/OSHA COVID-19 Prevention Emergency Temporary Standards](https://www.dir.ca.gov/dosh/coronavirus/ETS.html) (ETS) applies to all employers, employees, and to all places of employment. Employers must require unvaccinated employees to wear masks indoors, with the following exceptions:
> 
> - Work locations where there is only one employee who does not have contact with other people
> - Employees who are working from home
> - Employees who are covered by the [Aerosol Transmissible Diseases regulation](https://www.dir.ca.gov/title8/5199.html)
> - Employees working from a location chosen by the employee, which is not under the control of the employer (for instance, an employee teleworking from a café or a friend’s home).
> ...
> State employees who work on-site and are unvaccinated must also wear masks. This is outlined in [CalHR’s Vaccine Verification and Testing Requirements](https://www.calhr.ca.gov/Documents/Vaccine-Verification-and-Testing-Requirements.pdf).

> **What are the mask requirements at workplaces?**
> 
> [CalHR’s Vaccine Verification and Testing Requirements](https://www.calhr.ca.gov/Documents/Vaccine-Verification-and-Testing-Requirements.pdf) say that state employees who work on-site and are unvaccinated must wear masks at work.

**Comment by mediajunkie** [comment]
please feel free to follow up directly
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Governor's office has provided updated copy and OKed several other changes. These are all published.
