### ISSUE TITLE
Address open issues in CDT Accessibility report

### ISSUE THREAD

**Issue by jbum** [cagov/covid19#6225]
CDT provided us with an accessibility report for the State-dashboard page which lists various issues reported by the Axe tool with the usage of Aria on the charts and UI on that page.

I've copied the report here:

https://docs.google.com/document/d/1UwkZnq-QFCLJQj_bSEtbfr3Kv33sGqUuFNfM2bwzdtQ/edit?usp=sharing

There are too many issues in the report to open up individual tickets, but we can use the comment feature in Google docs to go through the issues.

I am currently addressing some of the low-hanging fruit, such as duplicate IDs.

**Comment by jbum** [comment]
Currently preparing patches for issues #3 and #4.

**Comment by zakiya** [comment]
Can we close this now?

**Comment by jbum** [comment]
Yep :)
