### ISSUE TITLE
Mega-events: update mask policy changes

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6230]
Starting March 1, masks are not required for unvaccinated people indoors. They are strongly recommended for everyone. 

[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) to update mask policy on _Mega-events_.

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you please review?

**Comment by m-sullivan7** [comment]
Looks good to me!

**Comment by LizNobriga** [comment]
@mediajunkie Edits to update _Mega-events_ with the new mask policy are ready for review in [staging](https://staging.covid19.ca.gov/mega-events/). 

Masks are covered in two places on the _Mega-events_ page:
- Indoor events
- Outdoor events

Proposed edits are shown in the [google draft](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#).

**Comment by LizNobriga** [comment]
Hi @mediajunkie. Thanks for forwarding the email with the updated mega-events guidance that CDPH published Friday. I reviewed it and confirmed our [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) in [staging](https://staging.covid19.ca.gov/mega-events/) are consistent. Let me know when we can publish or if you need anything else.

Also including two screenshots of the mega-events mask update (indoor and outdoor). 
![mega-events-indoor-mask-update](https://user-images.githubusercontent.com/58706834/157107667-640b1a51-e937-403d-9821-6eb5b6011ff7.png)
![mega-events-outdoor-mask-update](https://user-images.githubusercontent.com/58706834/157107692-b692051c-d94c-45d4-886b-ded4ebf10ad0.png)

**Comment by mediajunkie** [comment]
This is approved.

**Comment by LizNobriga** [comment]
Published
