### ISSUE TITLE
Testing: second round of free federal COVID tests

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6238]
The federal government will offer a second round of 4 free COVID home tests, as announced during the State of the Union. They expect to begin taking orders in the week of March 7. This issue is to update the _Testing_ page to let people know they can order another set. I recommend that we include a highlight box for people visiting the page.

**Comment by m-sullivan7** [comment]
@mediajunkie edits!

[Testing page](https://docs.google.com/document/d/18NG21vDRhqR4Y795Mi1ibYhcuJd1F_EGHiVJKIZrKyo/edit?usp=sharing) itself. Here's the key text:

> You can now get 8 free at-home tests shipped to you by the U.S. government. Limit is two shipments of 4 tests per household, beginning the week of March 7, 2022.

I also wrote a banner for whenever the tests go live next week. I used Peggy's previous banner on this topic as inspiration. As you can see, it's pretty close.

> **Get 4 more at-home COVID-19 tests for free**
> You can now get more free at-home tests shipped to you by the U.S. government. Limit is two shipments of 4 tests per household.
>
> [Get free test kits](https://special.usps.com/testkits)

**Comment by thepegisin** [comment]
Testing page updated and banner published.
