### ISSUE TITLE
Testing: Update flyer links

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6240]
From Carlos at CDPH:

> On your [Testing subnav page under When to Isolate Quarantine](https://covid19.ca.gov/get-tested/#when-to-isolate-or-quarantine), you all link to our flyers, [self-isolation instructions](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/self-isolation-instructions.pdf) and [self-quarantine instructions](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/selfq_handout.pdf). Could we instead link to the two pages above? Might be worth to revamp copy too. Molly can help jump in (and also happy to meet) but the difference is that the 2 new pages include a couple new steps beyond Isolation and Quarantine, which are both a step of [What to do if You Test Positive for COVID-19](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/What-to-do-if-You-Test-Positive-for-COVID-19.aspx) and [What to Do If You Are Exposed to COVID-19](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/What-to-Do-If-You-Are-Exposed-to-COVID-19.aspx).

This issue is to review the new resources, update the links and any surrounding content as appropriate.

**Comment by m-sullivan7** [comment]
@mediajunkie These edits are related to #6119, which proposed adding the links Carlos requested. I've put in new edits to remove the PDF flyer as part of them. The revised content would read:

> Learn more in [What to Do if You Test Positive](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/What-to-do-if-You-Test-Positive-for-COVID-19.aspx) from CDPH.

> Learn more in [What to Do if You Are Exposed](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/What-to-Do-If-You-Are-Exposed-to-COVID-19.aspx) from CDPH.

I can move these edits independently from the others if needed.

**Comment by mediajunkie** [comment]
I think we can go ahead an add these, since they were requested?

**Comment by thepegisin** [comment]
Published 3/9/22.
