### ISSUE TITLE
Update Testing page isolation/quarantine guidance per new docs and SMARTER plan

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#6244]
Carlos Sanchez from CDPH requested these changes by email. Went to me and Michael as Xian was out. This ticket will deal with the changes he requested. Another ticket will handle elevating the isolation/quarantine info as a whole.

- [x] Draft changes: https://docs.google.com/document/d/18NG21vDRhqR4Y795Mi1ibYhcuJd1F_EGHiVJKIZrKyo/edit#
- [x] Send to @mediajunkie for approval
- [x] Get approval
- [x] Stage
- [x] Check
- [x] Publish
- [x] Check

**Comment by mediajunkie** [comment]
Please go ahead and make these changes, as they were directly requested by Carlos.

**Comment by thepegisin** [comment]
Now published.
