### ISSUE TITLE
Draft a Banner Tuesday 5/26

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#633]
Please draft banner language that we can circulate to GO for review.

I think it can be very similar if not the same as when we last released update guidance both statewide and for counties. 

**Announcement:** We are moving hair salons for counties with variance. 

**Link to**: https://covid19.ca.gov/roadmap-counties/ 
(we will be adding guidance accordion there).

**Comment by KaylaPrusia** [comment]
Governor Newsom announced the re-opening of hair salons for counties that have been approved to move further ahead in Stage 2. [Read the guidance](https://covid19.ca.gov/roadmap-counties/), find industry-specific checklists and learn more about [California's resilience roadmap](https://covid19.ca.gov/industry-guidance/).

@abquirarte

**Comment by abquirarte** [comment]
Sweet! Thank you @KaylaPrusia! 
Sending over for approval

**Comment by KaylaPrusia** [comment]
Banner: Governor Newsom announced [hair salons may re-open](https://covid19.ca.gov/roadmap-counties/) in counties that have been approved to move further ahead in Stage 2. Retail services and places of worship are open under new statewide guidance. Read the guidance, find industry-specific checklists and learn more about [California's resilience roadmap](https://covid19.ca.gov/industry-guidance/).

@abquirarte

**Comment by thepegisin** [comment]
Churches reopening is going to be a big search today, and the guidance is our only content for that. Suggest you lose the last sentence and link "Retail services" and "places of worship" to their respective guidance. (Roadmap is already linked right above that.)

**Comment by abquirarte** [comment]
This is what came back to us (approved):

Governor Newsom announced that counties approved for accelerated reopening
can begin to reopen hair salons and barbershops. Statewide, retailers and
places of worship can reopen with modifications. Read the new guidance,
find industry-specific checklists and learn more about California's
resilience roadmap.

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by KaylaPrusia** [comment]
@abquirarte title of banner: **Update to Statewide Guidance**
?

**Comment by abquirarte** [comment]
that works! 
:)
woah, formatting from email response sucks lol.

**Comment by KaylaPrusia** [comment]
lol it's not so bad. Banner is live

**Comment by abquirarte** [comment]
thank yooou!
