### ISSUE TITLE
Mega-events: updated guidance takes effect April 1, 2022

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6332]
From draft shared by CDPH:
> Effective April 1, 2022, requirements for vaccine verification or proof of negative test for Indoor Mega Events will be lifted and move to a strong recommendation.

~~Add highlight box for April 1 changes~~ - DONE

Proposing edits to publish April 1 (when new changes take effect. See [draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit).

**Comment by m-sullivan7** [comment]
Reviewed and all looks good. I left one comment with a potential edit that's discretionary.

**Comment by LizNobriga** [comment]
@xian Is this highlight box okay to publish to _Mega-events_?
![image](https://user-images.githubusercontent.com/58706834/159090852-44830800-2475-4395-86ba-e624ced7c01a.png)
See [draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit) in google doc.

**Comment by LizNobriga** [comment]
@mediajunkie See the highlight box on [staging](https://staging.covid19.ca.gov/mega-events/). Okay to publish?

Thanks @jbum for fixing the highlight box issue!

![image](https://user-images.githubusercontent.com/58706834/159094124-40149b17-5efd-4ea6-8922-18a4fcafef30.png)

**Comment by LizNobriga** [comment]
The highlight box is published, but I'm keeping this ticket open because we'll need to make more edits when these changes actually take effect on April 1. Moving this ticket to To-do.

**Comment by LizNobriga** [comment]
Hi @mediajunkie. The changes to indoor mega-events take effect on April 1 (vaccination or negative test for entry to indoor mega-events changes from required to strongly recommended). These are [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#) to ideally publish on April 1 to update the indoor mega-events content. Could you see if we can ask for stakeholder approval by March 30 (since March 31 is a holiday)? 

- See [edits in the google doc](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit?pli=1#), or in the Word doc copy attached: [covid19.ca.gov_Edits for April 1 changes to indoor mega-events.docx](https://github.com/cagov/covid19/files/8327932/covid19.ca.gov_Edits.for.April.1.changes.to.indoor.mega-events.docx)
- See [page staged](https://staging.covid19.ca.gov/mega-events/) with edits

Also planning to remove the highlight box currently on the page around mid-April.

**Comment by m-sullivan7** [comment]
Published edits on behalf of @LizNobriga
