### ISSUE TITLE
State dashboard: CDPH age page and negative cases

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6341]
Two updates to the state dashboard page:

- Add the more finely sorted [CDPH age tables](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Age-Race-Ethnicity.aspx) to our demographic section as a hyperlink.
- Capture the following thoughts related to negative cases (as can be found for San Francisco and Santa Clara in last week's data):

> I think we should point out cleaning, data quality assurances, and deduplication as the cause of negative case counts.
> Only report date has negatives because of how its calculated (net new).  And episode date will never have negative.
> Any note about this should emphasize how it is an artifact of reporting delays and that episode date is the best source of data over time.

**Comment by m-sullivan7** [comment]
@mediajunkie [Proposed edits](https://docs.google.com/document/d/1oltQcCJjsMs_DLT4jk7eHa88RNpXkZTPpNwqxJyA_wE/edit?usp=sharing) to address yesterday's state dashboard improvement discussions.

**Comment by mediajunkie** [comment]
approved. please let me know when live.

**Comment by m-sullivan7** [comment]
Changes are live after a delay while the site worked through a bunch of translation updates. Closing this issue.
