### ISSUE TITLE
Quick wins for today Tuesday 5/26

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#636]
- [x] Page header and nav labels inconsistent (propose language)
- Stay home 
- county variance 
- State reopening/ Roadmap
@thepegisin want to take these on? ☝️ I can give you context :) 
- [ ] add timestamp back to home page @artuoma 
- [x] add "California" to homepage "California numbers" @artuoma 
- [x] Reorder how you can help section
- [x] Update image thumbnail for the roadmap page/county variance page 
- [x] Make search more integrated.

**Comment by thepegisin** [comment]
How you can help section re-ordered by page popularity:

- Meals for seniors
- Contact tracing
- Health Corps
- Plasma
- Discrimination
- Then the next five links, which are on different domains

**Comment by thepegisin** [comment]
Proposed this language in 5/27  OI team prototype:

- What's open
- Stay at home order
- Reopening guidelines

**Comment by abquirarte** [comment]
Closing for now, but flagging for @artuoma - should we add timestamp back to homepage? Or will that confuse it with the daily data updates?
