### ISSUE TITLE
Mega-events: add safe and smart events playbook

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6405]
~~CDPH has not published this safe and smart events playbook yet.~~

CDPH published the Safe and SMART Events Playbook on 4/1/22: https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/Events-Playbook.pdf

**Comment by m-sullivan7** [comment]
I think they're great edits! Concise and clear! No edits from me. 🙂

**Comment by LizNobriga** [comment]
@mediajunkie The [edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit#) to add the new [events playbook](https://www.cdph.ca.gov/Programs/CID/DCDC/CDPH%20Document%20Library/COVID-19/Events-Playbook.pdf) to _Mega-events_ are ready in [staging](https://staging.covid19.ca.gov/mega-events/#organizing-safe-events). Do we need stakeholder approval to publish?

**Comment by mediajunkie** [comment]
Ok to publish.
-- 
Christian Crumlish
Product Manager | Office of Innovation
covid19.ca.gov . cannabis.ca.gov . digital.ca.gov
415-672-5759 | ***@***.***

**Comment by LizNobriga** [comment]
Edits published
