### ISSUE TITLE
SNF new page/content to be added to the website 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#641]
### Proposed Content 

https://docs.google.com/document/d/13kEy9AgzUKjaWPhKsNdwXzMegY-GmUEm/edit

### Content Captain 

@thepegisin @ashleydraper 

### Timeline 
Tuesday noon

**Comment by ashleydraper** [comment]
A draft of the new page is posted [here](https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=3788&action=edit). 
I don't see where this will sensibly live if not on its own, it doesn't seem to work well with the healthcare page.
@TamaraIDEJA @abquirarte

**Comment by thepegisin** [comment]
- [x] Readability edit made: https://docs.google.com/document/d/13kEy9AgzUKjaWPhKsNdwXzMegY-GmUEm/edit

**Comment by abquirarte** [comment]
Added a few comments! @thepegisin @ashleydraper 

@TamaraIDEJA OK to post once these comments are resolved? Or should we run by SMEs?

**Comment by TamaraIDEJA** [comment]
The SME reviewed our draft in staging and proposed new edits: please review accept changes or let us know if we need to push back on any of these changes: https://docs.google.com/document/d/1tP2h5RSn8_sHHlHBgVYpTUZhPXyBUuln7D7IqQN9KH8/edit

**Comment by ashleydraper** [comment]
Page is live, propose closing the issue
@TamaraIDEJA @abquirarte

**Comment by thepegisin** [comment]
For homepage nav link, I suggest we put **Senior living** under **Working and living safely** @abquirarte

**Comment by abquirarte** [comment]
That works!
