### ISSUE TITLE
More contracts 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#643]
_I do not have the pdfs yet. Still working through long term solution with GovOps and GO._ 

**HCD**
Enterprise Solutions:$485k to assist task force with developing strategies to address housing insecurity, affordability and homelessness. 

**CDPH**
Goodwill Industries: Up to $7.5M to add capacity to support 15,000 calls/day to 211 centers in 53 counties.  No legal concerns.  Up to 350 additional staff to triage and provide basic information, 24/7 availability.

**DGS**
Turner Construction Co: $1.75 million to provide full essential temporary services for the mechanical, electrical low voltage, and plumbing systems to support the Federal Medical Station at the Riverside County Fairgrounds.

Interstate Oil Co: $608,150 to provide food mover services to the Alternate Care Site at Porterville Developmental Center.

All Clean Emergency Services: $534,750 to provide laundry services to the Alternate Care Site at Fairview Developmental Center.  Includes aerial map already in public domain.

Chef’s Catering: $1.268 million to provide meal services to occupants of the Alternate Care Site at Fairview Developmental Center.

McGrath’s Catering: $1,356,678 to provide meal preparation, delivery and pick up to support the Field Medical Station #2 in Riverside.

Service Master Restoration: $9,176,718 to provide environmental cleaning services to support the Alternate Care Facility at the Porterville Developmental Center.

Service Master Restoration (Amendment 1): decreases the above referenced SMR environmental cleaning services contract at PDC by $531,432 so that the total contract won’t exceed $8,645,286.

Service Master Restoration: $10,484,163 to provide environmental cleaning services to support the Alternate Care Facility at the Fairview Developmental Center.  

Express Relief Services: $1,218,720 to provide full shower trailer rental services, including COVID-19 containment to support the Alternate Care Facility at the Porterville Developmental Center.

Interstate Oil Co: $572,00 to provide temporary lighted warehousing capability to the Alternate Care Site at Porterville Developmental Center.

Mission Linen Supply: $434,657 to provide linen services to support patients at the Alternate Care Site at Fairview Developmental Center.  

Interstate Oil Co: $1.656 million to provide full water truck services, including COVID-19 containment to support the Field Medical Station at the Santa Clara County Convention Center.

Interstate Oil Co: $1.656 million to provide full water truck services, including COVID-19 containment to support the Field Medical Station #2 in Riverside.

Interstate Oil Co: $486,716.30 to provide transportation and delivery of diesel fuel for several light towers and generators at the Field Medical Station #2 in Riverside.  

Interstate Oil Co: $1.656 million to provide full water truck services, including COVID-19 containment to support the Field Medical Station at the LA Convention Center.

Interstate Oil Co: $873,500 to provide portable laundry services to the Alternative Care Facility at Porterville Developmental Center.

**Comment by LizNobriga** [comment]
@abquirarte this is done/live. Thanks for helping, @KaylaPrusia

**Comment by abquirarte** [comment]
thank you!

**Comment by LizNobriga** [comment]
Blue Flame contract and BYD attachment2 for N95s posted/live @abquirarte
