### ISSUE TITLE
Vaccination data: remove references to county-level info

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6449]
Update description of race and ethnicity and age chart to remove reference to county-level data.

**Comment by m-sullivan7** [comment]
@mediajunkie Here's a [Google Doc with an edit](https://docs.google.com/document/d/13KKCOQ9XCWIzAqN7VXT9s0W63ue2wDRskehhXQRMZ1c/edit?usp=sharing) to respond to Garrett's email about removing the county-level data from the _Vaccination data_ race and ethnicity and age chart. I didn't go with his proposed text (which included talking about "primary series," a term I doubt our readers use), just removing the reference to county-level data.

OK to publish?

**Comment by mediajunkie** [comment]
yes please publish
-- 
Christian Crumlish
Product Manager | Office of Innovation
covid19.ca.gov . cannabis.ca.gov . digital.ca.gov
415-672-5759 | ***@***.***

**Comment by m-sullivan7** [comment]
Edit published. I'll let Garrett and the thread know. Thank you!
