### ISSUE TITLE
Data pages: move update cadence info out of accordions

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/covid19#6450]
Extensive page feedback and survey comments from last week included references to data being out-of-date. We have concluded that people are not finding the notes regarding the new update cadences instituted last week.

To help users better understand when data updates, we propose moving this information outside of the accordions so people do not need to click to find it. We propose putting this information on:

- The "updated [date]" line, if available
- The same line as the link to the Open Data Portal source data, if there is no "updated [date] line

This work affects:

- State dashboard
- Health equity
- _Vaccination data_

_Variants_ already makes this information available outside the accordion.

**Comment by m-sullivan7** [comment]
@mediajunkie Staged pages ready for review:

**Comment by m-sullivan7** [comment]
@mediajunkie Staged pages ready for review:

- [State dashboard](https://staging.covid19.ca.gov/state-dashboard/)
- [Health equity](https://staging.covid19.ca.gov/equity/)
- [Vaccination data](https://staging.covid19.ca.gov/vaccination-progress-data/)

**Comment by mediajunkie** [comment]
postvax is just on Friday.

otherwise, looks good!

**Comment by m-sullivan7** [comment]
Good catch! A copy and paste error on my part. Thank you. 🙂

All are published, including a fixed state dashboard.
