### ISSUE TITLE
Get financial help: remove stimulus payments from card links

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6451]
[Draft](https://docs.google.com/document/d/16ptLNf5ShmUVwMB0RUNFf0xQP3B1UsTI3puoxHPKDrE/edit#)

**Comment by LizNobriga** [comment]
@mediajunkie We got approved to publish the removal of "Golden State Stimulus" on _Help for individuals and families_ in March and I overlooked removing the card link for "Stimulus payments" on [_Get financial help_](https://covid19.ca.gov/get-financial-help/). Update now published to link to "Tax credits" instead.

**Comment by mediajunkie** [comment]
thanks!
