### ISSUE TITLE
Add gatherings question to FAQ

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#649]
### Add to FAQ page:

**Are gatherings permitted?**  

Gatherings—meetings or other events that bring together persons from multiple households at the same time for a shared or group experience in a single room, space, or place such as an auditorium, stadium, arena, large conference room, meeting hall, or other indoor or outdoor space—pose an especially great danger of transmission and spread of COVID-19.  As a consequence, State public health directives prohibit professional, social and community mass gatherings.  

On May 25, 2020, in an effort to balance First Amendment interests with public health, the State Public Health Officer created an exception to the prohibition against mass gatherings for faith-based services and cultural ceremonies as well as protests. Those types of gatherings are permitted so long as they do not exceed 100 attendees or 25% of the capacity of the space in which the gathering is held, whichever is lower.  All other mass gatherings are prohibited until further notice

**Comment by KaylaPrusia** [comment]
Placing in first section of questions, under "Can I get a haircut?"

**Comment by KaylaPrusia** [comment]
QA is live on [the page](https://covid19.ca.gov/stay-home-except-for-essential-needs/#top)
