### ISSUE TITLE
Education: add Spanish PDF

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6509]
Survey monkey feedback: looking for Spanish PDF for what to do if my child has or might have covid

[Draft edits](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit#)

**Comment by LizNobriga** [comment]
@mediajunkie This edit adds links to Spanish and Chinese PDFs. Okay to publish?
![Screen Shot 2022-04-20 at 10 17 19 AM](https://user-images.githubusercontent.com/58706834/164286926-89252d31-d4df-4e3c-a60c-53c692a17090.png)
See in [staging](https://staging.covid19.ca.gov/education/#childcare)

**Comment by mediajunkie** [comment]
Yes

**Comment by LizNobriga** [comment]
published
