### ISSUE TITLE
Propose update language for CA is taking action section

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#652]
Propose updated language (active) for the CA is working around the clock list. Content can be proposed on this github issue. 
 
Timeline- end of day 

### California is working around the clock to respond to COVID-19

- Directed Californians to stay at home to slow the spread of the virus
- Made testing free for most Californians who are medically eligible for testing
- Ensured students continue to learn and get meals even when schools physically close
- Deployed the California National Guard to work at food banks
- Distributed millions of N95 masks and other protective gear to health care workers, with more to come soon
- Secured travel trailers and hotels to house people experiencing homelessness

**Comment by thepegisin** [comment]
Here's my proposal:

### California is working around the clock to respond to COVID-19
•	Slowed the spread of the virus with a [statewide stay home order](https://covid19.ca.gov/stay-home-except-for-essential-needs)
•	Implemented [phased reopening](https://covid19.ca.gov/roadmap/) to boost economy while keeping citizens safe
•	Made [testing and treatment](https://covid19.ca.gov/testing-and-treatment/) free for all Californians, including the uninsured 
•	Expanded [food programs](https://covid19.ca.gov/food-resources/) for students, families, and seniors
•	Distributed millions of N95 masks and other protective gear to health care workers
•	Secured [travel trailers and hotels](https://covid19.ca.gov/housing-and-homelessness) to house people experiencing homelessness

"N95 masks" would link to PPE Request page once that is published.

**Comment by abquirarte** [comment]
sent over for review.

**Comment by abquirarte** [comment]
We removed this section altogether, so we'll close! :) At least we have this ready in case we bring back.
