### ISSUE TITLE
Change "fully vaccinated" for my pages

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#6539]
Look into changing "fully vaccinated" to something like "primary series" for my pages:
- _Mega-events_
- _Safety in the workplace_
- _Education and childcare_

Note that many CDPH guidance docs have not been updated with new language (e.g., k-12 staff required to be "fully vaccinated").

**Comment by LizNobriga** [comment]
[Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit) for Mega-events

**Comment by LizNobriga** [comment]
@m-sullivan7 Could you take a look at the proposed edits for _Mega-events_?

**Comment by m-sullivan7** [comment]
Looks simple and good to me! 🙂

**Comment by LizNobriga** [comment]
_Mega-events_ edits to address "fully vaccinated"

- [Draft edits](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit) in google doc
- [Staged page](https://staging.covid19.ca.gov/mega-events/) with edits

@mediajunkie Are these edits okay to publish?

**Comment by LizNobriga** [comment]
"Fully" is used 4 times on _[Safety in the workplace](https://covid19.ca.gov/workers-and-businesses/)_, and it's used in all 6 linked guidance docs.

**Comment by LizNobriga** [comment]
> > The term, "fully," is used once on _[Education and childcare](https://covid19.ca.gov/education/)_:
> > > ### Vaccination requirement for school staff
> > > Teachers and school employees must [verify they are fully vaccinated, or get tested regularly](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Order-of-the-State-Public-Health-Officer-Vaccine-Verification-for-Workers-in-Schools.aspx) for COVID-19.
> > 
> > 
> > Since the linked CDPH guidance uses "fully" multiple times, I propose no changes.
> 
> I think Carlos mentioned yesterday that they're still in the process of finding all of their instances of "fully vaccinated". I'd ask him at tomorrow's joint meeting if this is a conscious CDPH decision or if they haven't gotten to this page yet.

Yes, he did say that. I plan to stay aligned with the pace of their changes.

**Comment by LizNobriga** [comment]
Draft edits ready for review
- [Mega-events](https://docs.google.com/document/d/1bTzgxzVUx8YJo6pjVkLgifFSvfVZZdcZw-cHB5kO_tM/edit)
- [Safety in the workplace](https://docs.google.com/document/d/14RZSitqD_RXyJqGfUU1lRUcgwu0C6Ox941msBF4fA7s/edit)
- [Education and childcare](https://docs.google.com/document/d/1YQGVDtWHzOTlal-SZ3vYuIvvCAu29ztoIBptsD80B_g/edit)

**Comment by LizNobriga** [comment]
Approval from Michael Beccaralli via email. Published 5/12/22.
