### ISSUE TITLE
Reviving the Telehealth page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#6565]
There's talk of reviving the _Telehealth_ page. Emily Estus is leading the discussion.

- [x] Find archived draft of _Telehealth_
- [x] Edit out broken links and outdated language: https://docs.google.com/document/d/14LQRYtAa-OWps1FC9D61QYNOUYbHRYAvKvJsBbbXTuI/edit
- [x] Send to Emily Estus et. al.
- [x] Meet to discuss 5/19

Notes:
- People aren't looking for this info on the CA covid site. 
- All covid treatment info lives on the CDPH site.
- General direction for covid site is to consolidate, not expand (with limited exceptions like SMARTER plan). 
- Resources to maintain accuracy of this page are limited.

**Comment by LizNobriga** [comment]
Info from CDPH on 5/12/22:

> Along with nurse hotlines run by health plans, we should also have language about calling the county hospital or county clinics/health services system or the nurse hotlines run by large medical centers or large health systems.  When people don’t have a primary care provider, often their route to a prescription is to call Sutter/Kaiser/UCSF/UCLA and say I have COVID and I’m sick and want medication or monoclonal antibody.  Then, the patient navigator for that systems sets them up with the COVID telehealth appt or urgent care visit if they need vital signs and an exam – and gets them the Rx for Paxlovid or sets them up with the infusion clinic for monoclonal Ab, if they don’t quality for oral meds.
>  
> County-level COVID Nurse Hotline:  I worked for LAC DPH for the first year of the pandemic, and our outbreak teams extensively relied on the LAC DHS nurse call lines(with physician back-up) to ensure appropriate and timely access to care for symptomatic patients (mostly coming from homeless shelters, as that was my outbreak team).  If possible, we should consider listing those counties or linking to the county webpages for those that operate such hotlines.
>  
> ·         Example:  LA County Dept of Health Services
> [COVID-19 Information - Health Services Los Angeles County (lacounty.gov)](https://dhs.lacounty.gov/covid-19/#1601294945959-e8f191ef-38ee)
> COVID-19 Questions and Nurse Advice Line
> Health Services has a COVID-19 Nurse Advice Call Line: 844-804-0055. It’s available from 7:00 A.M. to 7:00 P.M., 7 days per week.
>  
> It would be helpful to provide some systems-navigation education to the patient/user.
>  
> Telehealth services are usually with a provider (physician, physician assistant, or nurse practitioner) that can make a diagnosis and write a prescription.  If the telehealth service is not integrated into a traditional health care system (clinic/hospital system), they may or may not be able to order laboratory testing or imaging, like a chest xray.  If you need a traditional physical exam, laboratory tests or imaging, then the telehealth provider may advise you to go to a clinic, urgent care or emergency room/hospital.
>  
> Nurse call lines that are run by healthcare delivery systems are usually focused on “triage”, or trying to address your symptoms and advise you as to if you need to make a clinic appointment, go to urgent care, go to the Emergency Room/Hospital, or call 911 for immediate access to clinical care.
>  
> Nurse call lines that are run by health plans may be less focused on clinical triage and more focused on helping a health plan member get access to appropriate care, like a clinic appointment or connecting them to an urgent care or ER/Hospital that is “in network”, so that services will be paid for by the health insurance plan.
>  
> Patient navigator call lines for health plans or health care delivery systems are dedicated to helping patients understand how to appropriately access the healthcare delivery system in a timely and appropriate way.
>  
> Consider adding content to educate the user about what nurse call lines can do and what telehealth offers.  This helps direct people to the most efficient source for what they are looking for:
> So people don’t call an RN hotline and get frustrated that the RN can’t give them a Paxlovid rx.
> So people don’t call an MD telehealth provider and get surprised if the MD sends them to the ER for a CXR or vital signs and respiratory exam.
> Understand why calling their health plan may be the way to get to a telehealth service that is covered/paid for by their health insurance.
> That calling the health systems’ patient navigator may be the way that they have to access getting to a monoclonal Ab site.  Their primary care or a telehealth provider can’t write the prescription and get them that treatment if they don’t qualify for Paxlovid, generally.

**Comment by thepegisin** [comment]
Emailed recommendation to Emily Estus and other meeting attendees that telehealth content be added to the [COVID-19 Treatments](https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/Treatments.aspx) section of the CDPH website.
