### ISSUE TITLE
Content Updates to: housing, get financial help, education

### ISSUE THREAD

**Issue by ashleydraper** [cagov/covid19#661]
## Housing and homelessness 
[Clean Copy](https://docs.google.com/document/d/1LpFtIFPM7XcEjNdSCjk9VuBPzMz_m3VULWGHWvbxj5U/edit)
- [x] replace existing March 18th guidance with new [interim guidance](https://www.bcsh.ca.gov/hcfc/documents/covid19_interim_guidance.pdf) from BCSH (April 27, 2020)
- [ ] determine best home for [information for homeowners and renters about their protections and resources](https://www.bcsh.ca.gov/coronavirus19/renters_mortgage_guidance.pdf)
- [ ] ensure consistency across housing page and get financial help page

## Get financial help 
[Clean Copy](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#)
**Need:** track change version, list of what is changing/improvements

## Education
[Clean copy](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit#)
**Need:** track change version, list of what is changing/improvements

**Comment by ashleydraper** [comment]
Draft submitted for SMEs

**Comment by ashleydraper** [comment]
Here is the track change version of the [education](https://docs.google.com/document/d/1E21sHwj4Z3NFyoTxKEncKfaRN2hLIxkXm8efCSK-mSE/edit#heading=h.jwk3i0zhoiiz) 
@abquirarte

**Comment by ashleydraper** [comment]
[Get financial help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#heading=h.otlgfapoi9ve) major changes:

- updated bulleted list to reflect the headers of the following paragraphs

- completed changed the language under the California Eviction Moratorium and included [BCSH resource doc](https://www.bcsh.ca.gov/coronavirus19/renters_mortgage_guidance.pdf)

- edited language under 90-day grace period for all mortgage payments

- removed duplicative language around 90 day and 60 day relief

- major changes to the response to "What if my mortgage servicer is not communicative or cooperative?"

**Comment by ashleydraper** [comment]
@abquirarte

**Comment by abquirarte** [comment]
Thank you for framing it like that! It helps me see the difference. I'm
good with the language for the financial help page. 🚀

**Comment by ashleydraper** [comment]
WHOOHOO!!! Thanks @abquirarte :)

**Comment by ashleydraper** [comment]
Here is the [get financial help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#) page for review
@abquirarte

**Comment by abquirarte** [comment]
@ashleydraper reviewed! Added some clarifying comments/questions, other than that, I'm good with the changes. Thank you! ✔️

**Comment by ashleydraper** [comment]
WHOOO!!! Thanks, Wonderful :)

**Comment by abquirarte** [comment]
Are we updating the two other pages as well!?

**Comment by ashleydraper** [comment]
All of these pages are finally updated!!! WHOOO
@abquirarte
