### ISSUE TITLE
Public Recreation page updates

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#664]
Updates to Public Recreation page based on level of readability and user feedback. Low priority.

Hemingway score as of 5/18: 14
Hemingway score as of 5/28 (with readability/feedback edits): 11
Hemingway score as of 6/3 (with more readability edits): 9

[Public Recreation staging document (with edits)](https://docs.google.com/document/d/1yTaGKCWEGF9pnscXLr_Kbx_NSYVEQLWdu3yUi6w02Vg/edit#)

- [x] review by @thepegisin 

- [x] review and approval by @abquirarte

**Comment by abquirarte** [comment]
✔️ good for WP live!

**Comment by KaylaPrusia** [comment]
Updates are live on the page @abquirarte
