### ISSUE TITLE
Design updates to website and GO requests 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#665]
## navigation
- standardize the page names now that they are grouped in a more intuitive way? For example under "get help" some pages simply say food or childcare while others say help for workers, help for XYZ, etc. 
- Remove Stay Home Q&A  from "how you can help" 
- Rename "get food pages"  in the "how you can help" category. 
- [x] Fix navigation https://github.com/cagov/covid19/issues/665#issuecomment-635674507
- [x] Rename Testing and treatment to "find a testing site"
- [x] Remove sidenav from pages 
-  Fix width of pages now that sidenav is gone

## buttons
- [x] Make action links design consistent. (remove arrows?) "make the buttons look better and more integrated to the style of the photo, similar to the “search” button." - Inverse background )like in search. 
![image](https://user-images.githubusercontent.com/9556188/83225768-50410b00-a135-11ea-814b-fe7115f02cdb.png)

- [x] move the buttons on the picture to either 1) the nav bar or 2) under the photo

## County map link
- [x] Make it more prominent on the page. This is in lieu of embedding the map on the homepage. Have the map link to the county map. 
![image](https://user-images.githubusercontent.com/9556188/83214068-9176f200-a118-11ea-87a6-87fc509d5cb8.png)

- [x] Rename icon from ~county variance info~ to "county reopening map"
- [x] Add anchor link to county map are on county variance page

## icons

- [x] Update the icons (_county variance_ info to `county reopening map`). Replace Financial help with "Industry guidance" and link to 
https://covid19.ca.gov/industry-guidance/

![image](https://user-images.githubusercontent.com/9556188/83226742-841d3000-a137-11ea-9090-5b0c1d2092a2.png)

## head banner
- [x] Change language under “Your Actions Save Lives” to “As California reopens, Californians must follow best practices: wear a face covering, wash your hands, stay home when sick.”

## search/ quick answer
- [ ] Make sure that our search/quick answer MVP is part of this update 
- [ ] Clean up search result design

[GO list here](https://docs.google.com/document/d/1LAU4RmmgDfoaCweezAclz4kL6eGN8Ki04rJn3UxDvG0/edit?ts=5ed01e53)

**Comment by thepegisin** [comment]
For @artuoma - please make these changes to **Get Help** dropdown (on Staging)

- Change **Get Help** to **Get help**

- Reorder these buttons:
**Financial help**
**Food and food assistance** (adding "and food assistance")
**Help for workers**
**Help for businesses** (removing "and employers")
**Help for immigrants**
**Emotional support**
**Childcare**

**Comment by abquirarte** [comment]
**On county page**

Make image larger & add this paragraph over with the image below the “County Variance Info + date” section (like homepage): “Local health jurisdictions that meet the criteria set forth by the California Department of Public Health may move further ahead in the resilience roadmap.”
 Remove this paragraph from the other section.
Remove all references to further ahead in stage 2 and replace with
“further ahead in the resilience roadmap”
COUNTY CRITERIA BOXES

- [ ] Add pictures (icons/emojis) that could help signal what they mean before expanded? i.e. a test kit, chart, etc.
- Make the bullets check marks
- [ ] Move this paragraph to under the map:
- [ ] If a county decides to pursue a variance to move further ahead in the resilience roadmap, the local public health officer must:
- [ ] 1.  	Notify the California Department of Public Health (CDPH).
- [ ] 2.  	Certify through submission of a written attestation to CDPH that the county has met the readiness criteria (outlined below), including guidance to be issued by the county and detailed plans, and that the county is designed to mitigate the spread of COVID-19.
- [ ]

**Comment by abquirarte** [comment]
Have this link to the toolkit page: https://toolkit.covid19.ca.gov/ 
@artuoma 

![image](https://user-images.githubusercontent.com/9556188/83313434-0440a580-a1cb-11ea-8e8e-bc14d898e6cd.png)

**Comment by abquirarte** [comment]
Closing this!
