### ISSUE TITLE
Standardize new global navigation translation and structure

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#667]
- [x] 1 Enable category labels as part of the nav list
- [x] 2 Create new global nav structure and shape
- [x] 3 Develop a new loop to build the navigation according to new structure
- [x] 4 Add navigation functionality via JS to mimic bootstrap [navbar](https://getbootstrap.com/docs/4.4/components/navbar/) behavior

**Comment by artuoma** [comment]
@carterm I think you have the last puzzle piece.

**Comment by aaronhans** [comment]
Art's latest design, Carter's data driven nav, the simplification so there is only one nav structure in the HTML and the cleanup to put javascript code in .js files is all live. We will be doing additional cleanup in the underlying json which should have no user impact, will open other task to track those changes if they are big enough to warrant that visibility. This can be closed now

**Comment by abquirarte** [comment]
Amazing!!! 🤩💪🐻

from my Samsung Work Device
