### ISSUE TITLE
New Protest Guidance 

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#668]
Stay Home QA page. Due by COB 5/28

[Document to suggested changes/updates](https://docs.google.com/document/d/1ALr4lAbHTMPT8pZ7zh4uXbHJ3Ze6sM2qR5h7aYTtpEk/edit)

- [x] Updates made to [staging document](https://docs.google.com/document/d/14IL8TJMfBCZXcZ8lMph7aastRl3o7ym3/edit)

- [x] pushed live on site

**Comment by abquirarte** [comment]
Were these made as is?

**Comment by KaylaPrusia** [comment]
I haven't transposed any of the edits yet, will after this meeting

**Comment by abquirarte** [comment]
OK, can we can post as is for now? Test for readibility. then we can propose suggestions :)

**Comment by KaylaPrusia** [comment]
Yes, should be live on the site in about 10 minutes. Included in our [staging](https://docs.google.com/document/d/14IL8TJMfBCZXcZ8lMph7aastRl3o7ym3/edit#) as well

**Comment by abquirarte** [comment]
Thank you so much!
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by KaylaPrusia** [comment]
Updates are live. Will tackle readability with Peggy later (once I have a chance to clean up document)
