### ISSUE TITLE
Thank all my engineering friends

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#6706]
Honestly, words fail me at this moment that I leave ODI after 2+ years. But I wanted all my friends in engineering and RAD, you talented and supportive bunch, to know how much I will miss you. Keep being awesome.

**Comment by ChadABratton** [comment]
@thepegisin  I have a feeling this is not the end! I really hope to continue working with you one day soon!

**Comment by thepegisin** [comment]
Tagging @adam-little @kmbrlygl because I reached a 10-assignee limit.
