### ISSUE TITLE
WIC content for food page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#671]
Timeline: end of day tomorrow, early next week. 

- [x] Review suggested content. Test for readability. 
- [x] Propose changes

### Suggested content from SME:
Women, Infants, and Children (WIC) food benefits

 

WIC helps families get access to healthy foods and a lot more.  WIC provides nutrition education, breastfeeding support, benefits for healthy foods, and referrals to healthcare and other community services.

 

WIC serves babies and children up to age 5, pregnant women, and new mothers. Dads, grandparents, other guardians, and foster parents can enroll children up to their 5th birthday. Working families and migrant families are welcome to apply too.

 

Recently lost your job, income has changed or unable to work, even temporarily due to COVID-19? Families can check their eligibility to see if they qualify for WIC by visiting www.MyFamily.WIC.ca.gov or calling 1-888-WIC-WORKS (1-888-942-9675) for more information. WIC locations have procedures to help you get WIC benefits as quickly as possible as some locations may be closed to the public.  Please call for information before visiting.

**Comment by LizNobriga** [comment]
Edited new WIC content. Also revised other sections for improved readability scores (grades 7-9).

[Staging document](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit)

To @thepegisin for review.

**Comment by LizNobriga** [comment]
Ready for your review, @abquirarte [Staging document](https://docs.google.com/document/d/1OPOFCyLaxnlJ336689Y_ye-NlygC8M91/edit)

**Comment by abquirarte** [comment]
Looks good!!!
Good to go.

**Comment by LizNobriga** [comment]
Updates are live
