### ISSUE TITLE
New Guidance: For statewide and county variance pages

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#673]
See latest at the bottom of the thread! :) 
Updated 06-04-2020 at 5pm

Uploaded [here.](https://drive.google.com/drive/u/0/folders/1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5)

**Comment by LizNobriga** [comment]
@abquirarte @TamaraIDEJA Are we replacing the [current guidance for child care](https://www.cdss.ca.gov/Portals/9/CCLD/PINs/2020/CCP/PIN_20-06-CCP.pdf) on the [statewide industry guidance page](https://covid19.ca.gov/industry-guidance/#top) with the new guidance PDF for reopening child care dated 5/27 ([located in drive](https://drive.google.com/drive/u/0/folders/1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5))?

**Comment by LizNobriga** [comment]
Just FYI, [this issue](https://github.com/cagov/covid19/issues/688) has other revisions to the statewide guidance page and has been reviewed by @thepegisin.

**Comment by abquirarte** [comment]
I believe it's both an update and additional guidance. I haven't received
anything yet

from my Samsung Work Device

**Comment by LizNobriga** [comment]
@thepegisin This is ready for review in [staging](https://docs.google.com/document/d/14IUZDZ9NJrUXKZOJb-20qPwr9OGZLNUYitHpe7oQxWc/edit#). Please look for the green highlighted section on the second page. The PDFs are located in [drive](https://drive.google.com/drive/folders/1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5).

**Comment by LizNobriga** [comment]
Thanks again for reviewing, @thepegisin!

@KaylaPrusia, what do you think about a link on the Childcare page to the to "Supports for working families" pdf? Maybe above More resources?

**Comment by LizNobriga** [comment]
To @abquirarte for review. [staging doc](https://docs.google.com/document/d/14IUZDZ9NJrUXKZOJb-20qPwr9OGZLNUYitHpe7oQxWc/edit#) (see green highlighted section on page 2).

**Comment by abquirarte** [comment]
> @abquirarte @TamaraIDEJA Are we replacing the [current guidance for child care](https://www.cdss.ca.gov/Portals/9/CCLD/PINs/2020/CCP/PIN_20-06-CCP.pdf) on the [statewide industry guidance page](https://covid19.ca.gov/industry-guidance/#top) with the new guidance PDF for reopening child care dated 5/27 ([located in drive](https://drive.google.com/drive/u/0/folders/1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5))?


☝️  We are replacing. but we will be getting new PDFs!

**Comment by abquirarte** [comment]
We are getting 8 new guidances. Getting more details

**Comment by abquirarte** [comment]
Museums, Zoos, and Aquariums is replacing Outdoor Museums. 
- (will need to figure out the link situation, I guess we will retire the pdf link and point to the main page?)

## New:
- [ ] Museums
- [ ] Zoos
- [ ] Aquariums
- [ ] Fitness Facilities
- [ ] Campgrounds and Outdoor Recreation
- [ ] Casinos
- [ ] Cardrooms and Racetracks
- [ ] Family Entertainment Centers
- [ ]  Employer Family Friendly
- [ ]  Families and Caregivers
- [ ]  Day Camps
- [ ]  Schools Final Clean

### Updates:
- [ ] Hotels (replacing hotels – same location should be fine)
- [ ] Hair Salons (replacing Hair Salons and Barbering – same location should be fine)
- [ ] Restaurants (replacing dine-in restaurants – same location should be fine)
- [ ]  Child Care

## Retire
- [ ] Outdoor museums

**Comment by TamaraIDEJA** [comment]
Subject to change but here’s the latest:
 
### Statewide
- [ ] Employer Family Friendly
- [ ] Families and Caregivers
- [ ] Day Camps
- [ ] Schools
### County
## Tomorrow

- [ ] Hotels (for tourism and individual travel)
- [ ] Music film TV
- [ ] Professional sports (without live audience)
- [ ] Cardrooms and Race Tracks
- [ ] Campgrounds
- [ ] Casinos

## Beginning June 12, counties that are approved to progress further into the resilience roadmap can decide to open the following industries:

- [ ] Family entertainment centers
- [ ] Wineries and bars
- [ ] Zoos and museums
- [ ] Fitness
- [ ] Replacements
- [ ] Hotels (replacing hotels – same location should be fine)
- [ ] Hair Salons (replacing Hair Salons and Barbering – same location should be fine)
- [ ] Restaurants (replacing dine-in restaurants – same location should be fine)
- [ ] Child Care

**Comment by abquirarte** [comment]
- [ ] Update the "not open" list in county variance page

##Suggested flow of new county variance page

### County criteria (Accordions)

### Track county data (map)

### County by county guidance (as of June 5) 

-  Cardrooms and Race Tracks
-  Campgrounds
-  Casinos
-  Hair salons
-  Hotels (for tourism and individual travel)
-  Music, film, TV (No PDF, language below)
-  Professional sports (without live audience)- (No PDF, language below)
-  Restaurants

### not open  (CLEAN UP CONTENT BELOW)
The following sectors, businesses, establishments, or activities are not permitted to operate in the State of California at this time:

Personal services such as nail salons, tattoo parlors, gyms and fitness studios
Indoor museums, kids museums, gallery spaces, zoos and libraries
Community centers, including public pools, playgrounds, and picnic areas
Entertainment venues, such as movie theaters, gaming, gambling, arcade venues, pro sports,
Hospitality services, such as bars, wineries, tasting rooms and lounges
Nightclubs
Concert venues
Live audience sports
Festivals
Theme parks
Hotels/lodging for leisure and tourism – non-essential travel
Higher Education

**Comment by KaylaPrusia** [comment]
Once we have GO approval, we will mirror Stay Home QA list with County Variance list

**Comment by abquirarte** [comment]
- [ ] suggest edits for what is closed

**Comment by LizNobriga** [comment]
@abquirarte, can this be moved to Done?

**Comment by abquirarte** [comment]
Yes! closing. It will move to done. Thank you for helping me clean the backlog.
