### ISSUE TITLE
Workers page updates and improvements

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#678]
[Staging document with suggested changes/updates](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit#heading=h.vtszniw9p2d3)
 - [x] Draft edits to update/clean up
 - [x] Test for readability
 - [x] Review by @thepegisin 
 - [ ] Review by SME
 - [x] Approved for WordPress by @abquirarte 
 - [x] Pushed live to site (complete)

**Comment by LizNobriga** [comment]
@abquirarte, do you want to take a look at the Workers page revisions in staging?

**Comment by abquirarte** [comment]
yes please!

**Comment by LizNobriga** [comment]
The workers page updates are live.

**Comment by abquirarte** [comment]
Great. Thanks!

from my Samsung Work Device
