### ISSUE TITLE
Medi-Nurse Line - options to highlight

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#680]
Making this so we have somewhere to track...not sure what to label

Medi-nurse line info [working doc](https://docs.google.com/document/d/1-3mJwMimhJWoMc_B-Y3EE4rojigi03PT1dHyru8Z8Ck/edit?ts=5ed18622) (not a staging doc)

**Comment by abquirarte** [comment]
@orielgomez suggested language for the [immigrant guide page in staging](https://docs.google.com/document/d/1w76WrHiSX7pdlV98U7h1KAnJhX0Z-k_K9Rmq6TW-W4A/edit?ts=5ed98c51#heading=h.qn30c9x7f0so)
AQ and team will need to review for Monday posting.

**Comment by LizNobriga** [comment]
FYI, the edits to include medi-nurse line information on the immigrant communities are complete/live - thank you @orielgomez!

**Comment by LizNobriga** [comment]
Think we've taken care of addressing most items listed on the [working doc](https://covid19.ca.gov/guide-immigrant-californians/), @abquirarte. 

Do you want to consider possibly a block or daily banner? Or other ways to pass the info on to nonprofits? Otherwise this can be wrapped up.

**Comment by abquirarte** [comment]
I think a banner is reasonable. Let's plan one for this week!
The working doc hyperlink takes me to the Help for immigrants page. :)

I'm going to close this for now.
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Banner: 

> If you think you might have coronavirus symptoms, use the Symptom Screener or contact your doctor through telehealth. If you don’t have insurance, you can call Medi-Nurse at 1-877-409-9052. Medi-Cal members can call too.

**Comment by LizNobriga** [comment]
[working doc](https://docs.google.com/document/d/1-3mJwMimhJWoMc_B-Y3EE4rojigi03PT1dHyru8Z8Ck/edit?ts=5ed18622)

**Comment by abquirarte** [comment]
Closing this issue. 
Let's get the banner up this week or next!
