### ISSUE TITLE
Statewide industry guidance - remove stage 2 language and clean up

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#688]
[Staging document](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit)

  - [x] Edits for readability and clarity
  - [x]  Removing "faster into stage 2" / replace with "further into the reopening roadmap" 
  - [x]  Review by @thepegisin
  - [x]  Review by @abquirarte
  - Review by SME _AQ reviewed. Approving for posting_
  - [x]  Approved for WordPress
  - [x]  Pushed live to site (complete)

**Comment by LizNobriga** [comment]
This one is ready for your review, @abquirarte

**Comment by abquirarte** [comment]
I've reviewed. I think it's good to update in WP.

**Comment by LizNobriga** [comment]
ok, will update now!

**Comment by LizNobriga** [comment]
Update are live, finally! @abquirarte
