### ISSUE TITLE
SEO improvements for Contact tracing page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#689]
Add more incoming links that point to https://covid19.ca.gov/contact-tracing/. Link to the page from:

- [x] https://covid19.ca.gov/
- [x] https://covid19.ca.gov/roadmap/ (where “contact tracing” is mentioned under Stage 1)
----
- [x] Minor issue: If the URL https://californiaconnected.ca.gov is being promoted, the redirect should be tweaked so it goes directly to https://covid19.ca.gov/contact-tracing/ (with the final “/” at the end) instead of taking an unnecessary step to the version without the “/” at the end. @ChadABratton 
----
- [x] It looks like there’s a typo on https://covid19.ca.gov/contact-tracing/: Where the question says “Can I apply for a con**tra**ct tracing position?”
- [x] Fix typo in metadata: "do you part" should say "do **your** part"

**Comment by thepegisin** [comment]
For link on homepage, suggest we put **Contact tracing** at the top of the **How you can help** menu.

**Comment by abquirarte** [comment]
> For link on homepage, suggest we put **Contact tracing** at the top of the **How you can help** menu.

We have it in the "health information," you'd suggest moving it?

**Comment by thepegisin** [comment]
Actually, no - scratch that! It fits, and the help menu is too long.
