### ISSUE TITLE
More contracts for contracts page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#690]
**- Timeline-** - Tomorrow- Tuesday June 2. 
- Add contracts to contracts page.  I will email them to you :) 
- Note: They will need to be replaced once remediated. OES will ping us when this is done. They will be saved in the OneDrive. 

----

Email 1:

Hitchens Harrison and Co: $19M PO for 1,000 anesthesia machines.
Adaptive Energy 1: $19M for 5.1M gowns
Adaptive Energy 2: $120k for 5000 coveralls
Adaptive Energy 3: $2.8M for 35M pairs of gloves
Pioneer Products: $18.25M for 5M isolation gowns
Epic Reliable Services: $21M for 1000 ventilators.
 

Email 2:

MedSupply America: $10.6M for 3M N95 masks
UniSpace 1: $12.5M for 2M isolation gowns
UniSpace 2: $1.5M for 12.5M gloves
UniSpace 3: $1M for 1300 emergency field beds
Care Wear Uniforms: $44.25M for 15M KN95 masks
 

Email 3:

Medical Dynamics Inc. 1: $9.6M for 5000 infusion pumps
Medical Dynamics Inc. 2: $20.8M for lots of “cannulas” of differing types
Medical Dynamics Inc. 3: $368k for 500 humidairs
Medical Dynamics Inc. 4: $7.6M for 2000 humidairs and related equipment
Medical Dynamics Inc. 5: $23.8M for 1200 ventilators
Frontline Support Inc. 1: $8.1M for 2M safety goggles
Frontline Support Inc. 2: $8.1M for 2M safety goggles

**Comment by LizNobriga** [comment]
These are all live

**Comment by LizNobriga** [comment]
Documenting Ashli healthcare contract added/live today 6/3

**Comment by abquirarte** [comment]
Yay!  Closing for now. :)
