### ISSUE TITLE
Updates to plasma page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#705]
### request from email below
(I will forward attachment to you)
A few requested updates to the webpage on CCP:

To align with changes implemented in the June letter to go out (see attached), would you kindly make the following changes appended below to the webpage language under “Who can donate COVID-19 plasma?”(sections changed are highlighted for ease of reference).
As an additional resource under the “Stay informed” section at the bottom of the webpage, would you include the following hyperlink: The Fight Is In Us COVID-19 Plasma Coalition: https://thefightisinus.org/
Finally, would you kindly add the following Stanford Blood Center sites to the locator:
 
MENLO PARK DONOR CENTER
445 Burgess Drive
Suite #100
Menlo Park, CA 94025

(888) 723-7831 Map / Directions

 

 

MOUNTAIN VIEW DONOR CENTER
515 South Drive
Suite #20
Mountain View, CA 94040

(888) 723-7831 Map / Directions

 

 

SOUTH BAY DONOR CENTER
295 E. Hamilton Avenue
Campbell, CA 95008

(888) 723-7831 Map / Directions

 

 

Who can donate COVID-19 plasma?

·         A person who had a test that showed coronavirus infection,
AND

·         Has felt well for at least 28 days*,
AND

·         Passes the usual rules for blood donation. 

*If you want to donate before one month has passed since you recovered, please check with your blood center as some centers will require a negative swab test. The blood center may also have other rules.

**Comment by JasonKarim** [comment]
Language is updated! Aaron or Art: Can you please add the Stanford sites to Plasma Center locator, as requested?

**Comment by aaronhans** [comment]
3 new locations are added and being returned from the production API now

**Comment by abquirarte** [comment]
Awesome!!

from my Samsung Work Device
