### ISSUE TITLE
New accordions on county page: pro sports and music/tv/film

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#711]
### New Accordions 

Professional Sports​

Professional sports in California may resume training and competition without live audiences, subject to approval by county public health officers within the jurisdiction of operations. To reduce the risk of COVID-19 transmission, athletes, coaching staff, medical staff, broadcasting staff and others at sporting facilities or events must abide by COVID-19 protocols agreed by labor and management, which may be further enhanced by county public health officers.  Back office staff and management must adhere to Office Workspace guidelines published by the California Department of Public Health and the California Department of Industrial Relations, to reduce the risk of COVID-19 transmission. Retail staff must adhere to Retail guidelines published by the California Department of Public Health and the California Department of Industrial Relations, to reduce the risk of COVID-19 transmission.
Music, TV and Film Production

Music, TV and film production may resume in California, subject to approval by county public health officers within the jurisdictions of operations. To reduce the risk of COVID-19 transmission, productions, cast, crew and other industry workers should abide by safety protocols agreed by labor and management, which may be further enhanced by county public health officers.  Back office staff and management must adhere to Office Workspace guidelines published  by the California Department of Public Health and the California Department of Industrial Relations, to reduce the risk of COVID-19 transmission. 

### Content Captains
@ashleydraper @thepegisin @LizNobriga to tag team on this 

### Timeline 
By noon tomorrow or asap

**Comment by LizNobriga** [comment]
Sounds good!

**Comment by abquirarte** [comment]
Closing this, I moved the content above to once central issue number #673
