### ISSUE TITLE
Stay Home QA content reorganization

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#712]
Remove the following questions/answers from Stay Home QA to respective pages

- [x] Move to Education page:

> **My school provides free grab-and-go meals. Are those still available?**
Yes. It is essential to keep children fed. Check with your local school district for days and times meals are offered.

- [x] Move to Childcare page:

> **Can I get childcare during the stay home order?**
> Yes, all childcare facilities can open with necessary modifications. See the Childcare page.
> **Can my babysitter still come to the house?**
> Yes, a childcare worker can come to your home if necessary and should adhere to basic prevention guidelines (like handwashing for at least 20 seconds, physical distancing, staying home if feeling ill).

- [x] Move to Healthcare page:

> **What if I need to visit a health care provider?**
> If you have coronavirus symptoms, please contact your doctor through telehealth or use the Symptom Screener self-checker.If you have other illnesses or chronic conditions, use telehealth to get care from home.
If you need to go to the hospital, call ahead so they can prepare for your arrival. If you call 911, tell the 911 operator your exact symptoms so the ambulance provider can be ready to treat you safely.

> **What about routine, elective, or non-urgent medical appointments?**
> Preventive care services and non-emergency surgeries, like organ replacements and tumor removals, can take place if hospitals have enough capacity and protective equipment to do so safely. Eye exams, and elective procedures should be cancelled or rescheduled. If possible, health care visits should be done remotely. Dental services and preventive dental care may be resumed. Contact your doctor through telehealth to see what services they are providing.

> **Can I get my prescriptions filled?**
> Yes. You may leave your home to get prescriptions or cannabis from dispensaries with medical permits.
> You can contact your doctor through telehealth to get a new prescription or adjust your existing prescriptions. 
> 

> **How can I make sure the older Californians in my life are safe and healthy during the stay home order?**
> You should check in on your older neighbors and loved ones with a call, text or physically distanced door knock to make sure they are okay. You can also teach them how to FaceTime, Zoom, Google Duo or use Facebook video to communicate. The most important thing you can do is to keep in touch with older loved ones for their mental health and safety.

> **I am an older Californian who is isolating at home and I need non-urgent assistance. What can I do?**
> You can call the statewide hotline for older Californians at 1-833-544-2374 for your non-urgent medical needs, to get meals delivered, track down prescriptions and more. The most important thing you can do is stay home for your health and wellbeing. If you are experiencing an emergency please call 911.

> **Can I leave home to care for my elderly parents or friends who require assistance? Or a friend or family member who has disabilities?**
> Yes. Be sure that you protect them and yourself by following physical distancing guidelines such as wearing a mask, washing hands before and after, using hand sanitizer, maintaining at least six feet of distance when possible, and covering your cough or sneeze. If you have early signs of a cold, please stay away from your older loved ones.

> **Can I visit loved ones in the hospital, nursing home, skilled nursing facility, or other residential care facility?**
> Generally, no. There are limited exceptions, such as if you are going to the hospital with a minor who is under 18 or someone who is developmentally disabled and needs assistance. For most other situations, the order prohibits visitation to these kinds of facilities. This is difficult, but necessary to protect hospital staff and other patients. Check the frequently asked questions for friends and family with a loved one in a skilled nursing or residential care facility for more detailed information.

- [x] Add question related to smog checks (recurring user question)

> **Can I get my smog checked?**
> The Bureau of Automotive Repair advises drivers to still pay DMV vehicle registration fees to avoid any late fees. However, you will not receive your new registration or year sticker until the smog information has been received by DMV. Once state and local orders or directives are no longer in effect, consumers can then obtain the required smog check certificate to complete the DMV vehicle registration process.

**Comment by suleman123s** [comment]
Hello

**Comment by abquirarte** [comment]
@KaylaPrusia sending over to GO :) Thank you

**Comment by abquirarte** [comment]
@KaylaPrusia ☝️ those are good to move!!! 

### Now:
- [ ] KP Send over track change version with edits based on new guidance around what is open and what isn't 
- [ ] AQ to send track change draft to GO legal

**Comment by KaylaPrusia** [comment]
@abquirarte let me know what you think - [staging doc](https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit)

**Comment by abquirarte** [comment]
- [ ] Sending to GO legal for vetting/approval 6//4/2020 8pm

**Comment by KaylaPrusia** [comment]
@abquirarte this is completed, you can close this issue :)

**Comment by abquirarte** [comment]
Yay!!
