### ISSUE TITLE
New Contract PDF for Contracts Page- August 2018

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#715]
### Contracts 
New contracts description bellow and attachments in the emails (1 and 2) Angie sent. 

### Timeline 
Tomorrow afternoon

### Content Captains
@LizNobriga @KaylaPrusia 

- [x] Universal Security: $1.086 million to provide unarmed security guard services at the Federal Medical Site at the Santa Clara County Convention Center.  
- [x] Pro Guard Security Services: $656,640 to provide armed security guard services at the Federal Medical Site at the Santa Clara County Convention Center.  
- [x] Pro Guard Security Services (Amendment 1): added $820,800 to the above-referenced Pro Guard Security Services contract increasing the total contract amount to $1,477.440 to add unarmed security.   
- [x] Power Security Group: $529,920 to provide unarmed security guard services at the Federal Medical Site #2 in Riverside.
- [x] S&S Labor Force: $1,828,224 to provide both armed and unarmed security guard services at the Federal Medical Site at the Los Angeles Convention Center.  
- [x] CitiGuard: $379,280 to provide both armed and unarmed security guard services at the Alternate Care Site at the Fairview Developmental Center.
- [x] Turner Construction (Sleep Train): $8.2 million to provide full essential temporary services for the Sleep Train Arena and adjacent Practice Facility for use as an Alternate Care Site.
- [x] O’Melveny: Legal services with the O’Melveny  law firm, for a maximum of $600k to support: (1) acquisition of Verity properties (the two hospitals where owner was in bankruptcy) and (2) potential acquisition or lease of Motel 6.
- [x] Military Department: ~$280k for computers, displays and other IT equipment to support Fireguard

**Comment by LizNobriga** [comment]
Contracts are live!  :muscle:@KaylaPrusia 
@abquirarte @TamaraIDEJA

**Comment by abquirarte** [comment]
Wohoo!

We have a couple of swamps. Coming your way (inbox) 

We would like to swap out for ones currently posted – the two Deloitte contracts and the two iFish contracts. They are identical, exempt now have contact information for staff blacked out.

**Comment by LizNobriga** [comment]
@abquirarte, the two Deloitte and two iFish contracts with contact info black out are on the site. Moving to Done. fyi @KaylaPrusia

**Comment by abquirarte** [comment]
🎉 ✅

**Comment by abquirarte** [comment]
Repurposing this issue: 

## Timeline- Post by noon 8/19/2020 
Contract in your inbox @LizNobriga 

- [ ] Stage content
- [ ] Send link 
- [ ] Publish page
- [ ] Upload PDF

FYI: @kenbasart @hannahslee

**Comment by LizNobriga** [comment]
This will be the link if you need to send it @abquirarte 
[https://files.covid19.ca.gov/pdf/Logistics-health-inc-CDPH-amendment-2.pdf](url)

**Comment by LizNobriga** [comment]
[Staging view](https://staging.covid19.ca.gov/contracts/#top) is ready

**Comment by LizNobriga** [comment]
Her's a [doc](https://docs.google.com/document/d/1qo_iVRRhB-hxw9WbrF-q6hyZF83dtilCDhCrFxNHhP4/edit) with links to the contracts tracker, contracts google staging doc, and contracts drive folder.

**Comment by LizNobriga** [comment]
Contracts page and link are live.
