### ISSUE TITLE
Update to SD: Sign Up for Local Alerts Info

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#728]
### Context
On sign up for local alerts, San Diego zips are being directed to an alert system they are NOT using for covid info. That’s being kept for things like wildfires. 

### Replace with: 
Alert options for covid info are: Text to subscribe: text COSD COVID19 to 468-311 (please note space between COSD and COVI19)
Email updates: https://public.govdelivery.com/accounts/CASAND/subscriber/new?topic_id=CASAND_408 

@aaronhans @abquirarte @thepegisin

**Comment by abquirarte** [comment]
This requires an update to the dataset.
Thanks Tam!

From my phone

________________________________

**Comment by thepegisin** [comment]
I suggest we change the link to [https://www.sandiegocounty.gov/coronavirus.html](https://www.sandiegocounty.gov/coronavirus.html). This is I signed up for alerts. The instructions for text signup are about halfway down the page.

**Comment by aaronhans** [comment]
new link is in production

**Comment by thepegisin** [comment]
Change is up and looks good.

**Comment by abquirarte** [comment]
sweet!
