### ISSUE TITLE
FB pixels for Social media campaign

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#733]
GO and CDPHS are starting to run ads in multiple languages (RS-E is the agency executing these ads). To have access to and be able to optimize against the full suite of ad options, we need to add a couple of Facebook pixels to the covid19.ca.gov website—one for the ads GMMB is running in English and Spanish (via CDPH’s Facebook ad account), and one for the ads RS-E is running in the priority languages

Code and instructions below. @artuoma 

https://drive.google.com/drive/u/0/folders/1fcxEamy7haJ0Q2qxeJtVNO9IHfwO5iql

**Comment by aaronhans** [comment]
The facebook code referenced is not just a pixel it is a large tracking script.

We can already track campaigns back to specific sources if we use the google campaign url parameters. Can we use that to trace our campaigns instead of putting facebook code on our site?

**Comment by abquirarte** [comment]
I'll loop you in on the email thread with the campaign vendor that made the request on behalf of GO!

**Comment by aaronhans** [comment]
I proposed the server side tracking method to integrate with the vendor and gave them directions on what we need to set that up.

Had a meeting with @jpetrucione and Britt where we went over JP's needs which are to get a handle on which ads are running when and where they are directing traffic. We agreed that my tracking proposals seemed fine but it is more important to get in the loop on what the ad team is doing so we can have visibility going forward. The initial directions they sent wouldn't have given us any visibility because we don't have access to those accounts.

Next step: JP is going to setup a meeting with the vendor so we can figure out how to get the whole picture from our vantage point

**Comment by aaronhans** [comment]
If it is helpful we can keep this open to remember to follow up but there are no current action items on our end.

**Comment by abquirarte** [comment]
Yes please, let's keep it open.

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by aaronhans** [comment]
We met with the ad team 6/18:
- They will use GA compatible utm parameters for inbound traffic from their facebook and other ad campaigns 
- They will let us know when they are running campaigns and where they are pointing
- They do not have a facebook developer account so @aaronhans is set one up to get the tokens required for server side facebook reporting and requested access to the ad accounts based on the ids the vendor provided (still awaiting access approval as of 6/19)

**Comment by abquirarte** [comment]
Can we close this?
@traintestbritt @aaronhans @jpetrucione

**Comment by aaronhans** [comment]
Still work to do here, I'll follow up with the ad placement team. I still need my access approved

**Comment by aaronhans** [comment]
@kenbasart and @abquirarte I brought this up with @traintestbritt yesterday and she was pretty sure the people running these campaigns got all the data they needed directly from the facebook dashboards and we didn't need to add this traffic confirmation ping anyway

So I think we can probably close it but we can revisit this approach if we get a similar request in the future

**Comment by abquirarte** [comment]
OK. Thank you @aaronhans and @traintestbritt !! 

cc: @hannahslee
