### ISSUE TITLE
More contracts (PDFs) for contracts page- June

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#735]
New contracts ready for posting. I will forward to the content team and CC: Aaron/Carter. 

Perhaps would to jump on a call and coordinate?

What would be the best way to test these? New process? Or WP Library? 

CDPH contracts 
- Aya
- Optum
- Medifis 
- Syrup Ventures

(5 attachments)

**Comment by KaylaPrusia** [comment]
@abquirarte contracts are renamed and staged. How should we upload?

**Comment by LizNobriga** [comment]
@abquirarte these are staged in google doc and renamed in contracts drive folder

**Comment by aaronhans** [comment]
We have a new test in place that will block production builds if there is some filename case issue like we experienced or anything that breaks the site in a Windows environment like our current production server.

We do not yet have a good solution for pdf management going forward, looking into some storage CDT has or CDN options integrated into WordPress.

So for now you can use either WordPress or github whichever you prefer. You will not be able to trigger any issues with the site.

We are working on a better way to manage the pdfs in the future and we will show you some better options soon

**Comment by abquirarte** [comment]
- [ ] Add Advoque (DGS) 
Before 11am today if possible. 
It will need to be replaced later with remediated copy. 
AQ sending copy to your inbox. :) 

@LizNobriga

**Comment by abquirarte** [comment]
- [ ] Two additional contracts with Frontline Support Inc (two others have previously been posted). Both of these have been cancelled, so please note that using the same convention as the Syrup Ventures entry:

Syrup Ventures LLC (cancelled): Syrup-ventures-LLC-DGS-cancelled (PDF)

Email coming @LizNobriga

**Comment by TamaraIDEJA** [comment]
- [ ] more contracts from DMV arrived @LizNobriga they are in your email. Thank you!

**Comment by aaronhans** [comment]
The following files were updated Friday. They were received from the 6/25 folder of the drive shared from Ryan Gronsky at CalOES

Advoque-DGS.pdf 
Aya-healthcare-inc-CDPH.pdf 
BYD-Motors-LLC-OES-2.pdf 
CDW-government-LLC-CalGuard.pdf 
Citiguard-inc-DGS.pdf 
Frontline-support-inc-DGS-3-cancelled.pdf 
Frontline-support-inc-DGS-4-cancelled.pdf 
Kaiser-dignity-LA-county-CDPH.pdf 
Logistics-health-inc-CDPH.pdf 
Medefis-inc-CDPH.pdf 
Power-security-group-inc-DGS.pdf 
Syrup-ventures-LLC-DGS-cancelled.pdf

**Comment by LizNobriga** [comment]
i think this can be closed @abquirarte

**Comment by abquirarte** [comment]
no longer June, thank you!
