### ISSUE TITLE
Pages that need publishing 6/8/20

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#736]
List the pages here that need publishing today (non-urgent, EOD is fine):

- [x] Masks [/masks-and-ppe/](https://covid19.ca.gov/masks-and-ppe/) - Fixed leading spaces in links

**Comment by ashleydraper** [comment]
- [ ] [County variance](https://covid19.ca.gov/roadmap-counties/#track-data) - Updated casinos, hotels,  zoos and museums, and cardrooms and racetracks

**Comment by KaylaPrusia** [comment]
- [ ] [Stay Home QA](https://covid19.ca.gov/stay-home-except-for-essential-needs/#top) - updated what's open/closed:

- What's open: (added) Movie theaters and drive-in theaters (with modifications)
- What's closed: (removed) Entertainment venues, like movie theaters and arcade venues

**Comment by LizNobriga** [comment]
- [ ] [statewide industry guidance](https://covid19.ca.gov/industry-guidance/)

- Added to Retail accordion: "Drive-in **and** movie theaters can re-open with additional considerations."

**Comment by ashleydraper** [comment]
Removed 'movie theater' from what's closed

**Comment by thepegisin** [comment]
It looks like publishing pipeline is working, so I'll close this issue.
