### ISSUE TITLE
Updates to Childcare page

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#737]
Updates to [Childcare page](https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit#) based on:

- [x] Readability 
Hemingway score: Grade 10 (6 HTR, 6 VHTR sentences)
Hemingway score: Grade 9 (9 HTR, 2 VHTR sentences)

- [x] Update link to childcare guidance from CDE

- [x] Reviewed by Peggy (on 6/4)

- [x] Review/approval @abquirarte

**Comment by KaylaPrusia** [comment]
@abquirarte updates to [childcare page](https://docs.google.com/document/d/1Yy1T5eroDr0JuOWZSC1r8ZlHnQmhqZpi7Bs70MUCPCc/edit#) are ready for your review.

**Comment by abquirarte** [comment]
Reviewed. Added some comments. Other than that, good to go!

from my Samsung Work Device

**Comment by KaylaPrusia** [comment]
Updates to childcare page are live. Thanks!

**Comment by abquirarte** [comment]
yay!
