### ISSUE TITLE
Updated policy guidance: Family Entertainment Centers 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#738]
Coming soon ... updated guidance on Family Entertainment Centers. (awaiting for guidance PDF for replacement)

Will require removing "Movie Theaters" from the list of closed industries. 

**When: today.** 

@carterm @aaronhans @artuoma (FYI)

**Comment by thepegisin** [comment]
Assume this would mean doing this also. @abquirarte can you confirm? 

- [ ] Remove from [Stay home Q&A: What's closed](https://covid19.ca.gov/stay-home-except-for-essential-needs/) "Entertainment venues, like movie theaters and arcade venues"
- [ ] Add to [Stay home Q&A: What's open](https://covid19.ca.gov/stay-home-except-for-essential-needs/) **"Movie theaters and ** drive-in theaters (with modifications)"
- [ ] Add to [Industry guidance: Retail](https://covid19.ca.gov/industry-guidance/) "Drive-in **and** movie theaters can re-open with additional considerations. "

**Comment by abquirarte** [comment]
Correct!

from my Samsung Work Device

**Comment by thepegisin** [comment]
@abquirarte Should the accordion title for **Family entertainment centers** also include movies now? I'm not sure anyone interested in movies would look under that heading.

**Comment by abquirarte** [comment]
I think so!

from my Samsung Work Device
