### ISSUE TITLE
Updates to Businesses and employers page

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#739]
- [x] Links to industry guidance pages
- [x] Link to family-friendly practices for employers
- [x] Add Families First Coronavirus Response Act: [Employer Paid Leave Requirements](https://www.dol.gov/agencies/whd/pandemic/ffcra-employer-paid-leave)
- [x] Add Department of Fair Employment and Housing [resources](https://www.dfeh.ca.gov/covid-19-resources-and-guidance/)
- [x] Add Dept of Industrial Relations Covid-19 [sick leave](https://www.dir.ca.gov/dlse/Comparison-COVID-19-Paid-Leave.html)
- [x] Add Dept of Labor [workers' comp](https://www.labor.ca.gov/coronavirus2019/#chart)
- [x] Improve readability
- [x] Update Employers Q/As and remove Stay Home Order Q/As
- [x] Purge content

[Staging doc here](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#)

**Comment by LizNobriga** [comment]
@thepegisin, ready for your review.

**Comment by LizNobriga** [comment]
Thanks, @thepegisin! 

@abquirarte, edits are ready for your review now. [Staging doc](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#).

**Comment by abquirarte** [comment]
✅ reviewed. I'm good with publishing this to WP.

**Comment by abquirarte** [comment]
great! closing!
