### ISSUE TITLE
New. BYD 2  contract 7/22/2020

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#744]
### Context
Update version of amendment 3 to the BYD contract with remediated version. 
Update what is on the website so that the third amendment is replaced with the remediated version. 

I will forward attachment. 

### Timeline:
EOD

**Comment by LizNobriga** [comment]
@abquirarte remediated version of amendment 3 of BYD contract uploaded to github

**Comment by LizNobriga** [comment]
@abquirarte, what is the difference between BYD contract amendments 3 and 4? Do we need to remove BYD contract amendment 4 from the Contracts page? fyi @KaylaPrusia

**Comment by abquirarte** [comment]
@LizNobriga I think we just replace amendment 3. Leave 4 as is. :)

**Comment by abquirarte** [comment]
recycling this issue. @LizNobriga 

> Big contract will be announced tomorrow re: PPE. (In your inbox).  We can stage content in page to publish at 11:43am and post the actual PDF at 12:00pm. 

> Please send the link that this PDF will become so it can be included in press release when ready.

**Comment by LizNobriga** [comment]
[contracts page staging doc](https://docs.google.com/document/d/18CYotMzjPfc-F-MTjFaQGni1_yytUWYxrBa-0u8A3-I/edit#)
[contracts tracker](https://docs.google.com/spreadsheets/d/1-mNVOWQ8g6b0xTsaRMu_brQni66fqvTZ28zTwHY_tx8/edit?ts=5ebdf87e#gid=697206094)

**Comment by LizNobriga** [comment]
contract is live
