### ISSUE TITLE
Fix- link to outdoor guidance in 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#747]
The outdoor museums guidance link in the industry page doesn't work. 
We are noticing a glitch in the link to the outdoor museum guidance:
https://covid19.ca.gov/industry-guidance/#top
links to:
https://covid19.ca.gov/pdf/covid19.ca.gov/pdf/guidance-outdoor-museums.pdf

It should link to: 
https://covid19.ca.gov/pdf/guidance-outdoor-museums.pdf

**Comment by LizNobriga** [comment]
@abquirarte, links works, moving to done.

**Comment by abquirarte** [comment]
✅
