### ISSUE TITLE
Stay Home QA Updates

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#749]
Updates to Stay Home QA 6/9

- [x] Update answer to "Can I travel?" based on CDC recommendation

- [x] Update answer to "Can I visit State Parks?" based on new camping/outdoor rec guidance

- [x] Update DMV answer based on [June 9 press release](https://www.dmv.ca.gov/portal/news-and-media/dmv-reopens-remaining-field-offices-to-public/)

[Staging document](https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit#)

**Comment by abquirarte** [comment]
✔️ reviewed! Added a comment. Everything else looks good to go!

**Comment by KaylaPrusia** [comment]
@abquirarte updated the travel question to include (in bold):

You can travel for urgent matters or if such travel is essential to your permitted work. Even though businesses around the state are opening up, avoid travelling long distances for vacations or pleasure as much as possible. This is to slow the spread of the coronavirus. 

**If you do travel away from your community, consider:
- Is COVID-19 spreading where you are traveling?
- Are you or those you are traveling with more likely to get very sick from COVID-19?
- Will you be able to keep 6 feet of physical distance from others during or after your trip?

If you do travel, take steps to keep everyone safe like wearing a face cloth covering, keeping 6 feet of physical distance from those not in your household, and wash your hands frequently.**
  
Do not travel if you are sick, or if someone in your household has had coronavirus in the last two weeks. Do not travel with someone who is sick.

**Comment by abquirarte** [comment]
Where do the questions come from? :)

**Comment by KaylaPrusia** [comment]
@abquirarte [CDC guidance](https://www.cdc.gov/coronavirus/2019-ncov/travelers/travel-in-the-us.html)

**Comment by KaylaPrusia** [comment]
Updates are live! @abquirarte

**Comment by abquirarte** [comment]
yay!
