### ISSUE TITLE
Update to guidance (statewide and county)

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#750]
- [x] Clarify/connect statewide guidance for hotels with county guidance for hotels to reopen with approval (and check for any other overlapping guidance areas between these pages)

**Comment by abquirarte** [comment]
Is this in progress? :)

**Comment by LizNobriga** [comment]
yes, thanks! @KaylaPrusia, would you have time to coordinate on this later today?

**Comment by KaylaPrusia** [comment]
Yes. I have an SNF interview from 3-3:30 but other than am pretty open :)

**Comment by LizNobriga** [comment]
ready for review @abquirarte [staging doc](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit)

**Comment by abquirarte** [comment]
reviewed ✔️

**Comment by abquirarte** [comment]
Replace updated guidance for the following (some in industry page, some in county page) 

AQ getting clarification with SMEs. 

- [ ] restaurants, bars, wineries (6/10) 
- [ ] retail (6/15)
- [ ] hair saloons (6/15)
- [ ] Fitness facilities (6/15)
- [ ] Places of worship (6/12)

CC: @LizNobriga @TamaraIDEJA @ashleydraper

**Comment by LizNobriga** [comment]
New retail guidance pdf (dated june 15) is live now. 

@ashleydraper think they decided to only replace retail for today.

**Comment by abquirarte** [comment]
## **Mask guidance coming**

[Look at the draft language](https://docs.google.com/document/d/1dPI5hj8IlxYINqY7jGx6_Hj7Y8cYhmEt4BXaFSzKdXY/edit?usp=sharing) and **stage content** in content doc and relevant WP pages, but don't publish until we get green light from GO. 

PDF guidance/link coming.

**Comment by abquirarte** [comment]
- [ ] Update banner

- [ ] Update masks page

- [ ] Update health care page

Any other pages?

**Comment by KaylaPrusia** [comment]
Reviewing stay home page, there are instances where we say face coverings are strongly recommended. Will create a clean doc pertaining to these answers, review and stage document here

**Comment by KaylaPrusia** [comment]
@abquirarte Peggy and I reviewed/made suggestions based off mask guidance from today. I'm sure legal will want to take a look before we post - [here is the staging document](https://docs.google.com/document/d/1birVt1BlW8G2HMoRkP5RnQC718pwyom9mkj0ZIJx31o/edit).

**Comment by LizNobriga** [comment]
I think we can move this to closed.
