### ISSUE TITLE
Great Plates program extension and content updates 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#752]
### Update Guidance 
(forwarded email w attachment)
 
### Update Content - Announcing extension of the program

“We are pleased to announce that the Federal Emergency Management Agency (FEMA) Public Assistance (PA) program has authorized a time extension for the Great Plates Delivered program to July 10, 2020.”

- [x] Update banner
- [x] Add blurb to Great Plates page

 ### Add a blurb on reporting guidance 
SMEs also forwarded to us the word doc Reporting questionnaire guidelines  that they would like to have local administrators submit to us via email twice a week. This form is also available in the program guidance PDF. CalOES have communicated with local administrators weekly, and they have been submitting this information to us biweekly via email. 

(this reporting guidance process is less than ideal... happy to think through what makes most sense - they envisioned the program admins drafting biweekly email report + attaching word doc they can download for our website) 

- [x] Replace Program guidance on page
- [x] Add Reporting doc on page

### Content Captain 
@ashleydraper @thepegisin 

### Timeline 
Since this is the news everyone is anxiously waiting for, please make updates asap

**Comment by thepegisin** [comment]
For homepage banner, I propose this:

[Great Plates Delivered](https://covid19.ca.gov/restaurants-deliver-home-meals-for-seniors/) has been extended! Thanks to FEMA Public Assistance, this senior meals from restaurants program will continue to deliver until July 10.

**Comment by KaylaPrusia** [comment]
Document uploads are live!

**Comment by ashleydraper** [comment]
The participant FAQ doc has been added see github #762 
@TamaraIDEJA @thepegisin

**Comment by TamaraIDEJA** [comment]
- [ ] Please update the data reporting questionnaire - forwarded via email.

@ashleydraper @thepegisin thank you!

**Comment by ashleydraper** [comment]
Questionnaire has been [updated](https://github.com/cagov/covid19/pull/811)

**Comment by abquirarte** [comment]
Yay
