### ISSUE TITLE
Contact tracing updates 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#757]
Per GO, these have been vetted and approved. 

## Questions 
**What is a close contact?**

A close contact is someone who was within 6 feet of a person with COVID-19 for at least 15 minutes while they were contagious.  Household members, intimate contacts, and caregivers are the most common. But, other people could be included.

**Will contact tracers track my location?**

California’s contact tracing program does not use any cell phone tracking technology. Someone from your local public health department will speak privately with you and all information is confidential and protected by California’s strict privacy laws. They may stay in touch to make sure your symptoms aren’t worsening.

**Comment by abquirarte** [comment]
@thepegisin let's go ahead and post please :)

**Comment by thepegisin** [comment]
Just checking:
- [ ] Was readability edit approved?
- [ ] And @JasonKarim's two added Q/As?
Staging document: https://docs.google.com/document/d/1Oax_Pku3fMzngWY_D1jCAqPWdFbh_7PxGhBBUlqce3c/edit#heading=h.klfv0zl0zf92

**Comment by thepegisin** [comment]
- [ ] Updates published.
