### ISSUE TITLE
Clarify gathering information on Stay Home page

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#758]
- [x] Suggest edits to several questions re: gatherings

- Remove: "do not gather with any number of people who are not members of your household"

- [x] Establish best practices for when outside of home: 

- Maintain 6 feet of physical distance from those not in your household

- Wear a face cloth covering

- Wash or sanitize your hands as often as possible

- [x] Review by @thepegisin 

- [ ] Review by @abquirarte 

- [ ] Review by GovOps/SME

[Staging document](https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit#)

**Comment by KaylaPrusia** [comment]
@thepegisin staging is ready for your review

**Comment by KaylaPrusia** [comment]
@abquirarte , [staging](https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit#) is ready for your review. QAs with edits:

- If I am not an Essential Critical Infrastructure Worker, can I still leave the house?

- Are mass gatherings permitted?

- I want to express my political views.  How can I make my voice heard?

- Can I engage in political protest gatherings? 

- What conditions must be met to resume religious services at places of worship?

- Can children attend group activities (like Sunday school or Hebrew school) at places of worship?

**Comment by abquirarte** [comment]
Given pending litigation i will have to run these by GO legal 🙃

from my Samsung Work Device

**Comment by abquirarte** [comment]
Let me know if there is a new copy we want to route by GO. They're open to suggestions
@thepegisin @KaylaPrusia 

cc: @LizNobriga

**Comment by KaylaPrusia** [comment]
@abquirarte can we merge this with issue #808 ? The edits from yesterday/today are living in that issue/document

**Comment by abquirarte** [comment]
Yes! I will reference this in 808 and close this one :)
