### ISSUE TITLE
Replace Policy PDFs- support working families + practices for employer

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#763]
Timeline: This morning 

Page: https://covid19.ca.gov/industry-guidance/ 

Replace Support working families and practices for employer guidance documents. New versions have accessibility fixes. 

I will forward the email with new PDFs. :)

**Comment by LizNobriga** [comment]
@abquirarte, think these are live now (hard to tell because the dates are the same, but I think the header colors changed).

**Comment by abquirarte** [comment]
Thank you!!
