### ISSUE TITLE
create fully static env (no server) staging

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#764]
We have used out staging server for part of the production pipeline so now need a new staging environment which is where we push things that may not be destined for production

This is a good opportunity to upgrade our hosting architecture to make it less error prone, cheaper and easier to mange by not using server.

We can use Azure static web app service for this:
- [x] setup new Azure static web app service
- [x] Set it up to depoy from staing
- [x] Remove old staging pipelines
- [x] Test advanced features like redirects in the new env
- [x] Write docs on new env

**Comment by aaronhans** [comment]
FYI @carterm and @ChadABratton the new Azure static web app service environment is case sensitive

**Comment by aaronhans** [comment]
Verified redirects using the routes.json work and we can still use wildcard to 404, info on the new urls and admin in azure are in the staging readme

**Comment by abquirarte** [comment]
closing.
