### ISSUE TITLE
Updates to Health Corps page 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#765]
SME would like to add 7 attachments/docs to the Health Corps page to help with onboarding. I will follow-up and ask if the documents they want us to update are already accessible. (Proceed with posting anyway, we can replace the docs later). Consult with @artuoma and @aaronhans for non-pdf documents- is it OK just for download? 

Documents:
- How to file a complaint 
- Program FAQ details 
- Direct deposit
- Travel Info
- Travel expense claim
- SNF Orientation
- EMSA Pocket Travel Guide

Timeline- End of day/Friday AM
@thepegisin @JasonKarim 

- Angie will forward you the attachments. 
- Save the PDFs/documents in our Google folder
- Consider any other content updates we may need on the page itself. 
- These could be bulked in an accordion.

**Comment by abquirarte** [comment]
✔️ reviewed accordion. 

@thepegisin or @JasonKarim 

Any other content changes we want to propose for the page itself? (updates).

**Comment by JasonKarim** [comment]
The Health Corps page didn't get any meaningful feedback comment for several weeks. Hence we are not suggesting any changes at this time.

**Comment by thepegisin** [comment]
I'm good with it.

**Comment by abquirarte** [comment]
great, good to go ✔️
