### ISSUE TITLE
Translations for site

### ISSUE THREAD

**Issue by orielgomez** [cagov/covid19#773]
### new issue as of 7/8/2020

Add a page to Covid wiki on translations for better documentation:
https://github.com/cagov/covid19/wiki

Initial documentation saved here: https://docs.google.com/document/d/1v4RNfUq97DduXoQqfqNgco0Hhu1DeNl1OdrnfUNwXqc/edit 

Proposed pipeline from April 22: 
https://docs.google.com/document/d/1Y74qSIXeK0iW-2354ZhNxcN0VW3j1LfXPZHEYtGRB2A/edit#

----------
### original issue

~The covid19.ca.gov site is being translated into multiple languages. Languages include English, Spanish, Chinese (traditional and simplified), Korean, Tagalog, and Vietnamese.~

Any edits or feedback to translated content can be recorded in the following:

Translations for nav headings can be found [here].(https://github.com/cagov/covid19/blob/master/pages/_data/pageNames.json).

Any flags or bugs on the site can be documented [here](https://docs.google.com/spreadsheets/d/1EKFgkjBaQKrV6ePgBFLjOGuxFqVVaIv0zjX1QknKNlI/edit#gid=0).

**Comment by abquirarte** [comment]
@orielgomez I think it's time we document all of our translations stuff in a Github Wiki. I'm re-purposing this issue to track that. Let me know if you'd like to brainstorm on how to go about this.

**Comment by abquirarte** [comment]
@orielgomez i'm going to close this since you are tracking on a separate issue.
