### ISSUE TITLE
Design Fixes to county page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#775]
When: Friday 

- Make sure that the counties page links to https://covid19.ca.gov/roadmap-counties/
right now it links to: https://covid19.ca.gov/roadmap-counties/#track-data
![image](https://user-images.githubusercontent.com/9556188/84466945-7a172900-ac2f-11ea-95ef-7e75f6c8f41a.png)

- [x] Make design more "clickable"
>Is there a place / somewhere counties are on a watch list or monitoring list because covid numbers are going up? My wife is asking for her county San Joaquin.
They have an uptick and she wanted to have a place for the Mayor and city council to easily see for themselves.  Found this : https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/CountyMonitoringDataStep2.aspx This links from our website in the county data monitoring page but it’s hidden in a graphic that you wouldn’t necessarily think is clickable

![image](https://user-images.githubusercontent.com/9556188/84466774-0f65ed80-ac2f-11ea-857a-5dd892e78b26.png)

**Comment by kkoryaka** [comment]
More clickable buttons are done and live. Need to fix the homepage link to that page

**Comment by kkoryaka** [comment]
Homepage link is also fixed.
