### ISSUE TITLE
Guidance in Spanish and other languages

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#776]
Several guidance documents are being translated. 
The first batch is here. 
I will forward to Oriel, Liz, Carter, Art, and Aaron. 
cc: @artuoma @carterm 

### Challenge
Figure out how to add translated guidance to both Github (assuming we will add-ES), and how to properly link to them from the respective Spanish/Language pages. 

### Guidances
-Child Care Program guidance
-Support for Working Families

**Comment by orielgomez** [comment]
PDFs were uploaded today. This is done

Addressing challenge is simple, with standardizing the naming conventions for PDFs, we are able to identify PDFs in multiple language by adding the language codes at the end.

**Comment by abquirarte** [comment]
Thank you! 
Were the PDFs then added to the Spanish page?

**Comment by orielgomez** [comment]
Yes, they can be found in the industry guidance page:

Childcare programs can be found [here](http://covid19.ca.gov/pdf/guidance-supportworkingfamilies-es.pdf)

Help for working families can be found [here](http://covid19.ca.gov/pdf/guidance-supportworkingfamilies-es.pdf)

**Comment by abquirarte** [comment]
Gotcha. This still links to the English page: 

![image](https://user-images.githubusercontent.com/9556188/84557012-38908780-acdc-11ea-9325-bdc0e851ba17.png)


How do we link to the right thing? Or is this something the vendor has to do for us?

**Comment by orielgomez** [comment]
I did not receive the translated PDF for "Family friendly practices for employers." We only received two PDFs

I linked to the child care programs,
![child care programs](https://user-images.githubusercontent.com/58240906/84557180-bc973f00-acdd-11ea-8add-8e4d206c947c.PNG)

Here is where I linked the help for working families pdf:
![image](https://user-images.githubusercontent.com/58240906/84557204-eb151a00-acdd-11ea-9d8b-01758ca73e3f.png)

**Comment by abquirarte** [comment]
🙇 I fail. lol thank you @orielgomez 

In seeing this I wonder if it would be a good idea to note that the PDFs are in Eng?

**Comment by orielgomez** [comment]
I agree. In some places of the site, we have in parenthesis that the info or guidance is in English. This is usually if we are linking out to another dept or agency

**Comment by orielgomez** [comment]
Is this issue ready to close? @abquirarte

**Comment by abquirarte** [comment]
We just got another one from Maureen!

[  ] Tagalog "Support for working families" in accessible format

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by orielgomez** [comment]
Saw it! Will be uploaded tomorrow :)

**Comment by abquirarte** [comment]
(in your inbox @orielgomez )
More guidance:
[  ] Reopening childcare- simplified Chinese- accessible
[  ] Reopening childcare- Arabic- accessible
[  ] Reopening childcare- traditional Chinese- accessible

**Comment by TamaraIDEJA** [comment]
- [ ] Reopening childcare - Korean 

- [ ]  Reopening childcare - Tagalog

**Comment by orielgomez** [comment]
Translated guidance docs have been uploaded to github, waiting for @carterm to approve pull requests to go into master. 

@abquirarte @TamaraIDEJA

**Comment by TamaraIDEJA** [comment]
- [ ] Support working families - Tagalog
- [ ] Support working families-Chinese-Traditional
- [ ] Support working families-Chinese-Simplified 
- [ ] Support working families-Arabic

@orielgomez

**Comment by orielgomez** [comment]
I uploaded the support working families in tagalog earlier today

I have uploaded the support working families in ar, zh-hans, and zh-hant and placed their respective links into the pages. Sent a pull request to update pages with new links into master

@abquirarte @TamaraIDEJA

**Comment by abquirarte** [comment]
merged the ones I saw!

[Oriel's Tracking sheet here](https://docs.google.com/spreadsheets/d/1EKFgkjBaQKrV6ePgBFLjOGuxFqVVaIv0zjX1QknKNlI/edit#gid=659395124)

**Comment by orielgomez** [comment]
We are now up to date with incoming pdfs from CDSS.

Status on Translated Guidance PDFs 6/17/20:

Support working families:
-         Have: ar, es, zh-hans, zh-hant, tl
-         Missing: ko and vi

Child care programs:
- Have: ar, es, zh-hans, zh-hant, ko, tl
- Missing: vi, farsi

Expanded personal care services:
- Have: es, ko, vi
- Missing:  ar, tl, zh-hans-zh-hant

**Comment by aaronhans** [comment]
Let me know if you need anything else from engineering here @orielgomez

**Comment by orielgomez** [comment]
@aaronhans There are still a couple of guidance docs that we are still waiting for from CDSS. Nothing else needed from engineering here for now. Thank you!

**Comment by abquirarte** [comment]
@orielgomez can you send me the spreadsheet that tracks which ones we have, their links, and which ones are missing so i can follow-up?
