### ISSUE TITLE
Expanded Personal Care Services + Places of Worship Guidance

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#779]
### New Guidance doc 
On our drive:
https://drive.google.com/file/d/1nmuwy2kqQmKx-Z9UF1Ww3itKeFweGfJY/view?usp=sharing
https://drive.google.com/drive/folders/1tdEgmxB5L3Bb-RLX8bXjw2ihNBS5k3-5

### Comments
FAQ language from Legal is incoming please stay tuned..!
We do not need to update accordion 

### Content Captains 
@ashleydraper @thepegisin @LizNobriga 

### Timeline 
asap - noon

**Comment by LizNobriga** [comment]
county variance page [staging doc](https://docs.google.com/document/d/1bz5oU2idZ3heF4GLQY7d1jhFVSiylFUbdnDKcAoeFQ0/edit#)

**Comment by LizNobriga** [comment]
Note to look at june 12 blurb on county variance page next week.

**Comment by LizNobriga** [comment]
link is: [https://covid19.ca.gov/pdf/guidance-personal-care-services.pdf](https://covid19.ca.gov/pdf/guidance-personal-care-services.pdf)
