### ISSUE TITLE
Ux Testing in Spanish/Other Languages

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#787]
Creating an issue so we can start tracking and coordinating our efforts!

[Working doc](https://docs.google.com/document/d/1M2943Db5NkgvEf2Tulmr2bGG--iRyQqj6egon_ZTQOI/edit)

[Draft Ux script (English)](https://docs.google.com/document/d/121DKQfQ-8RzVsdlXrQ5MpvlaOXD-9h0_eH8yZ99pex8/edit#heading=h.ip68ol2oju6u)
[Draft Ux Script (Spanish)](https://docs.google.com/document/d/1EeUR_KqfClRrHI2XLC_wdHX9XPcfWg5nqDWgiGZ4Xvo/edit)

Priorities to gain new insights and recruit new UX testers

- [ ] Translate Feedback survey into Spanish

- [ ] Add Spanish interest form to for possible UX testers

**Comment by LizNobriga** [comment]
Masks question added to draft script - thanks @hilaryhb and @RubenCDII!

**Comment by abquirarte** [comment]
Are we meeting on this soon?

**Comment by LizNobriga** [comment]
I'll look for a meeting time this week. Oriel and Ruben have conducted two sessions and have made adjustments to the script. Fyi, we are putting status updates in [this doc](https://docs.google.com/document/d/1M2943Db5NkgvEf2Tulmr2bGG--iRyQqj6egon_ZTQOI/edit) for the moment.
