### ISSUE TITLE
update wordpress skin so it looks like production

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#795]
WordPress drifted out of synch with main site, we need to update the skin and see what we can do to make them stay in synch automatically

**Comment by aaronhans** [comment]
- [ ] update navigation HTML
- [ ] update site chrome
- [ ] update CSS
- [ ] update in page JS
- [ ] get the public sans font to work in WP

**Comment by aaronhans** [comment]
got the font working with a google font hack since I still don't have access to the CDN. The WordPress skin is pretty close to the live site now so it is more helpful for authors to use it while writing new content. We should publish to "staging-only" in order to share with stakeholders. 

This task is complete, ready to close

**Comment by aaronhans** [comment]
Latest skin is checked into this repo https://github.com/cagov/covid-wp-author-skin

**Comment by abquirarte** [comment]
🚢
