### ISSUE TITLE
Allow WordPress pipeline to publish to staging only

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#797]
We discussed doing this by having authors add a tag to posts that would make the latest version of that post get published only to the staging branch. This will give them preview capability without deploying to production.

**Comment by carterm** [comment]
Maybe a "staging_only" tag?  They can remove the tag to publish to master.

**Comment by aaronhans** [comment]
This is in production now

**Comment by abquirarte** [comment]
Sweet. What does this entail for the content team? Anything we need to document?

**Comment by aaronhans** [comment]
Yes this is a massive achievement, kudos to @carterm!

Since Carter is out this week though I need to monitor this and make sure it works smoothly. If it doesn't we can rollback to the previous version of the service. Once we are sure we are in good shape I will share more info with the content team like:

How to have better visibility into the publishing process:
- any change to WordPress that is published will be picked up by our change monitoring service and get pushed to github, you can see a new commit in github or monitor the code-movement slack channel to see a notification everytime a change reaches github
- new updates to github trigger out static site generation build (using 11ty.dev). You can see this activity here: https://github.com/cagov/covid19/actions
- A completed build pointed at the staging site means the change that triggered that build is now visible at staging.covid19.ca.gov

The latest content publishing service works a different way which has generated some new tasks like #939

**Comment by aaronhans** [comment]
This is working nicely, good to close

**Comment by abquirarte** [comment]
Did we want to do a walk through with the content team? 

Wondering: 
If we test now on a live site, will the change only go to the live site or only staging? Do you then remove the tag once ready to publish live? And i'm assuming the build out to staging will take the same about of time to show up as it does on production?

**Comment by aaronhans** [comment]
Sure, happy to walk through things with the content team anytime

I've been testing this and it works as designed: posts with the "staging-only" tag will not go to production, only to staging. Any post published without the tag goes everywhere.

Builds to staging are much faster than production and we have full visibility into each step:
- you see the change commit in the staging branch
- then you can watch the staging built in github actions
- as soon as that staging build is complete ~3 minutes the change is browseable at staging.covid19.ca.gov

**Comment by abquirarte** [comment]
Fantastic!! 🚀 👨‍🎤
