### ISSUE TITLE
create CDN tactical purge button (FKA nuke button)

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#798]
Use Azure CDN API to create a button that will allow anyone on our team to purge specific urls from the CDN.

This will help in emergencies where we need to remove previously published content or accelerate an update. This can accelerate time to live by 10 minutes because we won't have to wait for the CDN to expire or get Chad's help clearing it

**Comment by abquirarte** [comment]
Is this done and documented? :)

**Comment by aaronhans** [comment]
new CDN for testing nuke: https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourcegroups/RG-ODI-SCRIPTTESTING-D-001/providers/Microsoft.Cdn/profiles/cdn-cdt-akamai-shared-d-001/endpoints/cov19staticwebapp/overview
https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourceGroups/RG-ODI-SCRIPTTESTING-D-001/providers/microsoft.cdn/profiles/cdn-cdt-akamai-shared-d-001/overview

new static web app for testing nuke: 
https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourceGroups/RG-GO-COVID19-D-001/providers/Microsoft.Web/staticSites/SWA-GO-COVID-D-004/staticsite

Remaining tasks:
- [ ] write script that hits CDN API and clears url 
- [ ] integrate github action that records changed files
- [ ] during deploy trigger script that stores changed file list
- [ ] store that changed file list somewhere it can be read and cleared
- [ ] create FAAS that retrieves list and runs purges
- [ ] integrate FAAS call into post deploy process

**Comment by aaronhans** [comment]
Update @ChadABratton has created this button in Azure (https://calenterprise.visualstudio.com/CDT.GO.COVID19CAGOV.Website/_build?definitionId=403). We need to integrate this into our deploy process so it is called with the urls to purge right after the new build reaches production

**Comment by aaronhans** [comment]
Tracking files modified via github action is done in this repo and can be reused: https://github.com/cagov/covid-static/blob/master/.github/workflows/azure-blob.yml#L12

**Comment by aaronhans** [comment]
will create new tickets for this after migration to new CDN is complete
