### ISSUE TITLE
Testing taskforce website and testing webspage

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#802]
## context 
The Testing Task Force is working on transitioning back to the state. CDPH is thinking this would be a good time to merge the TTF webpage with the Testing Sites/Testing and Treatment page, both links below:

https://testing.covid19.ca.gov/ TTF

https://covid19.ca.gov/testing-and-treatment/#top Testing Sites/ Testing and Treatment

From CDPH:
Who manages the content on the taskforce website? 
- The TTF comms team – after the end of the month, that will largely be me in conjunction with the CDPH comms team.

How often is the taskforce website updated? 

- About once a week is my best guess – could be less going forward.

Do you foresee the taskforce continuing to provide updates that the public needs to know? 

- Much of the content is most likely of interest to labs. There is some overlap in content for the public, such as information about testing sites, but that also is summarized on the existing testing

## Task:
Assess the content on both pages and provide recommendation on should these be merged? Should we migrate content to our page (add as accordion) and create a redirect. 

## timeline 
By noon tomorrow.

**Comment by thepegisin** [comment]
- What problem are we solving by merging the two pages? If it's content that's not aimed at the general public, moving it to our **Testing and treatment** page would likely contribute to page bloat.
- What information on the TTF page is changing? If nothing, we should probably just make sure we have a link to this page on our **Testing and treatment** page. If it's a lot, we could likely boil that down to one Q/A that is added to our page, and then we delete the TTF page.

**Comment by abquirarte** [comment]
I have the same questions @thepegisin. I'd rather leave these as is unless we see there is value. A compromise would be too add an accordion that summarizes the work of the taskforce. I have not looked at the content that they have. I wonder what labs they are referring to.

**Comment by JasonKarim** [comment]
I added the suggested edit to Testing & treatment page for review by @thepegisin.  Essentially pick-up the contents that public need from the TTF page (Explanation of coronavirus test vs antibody test) and the rest of the contents in their entirety.

**Comment by thepegisin** [comment]
- [ ] My edits to @JasonKarim's addition made.

**Comment by JasonKarim** [comment]
![image](https://user-images.githubusercontent.com/62369563/84712051-8d224580-af1c-11ea-9791-c0d62fba7496.png)
![image](https://user-images.githubusercontent.com/62369563/84712125-afb45e80-af1c-11ea-8d8c-272ef666c68e.png)

**Comment by JasonKarim** [comment]
Latest @abquirarte comments addressed, revision reviewed by @thepegisin, waiting for final approval.

**Comment by abquirarte** [comment]
I added a comment. It looks like it has to be reorganized?

I will check in with TTF and let them know we have suggested edits coming.


Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by JasonKarim** [comment]
@abquirarte Testing & treatment page is re-organized (was waiting for your blessing before moving things around)

**Comment by JasonKarim** [comment]
Re-arranged the page. Was waiting for your blessings before moving things
around.




Karim
CHHS Office of Innovation
Ph. 916-214-6311

**Comment by abquirarte** [comment]
Got my blessing! I will now send over to CDPH and TTF

**Comment by TamaraIDEJA** [comment]
### Content
in your mailbox

### Content Captains

@JasonKarim @thepegisin

### Timeframe

COB tomorrow
