### ISSUE TITLE
GO edits to Stay home Q&A

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#808]
[GO edits 6/15 staging doc](https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit) live now

In progress:
- [x] Suggested revisions to improve readability (@thepegisin)

**Comment by thepegisin** [comment]
Readability edits with tracked changes here: https://docs.google.com/document/d/14uqdRFnN8rCH8sKIE1ofUzBnG0MfMFKUX7F9Df_L1Mg/edit

Clean copy of readability edits here: https://docs.google.com/document/d/1lSp7H4eC5I_AcWt9XyJG31kB8uP-aMJYnsxHWHp25-8/edit#

**Comment by abquirarte** [comment]
👀 reviewing. Will send to GO policy and Legal for 👍 🤞

**Comment by abquirarte** [comment]
Closed https://github.com/cagov/covid19/issues/758 since this one takes over. :)

**Comment by KaylaPrusia** [comment]
@abquirarte have we heard back re: this? Particularly edits to the [stay home page to reflect mask guidance](https://docs.google.com/document/d/1birVt1BlW8G2HMoRkP5RnQC718pwyom9mkj0ZIJx31o/edit)...

**Comment by abquirarte** [comment]
Nope. Just pinged them again. Reminded them it's been a week.

**Comment by abquirarte** [comment]
We heard back!
Saved in folder (today's date) Download the document for track changes. If it doesn't work, I can forward. https://drive.google.com/file/d/1rlPkW1ySfiTPSAiR3Q4lwCWUB1Y-dJnl/view?usp=sharing

for context:
>CDPH will endorse mandatory face coverings at any gathering of any kind when physical distancing can’t be maintained. That’s what the guidance directed and they weren’t looking to differentiate on protected activities – baseline public health consideration irrespective of the event / place.

>For the p.1 edit, suggest it should be similar to the dog guidance below. You’re required to physically distance. Period. But carry a mask at all times and worn if needed.

**Comment by KaylaPrusia** [comment]
Yay! Looking through now

**Comment by KaylaPrusia** [comment]
Edits are live on the page

**Comment by abquirarte** [comment]
closing this. Working out of this one:
