### ISSUE TITLE
Refresh homepage header text

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#824]
Update homepage header text to more accurately reflect current directives.

Current:
**Your actions save lives**
As California reopens, Californians must follow best practices:
wear a face covering, wash your hands, stay home when sick.

But:
- A few counties don't require masks, so "must" is inaccurate
- We are still under a stay home order, not just if you're sick

- [x] Develop new language
~[ ] Get it approved by GO~ AQ sent a week ago.  
- [ ] Stage
- [ ] Publish

**Comment by thepegisin** [comment]
Suggested language:

**Your actions save lives**
As California reopens, stay healthy:
wear a mask, wash your hands, keep your distance.

**Comment by abquirarte** [comment]
✔️ Love the framework. Sent to GO.

**Comment by abquirarte** [comment]
This is taking a while, so I will go on a limb and say go ahead an publish with an edit. 

Your actions save lives
As California reopens, stay healthy:
wear a mask `or face covering,` wash your hands, keep your distance.

**Comment by thepegisin** [comment]
Shoot, I didn't see this. ^ But I have an update that I think is more timely and flows a little better.

The current tagline specifically references "reopening," which feels a little dated. Some counties are sort of "reclosing." Here's a more durable, brief tagline that prioritizes masks. I'm including how it looks in both desktop and mobile.

**Your actions save lives**
Keep Californians healthy.
Wear a mask, wash your hands, keep your distance.

<img width="532" alt="2020-07-02_proposed-tagline-desktop" src="https://user-images.githubusercontent.com/63249920/86418695-d648f800-bc85-11ea-84d2-a993a7f5e74e.png">
<img width="300" alt="2020-07-02_proposed-tagline-mobile" src="https://user-images.githubusercontent.com/63249920/86418700-d943e880-bc85-11ea-83ef-f83055bbf15c.png">

**Comment by abquirarte** [comment]
Sweet! Close when live :)

**Comment by thepegisin** [comment]
We are live!
