### ISSUE TITLE
Update to Businesses page - PPP

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#830]
[google staging doc](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#heading=h.b8qkspxdvu7i)

- [x] updating EIDL info - SBA accepting applications from all businesses as of June 15 (not just agricultural)

- [x] new changes due to Paycheck Protection Program Flexibility Act, interim final rule

**Comment by abquirarte** [comment]
OK let's publish what we have!

**Comment by LizNobriga** [comment]
drafting new edits, will ping @thepegisin when ready for review!

**Comment by LizNobriga** [comment]
- [ ] Proportion of PPP funding that must be used on payroll costs to qualify for full forgiveness dropped to 60% (from 75%). 
- [ ] Loan Forgiveness Application revised 6/16/20, including standard application and instructions, and EZ application and instructions that can be used by some borrowers
- [ ] Adjustment to payroll costs and owner compensation in calculating PPP loan forgiveness under new 24-week covered period (previously was 8-week period)
- [ ] Minimum term for PPP loans raised to five years for all loans made on or after June 5. For loans made before June 5, the two-year minimum maturity remains in effect unless both the borrower and the lender agree to extend it to five years.
- [ ] Verify that the application deadline for PPP loans remains June 30.

**Comment by LizNobriga** [comment]
@thepegisin has reviewed, ready for @abquirarte review [staging doc](https://docs.google.com/document/d/1ZZWgYFzIw1Vg9FMwf3o2NRR0jzyBj-c6t8Uxwz9novA/edit#heading=h.b8qkspxdvu7i)

**Comment by LizNobriga** [comment]
changes are live @abquirarte

**Comment by LizNobriga** [comment]
- [ ] update links for PPP loan forgiveness application and instructions for Q/A: 
`Where do I find more information on allowable expenses for a forgivable loan under the Paycheck Protection Program?`

**Comment by LizNobriga** [comment]
items are all complete/live - ready to be closed @abquirarte

**Comment by abquirarte** [comment]
great thank you!
