### ISSUE TITLE
Translate hotline info in footer on translated pages

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#836]
New hotline info appears on footer of translated pages in English. 

Please translated and replace on the footer of these pages.

**English text:**
COVID-19 hotline: 1-833-422-4255 M-F 8AM-8PM, Sa-Su 8AM-5PM

Phone number is a dial link.

**Comment by carterm** [comment]
Moving the text into the footer data WP pages.

**Comment by carterm** [comment]
Translatable labels are now at the end of the footer files.
https://as-go-covid19-d-001.azurewebsites.net/wp-admin/edit.php?category_name=footer-data
