### ISSUE TITLE
Provide User Feedback to Testing Taskforce

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#837]
### Effort 

Testing Taskforce is going to take a stab at editing their page. They have asked us to provide insight and guidance. Team, can you help prepare key questions, user feedback and anything that came through from the latest user testing of the testing page - so that we can share with them. Any persistent or emerging themes you are tracking? Thank you very much! 

### Captains 
@JasonKarim @thepegisin @KaylaPrusia @hilaryhb 

### Timeline 
Not urgent - end of this week - beginning of next week is fine

**Comment by abquirarte** [comment]
This was previously tracked here :) 
https://github.com/cagov/covid19/issues/802

**Comment by JasonKarim** [comment]
We have suggested [edit](https://docs.google.com/document/d/19Xl1MoNLaA8n9sCjEqI9MTkQlIoJKTUzcHCa5bXOyjg/edit#) and are [collecting feedback comments ](https://docs.google.com/document/d/1kbWunQomUxyfKHw6WONTJ_4e9aGfMfJUcdbuHPiLZ4g/edit)
