### ISSUE TITLE
Update survey name/menu item

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#847]
The survey page and menu item are misnamed. They use an old name for the roadmap, and not the current name.

Please update accordingly:

- [x] In the page title, replace **Recovery** with **Resilience** and make the **s** in **Survey** lowercase (**Give your input: California Resilience Roadmap survey**) @ashleydraper 

- [x] In the **How you can help** menu, change **Recovery roadmap survey** to **Resilience Roadmap survey** @kkoryaka

**Comment by ashleydraper** [comment]
@thepegisin 
Looks like Resilience is already on the page. Don't see the word "survey"

**Comment by abquirarte** [comment]
Closing, i think this is live
