### ISSUE TITLE
Auto-fix content links to translated pages

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#850]
During the build, any links to internal pages that have translated version should be automatically updated.

`href="https://covid19.ca.gov/sign-up-for-county-alerts/"`
should change to...
`href="https://covid19.ca.gov/sign-up-for-county-alerts-ar/"` (for Arabic)

It's possible, we could have the Wordpress service do this automatically when translations are loaded into the repo, rather than during build time.

**Comment by carterm** [comment]
A quick win would be to put 11ty code in the url...
`href="https://covid19.ca.gov/sign-up-for-county-alerts{{tags | langFilePostfix}}/"`

...but that might bust the translation pipeline, and it would be hard to expect the content folks to do that.

**Comment by abquirarte** [comment]
Is this the same thing as what I've captured in #930 ? @carterm

**Comment by carterm** [comment]
We have the document--en.pdf -> document--es.pdf process in place for pdfs, and full url links to the covid19 site will automatically be switched for translated pages.
