### ISSUE TITLE
Quick win: Reduce menu items under How you can help

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#851]
Per user feedback, this menu list is long and may be too cluttered with low-appeal links. And as many of the links aren't on our site, they aren't internal destinations.

Solution:
- [x] Create a new page called **More ways to help** @thepegisin 
- [x] Put links to [Volunteering](https://serve.ca.gov/), [Checking on the elderly](https://www.engageca.org/), [Donate medical supplies](https://www.covid19supplies.ca.gov/), and [Technology solutions](https://tech.covid19.ca.gov/) there. @thepegisin 
- [x] Get approval from @abquirarte, publish
- [x] Once new page is up, remove these links from the menu. @kkoryaka 
- [x] Reorder remaining links like so: Fighting discrimination, Plasma donation, Resilience Roadmap survey, California Health Corps, Great Plates provider form, Social media sharing, More ways to help @kkoryaka 

- [ ] Last steps: Add back in **Social media sharing** (next to last link - https://toolkit.covid19.ca.gov/), capitalize the **R** in **roadmap**.

**Comment by carterm** [comment]
Need to table-ize the footer links so that it uses the same translation file as header.

**Comment by aaronhans** [comment]
Is it helpful to get a report on which pages still remaining in the nav are least popular and by how much?

**Comment by thepegisin** [comment]
Yes!

**Comment by abquirarte** [comment]
Looking forward to seeing this in staging!

**Comment by thepegisin** [comment]
Drafted the page in Staging docs. Ready for your review, @abquirarte.

https://docs.google.com/document/d/1tOuSNkCIKFVCUtSzmC0vEqZUafFTjXXY-4Vdo2zLDIY/edit#

**Comment by abquirarte** [comment]
Love it. Looks great.
Let's push. 🚀
