### ISSUE TITLE
Wacky varying accordion lengths on the County variance page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#853]
Accordions should be all the same length, but that's not happening on the [County variance](https://covid19.ca.gov/roadmap-counties/) page.

![2020-06-17_1744](https://user-images.githubusercontent.com/63249920/84965284-59cdeb00-b0c3-11ea-9698-26a236ec602d.png)

**Comment by aaronhans** [comment]
errant div was introduced in the 3 panel custom html block causing all kinds of strangeness. I removed it and republished the post
