### ISSUE TITLE
Broken links to fix - English pages 6/17

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#856]
Pulled a broken links report on SiteImprove 6/17. Checked all of them, and these are actual broken links we need to fix. 

@JasonKarim 
- [x] **Health care:** https://covid19.ca.gov/healthcare/ 
In accordion text of I have a concern or complaint…, last word in link (**Care**) has broken link. Make whole link go to https://www.healthhelp.ca.gov/ 

@ashleydraper 
- [x] **Great Plates Delivered:** https://covid19.ca.gov/restaurants-deliver-home-meals-for-seniors/
Several dial links on this page are not working. Please click all and make sure they bring up a dial app, not a blank page. If not, check link formatting. Correct -> tel:[800-555-1212] (no / after)

@LizNobriga 
- [x] **Businesses and employers:** https://covid19.ca.gov/business-and-employers/
Several dial links on this page are not working. Please click all and make sure they bring up a dial app, not a blank page. If not, check link formatting. Correct -> tel:[800-555-1212] (no / after)
- [x] **Telehealth:** https://covid19.ca.gov/telehealth/
Several dial links on this page are not working. Please click all and make sure they bring up a dial app, not a blank page. If not, check link formatting. Correct -> tel:[800-555-1212] (no / after)

@KaylaPrusia 
- [x] **Stay home Q&A:** https://covid19.ca.gov/stay-home-except-for-essential-needs/
Under **Can I go to the Department of Motor Vehicles (DMV)?**, link to extension online is broken. Find new link or leave as plain text.

**Comment by ashleydraper** [comment]
@thepegisin 
I've addressed all of the phone numbers and double checked that they worked on my cell phone. Are you still noticing broken links?

**Comment by thepegisin** [comment]
They work now. I think the problem was a / at the end of the link broke it.

**Comment by thepegisin** [comment]
Great job, guys!
