### ISSUE TITLE
Broken links to fix - translated pages 6/29

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#858]
Found a whole lot of broken links using SiteImprove. Approximately 90 of them in the translated pages alone. It appears to be every PDF on a translated page, among other things.

The highest priority one to fix is the Immigrant's Guide PDF. **All links to translated Immigrant's Guide PDFs are currently broken.**

@carterm, details are in the attached document. Please fix and let me know if you need my help.
[https://docs.google.com/document/d/1lnA4dgdMMhI19SBCY6Xoq9q2jHs0yYRE/edit](https://docs.google.com/document/d/1lnA4dgdMMhI19SBCY6Xoq9q2jHs0yYRE/edit)

**Comment by abquirarte** [comment]
@orielgomez has a cool spreadsheet where he is keeping track of some of these translated links. Can we add here too so we can track? 

Thank you for flagging this!

**Comment by carterm** [comment]
I believe he has the spreadsheet here...
https://github.com/cagov/covid19/issues/773

**Comment by thepegisin** [comment]
Did a little more digging to see if we can fix translated Immigrant's Guide links quickly. Short answer: no. They're not in WP so can't quickly and manually author.

We have two problems here:

- Translated pages are supposed to keep up with their English versions. But they're not. There's a paragraph in the English version that has links to all translated versions of the Immigrant's Guide PDF. Its links are correct. But the translated version of this paragraph has old links that are broken. 

- Each translated page needs to link to the Immigrant's Guide PDF in its language. English links to English PDF, Spanish links to Spanish PDF, etc. But you have to know the URL, and you probably have to replace it manually. It's an IT problem, not a translation issue. If we don't have the capability to manually edit each page, we can't fix the links.

Here are the broken and correct links for all translations of the Immigrant Guide PDFs. 
[ImmigrantsGuidePDFLinks.txt](https://github.com/cagov/covid19/files/4801784/ImmigrantsGuidePDFLinks.txt)

**Comment by orielgomez** [comment]
This broken links probably warrants a talk with all content team and captains to help with this big lift. Will schedule something and strategize on this - my thought is to have this done in waves.

**Comment by orielgomez** [comment]
I have manually updated all pages with their relevant links and have pinged CDSS regarding the Traditional Chinese guide, cannot seem to find it. @thepegisin 

Thank you @KimberlyglennTSM for approve copious amounts of pull requests.

**Comment by KimberlyglennTSM** [comment]
Thanks Oriel,

Kimberly
*Kimberly Glenn*
Team Success & Delivery Manager
c. 916-270-3515
Kimberly.Glenn@Alpha.ca.gov
Alpha.CA.gov <http://alpha.ca.gov/>
Follow us: Web | Blog | Twitter

**Comment by thepegisin** [comment]
Thank you, @orielgomez! That was a major and badly-needed fix. 

- [x] Fix Immigrant's Guide PDF links in **Help for immigrants** page body text

Note that there are still two broken links to it in the **Help for immigrants** page accordions for all translated pages. On the Spanish page, those accordions are:

- **Recibir este apoyo afectar...**
- **Para que otros programas...**

Can these be fixed?

- [ ] Fix Immigrant's Guide PDF links in accordions

**Comment by thepegisin** [comment]
Update: Attached is the 6/29 broken links report. Checked all the broken links that SiteImprove caught and here's what's still broken: [https://docs.google.com/document/d/1fYQrcl1Kc4YLi1Iw_MClLPv1Yc5jOKfE/edit](https://docs.google.com/document/d/1fYQrcl1Kc4YLi1Iw_MClLPv1Yc5jOKfE/edit)

**Good news:** You fixed a lot of links!
**Bad news:** There are still 61 left to fix.

Please take a stab at these and let me know if I can clarify anything. @carterm @orielgomez

**Comment by aaronhans** [comment]
We made some severe backward steps but took remediation measures. Process going forward will be to use siteimprove reports directly and clean up the reports by flagging any false positive as "ignore" so siteimprove reports become more reliable.

There are still a few remaining broken links so I'll leave this open

**Comment by aaronhans** [comment]
Latest link report contains much fewer issues
- [ ] broken links to news (which is not translated) from translated homepages
- [ ] broken links inside immigration post (Oriel addressed, will cascade with AvantPage update)
- [ ] couple more tel links with invalid syntax on great plates
- [ ] broken link reported on data.ca.gov which was temporarily offline, back up now

The broken links report is cleaned up now, some invalid issues are ignored so report should only contain real issues. We should continue to monitor that report but we have addressed the current list and can close this issue.

Thanks for championing this @thepegisin

**Comment by abquirarte** [comment]
yay!!!! ❤️
