### ISSUE TITLE
Great Plates Content Update 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#860]
- [x] The City of Stockton has suspended its Great Plates Program as of June 10, 2020, for lack of funding. It would be most accurate to use this wording something like this. City of Stockton: Program suspended as of June 10, 2020.

@ashleydraper

**Comment by ashleydraper** [comment]
@TamaraIDEJA @abquirarte 
updated the website to reflect the suspension of Stockton's great plates program

**Comment by ashleydraper** [comment]
@TamaraIDEJA @abquirarte 
Proposing we close this issue
