### ISSUE TITLE
Contact tracing page updates 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#871]
To add to Q/A in contact tracing page. Content has been approved by JIC and GO. 

How do I become a contact tracer?

The initial phase of California Connected, the state’s contact tracing program, will utilize existing resources and redirect state employees to begin contact tracing efforts. Offers of additional support from the private sector and qualified members of the public are appreciated, but contact tracers from outside state government may not be needed until a future phase. Thank you for wanting to share your expertise and resources with your fellow Californians.

**Comment by JasonKarim** [comment]
New Q/A added & follow Q/A deleted:

Can I apply for a contact tracing position?
Contact your local health department to see if they are hiring contact tracing staff.
