### ISSUE TITLE
Quick wins from usertesting.com for Statewide industry guidance

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#873]
Quick wins from 6/14: [Usertesting.com search and QA](https://docs.google.com/document/d/1w8Bj3T3XmUQBHayIZuANQ72IIeBwQekxzUZTCeSsZEU/edit?ts=5ee96815#)

On Statewide industry guidance page, some people thought the “must” information was all they would need to do, and didn't scroll down to the industry-specific guidance below (accordions).
- [ ] Need to call out that “the exact business type has additional details and checklists below.”  

[google staging doc](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit?dls=true) and [clean copy](https://docs.google.com/document/d/1pjAoDGWc5SqjkgIK2jxd7b4VnvCqtjGZMZ8hEhx__Cg/edit)

**Comment by LizNobriga** [comment]
Revisions ready for your review, @thepegisin.  [google staging doc](https://docs.google.com/document/d/1BAOrl_P00ljbxEHK5zduvj9_YAIikHJM/edit#) and [clean copy](https://docs.google.com/document/d/1pjAoDGWc5SqjkgIK2jxd7b4VnvCqtjGZMZ8hEhx__Cg/edit#)
Hemingway score: 
![image](https://user-images.githubusercontent.com/58706834/85347297-02f25800-b4ad-11ea-99ac-828d4cb65f94.png)
Note: This score doesn't included CDPH bold text regarding face coverings.

**Comment by LizNobriga** [comment]
Also considering adding a heading like **`Employer policies`** so the section listing sick leave, workers' comp, and family-friendly practices doesn't blend into the section preceding it.

**Comment by thepegisin** [comment]
LOL - unfortunately, the user doesn't get to miss those hard-to-read sections of the page.

Readability for this section: Grade 8, 2 hard-to-read sentences, 1 very-hard-to-read sentence.
Readability for the whole page: Grade 12, 13 hard-to-read sentences, 58 very-hard-to-read sentences.

**Comment by LizNobriga** [comment]
@abquirarte  - 

The statewide industry guidance revisions are ready for your review. This was initially identified as a 'quick win' from @hilaryhb's user testing, but has evolved into a larger improvement effort to the entire page. 

Thank you to @thepegisin for reviewing and pushing for more! 

I think it's easiest to review the [clean copy](https://docs.google.com/document/d/1pjAoDGWc5SqjkgIK2jxd7b4VnvCqtjGZMZ8hEhx__Cg/edit#) that I'm linking here. The marked up version has become difficult to follow.

Also, only one accordion (agriculture) is included in the revision. If we can hopefully get buy in for this one, we can make similar revisions to the remaining accordions. A few have more specific language, which we can address at that point.

**Comment by abquirarte** [comment]
Closing this since yesterday's updates probably take over this.
