### ISSUE TITLE
"Select language" button not translated in either Chinese version

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#874]
In both our Simplified Chinese and Traditional Chinese version of the website, the **Select language** button at the top is not translated (though the **Search** button next to it is).

Simplified Chinese: https://covid19.ca.gov/zh-hans/

Traditional Chinese: https://covid19.ca.gov/zh-hant/

**Comment by carterm** [comment]
Fixed.  Also fixed the "More..." at the bottom of the language list and the "COVID-19 Hotline" text.

**Comment by carterm** [comment]
https://github.com/cagov/covid19/commit/4224895fc026f4af0fcd271924631afccf7a8a5f

**Comment by carterm** [comment]
https://github.com/cagov/covid19/commit/fb77336cefe6b833d37fdc35dfdb210c54dcfb68

**Comment by carterm** [comment]
Confirmed deployment.
