### ISSUE TITLE
Replacing infographic- contact tracing page, Eng and Spa

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#888]
## context
There is a a minor edit to the CA Connected infographics—reques is to update the English and Spanish on the COVID-19 contact tracing pages.

## Timeline
tomorrow EOD

Source:
They files are here in both JPG and PDF format: [Images](https://gmmb.box.com/s/cvoyinxqz0xqd9kk4ch5zq2xp4lahocf )

**Comment by thepegisin** [comment]
To update this, I need help with learning how to upload an image or file and getting its correct URL for insertion into the page.

**Comment by orielgomez** [comment]
@thepegisin I can show you how to upload a file into github.

Just to clarify, are we uploading this as a PDF or jpg? @abquirarte

**Comment by aaronhans** [comment]
I'd like to:
- [ ] use the new binary file management repo for this 
- [ ] in addition to writing a new eleventy post processing script that looks for the existence of a translated file and inserts it into the HTML if it finds it. 

This will allow us to use translated images and pdfs safely without risk of the translators overwriting our links

**Comment by orielgomez** [comment]
@aaronhans sounds great. I'l like to hear more about this

**Comment by aaronhans** [comment]
I'll update these files and write the 11ty plugin tomorrow after the new domain is fully operational. Chad, Carter and I will handle the next few binary file updates (img and pdfs) and writeup tips for using the new repo when we are sure everything is working smoothly

**Comment by abquirarte** [comment]
Great, thank you guys!

**Comment by aaronhans** [comment]
step 1: two new compressed files uploaded to new CDN
 https://files.covid19.ca.gov/pdf/img/California-Connected-Infographic--es.jpg
 https://files.covid19.ca.gov/pdf/img/California-Connected-Infographic--en.jpg
step 2: PR to rewrite translated links dynamically https://github.com/cagov/covid19/pull/892/files

once PR is merged we can modify english post in WordPress to use the --en file, then the translated version will get the new url and it will be dynamically rewritten during build to the localized file

**Comment by aaronhans** [comment]
New images and pdf are deployed to new CDN using new url format, new translation link filter is part of build now so urls in this format in the english version are rewritten if translated files are found so these links will not be broken by the translation team

**Comment by abquirarte** [comment]
Amazing! So these are now live?

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by aaronhans** [comment]
Yes

**Comment by abquirarte** [comment]
Thank you @aaronhans 🚀
