### ISSUE TITLE
Stay Home / DMV Updates

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#891]
Updates to the DMV q/a based off of [press release](https://www.dmv.ca.gov/portal/news-and-media/dmv-resumes-behind-the-wheel-drive-tests-with-new-protocols-on-friday/)

- [x] [Staging document](https://docs.google.com/document/d/13CTjenmiQTt1EuJ7jkl0ooccqwDKbbQgn_El7JHOgck/edit#)

@abquirarte staging doc is ready for your review

**Comment by abquirarte** [comment]
looks great! Let's get this live @KaylaPrusia !

**Comment by LizNobriga** [comment]
I can cover since @KaylaPrusia is out Wed-Thurs.

**Comment by LizNobriga** [comment]
These are live!

**Comment by abquirarte** [comment]
yay! Thank you!
