### ISSUE TITLE
Team sports- clarifying language for county page, statewide guidance

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#897]
GO reached out. We need clarifying language around youth sports/group sports. Guidance for that coming (eventually). 

Timeline: tonight, Tuesday 6/23

- [x] Consider adding this to: Gyms guidance, and Day Camps
>"Recreational Team Sports are not permitted at this time and will be subject to separate guidance" 

- [x] Add to list of *what is NOT open statewide or county*

**Comment by LizNobriga** [comment]
[staging for stay home](https://docs.google.com/document/d/1BWClKx5CUxerlFr0gyqmo1vrcCJbrXNffdDR73YQFXA/edit#heading=h.gntmlftbqn4i)
[staging for county variance info](https://docs.google.com/document/d/1BchWugtDrVecV7MnjQ3Mnn0tqPkpUehhe76uJRXd4B8/edit#)

**Comment by abquirarte** [comment]
✔️ great! Let's publish and confirm when live 🙏

**Comment by LizNobriga** [comment]
[staging for statewide industry guidance](https://docs.google.com/document/d/1cWrm82fnG1N_gFunobcCcGPInofKD1GFltZVXI73sws/edit#)

**Comment by LizNobriga** [comment]
These are live
