### ISSUE TITLE
Design/Content Update Considerations 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#90]
![covid19page](https://user-images.githubusercontent.com/9556188/77239541-2a2d4680-6b99-11ea-8b6a-8b0664542310.PNG)

## Considerations
- HTML the Essential PDF
- Add volunteering- "serve.ca.gov"
- Move "avoid gatherings" to don't list 
-[Review info architecture](https://docs.google.com/document/d/1SYQPmBNFjWtruABzQei1MpIIFIXzk8ddmhHzKaAUCGw/edit)
- Make get testing and treatment it's own page
- Review content in what you can do page
- Clean up FAQ - categories?
- County Alerts
- Spanish (?)
- Make an action link: See the list of Essential Critical Infrastructure Workers (pdf).

### Other Features
Map?
Search?
New info architecture?
New services highlighted?
Push for county alerts
Glossary
County scrapper?

**Comment by abquirarte** [comment]
From Corey:
Also, a quick list of usability/design changes that should be possible for the team without major approvals. because they can be done without any word changes:

- Adding accordions on Q&A
- Implementing search (esp important as the content gets less edited and organization gets sprawling)
- Moving testing & treatment to its own page (no content changes)
- Make every question an h4 instead of bold so they get anchor tags

**Comment by artuoma** [comment]
##I can take on:
- Adding accordions on Q&A
- Moving testing & treatment to its own page
- Make every question an h4 instead of bold so they get anchor tags

**Comment by abquirarte** [comment]
- [ ] CA.gov logo will link to GO site
- [ ] Actions save lives logo will link to toolkit
- [ ] CDPH will link to Covid19 page on CDPH site

**Comment by abquirarte** [comment]
Closing this issue @artuoma most of these have been addressed. Others will be turned into their own issues if necessary.
