### ISSUE TITLE
Edits, contact tracing page. 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#904]
Given there is no treatment yet for COVID-19, CDPH and the contact tracing team are requesting for us to remove the word "will receive treatment" from the page and replace with "medical care" 

https://twitter.com/CAgovernor/status/1276341914086694912?s=19

## timeline 
By tomorrow AM 

[X] update Google staging doc 
[X ] stage in WP 
[X] publish in WP page 
[X] ping AQ and close issue when live

**Comment by JasonKarim** [comment]
Done! Thanks.



Karim
CHHS Office of Innovation
Ph. 916-214-6311
