### ISSUE TITLE
Significant code ugliness on Latest News page

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#910]
Code showing where it shouldn't be on the Latest News page. Looks like it only happened on two news releases from June 24.

<img width="760" alt="2020-06-29_11-42-40" src="https://user-images.githubusercontent.com/63249920/86043772-02eade80-b9fe-11ea-9f0a-9efae8f7c2c8.png">

Who can fix?

**Comment by aaronhans** [comment]
Thanks @thepegisin 
I need to:
- [ ] push a fix which cleans up the code 
- [ ] need to figure out how the scraper got confused

**Comment by abquirarte** [comment]
closing?

**Comment by aaronhans** [comment]
I need to do more research into cause still, just fixed symptoms so far

**Comment by aaronhans** [comment]
Remaining tasks here:
- [ ] complete unit test coverage on news crawler
- [ ] add e2e test to verify not submitting gibberish again

**Comment by aaronhans** [comment]
CCG-646
