### ISSUE TITLE
Broken links to fix - English pages 6/29

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#913]
Broken links report for 6/29. These were caught by SiteImprove, and I checked them.

Details: [https://docs.google.com/document/d/15Q2Wz_hVXxpB9ykLix4AUlfCfuuXzXE6/edit](https://docs.google.com/document/d/15Q2Wz_hVXxpB9ykLix4AUlfCfuuXzXE6/edit)

Content captains, please fix:

@ashleydraper 
- [x]  **Housing and homelessness**
- [x]  **Great Plates**

@thepegisin 
- [x]  **Essential workforce**

**Comment by ashleydraper** [comment]
@thepegisin 
The broken links on the housing page should be fixed. Let's chat tomorrow about the 211s on the great plates page.

**Comment by ashleydraper** [comment]
@thepegisin 
the 211s have been addressed!

**Comment by ashleydraper** [comment]
@thepegisin 
This issue is closed
