### ISSUE TITLE
7/1 Updates to Stay Home QA page

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#925]
[@abquirarte sent draft to GO, just documenting here as well]

Stay Home QA page 7/1 updates, including:

- [x] [Align what's open/closed](https://docs.google.com/document/d/1IjhaoR1G-6w3dl_pqSva34ok5wvw1UB5Fy3QfRxyOQw/edit) 

- [x] [DMV updates](https://www.dmv.ca.gov/portal/news-and-media/dmv-makes-it-easier-for-commercial-drivers-to-keep-on-trucking/)

[Staging doc](https://docs.google.com/document/d/1-717sVzLVN80_aYX2xJZ-FYCrYotBEv5nweWL-W8sOY/edit?ts=5efd3618#)

**Comment by abquirarte** [comment]
Follow up question/comment from GO
> Technically the whole list that's under counties not on monitoring list are open in counties with variances

**Comment by KaylaPrusia** [comment]
Staging doc reflects updated changes - snuck them in late yesterday. Not sure if they received a version or have access to the live doc?

**Comment by abquirarte** [comment]
I sent them the updates in the afternoon. 
Got this feedback: 
>The list of what can be open in counties with variance was incomplete. Can you fix it and resend please?

I will forward you the email so you can modify and we can resend.

**Comment by KaylaPrusia** [comment]
The [staging doc](https://docs.google.com/document/d/1-717sVzLVN80_aYX2xJZ-FYCrYotBEv5nweWL-W8sOY/edit#heading=h.b93fcwh8ubbj) is now accurate on what is open in counties with variance

**Comment by KaylaPrusia** [comment]
@abquirarte any word?

**Comment by abquirarte** [comment]
Yes as of like 5 mins ago. WIll forward to your inbox.

**Comment by abquirarte** [comment]
@KaylaPrusia any other updates we want to send over?

**Comment by KaylaPrusia** [comment]
I think we are aligned and this issue can be closed
