### ISSUE TITLE
Industry guidance page improvement iteration

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#926]
Making an issue for this to ensure that improvement through iterative process is not lost. 

Tagging all content and related teammates for general awareness, and so you can add any thoughts or input!

[staging doc 1](https://docs.google.com/document/d/1--MqqlmdnocqvTPd4qHdNr_DMKkoNIsmWybDo2LZdL4/edit)
[staging doc 2](https://docs.google.com/document/d/1OWc2o_k3RhLKPzEIxZzkjKOhnva6jsjgOgPU6GBQMrM/edit#)

**Comment by abquirarte** [comment]
- [  ] replace guidance docs with updated versions of content with mask 😷  guidance 

- [  ] add checklists too (in your inbox @LizNobriga )

**Comment by LizNobriga** [comment]
Awaiting guidance updates for:
- [ ] limited services
- [ ] casinos
- [ ] public transit (newer update)

**Comment by LizNobriga** [comment]
- [x] Delete: `The industry guidance below will be updated to reflect the revised policy on the use of face coverings.` ([see staging doc](https://docs.google.com/document/d/1_DrNgPky5wRQ8hD8gapOUIPNPVFbZYYp4pwwsw12iCw/edit#))

**Comment by abquirarte** [comment]
In your inbox hew guidances for restaurants. 

[Staged content](https://docs.google.com/document/d/1FmRV8vQifIb3MJl3MTZhfqMtR8zYEDivcpmVepGwAP4/edit#heading=h.gcoxmqz1kjns)

**Comment by LizNobriga** [comment]
[Edits](https://docs.google.com/document/d/1FmRV8vQifIb3MJl3MTZhfqMtR8zYEDivcpmVepGwAP4/edit#heading=h.gcoxmqz1kjns) for new restaurant guidance are live:
- [x] take-out
- [x] outdoor dining

**Comment by LizNobriga** [comment]
[staging doc](https://docs.google.com/document/d/1--MqqlmdnocqvTPd4qHdNr_DMKkoNIsmWybDo2LZdL4/edit#)
- [x] review by @thepegisin 
- [ ] review by @abquirarte 
- [ ] edits live

**Comment by LizNobriga** [comment]
@abquirarte, edits are ready for your review:
[industry guidance page staging doc](https://docs.google.com/document/d/1--MqqlmdnocqvTPd4qHdNr_DMKkoNIsmWybDo2LZdL4/edit#)

**Comment by abquirarte** [comment]
Going to tag along this issue @LizNobriga 

> DIR has flagged the following sentence that appears in nearly all of the published industry guidance: “Employers **should** provide face coverings to workers or reimburse workers for the reasonable cost of obtaining them.” Elsewhere in the guidance documents we note that“Employers **must** provide and ensure workers use all required protective equipment, including eye protection and gloves where necessary.”  CalOHSA Legal determined employer responsibility on provision of face coverings and they’ve been receiving intake from employers’ attorneys on potential inconsistency.

Every industry guidance will need to be changed from should to must  
The exception is schools which already has the ‘must.’ 

Check your email for a full list. (table)

**Comment by LizNobriga** [comment]
This is done!

**Comment by abquirarte** [comment]
## Higher ed and youth sports guidances 

One more today with the guidances coming out :) so not closing this yet!

- 2 new PDFs for our covid site: (youth sports guidance, Higher Ed) - all counties section, include date of when it was updated. 
- 1 updated PDF (Schools guidance update- will now include youth sports, may need to update description and include a date. 
- and a link to CDPH page (Youth sports FAQ)

**Comment by LizNobriga** [comment]
[staging doc](https://docs.google.com/document/d/1g2sZLKHV-ESFNB1Rzd7gEdD9M1aYWOPZqiUO1uOFTco/edit) for edits to industry guidance page

**Comment by LizNobriga** [comment]
Schools and Youth sports [staging doc](https://docs.google.com/document/d/1g2sZLKHV-ESFNB1Rzd7gEdD9M1aYWOPZqiUO1uOFTco/edit) and [staging-only view](https://staging.covid19.ca.gov/industry-guidance/)

Awaiting CDPH links:
- [ ] Schools FAQ
- [ ] Waiver links (3) - process overview, template waiver letter and cover form, and waiver notice form
- [ ] Youth sports questions and answers

Waiting for green light to upload PDFs to github:
- [ ] Schools (original url)
- [ ] Schools (new url)
- [ ] Youth sports

:pause_button:Holding off on Higher education.
:heavy_check_mark:Got confirmation to remove recreational team sports from Day camps accordion.

**Comment by LizNobriga** [comment]
Everything is live @abquirarte

**Comment by abquirarte** [comment]
🎉 

Higher ed is still being reviewed! We'll create a dif issue for that. Thank you @LizNobriga !
