### ISSUE TITLE
reenable surveymonkey stuff

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#929]
surveymonkey links were disabled because they went offline all day 7/3

We can put the Feedback link back in the footer when surveymonkey is available again:

the feedback link (https://www.surveymonkey.com/r/COVID19CAGOV) has been removed from https://as-go-covid19-d-001.azurewebsites.net/wp-admin/post.php?post=1040&action=edit

and reenable the survey prompt here: https://github.com/cagov/covid19/blob/master/src/js/survey/survey.js#L5

**Comment by aaronhans** [comment]
These actions were taken, survey back up and feedback link restored

**Comment by abquirarte** [comment]
🚀
