### ISSUE TITLE
Add users to Github

### ISSUE THREAD

**Issue by ChadABratton** [cagov/covid19#94]
Add the following users per @TamaraIDEJA 
JasonKarim
KaylaPrusia
LizNobriga

**Comment by ChadABratton** [comment]
Created new team covid19 and added existing alpha staff and larger covid19 team
![image](https://user-images.githubusercontent.com/28573666/77343858-98841d00-6cef-11ea-8ac9-b6a428d6efe6.png)

**Comment by abquirarte** [comment]
assuming this is now done. thank you!
