### ISSUE TITLE
Great Plates Delivered update 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#940]
### Update 
Please update the program guidance (revised as of 6/12/20) on the website. I forwarded it to your mailbox. The only change here is the questionnaire (there is an additional question at the bottom, per the Governor’s request). All local admins have already been informed of this change.
 
### Content Captain 
@ashleydraper @thepegisin 

### Timeframe 
COB today

**Comment by ashleydraper** [comment]
@TamaraIDEJA @thepegisin 
This update is baking - already committed

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
Proposing we close this issue
