### ISSUE TITLE
Build Was this page helpful yes/no plus survey front/backend

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#945]
Should submit boolean immediately, extended survey is optional. This dev task is not ready for implementation, design is still in progress

**Comment by aaronhans** [comment]
PRD: https://docs.google.com/document/d/13v2skLxkah2Jh_7HLytNqnwUlyHkOhe23v5gWNHol4w/edit#

**Comment by aaronhans** [comment]
Coordinate with @kkoryaka working on the design in #962 
- [ ] integrate the web component into the site
- [ ] publish web component to npm
- [ ] make sure it is transpiled for IE11
- [ ] build FAAS endpoint to receive all form posts
- [ ] fire up Cosmos DB to store data
- [ ] design data structure to allow all anticipated queries
- [ ] store submitted data into Cosmos
- [ ] create another FAAS for data retrieval
- [ ] build sample chart view on github pages so data is viewable easily

**Comment by abquirarte** [comment]
all boxes ready?

**Comment by aaronhans** [comment]
I haven't built the APIs to power retrieving the data yet but we could start collecting it

**Comment by aaronhans** [comment]
- built APIs to retrieve data at:
https://fa-go-alph-d-001.azurewebsites.net/WasHelpfulData/1595289600000/1595376000000?url=road

format to query it is: https://fa-go-alph-d-001.azurewebsites.net/WasHelpfulData/{start date timestamp}/{end date timestamp}?url={url encoded string used to retrieve all LIKE strings}

- view to choose dates, and parts of url to filter dataset:
https://news.alpha.ca.gov/covid-comments/

initial task set is complete, we can close this

**Comment by aaronhans** [comment]
Additional action items:

- [ ] Immediately remove view and lockdown endpoints
- [ ] Need to figure out how to secure the endpoints and views because people have entered PII into the comments box

**Comment by aaronhans** [comment]
details on how to access the view securely were provided via slack, the endpoint is no longer accessible without azure codes and there is. a new private repo for the view at https://github.com/cagov/comment-reports the private repo doesn't contain any sensitive information, you still need to provide the code in the url to see data

**Comment by abquirarte** [comment]
Thanks @aaronhans !
