### ISSUE TITLE
Broken links in PDFs 7/6/20

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#947]
Hey, SiteImprove detects broken links in PDFs! And we have a couple in there.

Need to contact the SME for these PDFs and have them fix, then re-upload.

- [x] [Executive Order N-33-20](https://covid19.ca.gov/img/Executive-Order-N-33-20.pdf) has these two, which look like typos:

<img width="721" alt="2020-07-06_17-11-20" src="https://user-images.githubusercontent.com/63249920/86672774-d7db2e80-bfab-11ea-928e-9160204a65fe.png">

- [x] The Essential Critical Infrastructure Workers PDF has an outside link that no longer works.

<img width="724" alt="2020-07-06_17-14-41" src="https://user-images.githubusercontent.com/63249920/86673174-44eec400-bfac-11ea-92ac-306ad2e8f07e.png">

**Comment by abquirarte** [comment]
Yes! Thank you! We'll need to send to GO :]

**Comment by thepegisin** [comment]
Reminder: Still broken as of 7/24/20.

**Comment by thepegisin** [comment]
Fixed!
