### ISSUE TITLE
WP Migration PDFs not importing

### ISSUE THREAD

**Issue by carterm** [cagov/covid19#95]
The images work, but PDF files don't move over automatically when added to Wordpress

**Comment by carterm** [comment]
Fixed here...
https://github.com/cagov/wordpress-integration-api/commit/8ab9b75197526255bacc4997a09773976255321d

**Comment by abquirarte** [comment]
Does it work now? 
We have a pdf we need to replace that we could test it with.

**Comment by carterm** [comment]
It's working now.
