### ISSUE TITLE
Update Testing & treatment page to answer call center frequently asked question, “Can two people that both tested positive hang out/stay together?”

### ISSUE THREAD

**Issue by JasonKarim** [cagov/covid19#951]
Update Testing & treatment page to answer call center frequently asked question, “Can two people that both tested positive hang out/stay together?”

Q/A drafted. @thepegisin to review next!

**Comment by JasonKarim** [comment]
![image](https://user-images.githubusercontent.com/62369563/86981418-67631780-c13b-11ea-87b0-050903b9f68e.png)

![image](https://user-images.githubusercontent.com/62369563/86981492-99747980-c13b-11ea-8adb-a2f84f7d5233.png)
![image](https://user-images.githubusercontent.com/62369563/86981535-b3ae5780-c13b-11ea-82a9-88e7693bd3bf.png)
![image](https://user-images.githubusercontent.com/62369563/86981573-c6c12780-c13b-11ea-8723-1ee8659a0a9c.png)

**Comment by TamaraIDEJA** [comment]
Science Branch responded w the following: 

Proposed new Q&A (feel free to edit)
(Answer is not accurate – see proposed answer and more background below.)
 
**Can two people that both tested positive hang out/stay together?**
No, if you test positive or negative for COVID-19 on a viral or an antibody test, you still should take preventive measures to protect yourself and others. Some tests, like the antibody test, can be useful to detect a past COVID-19 infection but are not accurate methods to demonstrate immunity. While people who have recovered from COVID-19 are likely immune from reinfection for a period of time, we do not know yet if and when a person can be reinfected with COVID-19. Scientist are working to understand this.

Here is CDC guidance (https://www.cdc.gov/coronavirus/2019-ncov/testing/serology-overview.html) on past infection:
“If you test positive or negative for COVID-19 on a viral or an antibody test, you still should take preventive measures to protect yourself and others.

We do not know yet if people who recover from COVID-19 can get infected again.  Scientists are working to understand this.”
 
There are a number of issues here:
1.       It will be confusing if we have different public health guidance for people previously infected vs. not infected.  We don’t want people not masking or gathering in groups and claiming they’ve all been infected so the rules don’t apply to them
2.       People don’t have a good handle on what is meant by a “test”.  Are we talking antibody tests? Those don’t seem accurate enough to establish immunity.
