### ISSUE TITLE
Finish fully automating quick answers crawler

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#952]
The quick answers on covid19.ca.gov search are powered by https://github.com/cagov/Cron/tree/master/qnacrawler but still needs a couple buttons pressed to refresh the dataset. These steps can be fully automated so the crawler 

- [ ] runs as a cronjob
- [ ] submits new dataset to qnamaker
- [ ] triggers reindex
- [ ] publishes updated dataset

**Comment by abquirarte** [comment]
Yup, let's move this up the list.

**Comment by abquirarte** [comment]
2-3 days of work. 
May need to be a P2 thing. 

cc: @hannahslee and @kenbasart

**Comment by aaronhans** [comment]
Current not yet automated process

Run the following scripts from https://github.com/cagov/Cron/tree/master/qnacrawler:```node index.js && node merge-editorial.js && node excel.js```

Login to: https://www.qnamaker.ai/Home/MyServices
- Choose the "call center" knowledge base (We had ambitions of automating the call center Q&A scripts)
- In Settings tab choose: Import Knowledge Base
- Select excel file generated from scripts above (We used to use csv but azure cognitive search introduced a bug with parsing markdown in csv so we switched to excel to get around it)
- Authorize full replace
- Review the generated Q&A pairs to make sure formatting of answers is preserved
- Click save and train button
- Click publish button

**Comment by aaronhans** [comment]
CCG-645
