### ISSUE TITLE
Create a way for translation content from human translators to be reviewed for deployment

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#958]
We saw a funny bug recently where it looks like AvantPage returned HTML with an unclosed bold tag that isn't present in the English original.

This type of error is a possibility so it would be safer to let new translations be browseable by someone on our end before we hit an accept button for them to go live.

**Comment by carterm** [comment]
It wouldn't take much to create PRs from new translated content.

**Comment by carterm** [comment]
Done.
https://github.com/cagov/wordpress-integration-api/pull/42
