### ISSUE TITLE
Add "safelymakingca.org" link to Mask/PPE pages

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#967]
## User story: "As an employer, I'd like to know where I can go to purchases non-medical PPE for my staff, so that they can remain working in a safe manner" 

We got a request to include the safelymakingca.org link to our website. SME suggested locations, but I'll defer to you on where this best fits. I know @LizNobriga had suggested maybe in the industry guidance page. 

### Suggested locations from SME

>, on this page. https://covid19.ca.gov/masks-and-ppe/#top   under Kinds of Masks, Where to find:   add this sentence  “Here is a list of California manufacturers that have retooled their operations to make PPE, including masks.”   And then link to www.safelymakingca.org 

>The second location,  would just be in the drop down menu under working and living safely, just a button that says “Purchase PPE”  and then instead of going to another page, it would go to www.safelymakingca.org

**Comment by thepegisin** [comment]
Perfect timing. I was just updating the Masks page to address a user concern ("what's the right way to wear a mask?") and to incorporate social share images per @coreycaitlin's suggestion.

I think the place for the safelymakingca.org link is on the Request PPE page (renamed Get PPE), which I've adapted accordingly. Take a look.

**[Masks and face coverings](https://docs.google.com/document/d/1-7dSwuitgDWrB3mJ45yW-NG3ADA4N60CoUbXi1BL_vQ/edit#)** (Staging doc)
**[Get PPE](https://docs.google.com/document/d/1fUJMnbxK1BhkvmPU-2D_AA6n9orl66EBnC6SWo3hADU/edit#)** (Staging doc)

**Comment by abquirarte** [comment]
✅ I added some comments to one, but both look great! Go live!

**Comment by abquirarte** [comment]
These are good to go live.
