### ISSUE TITLE
Workers page updates and improvements

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#968]
- [x] add worker safety complaint info/link
- [x]  add FED-ED (extends UI benefits) info/link
- [x] make info easier to find when scanning the page (add sub-headings and anchor link to Q&A)

[staging doc](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit#)

- [x] review by @thepegisin 
- [x] review by @abquirarte /approved for posting
- [x] edits are live

**Comment by abquirarte** [comment]
yay thank you, will review after Peggy

**Comment by LizNobriga** [comment]
@thepegisin has finished reviewing! Ready for you, @abquirarte! [staging doc](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit#heading=h.5sliolr8itsx)

**Comment by abquirarte** [comment]
✅ looks great! ready to go. Will flag for SMEs as FYI

**Comment by LizNobriga** [comment]
Edits are live! @abquirarte

**Comment by abquirarte** [comment]
Fantastic!
