### ISSUE TITLE
Local info updates and edits

### ISSUE THREAD

**Issue by KaylaPrusia** [cagov/covid19#969]
- [x] Update "How is the state protecting incarcerated people in California?"

- [x] Update resource for child custody/visitation question

- [x] New q/a on jury duty

Here is the [staging document](https://docs.google.com/document/d/1uYrsDp60x1BRHi_OYNamzDqrueUMj4U-DKEZ6AEOg8U/edit#)

- [x] Review by @thepegisin 

- [x] Review / approval by @abquirarte 

- [x] Edits live on website

- [ ] How should we translate county website information to the county variance page?

**Comment by KaylaPrusia** [comment]
@abquirarte the staging doc is ready for your review!

**Comment by abquirarte** [comment]
Looks great @KaylaPrusia ! Added one comment for a potential edit. Other then that, this is good to go. 

Should we coordinate with @thepegisin and @ashleydraper on how to get this page better linked in the County variance page and other places where we reference local?

**Comment by KaylaPrusia** [comment]
Edits are live!

And yes - how best to approach. Are we thinking we want to replicate the list on the county variance page so people aren't jumping between pages? Or would an anchor link to that accordion be enough?

**Comment by abquirarte** [comment]
Closing this for now. Assuming you and Peggy connected!
