### ISSUE TITLE
New mental health resources 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#976]
### Content 
Mental Health SMEs have asked us to update the website with the new mental health resources that GGN is planning to highlight towards the end of next week in his presser. They want us to create a new page but we told them that that may or may not be optimal, and that the content team will review the new resources and propose the best way to make this new information prominent and easy to find. 

I forwarded you two emails 1) high level context 2) list of new resources

Please collaborate and propose where/how we should display these additional resources on our website. 

### Content Captains 
@KaylaPrusia @ashleydraper @thepegisin 

### Timeline 
Draft to present to SMEs early next week.

**Comment by KaylaPrusia** [comment]
@TamaraIDEJA would it be possible to get access to the links provided on the spreadsheet? Spreadsheet links take us to a learning management system that requires credentials

**Comment by TamaraIDEJA** [comment]
@KaylaPrusia following up on this momentarily! Thanks for a nudge!

**Comment by TamaraIDEJA** [comment]
Update -  Sent you their proposed list of resourcers via email.

Timing has shifted a bit. They proposed postponing the press conference as they are really close to obtaining FEMA finding approval.. they want to be able to announce that during the press conference. I would say that we should target end of this week for our draft proposal to SMEs.

Caveat from another email where they rceived input from Agency Undersecretary and Chief Comms Officer - "they leaned toward having the kids and families content primarily live on the State COVID-19 website, with links to the CalHOPE and other department (DMHC, CDA, DSS, etc) websites."

@KaylaPrusia @ashleydraper @thepegisin

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
Okay, so by Friday is fine?

**Comment by TamaraIDEJA** [comment]
Returned edits....

**Comment by TamaraIDEJA** [comment]
### Edits from SMEs
We received edits from the SMEs Manage stress for health https://docs.google.com/document/d/10SIqrAISEXcxeNHnoY1g2EIMcTXq9cDh_zYv1fOcs6Q/edit?usp=sharing

**Comment by ashleydraper** [comment]
@TamaraIDEJA 
I don't have access to this document

**Comment by ashleydraper** [comment]
Edits are baking, but can be readily viewed in staging here: https://staging.covid19.ca.gov/manage-stress-for-health/#top. Proposing to close this issue.

@TamaraIDEJA
