### ISSUE TITLE
Updates to county page, Stay home QA, industry guidance

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#979]
## context
Gov is announcing sectors that will be closing. I've ping you via email and slack with a list. This may affect several pages. 
More to come tomorrow, but we should be ready to have updated content before/by the noon press conference. :) 

Potentially affected pages:

- Stay home QA @KaylaPrusia 
- County variance page @ashleydraper 
- other areas @LizNobriga @thepegisin 

## deadline
By 11:45am tomorrow 
Further context in slack :)

**Comment by KaylaPrusia** [comment]
Prepped edits to the [Stay Home staging do](https://docs.google.com/document/d/15UZxEstPuqnXGb92yU0SvS9ooulz19lpb9Q5-bjAUuE/edit#)c to outline what's now open/closed
