### ISSUE TITLE
New content: Reporting tool for water shut-off 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#980]
## context 
"we've translated the [water shut-off Executive Order protections](https://www.gov.ca.gov/2020/04/02/governor-newsom-issues-executive-order-protecting-homes-small-businesses-from-water-shutoffs/) onto the covid-19 website. The water board has developed the following tool that allows Californians to report a shut-off, that can be linked to. I've looped in our programs folks, it would be great to see how best we can create an easy to understand explanation of the protections individuals have, and how they can report issues. Really want to try and capture some of the great water work that has been done in connection with COVID-19 response."

Link to the tool: https://watershut-off.covid19.ca.gov/

## deadline 
End of week (July 20th), requires follow-up conversations with SME

From SME:
> The Water Boards seeks to reach out to the public to establish if water providers are complying with Gov. Newsom's April order restricting the shut off of water during the COVID crisis. In doing so, the Water Boards created a webpage with the help of IT and CDT that allows the anonymous reporting of water shut off incidents of varying kinds, with that page also requesting specific information about the shut offs. It is not known whether the shut offs are occurring in the Latino community. This fact underscores the urgency in the plan for a Spanish language page. However, the Water Boards was unable to get buy-in from IT about putting up a dedicated Spanish language page for the reporting of water shut offs. Rather, we had to settle for a banner note directing those needing Spanish language assistance to call a dedicated number to report shut offs. That said, if we could have the information parsed in any other manner or scope-where it could be accessed by Spanish-speakers and other languages, this would be a great help to the Water Boards plan to establish if shut offs have been happening.

## Task and consideration

- [x] Review the context
- [x] draft content to add to Immigrant Guide page (to be translated), or any other relevant places

**Comment by ashleydraper** [comment]
Added water shut-off guidance to [Get Financial Help](https://docs.google.com/document/d/1gaircIbaAOqGdK3KCtDSXZlhnchEGFDkTWdLgRTYAxE/edit#). 
Pinging @orielgomez on this too for Spanish translation and input.

**Comment by abquirarte** [comment]
Thank you @ashleydraper looks great! I think it's simple and good to go. 

@orielgomez did you suggest content for this in the immigrant guide page? I don't see them in the Google Staging doc. :)

**Comment by orielgomez** [comment]
@abquirarte finishing up this content. Do we have the number that Spanish speakers can call to report any shutoffs?

**Comment by abquirarte** [comment]
Thank you! It will show up when the website works :) lol
But I will ask SME just in case.

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by abquirarte** [comment]
The changes are live in get financial help page and immigrant guide page
