### ISSUE TITLE
Minor update to contact tracing page- Digital toolkit

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#983]
### request 
> could we add a line on the California Connected website that would take people directly to the partner toolkit page to access more contact tracing assets. Thinking it could say “Click here to access the California Connected digital toolkit.” and linking to toolkit.covid19.ca.gov/partners. Definitely open to your recommendations on the best location on the page, but maybe at the bottom with “stay informed”? 

### timeline
EOD tomorrow - Tuesday

**Comment by thepegisin** [comment]
- [ ] Updated
