### ISSUE TITLE
Publish to staging only bug

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#984]
Publishing to staging is done from a branch from master which diverges when there has been prior publishing to staging

We want to allow continued divergence between master and staging in WordPress content

It is fine to overwrite what is in staging completely with the content from WordPress

**Comment by carterm** [comment]
After doing some research, I can control merging options only with a pull request.  I can still auto-approve the pull request.  Rather than skipping the merge to production, I can just skip auto-approving PRs with "staging-only" in them.  I should look into marking those "draft" as well.

**Comment by carterm** [comment]
This PR should fix it...https://github.com/cagov/wordpress-integration-api/pull/39

**Comment by carterm** [comment]
Confirmed fix.
