### ISSUE TITLE
covid case stats publish now administrative controls

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#987]
We are frequently getting requests to speed up or delay the daily stats publishing. Currently we have a cronjob executing daily at 1pm that pulls the data from snowflake.

In order to comply with needs to sometimes publish sooner we should create:
- [ ] Publish now button which can be pressed any day after 11am if we want to publish before the 1pm auto publish

Creating a button to delay the cronjob is more complicated, maybe we already have a generally acceptable publish time of 1pm and the availability of a publish now button will meet our future needs

**Comment by abquirarte** [comment]
I actually think it's opposite.  Automated updates at 11am and trigger
later updates when Gov speaks and we need to delay. That sounds harder?

**Comment by abquirarte** [comment]
Though maybe it can still work out. We'd just have to be punctual about 11.
(Since that's when the other data assets get updated)

**Comment by abquirarte** [comment]
@aaronhans CDT published at 11am today. We are out of sync with them right now. Can we revert back to the 11am automated update or build in the functionality so that even if it's at 1pm we can trigger the update at 11am to sync with them?

**Comment by aaronhans** [comment]
I switched the default runtime back to 11am.

What if we rebuild the update process so that it looks at a flag and decides whether to:
- open a PR with the data update that will have to be manually merged to go live
- automatically merge the update

Then if we wanted to delay updates for a day or multiple days in a row we could flip the flag off and merge the PRs daily when we were ready. We would flip the flag back to auto when the time sensitivity was relaxed.

We could create a url on azure that we could visit to flip the flag off and on and it could notify slack of its current status anytime it got switched.

**Comment by abquirarte** [comment]
That works!!!
